### PR TITLE
ttH with top mass variation and semileptonic, dileptonic decay

### PR DESCRIPTION
**Pull request by Andrej-CMS**
Dear GEN experts,
please check the cards.
Kind regards,
Andrej

### CODE REVIEW

**Comment by efeyazgan** [comment]
Why is the following not 172.5 GeV?
qmass  171.5     ! mass of heavy quark in GeV

**Comment by efeyazgan** [comment]
Sorry, ignore my comment, I saw the file name later.

**Comment by efeyazgan** [comment]
These parameters below:
tdec/wmass 80.385  ! W mass for top decay
tdec/wwidth 2.085
tdec/twidth  1.41
tdec/emass 0.000548
seem to be different than those in, e.g., https://github.com/cms-sw/genproductions/blob/master/bin/Powheg/production/2017/13TeV/TT_hvq/TT_hdamp_NNPDF31_NNLO_ljets.input 
It may be better to use the same parameters as in the standard top samples. 
@jfernan2, could you please check as well?

**Comment by Andrej-CMS** [comment]
Dear @all,
please check the changed parameters again.

**Comment by Andrej-CMS** [comment]
Dear Gen Experts @all,
Could you please check the cards again? The parameters have been changed.

**Comment by vischia** [comment]
Dear GEN experts,

are the parameters OK? Can the PR be merged?

Thank you in advance for checking!

Cheers,
Pietro for HIG MC

**Comment by jfernan2** [comment]
+1 
I don't see problems with these settings

**Pull request merged**
