### PR TITLE
four leptons added

### PR DESCRIPTION
**Pull request by nadjieh**
Similar to 3l case with Madspin changed to four lepton decay

### CODE REVIEW

**Comment by agrohsje** [comment]
Hi @nadjieh. Looks good to me. If you can you could clean up the fragments a little bit. had and j are not used, you could move the lepton definitions to madspin, remove the lines with # in madspin to make it easier.

**Comment by nadjieh** [comment]
Hi @agrohsje 
had is used in the decay. Do you mean the definition should go to madspin for that as well?

Also, do I need to regenerate gridpacks or only update the git?

**Comment by agrohsje** [comment]
No, no. Don't update the gridpack. Unless @qliphy spots a mistake that I didn't. 
My comments are just cosmetics to make it easier. 
had is currently not used in madspin.

**Comment by nadjieh** [comment]
@agrohsje 
" had is currently not used in madspin."

Ah yes, this is remnant of 3l. Will do ...

**Comment by nadjieh** [comment]
@agrohsje can you please check it now?

Thanks!

**Comment by agrohsje** [comment]
Thanks! +1 @qliphy

**Pull request merged**
