### PR TITLE
Charged resonance missing cfgs

### PR DESCRIPTION
**Pull request by shchauha**

### CODE REVIEW

**Comment by govoni** [comment]
for what production are those cfg files intended?

**Comment by shchauha** [comment]
These are for Charged resonance Pythia samples to be produced with Moriond setting. Analysers had requested Madgraph and Pythia samples earlier. Madgraph ones are already produced. Pythia configs had some issues that time, they are fixed now by analysers.

**Comment by govoni** [comment]
ok. Please remember that for 2017 productions the tune will have to be changed in each of the files.

**Comment by shchauha** [comment]
Okay Thanks Pietro.

**Pull request merged**
