### PR TITLE
Revert "Upload cards for ALP model for WZG analysis"

### PR DESCRIPTION
**Pull request by sihyunjeon**
Reverts cms-sw/genproductions#3109

### CODE REVIEW

**Comment by sihyunjeon** [comment]
@menglu21 @Senphy Let me rever this. I don't see madspin here

**Comment by sihyunjeon** [comment]
although in the description you wrote you will use MadSpin to decay W

**Comment by sihyunjeon** [comment]
@Senphy can you make a new pull request?

**Comment by sihyunjeon** [comment]
For 1), WZAToLNuLLA_4f_NLO is renamed as LLWA_WToLNu in McM, which means that the W has an on shell requirement and is decayed with Madspin.

Sorry I misread this message from you a little bit. Let me revert and remerge but you need to remove something in run_card.dat. I will re-revert this and merge with the fix.

**Comment by Senphy** [comment]
Never mind. Sorry for not making it clear. Thanks for your check.

**Pull request merged**
