### PR TITLE
DYBJetsToLL, DYBJetsToNuNu and WBJetsToLNu datacards

### PR DESCRIPTION
**Pull request by perrozzi**
adapted from https://github.com/cms-sw/genproductions/tree/2a3a99875e5424505436ed7378e15dac5a6f9f27/bin/MadGraph5_aMCatNLO/cards/production/13TeV/DYBBJetsToLL_M-50_5f_LO_MLM

### CODE REVIEW

**Comment by perrozzi** [comment]
hi, could you please check/merge?

**Comment by perrozzi** [comment]
a gentle reminder

**Comment by perrozzi** [comment]
updated the PR to start the ME production from the single b case. added also dyll

**Comment by bendavid** [comment]
Don't you want up to bquark j j j to match the inclusive LO samples?

**Comment by perrozzi** [comment]
of course, thank... (done)

**Comment by bendavid** [comment]
The dytoll cards are also named "ToNuNu".  Otherwise things look fine.

**Comment by perrozzi** [comment]
ok, hopefully it's all now, thanks again

**Pull request merged**
