### PR TITLE
ZprimetoNN cards

### PR DESCRIPTION
**Pull request by sihyunjeon**
Hi, this is Zprime to pair of heavy neutrino gen cards

Thanks in advance,

Sihyun.

### CODE REVIEW

**Comment by efeyazgan** [comment]
Is this for mg26 for a specific reason?

**Comment by sihyunjeon** [comment]
Not specifically but I had a chat about this with andreas 2,3 months ago and we thought it would be okay to use latest version.
I also checked our LHE files comparing v242 and v260 and there was no any odd differences between those two versions.

**Comment by sihyunjeon** [comment]
@efeyazgan  Hi Efe, is there any problem for merging these cards?

**Comment by efeyazgan** [comment]
No, I could look at the rest only now. Merging.

**Pull request merged**
