### PR TITLE
add reweighting for VHew

### PR DESCRIPTION
**Pull request by covarell**
Enable to run proper reweighting for VH with EW corrections

### CODE REVIEW

**Comment by perrozzi** [comment]
just to be paranoid: you tested the modifications and they have no effect on the other processes, right?

**Comment by covarell** [comment]
No.
Plus you have seen Carlo's comments today, which I would like to implement in the cards.

So I will update with another commit and run a full test_source_compilation round to check that other processes are not affected.

**Comment by covarell** [comment]
Ok. The changes to the cards are made and I tested the compilation of all RES processes.

I am now producing a HZJ (Z-> ee) gridpack, which I will ask Hbb contact to submit as GenOnly

**Comment by perrozzi** [comment]
thanks, so this PR can be merged right?

**Comment by covarell** [comment]
yes

**Pull request merged**
