### PR TITLE
Add cards for RunII-lecay and Run3 tZ'->ttt samples

### PR DESCRIPTION
**Pull request by desycms107**
Dear experts,

We are requesting the review of Madgraph cards of three-top samples for Run-2 and Run-3. It generates two processes, tZ'q and tZ'W where the Z' decays to tt~. Both the Z' mass and widths are varied.

Great thanks!

Kuan-Yu Lin

### CODE REVIEW

**Comment by desycms107** [comment]
Dear GEN convenors @lviliani @bbilin,

May I request a card review?

Best regards,

Kuan-Yu

**Comment by desycms107** [comment]
I just made 2 scripts. Are these reusable enough?

**Comment by bbilin** [comment]
yes they are reusable enough.

**Comment by bbilin** [comment]
I merged it too fast, but ok that is not a big problem. But still, why do you have this wall definition? You dont need to change anything, but wanted to understand.

define wall = u u~ d d~ s s~ c c~ b b~ e+ e- mu+ mu- ta+ ta- ve ve~ vm vm~ vt vt~

**Comment by desycms107** [comment]
It was a leftover line when we still put the top decay inside the ``proc_card.dat``.

**Pull request merged**
