### PR TITLE
clean up WZ and ZZ

### PR DESCRIPTION
**Pull request by sihyunjeon**

### CODE REVIEW

**Comment by sihyunjeon** [comment]
WZ to LNu2Q
p p > ell+ vl z (+ j)
p p > ell- vl~ z (+ j)
with z > j j

**Comment by sihyunjeon** [comment]
ZZ to 2Nu2Q
p p > vl vl~ z (+j)
with z > j j

**Comment by sihyunjeon** [comment]
ZZ to 4Q
p p > z z (+j)
with z > j j

**Comment by sihyunjeon** [comment]
@menglu21 @SanghyunKo @agrohsje @freejiebao

**Comment by sihyunjeon** [comment]
just merging this on my own

**Comment by agrohsje** [comment]
looks good to me!

**Pull request merged**
