### PR TITLE
Fall17 Powheg ggH cards

### PR DESCRIPTION
**Pull request by lviliani**
Powheg gg_H_quark-mass-effects cards for ggH->WW mass scan signals.
Number of calls, iterations, etc. are the same as the ones used in HZZ samples.

### CODE REVIEW

**Comment by perrozzi** [comment]
what is going on with cmsbuild?!? :-)

**Comment by lviliani** [comment]
I was wondering the same thing... I have just committed the powheg cards and a python script.
Is there any action required on my side?

**Comment by perrozzi** [comment]
no

**Comment by smuzaffar** [comment]
let me check

**Comment by smuzaffar** [comment]
we updated cms-bot to make an automatic mirror of all cms-sw repositories when something is pushed. It also enabled cms-bot to listen to PRs. This is fixed now and cms-bot should ignore PRs/Issues for this repo.

**Comment by perrozzi** [comment]
thanks a lot @smuzaffar

**Comment by perrozzi** [comment]
@lviliani can you please post only one datacard with a given mass point, and provide a script to produce all the others? we are trying to minimize the number of files in the repository to avoid slowdown. thanks

**Comment by lviliani** [comment]
Now there is only a template card and a script to produce all the mass points.

**Comment by perrozzi** [comment]
the cards look ok to me

**Pull request merged**
