### PR TITLE
Change to LHEGeneric filter

### PR DESCRIPTION
**Pull request by dnash86**

### CODE REVIEW

**Comment by dnash86** [comment]
From https://github.com/cms-sw/genproductions/pull/646#issuecomment-144315309

Rather than reopening the old one, sorry about the git confusion...

**Comment by dnash86** [comment]
These filters (based on LHEGenericFilter) work fine, thanks for the advice.

**Comment by bendavid** [comment]
Are these intended to be used with pLHE or wmLHE requests?

For wmLHE the "src" will have to be changed to "externalLHEProducer" in order for it to work.

**Comment by dnash86** [comment]
These are intended for pLHE requests.  I had tested them, and they seemed to work okay locally.

**Comment by bendavid** [comment]
Ok yes, they will work as is either locally (on lhe files) or with plhe requests.  If you want to use them with wmLHE requests you'll need to commit an additional version with the alternate "src" in that case.

**Pull request merged**
