### PR TITLE
Add option to specify local UFO files in extramodels.dat

### PR DESCRIPTION
**Pull request by nsmith-**
Based on whether or not it starts with a `/` for an absolute path.

### CODE REVIEW

**Comment by Saptaparna** [comment]
Looks fine to me.

**Comment by sihyunjeon** [comment]
@nsmith- Hi, would it not be better to use `-e` in shell script to check if the path exists and then copy the model file, instead of checking if it starts with "/"? for secure coding

**Comment by nsmith-** [comment]
It's a good idea to check the path exists yes, I'll add that. But I think its nice to check for both because otherwise someone might be trying to indicate a local file but misspells the path name and it would try to download that path from the web area, leading to a more cryptic error.

**Comment by nsmith-** [comment]
I think this is ready to merge

**Comment by sihyunjeon** [comment]
@menglu21 @mlizzo

**Comment by mlizzo** [comment]
PR is fine to me, @menglu21 if you agree I'm going to merge it

**Comment by menglu21** [comment]
hi all, sorry for the late reply. personally i would prefer not allow local UFO models, since here you also comment that "the local model should be uploaded to cms-project-generators.web.cern.ch", we know that sometimes people will forget to upload it and it may get harder to trackback. we can always help to put the model to the central place. let me know your opinion.

**Comment by nsmith-** [comment]
Ok I just learned one can also put the model in `addons/models` if I want a custom one without uploading... so doesn't that defeat the point of your last statement? Or am I missing something

**Pull request closed without merging**
