### PR TITLE
VBF_H_WW PDF updated for UL gridpack

### PR DESCRIPTION
**Pull request by mlizzo**
PDF set updated to 325300 in order to use the card for the production of VBF_H_WW gridpack for the UL campaign. Other than that, no changes have been implemented

### CODE REVIEW

**Comment by gourangakole** [comment]
Dear all;
I think I made a similar request earlier: why not modifying the template file instead of adding extra file:

https://github.com/cms-sw/genproductions/tree/master/bin/Powheg/production/2017/13TeV/Higgs/VBF_H_WW_NNPDF31_13TeV

**Comment by agrohsje** [comment]
Hi @mlizzo. What about the comment from Gouranga and updating the template. @gourangakole: Why don't you guys clean up a bit and just stick to templates and scripts. I think having the explicit cards causes confusion. Let me know if I should merge.

**Comment by mlizzo** [comment]
Hi @agrohsje, I used the makecards.py script to generate the card from the template file, I thought it was there exactly for this purpose (as I said in the comment, I just changed the PDF of the output file). I can update the PDF set in the template file, if that's what you mean, maybe it's useful since new gridpacks must be in compliance with UL requirements. Please let me know whether you agree.

**Comment by agrohsje** [comment]
Right. I had in mind to update the template as well. Ideally one would just work on the template, run scripts locally but don't commit the output. The reason of the template is to have everything in one place. If we now commit all the time the cards, then this is not true anymore and people will start to change the files but not the template, exactly as you did. Anyway. Adjusting the template is good and @gourangakole and Alexandros might clean up a bit in a separate PR.

**Comment by mlizzo** [comment]
Ok thanks for the clarification, maybe I misunderstood how the script was intended to be used

**Comment by agrohsje** [comment]
Ok. Please update the template and I merge.

**Comment by gourangakole** [comment]
> Right. I had in mind to update the template as well. Ideally one would just work on the template, run scripts locally but don't commit the output. The reason of the template is to have everything in one place. If we now commit all the time the cards, then this is not true anymore and people will start to change the files but not the template, exactly as you did. Anyway. Adjusting the template is good and @gourangakole and Alexandros might clean up a bit in a separate PR.

Yes, we shall do that. but for the time being as you suggested @mlizzo can update the template card with PDF.

**Comment by mlizzo** [comment]
Done! Please let me know whether it's fine like this

**Comment by agrohsje** [comment]
Happy with the PR. @gourangakole let me know and I merge.

**Comment by gourangakole** [comment]
> Happy with the PR. @gourangakole let me know and I merge.

I meant to say not immediate 😄 ..may in a week we shall need to talk to other contacts. so for the time being if you are happy with the content of this PR. Then please merge. we shall proceed with UL grid pack production.

**Pull request merged**
