### PR TITLE
ttH POWHEG gridpacks Pythia8 config

### PR DESCRIPTION
**Pull request by mharrend**
ttH POWHEG gridpacks: Added Pytia8 configuration for …

ttH, H->Nonbb, MH 125 GeV
ttH, H->GG, MH 125 GeV
ttH, H->TT, MH 125 GeV
Updated ttH, H->bb, MH 125 GeV to fix mW cut

### CODE REVIEW

**Comment by covarell** [comment]
@syuvivida @bendavid I remember the only POWHEG ttH official sample we sent had issues with the wmLHE step? What is the status of it now? Was it moved to CMSSW_7_1_16_patchX and then succeeded?

**Comment by mharrend** [comment]
Hello Roberto,

we produced already a ttH sample with this gridpack, so I would assume
that the gridpack is okay.

If you are okay with the current status of the gridpack you could
approve it now.

Best regards,

Marco

Marco A. Harrendorf
KIT - IEKP

**Comment by bendavid** [comment]
Marco, this pull request is already merged, is there something else waiting for approval?

**Comment by mharrend** [comment]
Hello Josh,

sorry, for stating it not clearer. I meant you can approve the
corresponding GenSim requests if there is no problem with the gridpack.

HIG-RunIIWinter15GS-00300
HIG-RunIIWinter15GS-00301
HIG-RunIIWinter15GS-00302

HIG-RunIIWinter15wmLHE-00195
HIG-RunIIWinter15wmLHE-00196
HIG-RunIIWinter15wmLHE-00197



Marco A. Harrendorf
KIT - IEKP

**Comment by bendavid** [comment]
Following a recent discussion, for the nonBB decay case, would be good to add also
23:mMin = 0.05 to cover also the HZZ case.

**Pull request merged**
