### PR TITLE
 added input cards for WH inclusive samples for HWW for Run3 

### PR DESCRIPTION
**Pull request by sv3048**
Dear experts !

I have prepared powheg input cards for /HWplusJ_HToWW_M-125_TuneCP5_13TeV_powheg-jhugen727-pythia8 and   /HWMinusJ_HToWW_M-125_TuneCP5_13TeV_powheg-jhugen727-pythia8 sample. The only change is the energy from 13 to 13.6 TeV. Kindly have a look at it at your convenience.

Thanks and Regards,
Sadhana Verma
adding @amanagrawal1280

### CODE REVIEW

**Comment by sihyunjeon** [comment]
small note - sample name should be `_powheg-`

**Comment by menglu21** [comment]
Hi @sv3048 
1. could you please merge this PR and https://github.com/cms-sw/genproductions/pull/3530 in one directory, e.g., HWMin(Plu)J_HToWW
2. then the name of cards in this PR can be HWMin(Plu)J_HToWW_WToAnything_***

**Comment by vischia** [comment]
Hi all,

taking over this PR and [#3530](https://github.com/cms-sw/genproductions/pull/3530) as the new contact. Will close the other one and move everything to this one, as suggested, in the next few days.

**Comment by vischia** [comment]
Hi @menglu21 , do you prefer one HWJ_HToWW folder, and then Plu/Min inclusive/exclusive cards, or a HWMinJ_HtoWW and a HWPluJ_HtoWW folder with inclusive/exclusive cards?

**Comment by vischia** [comment]
Will go for the latter, in analogy with other preexlisting cards.

**Pull request closed without merging**
