### PR TITLE
added MadGraph5_aMCatNLO cards for TGJets sample

### PR DESCRIPTION
**Pull request by mmachet**
I started from the cards for TTGJets of pull request #337. I just removed the t~

### CODE REVIEW

**Comment by syuvivida** [comment]
Don't you need the equivalent processes for the t~ or will they be generated separately? 
p p > t~ a [QCD]
p p > t~ a j [QCD]

**Comment by mmachet** [comment]
Yes you are right. Is it sufficient to add:
generate p p > t~ a [QCD]
add process p p > t~ a j [QCD]

in the run card and:
decay t~ > w- b~, w- > all all
in the madspin card?

**Comment by mmachet** [comment]
Yes you are right. Is it sufficient to add:
generate p p > t~ a [QCD]
add process p p > t~ a j [QCD]

in the run card and:


decay t~ > w- b~, w- > all all


in the madspin card?

2015-05-10 13:52 GMT+02:00 syuvivida <notifications@github.com>:

**Comment by syuvivida** [comment]
In the process card, you could have the following lines

generate p p > t a [QCD] @0
add process p p > t a j [QCD] @1
add process p p > t~ a [QCD] @2
add process p p > t~ a j  [QCD] @3
In the madspin card,
Yes, I think adding this line would be enough
decay t~ > w- b~, w- > all all

**Comment by mmachet** [comment]
ok thank you,
I'll change the cards and commit.

Martina

2015-05-11 7:49 GMT+02:00 syuvivida <notifications@github.com>:

**Comment by mmachet** [comment]
cards changed.

2015-05-11 9:54 GMT+02:00 Martina Machet <martina.machet@cern.ch>:

**Comment by syuvivida** [comment]
The cards look nice to me now. But please wait for the review of Josh/Roberto/Silvano.

**Comment by mmachet** [comment]
ok!

2015-05-11 11:15 GMT+02:00 syuvivida <notifications@github.com>:

**Comment by bendavid** [comment]
Hi Martina,
I'm not sure about the physics content of this.

Single top is always produced in association with an extra jet (and usually it's preferred to do the generation in the 4 flavour scheme where the additional bjet is explicit as well).  I would suggest to discuss with the top MC contacts/experts (mainly @maierbenedikt who has been handling the single top requests, and start from the default single top cards and add a photon)

Have you actually tried p p > t~ a [QCD]?  Are there any diagrams found?

**Comment by maierbenedikt** [comment]
Hi Martina, 

p p > t(~) a  will indeed give you no diagrams for the Standard Model, nor at LO or NLO.

I assume you want to generate the single-top t-channel (i.e. the dominant production mode) with a photon?

We have had an 8 TeV tGamma sample produced at LO:

https://cms-pdmv.cern.ch/mcm/requests?page=0&dataset_name=tGamma_8TeV_madgraph

We used basically the 5fs (b's in proton) to generate

p p > a t j

However, in the meanwhile, the trend goes to NLO in the 4fs, so this is why I would advise to do 


generate p p > t b~ j a $$ w+ w- [QCD] 
add process p p > t~ b j a $$ w+ w- [QCD]

and decay the top with MadSpin.
This should be straightforward and is in line with what we do for the normal t-channel and also for tZ.

**Comment by mmachet** [comment]
Hi Benedikt,
thanks for the prompt reply and the useful suggestions.
Josh, if you agree with Benedikt's proposal I'll change the cards and
commit them again.

Thanks

Martina

2015-05-12 16:29 GMT+02:00 maierbenedikt <notifications@github.com>:

**Comment by bendavid** [comment]
Yes, I agree that Benedikt's proposal makes sense.

**Comment by mmachet** [comment]
I changed the cards, hope to have put correctly the 4fs (I also changed 4 = maxjetflavor in run card).

Martina

**Comment by mmachet** [comment]
sorry, changing the name of the directory I did reset in order to eliminate the previous directory.
Now I did a new pull request (#382)

**Pull request closed without merging**
