### PR TITLE
bbH_ybyt 2017 acrds

### PR DESCRIPTION
**Pull request by panwarlsweet**
Hello,

Could you please tell me what should be the model file for this process. I have used 
"import model loop_sm_MSbar_ybyt" what I understand from here
https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/Higgs/SUSYGluGluToBBH/bbH_4FS_yb2_proc_card.dat#L17

The above link is for bbH_yb2 sample.

And in 2016 LHE files for this sample, I found "import model loop_sm_MSbar_yb" .

I tried to find these model file where all files are uploaded but couldn't get anything. Please help.

### CODE REVIEW

**Comment by qliphy** [comment]
Adding @wywdiablo , who may give an answer.

In the meantime, the following links might be useful:
    https://answers.launchpad.net/mg5amcnlo/+question/283103
    https://cp3.irmp.ucl.ac.be/projects/madgraph/wiki/bbH#no1

**Comment by panwarlsweet** [comment]
Thank you very much for providing these links. According to the links, I have corrected process card. Could you please have a look so that it could be merged?

**Comment by qliphy** [comment]
@panwarlsweet   Do you find the model  loop_sm_MSbar_yb  now?

As this is a specific model, probably you should consult with the original uploader @wywdiablo  and relevant group.

**Comment by panwarlsweet** [comment]
yes, I found this in the tarball uploaded here https://cp3.irmp.ucl.ac.be/projects/madgraph/wiki/bbH#no1 for MG_26X version and according to that I corrected my process card. But if @wywdiablo could also cross-check it then it would be more good for me to go ahead with grid-pack generation.

Thanks a lot.

**Comment by panwarlsweet** [comment]
oh Sorry. I took your sentence in a wrong way. Indeed I didn't find the model file but if all the process are using this model file then I should be able to find it.

**Comment by soarnsoar** [comment]
Hi all :)

I worked on the same process - bbH.

Also I found that the wiki provides only MG5 output directory, which means I cannot use genproduction code.

So, I extracted the UFO model part from the provided output and I succeeded  in gridpack generations by CMS genproduction code!

I finished the test and I want to share the extracted UFO model files.
Here's a link to the UFO model file that I extracted. 
@panwarlsweet , this must be what you want :)
http://147.47.242.72/USER/jhchoi/hww/bbh_ufo_model/loop_sm_MSbar_yb.tar


I want to show you how I took the UFO model part from the file. Please find the PDF below and check whether there's anything wrong.
http://147.47.242.72/USER/jhchoi/hww/how_to_extract_ufomodel/how_I_ran_mg5_bbh_to_HiggMC.pdf



Here are the gridpacks which I made : 
http://147.47.242.72/USER/jhchoi/hww/gridpacks/bbH_4FS_yb2_slc6_amd64_gcc630_CMSSW_9_3_8_tarball.tar.xz
http://147.47.242.72/USER/jhchoi/hww/gridpacks/bbH_4FS_ybyt_slc6_amd64_gcc630_CMSSW_9_3_8_tarball.tar.xz


If there's nothing wrong on the UFO model, could you upload the UFO model file to cms-project-generators?
https://cms-project-generators.web.cern.ch/cms-project-generators/


Thanks for reading all these long messages :)

**Comment by panwarlsweet** [comment]
@soarnsoar, you have shared which I wanted to know for the grid-pack generation. Thank you very very much for the help. Honestly, I thought the tar files are cards for bbH process. I didn't know these are UFO files. 

Also, you have generated the grid-packs also. 

And I don't know if I have access to upload these UFO model file in cms web page https://cms-project-generators.web.cern.ch/cms-project-generators/. If someone could confirm I will be happy to help in it. :)

Apart from these, I have checked my cards by extracting the grid-pack and updated them in github. I want this request to be merged to request the sample. Could you please tell me if anything else needs to be done for this?

Thanks,

Lata

**Comment by soarnsoar** [comment]
@panwarlsweet 

Maybe there's sth you misunderstand. The tar file in the wiki(https://cp3.irmp.ucl.ac.be/projects/madgraph/wiki/bbH#no1) is MG5 output directory which can generates events.

What I provided is a UFO model file which you need for "import model <UFO_MODEL>" in proc_card.dat.

About the cms-project-generator web(https://cms-project-generators.web.cern.ch/cms-project-generators/), gridpack_generation.sh script downloads necessary models from the web. But the bbh model is not uploaded there, so you cannot generate gridpack of bbH.

So, for bbH gridpack generation, what we need is to upload the UFO model to cms-project-generator.

@qliphy , Could you upload the UFO model to cms-project-generator web?

I extracted the UFO model file from the MG output dir provided in the author's wiki.
(https://cp3.irmp.ucl.ac.be/projects/madgraph/wiki/bbH#no1)

Please let me know if you have any question.

Cheers,

Junho

**Comment by panwarlsweet** [comment]
Hello Junho,

I got your point that how you generated grid-pack. You put the model file locally to call it in genproduction. And yes, you are right one needs to upload the grid-pack so that grid-pack generation script could take it from cms generator web. 

Thank you very much. I will wait for merging these cards so that I could generate the grid-pack with parameters I want for the process.

**Comment by soarnsoar** [comment]
Dear Lata, 

Yes. But only one point is missing. The gridpack generation script takes "UFO model file" from cms generator web. Not gridpack.

Best,

Junho

**Comment by qliphy** [comment]
@soarnsoar @panwarlsweet    I will upload the UFO model.  Just to make sure, it is this one, right?:
http://147.47.242.72/USER/jhchoi/hww/bbh_ufo_model/loop_sm_MSbar_yb.tar

But then do you also need a extramodels.dat to specify the model?

**Comment by soarnsoar** [comment]
Dear @qliphy ,

1) The file is right one.

2) About extramodel.dat, exactly. We need extramodels.dat for it.

The card should contain the line

loop_sm_MSbar_yb.tar

(When I made the gridpacks, I added some lines into "gridpack_generation.sh" to make it download the UFO model.)



3) By the way,  @Andrej-CMS  asked

why "3 = ickkw" , which means using FxFx. 

The process is NLO but has no additional parton in ME level.

So, "0 = ickkw" seems right.

**Comment by qliphy** [comment]
Yes, ickkw should be 0.

@panwarlsweet   Please take into account the above comments.  Thanks!

**Comment by panwarlsweet** [comment]
Dear all,

Thank you very much for help. I have made all the changes in the cards.

**Comment by qliphy** [comment]
Ok,    loop_sm_MSbar_yb.tar is uploaded now.

**Comment by soarnsoar** [comment]
Dear @qliphy ,

I am afraid that there seems wrong part in the UFO file.
If you download the file (http://147.47.242.72/USER/jhchoi/hww/bbh_ufo_model/loop_sm_MSbar_yb.tar) and untar it, you can see "restrict_no_yt.dat".

I guess that the name of the dat file means "ymt = 0" (OR ymt = not defined) . But the file contains
6 1.730000e+02 # ymt

which means ymt = 173. I think it should be ymt = 0 to restrict the process with no yt.


(If you check the author's outputfiles from the author's wiki - https://cp3.irmp.ucl.ac.be/projects/madgraph/wiki/bbH#no1,  you can see 
bbh_ybyt has ymt = 172.5
bbh_yb2 has ymt = none.
)

(Unless my thought is wrong) I want to suggest that we should review this UFO model because I extracted the file from the author's output by my hand, which means the model was NOT provided by the author. I already sent an email to the author to show how I extracted the UFO model but I haven't got reply yet.

Also, some of the parameters in the restrict_no_yt.dat seems outdated.


So, I want someone to review the UFO model and the parameters in it.


Thanks for reading :) I hope to make it right if there's sth wrong.


Best regards,

Junho

P.S.

Summary 
1. restrict_no-yt.dat has non-zero ymt. (seems not making sense)
2. also the parameters in it seem outdated.
3. I want a review by experts .

**Comment by qliphy** [comment]
Thanks @soarnsoar 

But if you check restrict_default.dat,  you can find 
          6 0.000000e+00 # ymt
so that is what then meant for.  The names for the restrict files are indeed confusing.

UFO is quite technical and physical and not a thing to be reviewed thoroughly by people here.  
as I mentioned above, it is better to get confirmation from the authors, : 
"As this is a specific model, probably you should consult with the original uploader @wywdiablo and relevant group."

**Comment by soarnsoar** [comment]
Dear @qliphy, and  @wywdiablo 

I sent an email to the author and got reply. Please find the below message from the author
========================================================
as I told you before, you cannot consistently create the bbH folders yourself, as it 
requires more than just a UFO model. You can create a restricted one where you set the 
ymt value to zero this is simple, but for yb you will not get the running of the MSbar 
mass. Therefore, you have to use the folders from the homepage.

Cheers,
Marius
========================================================

From the author's saying, I think the UFO model that I made could be inconsistent with the author's.

Then,

1) should we produce pLHE files by using the author's output folder?
2) In that case, the pLHE is consistent to other samples from genproductions code?
3) I cannot get MG5 v261 source from the madgraph homepage. If I run the author's output of v261 using MG261 from cms-project-generators page, all the jobs fail. Is there anyone who knows how to make a proper sample from the author's output folder?
4) Dear @panwarlsweet , the UFO model seems wrong. So. could you follow the author's suggestion on the wiki ?(https://cp3.irmp.ucl.ac.be/projects/madgraph/wiki/bbH#no1)

5) Dear @qliphy, sorry for  making thins go wrong. Could you remove the loop_sm_MSbar_yb.tar? The author says we should use his output folder. I guess we cannot use cms-genproductions code for this process.

Best regards,

Junho

**Comment by qliphy** [comment]
@soarnsoar   Thanks for the update.  Then it seems to me that we should rely on pLHE.

I would suggest the analyzers to study a bit more and report at GEN meeting at some moment (you are welcome to contact us when you are ready)

@efeyazgan do you know how to remove loop_sm_MSbar_yb.tar?  It seems permission needed.

**Comment by panwarlsweet** [comment]
Hello everyone,

I will create the LHE files using the instructions given on the shared page and then go for pLHE request. Thanks a lot for help and all the details.

**Comment by soarnsoar** [comment]
@panwarlsweet Thanks:) If you succeed in making pLHE files using the author"s ouput, could you let me know? (because I've failed to do it) . My cern account is 'jhchoi'.


Best,

Junho

**Comment by panwarlsweet** [comment]
Hello Junho and all,

I have created grid-pack for bbH_ybyt /afs/cern.ch/work/l/lata/public/ForPhilippe/bbH_4FS_ybyt_NNPDF31_MG230_13TeV_slc6_amd64_gcc630_CMSSW_9_3_8_tarball.tar.xz 

I used the instructions from here https://github.com/mflechl/bbH/blob/master/bbH-gridpacks.sh
This was used to make bbH_yb2 grid-pack. I repeated same for bbH_ybyt

Here are the instructions to generate LHE from this grid-pack https://github.com/mflechl/bbH/blob/master/bbH-gridpacks.sh#L46-L48

I created one LHE file with 100 events and it can be found here
/afs/cern.ch/work/l/lata/public/ForPhilippe/cmsgrid_final.lhe

Please let me know if here everything seems fine to everyone.

**Comment by panwarlsweet** [comment]
@qliphy and all,

could you please comment if now everything looks fine to you?

**Comment by qliphy** [comment]
@panwarlsweet   It looks good with a quick look.  However, as this MC request is special, I think it would be nice to have a presentation at GEN meeting and for wide discussion. 
Would you be available to make it at 26th, if it is not so late? 
https://indico.cern.ch/event/783803/

It would also be nice if you can make some validation plots.

**Comment by panwarlsweet** [comment]
@qliphy, most probably I should be able to present it in generator meeting. I will let you know once I have some validation plots.

**Comment by qliphy** [comment]
Thanks!  I have added you on the agenda of 26th GEN meeting
https://indico.cern.ch/event/783803/

**Pull request merged**
