### PR TITLE
Merge the intermediate master_powheg_gcc5 to master

### PR DESCRIPTION
**Pull request by perrozzi**
Second, final step of the powheg_gcc530 branch merge to master.
This powheg version supports the new, faster reweighting scheme.
@covarell succesfully tested a few processes after fixing some inconsistencies.
Once merged to master a larger scale test needs to be performed

### CODE REVIEW

**Comment by perrozzi** [comment]
in any case, the branch powheg_gcc48x will stay for any sort of back-compatibility need

**Comment by perrozzi** [comment]
@covarell let us know if this can be merged

**Comment by covarell** [comment]
yes!  @yuanchao

**Comment by covarell** [comment]
As soon as you merge I will update Twiki and send HN message.

**Comment by yuanchao** [comment]
I've went through the updated twiki. Gridpack production is fine except for a patch on the PDF info in LHE is dropped for the updated powheg source. I've done with an updated one and will create a PR for it.

**Pull request merged**
