### PR TITLE
four NLO higgs production processes

### PR DESCRIPTION
**Pull request by gourangakole**
A simple script is also added corresponding to each process to generate cards for different masses.

### CODE REVIEW

**Comment by gourangakole** [comment]
Dear @efeyazgan and @perrozzi ..
could you please check this cards?

**Comment by efeyazgan** [comment]
Could you please clean up the commented inputs and commands?

**Comment by gourangakole** [comment]
Thank you @efeyazgan. 
Now this should be fine.

**Comment by efeyazgan** [comment]
@perrozzi should the comments stay in  genproductions/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/Higgs/ggh012j_5f_NLO_FXFX_/ggh012j_5f_NLO_FXFX__MadLoopParams.dat

**Comment by bendavid** [comment]
The madloopparams file is not needed at all with this process anymore (was needed in madgraph 2.2.x and older)

**Comment by efeyazgan** [comment]
Thanks @bendavid. 
Then, @gourangakole please remove the file.

**Comment by gourangakole** [comment]
Thank you @bendavid  and @efeyazgan for the clarification. 
Now should be fine.

**Pull request merged**
