### PR TITLE
Mg261 Condor Support

### PR DESCRIPTION
**Pull request by qliphy**
https://github.com/cms-sw/genproductions/issues/2237

### CODE REVIEW

**Comment by soarnsoar** [comment]
Hi Qiang. I found that this PLUGIN/CMS_CLUSTER is not copied to mgbasedir when using submit_cmsconnect_gridpack_generation.sh

I don't know what causes this problem yet.

**Comment by qliphy** [comment]
@soarnsoar   Can you give me a log for this?

**Comment by qliphy** [comment]
@soarnsoar  It seems with cms_connect we still have the issue "root: cms_condor is not recognized as a supported cluster format."  A quick workaround is to change in gridpack_generation.sh from "cms_condor" to "condor" in several places.   In the meantime, we have a further check for cms_condor support .

**Comment by soarnsoar** [comment]
@qliphy , 
You can find the logfile here :

/afs/cern.ch/work/j/jhchoi/public/logfiles/mg261_dy0j_lo_cmscluster_Cp/


But I don't understand why this line 

https://github.com/cms-sw/genproductions/blob/0f4c6a90737f2424c3805494057b98343f9bbbdb/bin/MadGraph5_aMCatNLO/gridpack_generation.sh#L121

doesn't work when running submit_cmsconnect_gridpack_generation.sh.

When I ran the gridpack gen with "gridpack_generation.sh"at cms connect, the "CMS_CLUSTER" directory was copied properly. But when with submit_cmsconnect_gridpack_generation.sh, it wasn't.


This is what I observed. I haven't investigaed it further yet sorry. But please note that this symptom is only for "submit_cmsconnect_gridpack_generation.sh" script.

**Comment by qliphy** [comment]
@soarnsoar    Should be solved with #2284 and #2285 
Would you please have a test? Thanks!

**Pull request merged**
