### PR TITLE
Use the automatic PDF setting

### PR DESCRIPTION
**Pull request by jheikkil**

### CODE REVIEW

**Comment by qliphy** [comment]
Looks good to me.  But please set bwcutoff to 15.

**Comment by jheikkil** [comment]
Thanks for pointing that out to me! I guess AtoZh_M340 was the only one left with 15000? Could you confirm, please?

**Comment by qliphy** [comment]
Looks good now. Thanks!

**Comment by jheikkil** [comment]
Thanks for all the help! For future reference, could the twiki page be clarified with all this information?

**Comment by qliphy** [comment]
Yes, of course.  The basic message is already in the hn announcement
https://hypernews.cern.ch/HyperNews/CMS/get/generators/4164.html

We will make the twiki more clear.

**Pull request merged**
