### PR TITLE
add ggZZ012j_MLM cards for VBS ZZ

### PR DESCRIPTION
**Pull request by colizz**

### CODE REVIEW

**Comment by qliphy** [comment]
+1 @agrohsje

**Comment by agrohsje** [comment]
Hi @colizz . How will qcut be choosen. I saw that xqcut is quite low. But just curious.

**Comment by colizz** [comment]
Hi @agrohsje , thanks for your comments. 
We indeed had a study on xqcut in VBS ZZ analysis. We found that for loop induced events, ISR jets can be emitted directly from loop, resulting in generally softer jets. The below slide shows the cross-section and DJR plots with (xqcut, qCUT)=(5, 10) compared with conventional value (10, 20), indicating that the former seems a better choice for this process.
https://docs.google.com/presentation/d/1GHpPyWbML7fMkCkEl7XaDyDBkHRY73vuYr_XG0uZodo/

**Comment by agrohsje** [comment]
With "bad" you are referring to the second plot in the upper row, with the red circle? Do you have more qcut plots for xqcut 10? The acceptance is very low with 5/15.

**Comment by colizz** [comment]
Hi,
It's also because there is a hollow from the first plot in the upper row (error bar cannot compensate this), indicating the unsmooth stitching. We did not try more qCUT plots, but simply choose the recommended qCUT value based on xqcut. 
Indeed the acceptance is low, but we already produced enough LHE given this 8% matching rate (since the generation time is beyond McM limit we chose the pLHE campaign), so there's not so much to worry.

**Comment by agrohsje** [comment]
Thanks for the info. Maybe that is something to follow-up if we want to go for gridpacks. Will merge.

**Comment by colizz** [comment]
Many thanks!

**Pull request merged**
