### PR TITLE
add madspin grid mode patch

### PR DESCRIPTION
**Pull request by DickyChant**
This patch is a temporary solution for MadSpin grid running. 

More details can be found in [https://bugs.launchpad.net/mg5amcnlo/+bug/1955614](https://bugs.launchpad.net/mg5amcnlo/+bug/1955614)

### CODE REVIEW

**Comment by sihyunjeon** [comment]
Should we wait for Oliver to confirm the patch is ok?

**Comment by DickyChant** [comment]
I agree and I think finally nothing will be merged as the MadSpin issue can be fixed by MG5 side :)

**Comment by sihyunjeon** [comment]
So this wasn't an issue for mg265 (current master branch)?

**Comment by agrohsje** [comment]
@DickyChant @sihyunjeon . do you have any news about this pr.

**Comment by DickyChant** [comment]
> @DickyChant @sihyunjeon . do you have any news about this pr.

According to Oliver's response [1], this is now being integrated to the MG5 developing version. So I guess after a short period of time we can close this PR :)



> So this wasn't an issue for mg265 (current master branch)?

Sorry for my late reply. The answer is "yes" as that codes are newly added to MG5.

**Comment by agrohsje** [comment]
we agreed to merge the pr and remove once we move to a version with central fix.

**Pull request merged**
