### PR TITLE
diphoton card modification

### PR DESCRIPTION
**Pull request by gourangakole**
Diphoton card fix by removing .true. = reweight_PDF.
It was discussed in [here](https://github.com/cms-sw/genproductions/issues/1640)

### CODE REVIEW

**Comment by efeyazgan** [comment]
Could you please remove those lines instead of commenting?
(i.e. these lines:
+#.true. = reweight_PDF ! reweight to get PDF uncertainty
+#292201 = PDF_set_min ! First of the error PDF sets
+#292302 = PDF_set_max ! Last of the error PDF sets )

**Comment by efeyazgan** [comment]
Sorry that it comes in parts but could you please remove
#***********************************************************************
# MadGraph5_aMC@NLO *
# *
# run_card.dat aMC@NLO *
# *
# This file is used to set the parameters of the run. *
# *
# Some notation/conventions: *
# *
# Lines starting with a hash (#) are info or comments *
# *
# mind the format: value = variable ! comment *
#***********************************************************************
#

**Comment by gourangakole** [comment]
Sorry, I do not get.
I see first few lines are there in latest merged run card. For examples 

https://github.com/zenaiev/genproductions/blob/fa3906d3d60b6d72beb7cf35c58bb7575f7c059c/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/TT_FCNC/refcards/madgraph_card/TT_no_top_decay_LO_run_card.dat#L1-L13

**Comment by efeyazgan** [comment]
sorry I thought this was proc card (but it looks unnecessary as well).

**Comment by perrozzi** [comment]
shall be merged then?

**Comment by efeyazgan** [comment]
Yes, unless you see a problem.

**Pull request merged**
