### PR TITLE
Requesting Z(->qqbar) + Jets

### PR DESCRIPTION
**Pull request by rappoccio**
For EXO VV all-hadronic analysis, we need Z+Jets, where Z decays hadronically. We only request HT > 600 GeV because the trigger cannot go any lower.

### CODE REVIEW

**Comment by bendavid** [comment]
Are you sure you don't want the gamma* contribution here?

**Comment by rappoccio** [comment]
Hi Josh,

I've been going back and forth on this myself. The chances are slim that we'll be able to see this at all (it's hidden under multijets). @ahinzmann may disagree, but I think we just need the on-shell Z production. 

Cheers,
Sal

**Comment by ahinzmann** [comment]
I think we need no gamma*, only Z. Anything that is not peaky is for sure not visible at all under multijets. ALTAS showed they see W(qq)+jets, that's why we have this Z(qq)+jets as well.

**Comment by bendavid** [comment]
Ok, given that the modification to the shape of the peak from interference will be ~completely washed out by the jet resolution, agreed this makes sense.  (Also practically it's probably not possible to do the full 6 jet process with Z/gamma* interference)

**Comment by rappoccio** [comment]
Thanks Josh!

**Pull request merged**
