### PR TITLE
Adding decay-hadronization fragment for VBF Hgg powheg

### PR DESCRIPTION
**Pull request by OlivierBondu**

### CODE REVIEW

**Comment by bendavid** [comment]
Do the powheg LHE files have an SLHA table as in the madgraph case?  If so, may want to also include SLHA:useDecayTable = off to avoid similar problems.

**Comment by OlivierBondu** [comment]
I see nothing of the sort in the gridpack output

**Comment by OlivierBondu** [comment]
@bendavid : actually re-reading an old email thread of ours: should'nt we add '25:m0 = 125.0' ?
You were mentionning the reading of the Higgs mass from the lhe header was disabled

**Comment by bendavid** [comment]
Ah, yes, forgot about that, sorry.  Please make another pull request updating it.

**Pull request merged**
