### PR TITLE
Additional Mono-Higgs model cards, updated ZpBaryonic and Scalar cards

### PR DESCRIPTION
**Pull request by dburns7**
This request is to review and add the remaining mono-Higgs model cards, including one new simplified model (ZpHS) and five EFT models (EFT_HHxg5x, EFT_HHxx_combined, EFT_HHxx_scalar, EFT_xdxHDHc, and EFT_xgxFHDH). There is a small chance that additional EFT models will be added, but these will be relatively small compared with this request. Please let me know of any necessary modifications.

### CODE REVIEW

**Comment by dburns7** [comment]
What is the progress of reading these cards? Thanks.

**Comment by covarell** [comment]
Are all these models available as zipped archives in the generator afs area?

**Comment by dburns7** [comment]
Yes, right Eiko?



Dustin Burns
Physics Department
University of California, Davis

**Comment by syuvivida** [comment]
They are already in the afs generator area.

**Pull request merged**
