### PR TITLE
update HH bbVV 2l2nu high mass fragment

### PR DESCRIPTION
**Pull request by covarell**
@clacaputo @acarvalh
Following our discussion with Ilya Kravchenko on 2019 MC, I update the fragment to be with 2l2nu final states only.

### CODE REVIEW

**Comment by covarell** [comment]
Please hold on because there seems to be a problem with this request

**Comment by agrohsje** [comment]
Hi @covarell , should I close this PR or was it ok? I try to clean up a little bit.

**Comment by covarell** [comment]
This sample is no longer needed, honestly I do not remember the problem rafter 2 years :-)

**Comment by agrohsje** [comment]
Thanks @covarell. Let me close and clean up a little bit.

**Pull request closed without merging**
