### PR TITLE
WZ + 0j @NLO request

### PR DESCRIPTION
**Pull request by vuko-brigljevic**
This is a WZ + 0j configuration, created from the 13 TeV configuration, but taking only
0 jets, and changing ickkw to 0, and jetradius to 0.7.

### CODE REVIEW

**Comment by bendavid** [comment]
Can you remove the FXFX cards for now?

**Comment by vuko-brigljevic** [comment]
Hi Josh,

Sure, but as I am still pretty confused with git, let me
ask for the procedure, I would guess:

git rm WZTo3LNu01j_5f_NLO_FXF/<all_files>
git rm WZTo3LNu01j_5f_NLO_FXF

git commit -m "put here a comment"
 git pull --rebase upstream master
git push origin master

Is this enough?

Cheers,
Vuko



On Tue, Aug 18, 2015 at 7:58 PM, Josh Bendavid <notifications@github.com>
wrote:

> Can you remove the FXFX cards for now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/genproductions/pull/587#issuecomment-132297739>
> .
>



-- 
Vuko Brigljevic
Rudjer Boskovic Institute
Bijenicka 54, HR-10000 Zagreb (Croatia)
Phone: +385-1-4571318 GSM: +385-98-965 8104
Swiss GSM (while @ CERN): +41-76-278 3615
* Currently at CERN *

**Comment by bendavid** [comment]
No, if you're just updating an existing branch you don't need to do
"git pull --rebase upstream master"

the rest looks correct.

**Comment by vuko-brigljevic** [comment]
Hi Josh,

Thanks for the help! Done, and I see it's
gone from my repository:

https://github.com/vuko-brigljevic/genproductions/tree/master/bin/MadGraph5_aMCatNLO/cards/production/8TeV

Cheers,
Vuko

On Tue, Aug 18, 2015 at 8:23 PM, Josh Bendavid <notifications@github.com>
wrote:

> No, if you're just updating an existing branch you don't need to do
> "git pull --rebase upstream master"
>
> the rest looks correct.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/genproductions/pull/587#issuecomment-132307476>
> .
>



-- 
Vuko Brigljevic
Rudjer Boskovic Institute
Bijenicka 54, HR-10000 Zagreb (Croatia)
Phone: +385-1-4571318 GSM: +385-98-965 8104
Swiss GSM (while @ CERN): +41-76-278 3615
* Currently at CERN *

**Comment by vuko-brigljevic** [comment]
Can I now start producing the gridpacks according to

https://twiki.cern.ch/twiki/bin/viewauth/CMS/QuickGuideMadGraph5aMCatNLO

?

Cheers,
Vuko


On Tue, Aug 18, 2015 at 8:38 PM, Josh Bendavid <notifications@github.com>
wrote:

> Merged #587 <https://github.com/cms-sw/genproductions/pull/587>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/genproductions/pull/587#event-385691441>.
>



-- 
Vuko Brigljevic
Rudjer Boskovic Institute
Bijenicka 54, HR-10000 Zagreb (Croatia)
Phone: +385-1-4571318 GSM: +385-98-965 8104
Swiss GSM (while @ CERN): +41-76-278 3615
* Currently at CERN *

**Comment by bendavid** [comment]
Yes

**Comment by vuko-brigljevic** [comment]
Running... I let you know when it's done.

On Tue, Aug 18, 2015 at 9:09 PM, Josh Bendavid <notifications@github.com>
wrote:

> Yes
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/genproductions/pull/587#issuecomment-132320963>
> .
>



-- 
Vuko Brigljevic
Rudjer Boskovic Institute
Bijenicka 54, HR-10000 Zagreb (Croatia)
Phone: +385-1-4571318 GSM: +385-98-965 8104
Swiss GSM (while @ CERN): +41-76-278 3615
* Currently at CERN *

**Pull request merged**
