### PR TITLE
Parsing  code cleanup 

### PR DESCRIPTION
**Pull request by lorusso7**
I cleanup the parsing.py, I removed the all "~" files and I moved the cards in a  into a subfolder

### CODE REVIEW

**Comment by perrozzi** [comment]
thanks lorenzo, looks good to me. out of curiosity, do the example datacards contain errors to show possible examples of error/warning messages from the parseer, or are they just regular cards? I wonder if there is some duplication wrt the "standard" datacards already present in the repository

**Comment by perrozzi** [comment]
ping

**Comment by lorusso7** [comment]
Hi Luca, sorry for the delay reply. 
The  run/proc  datacards for "tt012j_5f_ckm_NLO_FXFX" come from "standard" datacards already present in the repository and they works fine for the gridpack production.
Instead I modified the other cards to show  some errors or warnings. In particular 
-in dyellell012j_5f_NLO_FXFX cards the proton is defined two times.
-in dyellell01234j_5f_LO_MLM cards the pdf set used is wrong.
-in  WJetsToLNu_HT-incl cards there is a double "lhaid" declaration.
Do you suggest to put a description in the README?

**Comment by perrozzi** [comment]
that would be very useful, thanks

**Comment by lorusso7** [comment]
I added a brief description of the  datacards errors  in the readme

**Pull request merged**
