### PR TITLE
Make MG  v2.5.5 default for 25x branch

### PR DESCRIPTION
**Pull request by kdlong**
All patches work in the current form. Tested a simple NLO gridpack without problems. Did not test any more complicated features. @bendavid did you have anything else in mind?

### CODE REVIEW

**Comment by bendavid** [comment]
Not sure we want to have 0j FXFX cards in the examples (since these actually won't produce correct physics results)

**Comment by kdlong** [comment]
Oops right. Fixed the name and matching. I added it because it's nice to have something quick to run when testing things but can remove it if others don't find it useful.

**Comment by bendavid** [comment]
Ok, that was supposed to be the purpose of wplustest_5f_NLO and wplustest_4f_NLO in fact.  (These are even faster to run because they are 2->1.

Otherwise looks fine to me.

**Comment by perrozzi** [comment]
@kdlong @vciulli @qliphy please confirm when ready to merge

**Comment by perrozzi** [comment]
what's the status here?

**Comment by kdlong** [comment]
From my perspective it's ready, but I can remove the DY cards if others prefer them to not be there.

**Comment by bendavid** [comment]
I think it's better to remove the drell yan cards as it may confuse people.  Or at least remove 0j from the name to be consistent with the usual naming scheme for non-merged samples.

**Comment by kdlong** [comment]
Replaced by #1231

**Pull request closed without merging**
