### PR TITLE
WGGJets and ZGGJets for 2017

### PR DESCRIPTION
**Pull request by gourangakole**
Original card are taken from [1](https://github.com/cms-sw/genproductions/tree/pre2017/bin/MadGraph5_aMCatNLO/cards/production/13TeV/WGGJets_5f_LO_MLM), [2](https://github.com/cms-sw/genproductions/tree/pre2017/bin/MadGraph5_aMCatNLO/cards/production/13TeV/ZGGJets_ZToHadOrNu_5f_LO_MLM) and [3](https://github.com/cms-sw/genproductions/tree/pre2017/bin/MadGraph5_aMCatNLO/cards/production/13TeV/ZllGGJets_5f_LO_MLM)
then changed the pdf and applied cleaning.

### CODE REVIEW

**Comment by efeyazgan** [comment]
You should set
T        = pdfwgt

**Comment by gourangakole** [comment]
Thank you @efeyazgan . Could you check once please.

**Comment by efeyazgan** [comment]
auto_ptj_mjj should be set to T (unless there is a specific reason for not doing it).

**Comment by gourangakole** [comment]
Hello @efeyazgan .... updated that too. I was not sure that is recommended for 2017.

**Pull request merged**
