### PR TITLE
Updated Cards for RunII

### PR DESCRIPTION
**Pull request by aashaqshah**
Hello, 
Please merge the pull request. We have updated run cards (lower cuts have been used for muons and jets) as per the discussions within the Exo group for the signature h->aa->bbmm. Since the samples haven't been simulated yet, we hope it is quite acceptable. 
Presetation have been made in the Exo-group and paths to gridpacks are:
h->aa->mmbb (ggF): /afs/cern.ch/user/a/aashah/public/GridPacks/h_aa/ggH
h->aa->mmbb (vbf): /afs/cern.ch/user/a/aashah/public/GridPacks/h_aa/vbf
h->Za->mmbb (ggF): /afs/cern.ch/user/a/aashah/public/GridPacks/h_Za

Thank you.

Best,
-Aashaq
On behalf of the mmbb group

### CODE REVIEW

**Comment by qliphy** [comment]
+1 @agrohsje

**Comment by agrohsje** [comment]
@aashaqshah gridpack_generation.sh in master is already using 2.6.5. It seems you make this PR from a very old branch using 2.4.2. I still see syscalc in the file. Can you please update your repo to master and then just commit the run_card that need adjustement. There is no need to modify gridpack_generation.sh. Note that just changing the mg5 version is in general no good idea as patches are tailored to specific versions. So one should not just modify the version by hand and leave everything else. Anyway master is 2.6.5 and modifying the run_cards is sufficient.

**Comment by aashaqshah** [comment]
> @aashaqshah gridpack_generation.sh in master is already using 2.6.5. It seems you make this PR from a very old branch using 2.4.2. I still see syscalc in the file. Can you please update your repo to master and then just commit the run_card that need adjustement. There is no need to modify gridpack_generation.sh. Note that just changing the mg5 version is in general no good idea as patches are tailored to specific versions. So one should not just modify the version by hand and leave everything else. Anyway master is 2.6.5 and modifying the run_cards is sufficient.

Thank you @qliphy .
I will follow your suggestions. Also, when you say you still find "syscalc" in the file, are you suggesting to remove the following lines also from the run_card.dat?
#
#*********************************************************************
# Store info for systematics studies                                 *
# WARNING: If use_syst is T, matched Pythia output is                *
#          meaningful ONLY if plotted taking matchscale              *
#          reweighting into account!                                 *
#*********************************************************************
 F  = cut_decays      ! Enable systematics studies
 T = use_syst

Thank you,

Best,
-Aashaq

**Comment by agrohsje** [comment]
Options can and should be kept.  Just make sure you pick up runcmsgrid, gridpack_generation and everything from master. Then you can remove this part from the PR and the cards are ok.

**Comment by agrohsje** [comment]
superseeded by https://github.com/cms-sw/genproductions/pull/2685

**Pull request closed without merging**
