### PR TITLE
tt+ll lowmass cards

### PR DESCRIPTION
**Pull request by cericeci**
Fixed the cuts file for low mass TT+LL production to run on master branch. Gridpack can now be produced without fortran compilation problems

### CODE REVIEW

**Comment by agrohsje** [comment]
Is this based on 2.6.5 cuts.f ? 
What are the production plans for this sample?

**Comment by cericeci** [comment]
I adapted the old 2.4.2 file to run on 2.6.5 rather than starting from scratch with the 2.6.5 template.  In retrospective it might not be the best idea in case the process card is modified, so I can refactor it to the later for consistency if needed.

The plan was to use this one for UL production.

**Comment by agrohsje** [comment]
Please see my proposal here: 
https://www.desy.de/~agrohsje/hidden/TTZJetsToLL_M-1to10_5f_NLO_cuts.f
It starts from 2.6.5 and should include your cuts. Please double-check and update the PR if ok with you.

**Comment by cericeci** [comment]
Many thanks for the help @agrohsje. I merged your proposal, reproduced the gridpack and checked that it matches what we need.

**Comment by sihyunjeon** [comment]
@agrohsje @cericeci 
I have one naive question about the naming of the gridpacks. It's named TTZJets while it doesn't have multiparton process added (surely you'd get additional partons from QCD NLO calculations but I am talking about the ME level added jets) while TTWJets has additional jets as in [1]. Wouldn't it be better to add one jet and do FxFx matching for this as well?

[1] https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/TTWJets/TTWJetsToLNu_5f_NLO_FXFX/TTWJetsToLNu_5f_NLO_FXFX_proc_card.dat

**Comment by agrohsje** [comment]
Hi @cericeci . I brought the same up in MCM. Let us know if the proposal above of adding one jet is what you like or not. If you don't want to redo production, we could still sync the settings and have one additional jet and ickkw=3 here.

**Comment by sihyunjeon** [comment]
@agrohsje should we not close this?

**Comment by agrohsje** [comment]
Will merge now.

**Pull request merged**
