### PR TITLE
Pdf last sync before production

### PR DESCRIPTION
**Pull request by perrozzi**
following https://github.com/cms-sw/genproductions/issues/1287

### CODE REVIEW

**Comment by kdlong** [comment]
Some of these PDFs (32XXXX) are not in the LHAPDF set in CMSSW_7_1_28.

**Comment by kdlong** [comment]
I don't see them in any current CMSSW version. I vote we exclude these from the list and then add them in 1-2 weeks when the LHAPDF version can be updated.

@bendavid, are there specific samples that should be put on hold until we have this?

**Comment by perrozzi** [comment]
btw, are ALL the other PDFs available both in 71x and 92x/93x ?

**Comment by bendavid** [comment]
Well I think the alphaS variations are in principle desirable for all V+jets and ttbar samples...

**Comment by kdlong** [comment]
For 5F, yes I think so. For 4F, no.

```grep 320900 /cvmfs/cms.cern.ch/slc6_amd64_gcc530/*/lhapdf/*/share/LHAPDF/pdfsets.index``

Gives no matches.

**Comment by perrozzi** [comment]
https://www.hepforge.org/archive/lhapdf/pdfsets/6.2/ being added to cvmfs, it should have them all

**Comment by perrozzi** [comment]
includes #1308

**Comment by perrozzi** [comment]
@covarell @yuanchao this PR contains substantial reorganization of make_rwl.py (use dictionaries and a single loop to store PDFs, added new PDF sets, allow 4F sets) and integration inside run_pwg.py (i.e. pwg-rwl.dat produced automatically at process compilation time checking 4F and 5F by process name, few checks and warnings added)

please test

**Comment by yuanchao** [comment]
Hi, Just did a quick test with DMGG process... I don't see the corresponding codes in master. So I try to checkout from perrozzi:pdfsync. A show stopper is that the make_rwl.py is done AFTER the PDF checks. So the script fails anyway...

`
if [[ $is5FlavorScheme -eq 1 ]]; then
  echo "INFO: The process $process uses the 5F PDF scheme"
else
  echo "INFO: The process $process uses the 4F PDF scheme"
fi

# enforce standard pdfs?
echo "INFO: PDF set for central value: ${teststandpdf}"
if ([[ $is5FlavorScheme -eq 1 ]] && [[ ${teststandpdf} -ne 306000 ]]) || ([[ $is
5FlavorScheme -eq 0 ]] && [[ ${teststandpdf} -ne 320900 ]]) ; then
   if [ $noPdfCheck == '0' ] ; then
      fail_exit "WARNING: The input card does not have the standard 2017 PDF (NN
PDF31 NNLO, 306000 for 5F, 320900 for 4F). Either change the card or run again w
ith -d 1 to ignore this message. Exiting now..."
   else 
      echo "WARNING: FORCING A DIFFERENT PDF SET FOR CENTRAL VALUE wrt standard 
2017 (NNPDF31 NNLO, 306000 for 5F, 320900 for 4F)"
   fi
fi

cd $WORKDIR
python make_rwl.py ${is5FlavorScheme} ${teststandpdf}
cd ${name}
`

> INFO: The process DMGG uses the 5F PDF scheme
> INFO: PDF set for central value: 260000
> WARNING: The input card does not have the standard 2017 PDF (NNPDF31 NNLO, 306000 for 5F, 320900 for 4F). Either change the card or run again with -d 1 to ignore this message. Exiting now...

**Comment by perrozzi** [comment]
Hi @yuanchao, I am not sure I understand. 
1) `perrozzi:pdfsync` is merged into `cms-sw:master` (i.e. this PR) so you should be able to get the modifications, please try again and let me know if you still have problems
2) I am not sure what you refer to as "show stopper". The PDF check, originally implemented by Roberto, in your case "correctly" fails because
`WARNING: The input card does not have the standard 2017 PDF (NNPDF31 NNLO, 306000 for 5F, 320900 for 4F). Either change the card or run again with -d 1 to ignore this message. Exiting now...`
as suggested in the WARNING message, you are running a 5F process and have different central PDF (260000) wrt the default 2017 one (306000). You can force the script to continue if you really want to use them (in your case is a test so doesn't matter) adding the argument `-d 1`. I tested extensively and it works, for instance compiling with:
`python ./run_pwg.py -p 0 -i powheg.input -f test -m DMGG -d 1`
Please try again and let me know if you still have problems

**Comment by yuanchao** [comment]
Sorry it seems that I mixed up with the stuff that checked out days before the merge is done. I just clean up everything and try again. The make-rwl part is working with the cms-sw:master.

As to PDF check, the error only shows up after the generated shell script is running. This means that if the check is failed, I'll know it only after the submitted jobs exits. Would it be better to be done in the driving python script, run_pwg.py?

**Comment by perrozzi** [comment]
good idea, can you please do it?

**Comment by yuanchao** [comment]
Give me some time.

**Comment by perrozzi** [comment]
@yuanchao when do you think you will have it ready?

**Comment by yuanchao** [comment]
CF #1339

**Pull request merged**
