### PR TITLE
adding single top tW DS cards

### PR DESCRIPTION
**Pull request by maierbenedikt**

### CODE REVIEW

**Comment by covarell** [comment]
The fact that there is no storerwgtinfo etc. is because these are still for powheg V1?

**Comment by maierbenedikt** [comment]
Hi Roberto, Yes, exactly!

**Comment by covarell** [comment]
Excellent, I may be wrong but is there a reason why we do not use pdf 263000 here? (Also a question to @bendavid )

**Comment by maierbenedikt** [comment]
263000 is the LO version if I am not mistaken:

NNPDF30_lo_as_0130


I was under the impression that 292200 (NNPDF30_nlo_nf_5_pdfas) was the "state-of-the-art" for 5FS NLO PDFs.

**Comment by bendavid** [comment]
263000 is indeed LO.

292200 and 260000 have identical central values (nnpdf30 nlo alpha_s=0.118 5f).  The only difference is that 292200 includes alphas variations as additional members of the central set, rather than as completely separate sets.  This is needed for aMC@NLO due to the current limitations on including multiple pdf sets.  For powheg 260000 or 292200 can be considered equivalent as long as the alpha_s variations are anyways included separately.

**Pull request merged**
