### PR TITLE
Cards for EXO-RunIIWinter15wmLHE for Dark Matter MonoPhoton

### PR DESCRIPTION
**Pull request by davidsheffield**
from Bhawna Gomber

### CODE REVIEW

**Comment by stosi** [comment]
For LO 4 flavour scheme, the PDF should be
'lhapdf'    = pdlabel     ! PDF set                                  
 263400    = lhaid     ! if pdlabel=lhapdf, this is the lhapdf number

**Comment by davidsheffield** [comment]
What PDF will be used when we change it to `'lhapdf' = pdlabel ! PDF set`?

**Comment by stosi** [comment]
It will take the value indicated in the following line, i.e. 263400

**Comment by davidsheffield** [comment]
Bhawna updated the cards and I added the changes to this PR.

**Comment by gomber** [comment]
Could you please tell if there is something missing in these cards? And how much time will it take to merge these cards?

**Comment by bendavid** [comment]
The pdfs are still not right (some of the cards are still not using lhapdf with 263400)

**Comment by gomber** [comment]
Yes I see the axial vector case had the issue. I corrected all the cards again and you can find it here:
/afs/cern.ch/user/g/gomber/public/13TeVCards/12May

**Comment by davidsheffield** [comment]
I've added those changes to the PR.

**Comment by gomber** [comment]
Thanks David,
Josh could you please see if it looks fine, so that
I can get the gridpacks during the weekend.

Regards
Bhawna
________________________________

**Comment by bendavid** [comment]
DarkMatter_MonoPhoton cards look ok.   (and you can already start producing gridpacks for these if you like)

There are some remaining issues with the W/Z cards.  (and sorry I did not see these before, since  the diff was too long to show in the web interface)

1) For consistency with other samples, suggest to use sm-ckm_no_b_mass
2) these are 5f samples (and this is strongly preferred), so pdf and other settings need to be consistent with 5f.  In addition, some other settings are needed since these processes are set up for jet matching.  Suggest to start from example 5f LO jet matching run card in
https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/cards/examples/dyellell01234j_5f_LO_MLM/dyellell01234j_5f_LO_MLM_run_card.dat
3) please remove the redundant files with ~ at the end (some backup files that probably got added to git by mistake)

**Comment by gomber** [comment]
Hi Josh and David

I completely forgot about W/Z+gamma samples which I requested earlier and saw this thread and did the changes in the card as suggested by Josh.

Cards are present here 
/afs/cern.ch/user/g/gomber/public/13TeVCards/12May/
Wgamma_Monophoton_Ptg130_2jets  
Zllgamma_Monophoton_Ptg130_2jets  
Znunugamma_Monophoton_Ptg130_2jets

Could you please update the git and see if eveything is fine, then I will go ahead and prepare 
gridpacks. So if both of you can have a look, it will be great.

Regards
Bhawna

**Comment by bendavid** [comment]
Sorry I think something has gotten screwed up in these updates.
I see now again
"+  nn23lo1	=  pdlabel      ! PDF set                                     
+  230000	=  lhaid      ! if pdlabel=lhapdf, this is the lhapdf number"
in the darkmatter cards, so the pdfs are again incorrect.

In addition, the extra files with "~" in the filename are still there for the W/Z cards. And for these cards the model was not updated as suggest (to sm-ckm_no_b_mass), the pdfs are incorrect, the run card settings are not consistent for 5fs, and the ickkw setting is not correct for jet matching.

**Comment by gomber** [comment]
I think something got screweed while copying to git, because in my public area where I copied the cards, I see the right pdf for dark matter samples, I do see the right PDF set 
  'lhapdf'      =  pdlabel      ! PDF set
  263400        =  lhaid      ! if pdlabel=lhapdf, this is the lhapdf number

And then in the W/Z card, I do see model sm-ckm_no_b_mass) and right pdf's 
  'lhapdf'      =  pdlabel      ! PDF set
   263000       =  lhaid      ! if pdlabel=lhapdf, this is the lhapdf number

David, could you please see whether you have copied the cards correctly from here
/afs/cern.ch/user/g/gomber/public/13TeVCards/12May

**Comment by davidsheffield** [comment]
There are no backup files with ~ in their name in the current head of this branch. Could you be looking at an old commit? https://github.com/davidsheffield/genproductions/tree/cards2/bin/MadGraph5_aMCatNLO/cards/production/13TeV/Wgamma_Monophoton_Ptg130_2jets

**Comment by gomber** [comment]
Also I just saw here as pointed by David
 https://github.com/davidsheffield/genproductions/tree/cards2/bin/MadGraph5_aMCatNLO/cards/production/13TeV

All the cards looks fine and has right pdlabel and lhaid.
Could you please see again?

Regards
Bhawna


________________________________

**Comment by bendavid** [comment]
Ok sorry indeed it was my confusion in checking the long diff (github orders the commits sequentially when looking at the "patch" form)

I'll look again.

**Comment by gomber** [comment]
Hi Josh, 

Did you get a chance to look again?
I will be on a vacation starting from Saturday and would like to get this done before that.

Regards
Bhawna

**Comment by bendavid** [comment]
So what I think are the last issues.
For the W/Z cards maxjetflavour needs to be set to 5 for consistent 5fs.
Then the lepton cuts should be relaxed (2.5 at lhe level is not really safe with respect to the acceptance)
Safest is just to remove the lepton pt and eta cuts entirely.

**Comment by gomber** [comment]
Thanks Josh, I wil fix these issues now and will update the cards again.
________________________________

**Comment by gomber** [comment]
Hi David, Josh

I have updated the cards and you can find the updated W/Z cards at the same palce :
/afs/cern.ch/user/g/gomber/public/13TeVCards/12May

David could you please update the git, and I think with this I can produce the gridpacks.? Right?
________________________________
From: Bhawna Gomber
Sent: 17 July 2015 15:28
To: cms-sw/genproductions; cms-sw/genproductions
Subject: RE: [genproductions] Cards for EXO-RunIIWinter15wmLHE for Dark Matter MonoPhoton (#388)

Thanks Josh, I wil fix these issues now and will update the cards again.
________________________________

**Comment by davidsheffield** [comment]
I've updated the W and Z cards.

**Comment by bendavid** [comment]
etal needs to be -1 rather than 0

**Comment by gomber** [comment]
Again updated with etal=-1 and cards are present again here:
/afs/cern.ch/user/g/gomber/public/13TeVCards/12May
________________________________

**Comment by davidsheffield** [comment]
The PR is already updated. 3435c3a

**Comment by bendavid** [comment]
Ok thanks, this looks good now.  In the future please don't mix very different physics processes in a single large pull request (since that slowed things down a lot in this case)

**Comment by gomber** [comment]
Thanks Josh!
Yes you are right it took longer because of different processes merged togehter.
________________________________

**Comment by gomber** [comment]
One more question in order to prepare gridpacks for Dark matter EWK model, the model needs to be added to
gridpack_generation.sh , which I don't see after doing the fresh checkout from git.

I did put the model file also in the same dir
/afs/cern.ch/user/g/gomber/public/13TeVCards/12May/EWModel_FermionDM_UFO.tar

Could one of you please put the model file in
https://cms-project-generators.web.cern.ch/cms-project-generators/

and update the gridpack_generation.sh, so that I can produce gridpacks for dark matter EWK model.
________________________________
From: Bhawna Gomber
Sent: 17 July 2015 16:29
To: cms-sw/genproductions; cms-sw/genproductions
Subject: RE: [genproductions] Cards for EXO-RunIIWinter15wmLHE for Dark Matter MonoPhoton (#388)

Thanks Josh!
Yes you are right it took longer because of different processes merged togehter.
________________________________

**Comment by bendavid** [comment]
Is the model already on the generator afs area?

**Comment by gomber** [comment]
I am not sure which afs area you are talking about.
I know MonoZ people (renjie Wang) would have asked for these samples too, but not sure how
he used this model file.
________________________________

**Comment by bendavid** [comment]
/afs/cern.ch/cms/generators/www/

**Comment by gomber** [comment]
I don't see the model there.
________________________________

**Comment by davidsheffield** [comment]
I've added it in /afs/cern.ch/cms/generators/www/EWModel_FermionDM_UFO.tar

**Comment by bendavid** [comment]
Ok, please make a pull request with the corresponding changes to gridpack_generation.sh

**Pull request merged**
