### PR TITLE
debugged, modified and tested process cards for reproduction MC samples

### PR DESCRIPTION
**Pull request by skudella**
We had a bug in our customized cards and therefore have to reproduce our MC samples for the 13TeV 2016 run. I fixed the bugs and tested all the gridpacks to do so.

SHA code assigned to the commit: 660a618adf3281cd7ef5867c4bf00075aff41e41

\Simon

### CODE REVIEW

**Comment by perrozzi** [comment]
hi, please solve the conflicts.
also, please move the datacards to bin/MadGraph5_aMCatNLO/cards/production/**pre2017**/13TeV/GstarToTpTop/

**Comment by perrozzi** [comment]
hi, you still seem to have a massive conflict with the master branch

**Comment by skudella** [comment]
I realized that my fork was not up to date, resulting in all of those conflicts. If it is ok with you, I would like to close this pull request and open a new one from my updated repo.

**Comment by perrozzi** [comment]
ok no problem

**Pull request closed without merging**
