### PR TITLE
PR to merge back the private rwgt fork to official branch

### PR DESCRIPTION
**Pull request by yuanchao**

### CODE REVIEW

**Comment by perrozzi** [comment]
the PR seems to still have conflicts, can you please solve them?

**Comment by yuanchao** [comment]
Conflicts resolved. (b_bbar_4l part removed for the moment)

**Comment by perrozzi** [comment]
thanks. may I ask why b_bbar_4l is removed?

**Comment by yuanchao** [comment]
For b_bbar_4l, the source was checked out separately in Aug. normal version. Some corresponding code is written accordingly in this script. Therefore for the Dec. rwgt version, I need to check again before adding it back.

**Comment by perrozzi** [comment]
can you please coordinate with @intrepid42 on the inclusion on b_bbar_4l?
I assume that we can merge this PR, then re-include asap this process to let the TOP group perform tests and produce events, right?
comments? timescales?

**Comment by intrepid42** [comment]
@yuanchao @perrozzi POWHEG-BOX-RES/b_bbar_4l already supports the new weights syntax, so it most likely just works with your new version. Please add it back, thank you.

**Comment by perrozzi** [comment]
PR merged to start testing the new release, b_bbar_4l will be added back asap, @intrepid42 please ping if this doesn't happen "soon"

**Pull request merged**
