### PR TITLE
change runninscale from 0 to 1

### PR DESCRIPTION
**Pull request by amagitte**
Hi all,

I have changed the running scale for the following Powheg input cards:

1- gg_H_quark-mass-effects_NNPDF30_13TeV_M1000GeV.input
2- gg_H_quark-mass-effects_NNPDF30_13TeV_M600GeV.input
3- gg_H_quark-mass-effects_NNPDF30_13TeV_M400GeV.input

from the previous value = 0 to the new one 1;

Cheers,
Alessio

### CODE REVIEW

**Comment by syuvivida** [comment]
What is the motivation for changing this running scale to 1?

**Comment by amagitte** [comment]
Hi,

The Powheg authors have suggested this configuration to generate heavy Higgs particle

Alessio

**Comment by amagitte** [comment]
Might you kindly approve the pull request?!

Many thanks!
Alessio

**Comment by amagitte** [comment]
Hi,

I added in all the Hadronizers, containing the decay of the Z by Pythia8 (*), the following line:
'23:mMin = 0.05'.
Even if in our production we don't use them ( we are using JHUGen) these files may be used by other analysis, and the new line makes these cfg more general.

Might you approve the pull request by today? 
I have done the previous one a week ago and  we would like to produce the signal as soon as possible!

Many thanks!
Alessio

(*) Hadronizer_TuneCUETP8M1_13TeV_powhegEmissionVeto_3p_H_ZZ_2l2nu_VBF_M*GeV_LepDECAY_LHE_pythia8_cff.py
      Hadronizer_TuneCUETP8M1_13TeV_powhegEmissionVeto_H_ZZ_2l2nu_ggH_M*GeV_LepDECAY_LHE_pythia8_cff.py

**Comment by amagitte** [comment]
Many thanks Roberto!

**Pull request merged**
