### PR TITLE
Add DYJetsToMuMu mll105to160 cards (2017 version)

### PR DESCRIPTION
**Pull request by UAEDF-tomc**

### CODE REVIEW

**Comment by perrozzi** [comment]
the cards look ok, but why there is "HT" in the name? it looks inclusive to me...

**Comment by UAEDF-tomc** [comment]
Indeed, there is no reason to have the HT, I removed it from all the cards

**Comment by perrozzi** [comment]
(then on the main folder too, I assume...)

**Comment by UAEDF-tomc** [comment]
Main folder is also renamed now.

**Comment by efeyazgan** [comment]
I guess we should also have "T = auto_ptj_mjj"

**Comment by UAEDF-tomc** [comment]
Yes, I changed it.

**Pull request merged**
