### PR TITLE
Adding VVTo2L2Nu cards for UL

### PR DESCRIPTION
**Pull request by zflowers**
Replacing previous pull request after addressing Meng's comments

### CODE REVIEW

**Comment by menglu21** [comment]
Hi @zflowers could you please remind me which PR you referred to, it seems you only deleted one file in this PR

**Comment by zflowers** [comment]
Hi @menglu21

Thank you for reviewing this PR. Here is the link to the previous closed PR: 

https://github.com/cms-sw/genproductions/pull/3258

My understanding was that with the syntax in the proc card, that the madspin card was no longer needed. Additionally, there should be two commits as part of this PR, with one of them including some updates to the pdf in the run card.

https://github.com/cms-sw/genproductions/pull/3271/commits

**Comment by menglu21** [comment]
ok, cards look good to me. @Saptaparna @mlizzo @Dominic-Stafford please have a check

**Comment by mlizzo** [comment]
Cards look good to me as well

**Pull request merged**
