### PR TITLE
Adding a branch for 3.5x release

### PR DESCRIPTION
**Pull request by michael-pitt**
Discussed in https://github.com/cms-sw/genproductions/issues/3326

Update `mg352` branch with:
* A new path to the MG tag file (**still linked to [launchpad](https://launchpad.net/mg5amcnlo/3.0/3.5.x/+download/MG5_aMC_v3.5.2.tar.gz)**)
* Patches: 
  * remove master patched not needed in `mg352`: 0036, 0037, 0038, 0040
  * tiny fix in 0006
  * copy 0076 patch from `mg33x` branch (patched 0037, 0077, 0078 not needed in `mg352`)
  * update 0076

### CODE REVIEW

**Comment by sihyunjeon** [comment]
Hi, can you be clear on what "new patches" mean? they are included in the 3.5.2 by default?

**Comment by sihyunjeon** [comment]
And you confirmed that other patches in https://github.com/cms-sw/genproductions/tree/mg33x/bin/MadGraph5_aMCatNLO/patches are all included in 352?

**Comment by sihyunjeon** [comment]
Ah looks like not. For example,

https://github.com/cms-sw/genproductions/blob/mg33x/bin/MadGraph5_aMCatNLO/patches/0037-fix_madspin_max_running_process.patch

there was different 0037 numbered patch that makes madspin run. Duplicated numbering is a bit unfortunate mistake due to diverging branches but in any case, can you integrate the patches in 33x branches as well?

**Comment by sihyunjeon** [comment]
i will add 352 in the web some point today

**Comment by michael-pitt** [comment]
Hi @sihyunjeon 
I tried to answer your comments by modifying my first comment, listing which patches were removed from the master and from the `mg33x` branches. I hope it makes it clearer. 

> Discussed in #3326
> 
> Update `mg352` branch with:
> 
> * A new path to the MG tag file (**still linked to [launchpad](https://launchpad.net/mg5amcnlo/3.0/3.5.x/+download/MG5_aMC_v3.5.2.tar.gz)**)
> * Patches:
>   
>   * remove master patched not needed in `mg352`:  0036, 0037, 0038, 0040
>   * tiny fix in 0006
>   * copy 0076 patch from `mg33x` branch (patched 0037, 0077, 0078 not needed in `mg352`)
>   * update 0076

**Comment by sihyunjeon** [comment]
nice very very nice!
thank you! i added mg352 to the web i'll fix the PR and merge right away

**Comment by sihyunjeon** [comment]
thanks again for doing this!

**Comment by stahlleiton** [comment]
Thanks for this PR. I will proceed to test it for heavy ions and prepare a PR with input cards for GammaUPC.

**Pull request merged**
