### PR TITLE
UL17_18_16 gen settings consistency check

### PR DESCRIPTION
**Pull request by efeyazgan**
This should only be merged when all HTCondor nodes get a cookie! (hopefully early next week)

### CODE REVIEW

**Comment by qliphy** [comment]
https://github.com/cms-sw/genproductions/blob/3fce7e5306d1819560ae26997a6214c1cb1cf49e/bin/utils/request_fragment_check.py#L435

This seems to be buggy, and different from master branch

**Comment by qliphy** [comment]
Should be 
https://github.com/cms-sw/genproductions/blob/master/bin/utils/request_fragment_check.py#L395

**Comment by efeyazgan** [comment]
@qliphy, thanks. I've updated the PR but this is still not ready to be merged.

**Comment by qliphy** [comment]
Removed the check on 16 core with low filter eff,  after the discussion with PPD:  
https://indico.cern.ch/event/841756/

**Comment by qliphy** [comment]
Justinas updated on Aug 15th that "cern-get-sso-cookie seems to be available in HTCondor"

**Pull request merged**
