### PR TITLE
added RPVSquarkTo4J cards

### PR DESCRIPTION
**Pull request by elliot-hughes**
I'm adding RPVSquarkTo4J cards for my analysis's signal samples in preparation for official production.

### CODE REVIEW

**Comment by perrozzi** [comment]
is the model using 4F PDF or 5F PDF? (you are specifying  4 = maxjetflavor which means 4F)
can you remind me which PDF is selected when nn23lo1 is used?

**Comment by elliot-hughes** [comment]
I believe `nn23lo1` corresponds to an internal MadGraph PDF called `NNPDF23_lo_as_0130_qed_mem0.grid`. If you want to look at it, you can find it in MadGraph5's `Template/LO/lib/Pdfdata` directory.

**Comment by perrozzi** [comment]
and which PDF flavor scheme is the model supposed to use?

**Comment by elliot-hughes** [comment]
As I understand it, `NNPDF23_lo_as_0130_qed_mem0.grid` is a "variable-flavor number" PDF, so it's not fixed to either 4-flavor or 5-flavor. And you're correct in pointing out that my run cards are setting a 4-flavor scheme. I'm not very knowledgeable about PDFs, but by my understanding I'm using an acceptable setup. Please enlighten me if I'm mistaken.

**Comment by perrozzi** [comment]
I am not sure I agree with this statement, sorry...
you must investigate which flavor scheme is using the model you are importing RPVMSSM_UFO
(@bendavid @kdlong @vciulli etc can you please I am not sure which is the default pdf flavor scheme, can you comment?)

**Comment by kdlong** [comment]
@elliot-hughes, is there any reason to prefer this PDF? It's best to use an up to date set like NNPDF 3.0 unless there's a good reason to use an older one.

**Comment by perrozzi** [comment]
ping

**Comment by kdlong** [comment]
As for the flavor scheme, this depends on the model. Is the model in MadGraph by default or are you loading it from somewhere?

**Comment by perrozzi** [comment]
ping. what shall we do here?

**Comment by elliot-hughes** [comment]
Hey, sorry about dropping out of communication. I've been delayed in sorting this out. Let's close this PR, and I'll open another after I make some revisions and test locally.

**Pull request closed without merging**
