### PR TITLE
Add ZG cards with mll cuts

### PR DESCRIPTION
**Pull request by andreypz**
This is to add a card for ZG -> MuMuG process with mll cut: 2 < mll < 15 GeV

It's for Z -> J/Psi + gamma analysis (for 2016 data).

### CODE REVIEW

**Comment by efeyazgan** [comment]
Are you intentionally using 230000 (NNPDF23_nlo_as_0119) set which has alpha_s=0.119?

**Comment by andreypz** [comment]
Hi,
I am using the default values from MG5_aMC_v2_6_0 version
I don't think this is important, but I could also change to different values, whatever you suggest.

**Comment by efeyazgan** [comment]
Then , you should switch to the default for pre2017 samples: 263000 (NNPDF30_lo_as_0130). 

And other things:
Could you please 
- Close this pull request and commit to the master?
- Put your cards to genproductions/bin/MadGraph5_aMCatNLO/cards/production/pre2017/13TeV/ZGTo2MuG_mll_cuts ?

**Comment by andreypz** [comment]
Could you point me to an example.
In a standalone MG, the option `NNPDF30_lo_as_0130 = pdlabel ` does not work

**Comment by efeyazgan** [comment]
You should have:
263000    = lhaid     ! if pdlabel=lhapdf, this is the lhapdf number

**Comment by perrozzi** [comment]
Hi Andrey, why are you using MG5_aMC_v2_6_0 version?
Why are using the standalone version?
please check https://hypernews.cern.ch/HyperNews/CMS/get/generators/3593.html

**Comment by andreypz** [comment]
Hi,
I used standalone version to optimize the cuts and test that it all works (doing this with gridpacks is less efficient).
I choose MG_2_6 because it's the latest. And because for 2017 we will have to use 2_5 or 2_6 for ZG process (due to a fix of asymmetry bug).
Is this a big deal if for this one we just do this one in MG26? It works, I have made the gridpack: `/afs/cern.ch/user/a/andrey/public/ZGamma`

I tried to use the same cards in master branch - they would not work. I suppose I could make them work with master, using older version of MG. But I'd prefer just use this one. Could you merge it?

**Comment by efeyazgan** [comment]
Could you please close this pull request and commit to the master?
 and put your cards to genproductions/bin/MadGraph5_aMCatNLO/cards/production/pre2017/13TeV/ZGTo2MuG_mll_cuts ?

**Comment by andreypz** [comment]
Unfortunately, these cards don't work with master branch.

**Comment by efeyazgan** [comment]
How urgent is this? Next week we plan to include mg26x in master.

**Comment by andreypz** [comment]
It's not urgent, I can wait till next week, I suppose.

**Comment by andreypz** [comment]
Hi @perrozzi @efeyazgan 
I'd like to add those cards to pre2017. I understand that you want me to commit them to master.
My question is: which version of MG is used when gridpack is produced from master? (Where can I find that info in the code?)

You mentioned before that mg26x branch was going to be merged to master, but this has not been done yet, right?

**Comment by andreypz** [comment]
So, by running it I see that version 2.4.2 is used when I run from master.
What do I do to get version 2.6.X? 
Is it possible from master, or should I put the cards to mg26 branch?

**Comment by efeyazgan** [comment]
You can start with 
git clone git@github.com:cms-sw/genproductions.git genproductions -b mg26x

**Comment by qliphy** [comment]
@andreypz   Just to remind you may also refer to this PR: https://github.com/cms-sw/genproductions/pull/1395

**Comment by andreypz** [comment]
Thanks,
I have  noticed that PR and subscribed to it.
At the moment it is not the same, because I decide to do it at LO. I made a new PR, #1397 for this.
However, NLO would be the next step.

**Pull request closed without merging**
