### PR TITLE
update aQGC VVjj hadronic 2017 madgraph cards

### PR DESCRIPTION
**Pull request by stalbrec**
This updates the used SMEFT UFO model, renames the processes in order to be consistent with two processes added here as well (ZNuNuZJJnoB and ZBBZJJnoB).

The new UFO model was discussed in this [HN](https://hypernews.cern.ch/HyperNews/CMS/get/generators/4671.html).

### CODE REVIEW

**Comment by agrohsje** [comment]
Any reason you add these to the proc_card: 
set group_subprocesses Auto
set ignore_six_quark_processes False
set complex_mass_scheme False
All default, no. 
Otherwise +1 @qliphy .

**Comment by stalbrec** [comment]
These are just remnants from when i was adopting the cards for VVjj semileptonic.
If they are the default, I can remove those lines if you like.

**Comment by stalbrec** [comment]
Should I remove those lines?

**Comment by agrohsje** [comment]
Right. If default please remove. Qiang can merge afterwards. 
+1 from my side @qliphy

**Comment by stalbrec** [comment]
I checked - they are all default.
I removed the lines.

**Pull request merged**
