### PR TITLE
update PDF sets for UL2019

### PR DESCRIPTION
**Pull request by yuanchao**
Adding 325300, 325500, and 30600 PDF sets.

### CODE REVIEW

**Comment by qliphy** [comment]
Thanks @yuanchao     325300, 325500, and 30600 PDF sets are currently only available with CMSSW_10_6_X.  Probably we should make this clear at some place, e.g. https://twiki.cern.ch/twiki/bin/viewauth/CMS/PowhegBOXPrecompiled

**Comment by agrohsje** [comment]
Hi @qliphy 306000 is available since long. Only  325300, 325500 were added, no?

**Comment by qliphy** [comment]
@agrohsje   Yes, but there seems to be re-ordering of 306000 here.

**Comment by agrohsje** [comment]
@qliphy I was referring to the TWiki warning. There only  325300, 325500 should be mentioned, no?

**Comment by qliphy** [comment]
@agrohsje   Yes, right.  In addition, we should also mention the CMSSW release for UL2019 should be 10_6_X

**Pull request merged**
