### PR TITLE
Qstar and Bstar signal samples with new tune, TuneCP5

### PR DESCRIPTION
**Pull request by rockybala**
New Qstar and Bstar samples with the latest tune "TuneCP5" are added for production.

### CODE REVIEW

**Comment by qliphy** [comment]
Please pay attention to the space and indentation:
https://github.com/cms-sw/genproductions/pull/1816/files#diff-4bb683c5c6d72d5e1e5a1824373ee47aR28

Moreover, please don't upload all fragments. Just an example one together with the script to make others.

**Comment by rockybala** [comment]
I find the space and indentation to be fine.
When I go to the link:  
https://github.com/cms-sw/genproductions/pull/1816/files#diff-4bb683c5c6d72d5e1e5a1824373ee47aR28
and open the file by clicking on the view button on the top right side, I find the correct indentation.
Can you please check what is going on?

**Comment by qliphy** [comment]
Yes, interesting! By clicking on the view button it looks fine.

**Comment by rockybala** [comment]
What should I do now?
Do I need to update to keep only one fragment and script to generate others?

**Comment by qliphy** [comment]
Yes, please. This is the usual requirement.

**Comment by rockybala** [comment]
Done!

**Pull request merged**
