### PR TITLE
fiz -z bug for mg5_amc

### PR DESCRIPTION
**Pull request by perrozzi**

### CODE REVIEW

**Comment by perrozzi** [comment]
gridpack_generation.sh was originally corrected by @qliphy but keeping -z, switched to -n

**Comment by bendavid** [comment]
I believe this affects the NLO run script as well.

**Comment by perrozzi** [comment]
yes I included it afterwards

**Comment by perrozzi** [comment]
@kdlong @qliphy can you please crosscheck and sign off (or suggest modifications) ASAP?

**Comment by qliphy** [comment]
@perrozzi  Tested with LO and it works well.

**Comment by perrozzi** [comment]
thanks a lot!

**Pull request merged**
