### PR TITLE
Configs from Begona

### PR DESCRIPTION
**Pull request by dnash86**
These are the configs for the M_100 bins for WToLNu.

### CODE REVIEW

**Comment by dnash86** [comment]
Could these be merged if there are no problems so I can push requests to Defined?

**Comment by bendavid** [comment]
Two issues
1) there seems to be a third empty file added by the pull request

2) These lines should be removed, since they conflict with the default/tune settings
+            'Main:timesAllowErrors = 10000',
+            'ParticleDecays:limitTau0 = on',
+            'ParticleDecays:tauMax = 10',
+            'Tune:ee 3',
+            'Tune:pp 5',

**Comment by dnash86** [comment]
Accidentally closed, reopened with edits now

**Comment by bendavid** [comment]
Looking back at the higher mass bins for this request, I see that the WToTauNu samples were produced both with and without Tauola.
(Logic was that without tauola is preferred to some extent since that is the default for most run 2 production, but Tauola was also needed for closer correspondence to the Wprime samples which still needed Tauola).

Would suggest to do the same here (add an additional card for WtoTauNu without tauola)

Will merge this as is not to further delay the other requests, but please go ahead and add the additional card in a new pull request.

(Btw, the issue with WPrimeToTauNau in pythia is now solved, so those samples can also be produced without tauola)

**Pull request merged**
