### PR TITLE
add VBF_H powheg 

### PR DESCRIPTION
**Pull request by OlivierBondu**
This gives consistent distributions when comparing to powheg V1: 
https://test-obondu3.web.cern.ch/test-obondu3/2015-03-31-POWHEG_VBF_H_V1_VS_V2_test5_v2/

### CODE REVIEW

**Comment by syuvivida** [comment]
The card have the necessary settings for producing PDF/scale weights. It looks fine to me.

**Comment by covarell** [comment]
Does it differ in any way from the one in the example directory? If not, we may even skip this pull...

**Comment by syuvivida** [comment]
Hi Roberto, actually for this process, I forgot to put input card. I will put Oliver's card into the example directory.

**Comment by covarell** [comment]
OK, I will close this

**Pull request closed without merging**
