### PR TITLE
Cards for TTW and TTZ

### PR DESCRIPTION
**Pull request by nstrobbe**
Cards for TTWJets and TTZJets, NLO with FXFX merging, decays using MadSpin.

### CODE REVIEW

**Comment by bendavid** [comment]
For ttZ I think you want to generate directly t t l+ l- (also including taus) to include the gamma* contribution.

**Comment by nstrobbe** [comment]
Ok, that would make sense. 
We also need the other decays, so do you then suggest to do something like:
generate p p > t t~ l+ l-
add process p p > t t~ nu nu~
add process p p > t t~ q qbar
(with appropriate multiparticle labels, and adding the 1j counterparts)

**Comment by bendavid** [comment]
Hi Nadja,
The qqbar case is really tricky to handle properly.  Are you sure you care
about this?  This should be negligible compared to inclusive ttbar + 2jet
production no?

simply doing add process p p > t t~ q qbar will not give you what you want,
since you will get instead pure qcd production rather than gamma*/Z
mediated production of the additional jets.

**Comment by nstrobbe** [comment]
Hmm.. We for sure need the invisible decay of the Z, since that results in ttbar + MET. 
I was thinking to include also the hadronic decays for completeness, and for analyses that ask for boosted objects where the mass would matter.

**Comment by bendavid** [comment]
Ok, if you need the hadronic case, the most feasible is to do p p > t t~ z and do the decay to qqbar in madspin.  This means you miss the gamma* contribution for the qqbar, but that should be fine.

This implies that you need to split into two samples at least.  (If you also want the off-shell breit-wigner tail for the neutrinos, then best is to produce the ll and nu nu together without madspin, and the qqbar in a separate sample with madspin if really needed)

**Comment by alkaloge** [comment]
Another syntax is like
generate p p > t t~ l l / h @1
add process p p > t t~ vl vl / h @2
add process p p > t t~ z / h, z > q q  @3

so you get the q q~ via on-shell Z

**Comment by bendavid** [comment]
That won't work at NLO though (since decay chain syntax is not supported)

**Comment by nstrobbe** [comment]
Can we then do 
generate p p > t t~ l l / h @1
add process p p > t t~ vl vl / h @2
add process p p > t t~ z / h @3

and then decay the top and z in madspin, with only including z > q q

**Comment by bendavid** [comment]
You can try, but this might cause problems (I'm not sure if madspin will
correctly skip the events with nothing to decay)

If not then it's sufficient to just split into two samples as said.

**Comment by nstrobbe** [comment]
Madspin will in any case still have the top quarks to decay right? 

Would it also make sense to do
generate p p > t t~ l+ l- $ h @1
instead of 
generate p p > t t~ l+ l- / h @1
?

That way we are keeping the off-shell higgs and interference effects for the tau+ tau- final state. Or do you think this will be completely negligible?
The tth sample is being generated as p p > t t~ h, with the higgs decayed by Pythia.

**Comment by bendavid** [comment]
The $ syntax is not supported at NLO (only $$ h, > h >, and /h), so no way to do it like that (anyway, don't think that's too important)

The possible problem with
generate p p > t t~ l l / h @1
add process p p > t t~ vl vl / h @2
add process p p > t t~ z / h @3

has to do with the manipulation of the cross sections and relative weighting between processes which madspin will attempt when it sees that the included Z decays account only ~70% of the total branching ratio.  As said, you could try it, but it might have problems in this direction.

**Comment by nstrobbe** [comment]
We decided that we will try to generate it in one sample. We will of course check whether things make sense. 
I have updated the cards accordingly.

**Comment by bendavid** [comment]
Alright, suggest to try with the ttZ first.  If that works you could also consider to do something similar for ttW (generate directly p p > t t l v for the leptonic case and do the hadronic decays with madspin) since there could at least in principle be some small polarization effects there which would not be captured by madspin. (These effects are likely pretty small, on the other hand, if you run into problems with combinatorics in madpsin in the ttW case it might even be faster to do it that way)

Will merge the cards as is for now and you can update the ttW ones if you want later.

**Comment by bendavid** [comment]
(for the ttZ the thing to check is that you get the expected proportion of hadronic/leptonic/invisible decays)

**Comment by bendavid** [comment]
Ah, one more thing.

When the inclusive ttbar requests were prepared, we had the TOP group set the maximum mll from the parton shower to 1GeV.  Looking at the google doc, this was matched with the HIG requests on lines 247-248

If you want a strictly continuous phase space when combining the inclusive ttZ with the ttbar sample, then you could also set mll>1GeV.  If you don't care and will mainly use this to cover phase space where the two leptons are resolvable, then also fine as it is.

**Comment by nstrobbe** [comment]
What is the difference between the Higgs requests and this one in fact?

**Comment by bendavid** [comment]
The Higgs request is only ttll (without the hadronic or invisible).  But indeed I think this is somewhere we simply missed in the deduplication/rationalization.  (And no one from Higgs has prepared either of those samples so far)

**Comment by nstrobbe** [comment]
Since they have not prepared them yet, we can still harmonize the requests now. 
I like the idea of having a continuous phase space. How about we have two requests, with adjusted total number of events (keeping the overall budget the same, at 750k)
1) this one, with mll>5, 600k events
2) a second one, only the ttll, with 1 < mll < 5, 150k events
Does it make sense?

**Comment by bendavid** [comment]
The planned Higgs requests were split into 1<mll<10 and mll>10, which probably makes more sense.  On the other hand, if you prefer to have one sample with mll>5 (and some analyses may use only that one) then also fine.

So yes, agreed to prepare two requests as you suggest.  Up to you whether to split at 5 or 10GeV.  (Then once the gridpacks are ready we may still discuss about the number of events to make sure everyone is happy.)

**Comment by nstrobbe** [comment]
Presumably, if people care about the 5-10 range, they will also want to use the 1-5 range. So I will make the split at 10 as you suggest. 

Shall I already make a new pull request now with this change? Or should I wait till we know that the gridpack went fine, and there is no issue with the relative proportions of l/nu/q?

**Comment by bendavid** [comment]
Yah you can already make a new pull request.

**Comment by nstrobbe** [comment]
actually, looking at the cards, how does one implement a maximum mll cut at NLO?

**Comment by bendavid** [comment]
You need to do it "by hand" using cuts.f
Take a look at
https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/cards/production/13TeV/dyellell012j_5f_NLO_FXFX_M10to50/dyellell012j_5f_NLO_FXFX_M10to50_cuts.f

**Pull request merged**
