### PR TITLE
Increase AGAIN maximum pdf weights

### PR DESCRIPTION
**Pull request by covarell**
Run2 UL weights exceed again the maximum number of allowed weights

### CODE REVIEW

**Comment by agrohsje** [comment]
Shouldn't we reduce the weights @menglu21 @Saptaparna instead of further increasing? The PDF weights slow down production a lot and I am pretty sure majority is not used at all.

**Comment by covarell** [comment]
Agreed, but this is for Run2UL where "in principle" many gridpacks should have already been produced (I'm wondering how...)

**Comment by covarell** [comment]
Run3 weights are already within the limits

**Comment by Saptaparna** [comment]
I am merging this, so we can at least proceed with production.

**Pull request merged**
