### PR TITLE
produce w as lnu without mass cuts

### PR DESCRIPTION
**Pull request by perrozzi**
please check that I didn't introduce errors :-)

### CODE REVIEW

**Comment by bendavid** [comment]
Madspin is now only needed to fill in spinup flags for the tau polarization (and only for W(->lv)H)
The appropriate madspin cards is the one containing a "dummy" decay as in
https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/cards/examples/wellnu012j_5f_NLO_FXFX/wellnu012j_5f_NLO_FXFX_madspin_card.dat

**Comment by perrozzi** [comment]
thanks, please check again

**Comment by bendavid** [comment]
for ZH madspin is not needed at all (so the madspin card should simply be removed)

**Comment by perrozzi** [comment]
done

**Pull request merged**
