### PR TITLE
GJets HT-binned MLM

### PR DESCRIPTION
**Pull request by yiiyama**
Cards for GJets_HT-* and GJets_DR-0p4_HT-*

### CODE REVIEW

**Comment by efeyazgan** [comment]
please remove p and j definitions

**Comment by yiiyama** [comment]
OK, I removed all p and j definitions - hopefully that's what you meant.

**Comment by efeyazgan** [comment]
Yes, thanks. Could you please also remove the multiple lepton definitions (keep the one you would use)?

**Comment by yiiyama** [comment]
Sure! In fact the proc cards only have
p p > a j {j} {j} {j}
so I got rid of all 'define's.

**Pull request merged**
