### PR TITLE
polarization samples for VBS ssWW

### PR DESCRIPTION
**Pull request by freejiebao**
Use new syntax https://answers.launchpad.net/mg5amcnlo/+faq/2243 to generate three polarization samples for VBS ssWW: VBS_SSWW_LL, VBS_SSWW_TL, VBS_SSWW_TT

### CODE REVIEW

**Comment by qliphy** [comment]
As you are using MG27X,  please provide a link to your checks/studies.

**Comment by freejiebao** [comment]
@qliphy here is a link for polarization study of VBS ssWW, MG5 v2.7.0 used: https://indico.cern.ch/event/891570/contributions/3769508/attachments/1997346/3338132/SMPVV20200303.pdf
But from the author of MG5, now v2.7.1.2 is recommended for VBS ssWW polarization study, but the syntax is same:
https://launchpad.net/mg5amcnlo/+download

**Comment by qliphy** [comment]
Please remove the MG5_aMC banner from the proc card, as mentioned here:
https://twiki.cern.ch/twiki/bin/view/CMS/Fall18Repack

**Comment by qliphy** [comment]
The gridpack is using MG27+, which is not totally validated yet in CMS.  However, from the slides, checks have been performed with Phantom.

+1  @agrohsje

**Comment by agrohsje** [comment]
1.) Suggest to remove this stuff. Nothing you added right? All just default: 
set default_unset_couplings 99
set group_subprocesses Auto
set ignore_six_quark_processes False
set loop_optimized_output True
set loop_color_flows False
set gauge unitary
set complex_mass_scheme False
set max_npoint_for_channel 0

2.) Same here. Can be removed, or do I miss something? 
#
  systematics	= systematics_program ! none, systematics [python], SysCalc [depreceted, C++]
['--mur=0.5,1,2', '--muf=0.5,1,2', '--pdf=errorset'] = systematics_arguments ! see: https://cp3.irmp.ucl.ac.be/projects/madgraph/wiki/Systematics#Systematicspythonmodule
# Syscalc is deprecated but to see the associate options type'update syscalc'#*********************************************************************
#  Additional hidden parameters
#*********************************************************************
  True	= clusinfo # hidden_parameter
  ['--mur=0.5,1,2', '--muf=0.5,1,2', '--pdf=errorset']	= systematics_arguments # Choose the argment to pass to the systematics command. like --mur=0.25,1,4. Look at the help of the systematics function for more details.
  0.0	= ptheavy # this cut apply on particle heavier than 10 GeV
  3.0	= lhe_version # hidden_parameter
  1.0	= ptonium # hidden_parameter
  1	= highestmult # hidden_parameter
  True	= pdfwgt # hidden_parameter
  1	= ktscheme # hidden_parameter

3.) For my education. In this line 1, 2  = me_frame, 1 and 2 are the particles as defined in the process line?

**Comment by kdlong** [comment]
Is there a setup to produce a gridpack in the CMS setup with 2.7.2?

**Comment by freejiebao** [comment]
I have done some clean of the cards
@agrohsje 
3) Yes. 1, 2 are indexes for particles in process line
@kdlong 
I used branch mg267,  and change the MG5 version to V2.7.1.2 (now it should be V2.7.2) in girdpack_generation.sh

**Pull request merged**
