### PR TITLE
changed folding parameters to decrease negative weight fraction

### PR DESCRIPTION
**Pull request by chayanit**
other mass points are still checking and will commit as soon as they're done. Thanks!

### CODE REVIEW

**Comment by covarell** [comment]
If you change a parameter you should update the file normally, not create a new one (directory and file)? Is there a specific reason to keep the old one as well?

**Comment by chayanit** [comment]
Ah no...I forgot I can update new ones on github (facepalm)

Thanks,
Chayanit

Sent from my iPhone

On May 22, 2015, at 8:38 PM, Roberto Covarelli <notifications@github.com<mailto:notifications@github.com>> wrote:


If you change a parameter you should update the file normally, not create a new one (directory and file)? Is there a specific reason to keep the old one as well?

**Comment by syuvivida** [comment]
@chayanit can we close this pull request?

**Comment by chayanit** [comment]
Yes, please. Thanks!

Cheers,
Chayanit

On Jun 6, 2558 BE, at 3:25 PM, syuvivida <notifications@github.com<mailto:notifications@github.com>> wrote:


@chayanit<https://github.com/chayanit> can we close this pull request?

**Comment by syuvivida** [comment]
hi @chayanit I don't have permission to do so. you have to close the request.

**Pull request closed without merging**
