### PR TITLE
fix patch 0006 when moving to MadGraph v2.6.7 

### PR DESCRIPTION
**Pull request by shu-xiao**

### CODE REVIEW

**Comment by qliphy** [comment]
Adding @lviliani @soarnsoar @pmandrik 
Can you have a check? Thanks.

**Comment by syuvivida** [comment]
@qliphy @agrohsje Could you let us know if additional tests or log files are required to merge this pull request? Thanks!!
@pmandrik has replied to our email and said the change should be OK.

**Comment by qliphy** [comment]
Thanks @syuvivida 

Is it possible for some of you to present the progress towards MG267 at forthcoming GEN meeting, e.g. 13 Jan or 20 Jan?
Let us know.

**Comment by shu-xiao** [comment]
@qliphy 
ok, I can give the report on 13 Jan for both requests (#2520 & #2521 ).
Please add me in the email list

**Comment by agrohsje** [comment]
you could make short test and compare the lhe output from a gridpack in 2.6.5 and 2.6.7 to see that results are consistent. 
cheers, alexander.

**Comment by agrohsje** [comment]
Patch reflected in 27x development branch:
https://github.com/cms-sw/genproductions/blob/mg27x/bin/MadGraph5_aMCatNLO/patches/0006-add-central-weights.patch
Will close PR.

**Pull request closed without merging**
