### PR TITLE
Florida Tech Request

### PR DESCRIPTION
**Pull request by JacobChesslo**
Mehdi Rahman, Dr. Marcus Hohlmann
ZDark to fDark, sDark, fDarksDark

EDIT:
For the request we have three **prompt** Dark Matter models, where they can decay into SM particles or first into DM matter particles and then into SM particles such as muons, through a spin 1 mediator, a dark Z-like boson ZD, which can interact with the Standard Model sector as well as the dark matter sector. 

**FD model: DM_KM_Med_Spin1_Fermioic_Prds.:**
pp collisions produce our ZD through kinetic mixing, which then eventually decays into ordinary matter and stable dark matter (fD2)

 **SD model: DM_KM_Med_Spin1_Scalar_Prds.** 
pp collisions produce our ZD through kinetic mixing then decaying into dark scalar matter (sD), which then decays into ordinary matter

**Combination of the two models: DM_KM_Med_Spin1_Fermionic_Scalar_Prds**
A combination of the above two, where the dark Z can decay into either fermionic or scalar matter.

**Mass Scans**
1. MZD scan- fD model
2. MZD scan- sD model
3. MZD scan- combination of two models - fD decays
4. MZD scan- combination of two models - sD decays
5. MfD1 scan- combination of two models - fD decays
6. MfD2 scan- combination of two models - fD decays
**Note**: MsD scan- combination of two models - sD decays: we are not doing mass scan for MsD because they dont seem to have enough sensitivity for higher masses

This is a 2018 Request

### CODE REVIEW

**Comment by agrohsje** [comment]
What is the purpose of including the UFO here? DMsimp_s_spin1_UFO.tar Isn't it on our official repo. If so it needs to be added there. 

Please remove things you don't use, like :
set group_subprocesses Auto
set ignore_six_quark_processes False
set loop_optimized_output True
set loop_color_flows False
set gauge unitary
set complex_mass_scheme False
set max_npoint_for_channel 0
define l+ = e+ mu+
define l- = e- mu-
define vl = ve vm vt
define vl~ = ve~ vm~ vt~

Moreover, I suggest to properly define p and collide protons, not jets. 

Please remove lines like this to help reviewing: 
#generate j j > ZD, (ZD > SD SD~, SD > mu+ mu-, SD~ > mu+ mu-)
### Output processes to MadEvent directory

If you can quickly comment on which setups you are submitting, this would be nice. You are going to modify 36 files. A short overview would be nice.

**Comment by JacobChesslo** [comment]
Where are the UFO files to be uploaded?
Can you clarify what you mean with "Output processes to MadEvent directory"? (Is this a proc_card edit/addition, do we replace "output MASS -nojpeg" with a new line)
With "If you can quickly comment on which setups you are submitting, this would be nice. You are going to modify 36 files. A short overview would be nice." can you clarify on this?
Thanks!

**Comment by agrohsje** [comment]
All models can be found here: 
https://cms-project-generators.web.cern.ch/cms-project-generators/

github was formatting my comment. I suggest to remove the lines with # in the proc card. output process ... is one of them. 

what is the reason to import the data card like this:
import model DMsimp_s_spin1_UFO ../models/DMsimp_s_spin1_UFO/param_card.dat  ? 

It is good practice to quickly describe such complex PR's. I don't know what to do with this info:  
Mehdi Rahman, Dr. Marcus Hohlmann
ZDark to fDark, sDark, fDarksDark

**Comment by JacobChesslo** [comment]
Where can we send the models .gz file (renamed each in proc_card.dat and extramodels.dat) for this request?

**Comment by JacobChesslo** [comment]
https://github.com/JacobChesslo/Research/tree/master/ZDarkModels

**Comment by JacobChesslo** [comment]
For the request we have three Long-Lived Dark Matter models, which a Dark Photon (ZD) could be produced through kinetic mixing with SM U(1)_gamma group:
1) A dark photon decaying into dark fermionic matter (fD1), which then eventually decays into ordinary matter and stable dark matter (fD2)
2) A dark photon decaying into dark scalar matter (sD), which then decays into ordinary matter
3) A combination of the above two, where the dark photon can decay into either fermionic or scalar matter

For 1) there is a single mass-scan, over ZD. Similarly for 2) there is a single mass-scan, over ZD.
For 3) there are two decay channels, that of sD and that of fD. For the sD path there is a single mass-scan, over ZD. For the fD path there are three mass-scans, over ZD, fD1, and fD2.

**Comment by JacobChesslo** [comment]
For the request we have three **prompt** Dark Matter models, where they can decay into SM particles or first into DM matter particles and then into SM particles such as muons, through a spin 1 mediator, a dark Z-like boson ZD, which can interact with the Standard Model sector as well as the dark matter sector. 

**FD model: DM_KM_Med_Spin1_Fermioic_Prds.:**
pp collisions produce our ZD through kinetic mixing, which then eventually decays into ordinary matter and stable dark matter (fD2)

 **SD model: DM_KM_Med_Spin1_Scalar_Prds.** 
pp collisions produce our ZD through kinetic mixing then decaying into dark scalar matter (sD), which then decays into ordinary matter
**Combination of the two models: DM_KM_Med_Spin1_Fermionic_Scalar_Prds**
A combination of the above two, where the dark Z can decay into either fermionic or scalar matter.

**Mass Scans**
1. MZD scan- fD model
2. MZD scan- sD model
3. MZD scan- combination of two models - fD decays
4. MZD scan- combination of two models - sD decays
5. MfD1 scan- combination of two models - fD decays
6. MfD2 scan- combination of two models - fD decays
**Note**: MsD scan- combination of two models - sD decays: we are not doing mass scan for MsD because they dont seem to have enough sensitivity for higher masses

**Comment by JacobChesslo** [comment]
Is there anything for us to edit/remove/include on our end?

**Comment by agrohsje** [comment]
Why do you change the number of events? The number of events here are only for the pilot run. If you generate large statistics, it will take a lot of time. You might just keep this at 5000 everywhere. The number will anyway not used for the final mc production. 
In blabla_proc_card.dat the line should be 
output blabla -nojpg 
From  https://twiki.cern.ch/twiki/bin/view/CMS/QuickGuideMadGraph5aMCatNLO : 
d genproductions/bin/MadGraph5_aMCatNLO/
./gridpack_generation.sh <name of process card without _proc_card.dat> <folder containing cards relative to current location>
e.g.
./gridpack_generation.sh wplustest_4f_LO cards/examples/wplustest_4f_LO 
Note: the output directory specified in the *_proc_card.dat should match the name of the process as used in the gridpack_generation.sh script

**Comment by JacobChesslo** [comment]
The number of events was talked about during theMC&I meeting and were confirmed from that end. The four samples that have a higher number of events, other than 50 000, are set to a higher number of events because the particular sensitivity for those samples is lower and require more events.
For a quick overview of the samples and number of events, see slides 25-31
[MC_I_meeting-14.pdf](https://github.com/cms-sw/genproductions/files/4956076/MC_I_meeting-14.pdf)

**Comment by JacobChesslo** [comment]
For the proc_card, the MASS is the searchable string that the script then finds and replaces with the specific sample's name. So once the script is ran, it does become blabla_proc_card.dat with the line
output blabla -nojpg

With the gridpack generation script, do we run this before the pull request goes through or afterwards?

**Comment by agrohsje** [comment]
The  number of events you specify there is not the number of events requested. This is just what you use for the pilot run.

**Comment by agrohsje** [comment]
> For the proc_card, the MASS is the searchable string that the script then finds and replaces with the specific sample's name. So once the script is ran, it does become blabla_proc_card.dat with the line
> output blabla -nojpg
> 

Ok. Missed the sed command.
 
> With the gridpack generation script, do we run this before the pull request goes through or afterwards?

Please generate once merged. As said, it is good to go from my side, I would just reduce the number of events to 5000, so that you have no problems generating the gridpack. The final number of events you produce from the gridpack is a totally different story. That is all fine, just for the pilot run it makes no sense to produce 200 k events.

**Comment by JacobChesslo** [comment]
So the number of events in the run_card is not relevant to the final amount produced? Is it just that multiple runs of the sample are then produced with the pilot events (so for example, 10 runs of 5000 events for a total of 50000 events)

**Comment by agrohsje** [comment]
Not even that. The pilot run is sort of testing and then to establish reweighting etc.  But the number of events there has 0 connection to the number of events produced in the end or how the split-up is done. The split-up is driven by the number of GEN/GENSIM events one can produce in 8 hours. And your total request is whatever you need.

**Comment by JacobChesslo** [comment]
The event number in the .sh file was changed to 5000 for all samples.
This should be the final edit before the pull is pushed

**Comment by JacobChesslo** [comment]
The pull request is ready to be pushed, we're ready to move forward with the process

**Comment by agrohsje** [comment]
+1 @qliphy .

**Pull request merged**
