### PR TITLE
add cards for  DYJetsToLL_M-5to50

### PR DESCRIPTION
**Pull request by wverbeke**

### CODE REVIEW

**Comment by vargasa** [comment]
Hello @wverbeke. Quick question, was this card used to generate [this](https://cmsweb.cern.ch/das/request?input=dataset%3D%2FDYJetsToLL_M-5to50_TuneCP5_13TeV-madgraphMLM-pythia8%2FRunIIAutumn18NanoAODv6-Nano25Oct2019_102X_upgrade2018_realistic_v20-v1%2FNANOAODSIM&instance=prod/global) sample?

**Comment by wverbeke** [comment]
Hi, I can not open the link you sent. Do you have the name of the sample, then I can check. I don't remember from the top of my head whether we used these card in exactly the way they were in this commit.

**Comment by vargasa** [comment]
`dataset=/DYJetsToLL_M-5to50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIAutumn18NanoAODv6-Nano25Oct2019_102X_upgrade2018_realistic_v20-v1/NANOAODSIM`

**Comment by wverbeke** [comment]
I checked the cards in the gridpack, and they are indeed the same ones as in this commit.

**Comment by agrohsje** [comment]
Superseeded by these files:
https://github.com/cms-sw/genproductions/tree/master/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/DYJetsToLL_M-10to50_13TeV-madgraphMLM-pythia8
Will close. Ping me in case this is not ok.

**Pull request closed without merging**
