### PR TITLE
Dark Higgs MadGraph requests hadronizer

### PR DESCRIPTION
**Pull request by jotadram6**

### CODE REVIEW

**Comment by jotadram6** [comment]
Hello, I would like to kindly remind you about this PR. Thanks

**Comment by efeyazgan** [comment]
This is for pre-Fall17, right?
Also, please add some description in the PR.

**Comment by jotadram6** [comment]
Yes, it is for pre-Fall17
Asking analyzers for the description.

**Comment by samsbaxter** [comment]
Description for pull request: Added Hadronizer for dark Higgs Madgraph request

**Comment by samsbaxter** [comment]
Details on Hadronizer:
LL 6-12 produce LHE events from gridpack
LL 17-38 standard CMS pythia 8 settings for 4-flavour scheme - with qcut set to 36 on L34
LL 39-42 Adding pythia settings for the BSM particles in the model (dark Higgs=Hs, dark matter=DM, Z prime=Zp)
LL 43-51 completing the script

**Comment by perrozzi** [comment]
Ciao, this is not a simple hadronizer and should not go in that directory.
You have tons of directory here https://github.com/jotadram6/genproductions/tree/fd701a38b4e95a094a0a7d2d30163b079d063e76/python/ThirteenTeV
each containing fragments similar to yours, each for a given process. Pick up the folder corresponding to your folder or create a new one there

**Comment by jotadram6** [comment]
Done

**Comment by perrozzi** [comment]
please also change the filename, follow a convention similar to https://github.com/jotadram6/genproductions/blob/de023bef6c1399c199bef6e4a685c35590516e3c/python/ThirteenTeV/WPrime/WPrimeToWZToLNQQ_M1600_TuneCUETP8M1_13TeV_pythia8_cfi.py

**Comment by jotadram6** [comment]
Done

**Pull request merged**
