### PR TITLE
Add DYJetsToEE LO madgraph cards for 14 TeV

### PR DESCRIPTION
**Pull request by federicovazzoler**

### CODE REVIEW

**Comment by qliphy** [comment]
Please refer to https://twiki.cern.ch/twiki/bin/view/CMS/Moriond18MC
For example, remove the banner and have the default PDF settings:
 lhapdf = pdlabel ! PDF set
 $DEFAULT_PDF_SETS = lhaid
 $DEFAULT_PDF_MEMBERS  = reweight_PDF

**Comment by federicovazzoler** [comment]
Thank you for the prompt reply! I removed the banner from the run(proc)_card and modified the pdfs. As far as I can see no other modifications are needed. I'll commit the corrected code in this PR.

**Comment by agrohsje** [comment]
yes. please update pr.

**Comment by qliphy** [comment]
+1 @agrohsje

**Pull request merged**
