### PR TITLE
Updating PDF sets to 2017 defaults for st_FCNC 

### PR DESCRIPTION
**Pull request by wajidalikhan**

### CODE REVIEW

**Comment by efeyazgan** [comment]
Please follow the instructions here: https://twiki.cern.ch/twiki/bin/viewauth/CMS/Moriond18MC#Checks_to_the_datacards_BEFORE_T

**Comment by wajidalikhan** [comment]
removed the duplicated definitions for the cleanup

**Comment by wajidalikhan** [comment]
The datacards were cleaned up following up the instructions at [1] to make them coherent. 

[1] - Please follow the instructions here: https://twiki.cern.ch/twiki/bin/viewauth/CMS/Moriond18MC#Checks_to_the_datacards_BEFORE_T

**Comment by wajidalikhan** [comment]
Hi Efe! Thanks for the feedback. "pdfwgt" specified only once in the new commit.

**Pull request merged**
