### PR TITLE
Fix for powhegUL branch to run on lxplus (Redhat9)

### PR DESCRIPTION
**Pull request by jaebak**
Made a fix for the powhegUL branch to run on lxplus (Redhat9).

Used the approach that was used in the existing scripts for slc6. The approach was extended to slc7.

The fix was discussed in cmstalk in the below link.

https://cms-talk.web.cern.ch/t/issue-with-large-generator-weights-for-run-3-powheg/50579/6

### CODE REVIEW

**Comment by covarell** [comment]
https://github.com/cms-sw/genproductions/pull/3797/files#diff-a946031d265db406992c699bd5f0960280050183f2643c5e902085667686c173L22-L25

Why are these lines removed?

**Comment by covarell** [comment]
https://github.com/cms-sw/genproductions/pull/3797/files#diff-306a635579daba4fb10220a64e87ff0b29416fe9cfa2acf8bb8abd5391f8b7cdR48

Here, can't you just import subprocess and use subprocess.getstatusoutput?

**Comment by covarell** [comment]
Thanks anyway for this important update

**Comment by jaebak** [comment]
> https://github.com/cms-sw/genproductions/pull/3797/files#diff-a946031d265db406992c699bd5f0960280050183f2643c5e902085667686c173L22-L25
> 
> Why are these lines removed?

The %? in ${UBOUND%?} means that a single character would be removed from $UBOUND,
where when $UBOUND is "pwgubound-0001.dat", 
${UBOUND%?} would be "pwgubound-0001.da"

Because this was strange, I removed those lines.

Would there be a case where removing a single character would work?

**Comment by jaebak** [comment]
> https://github.com/cms-sw/genproductions/pull/3797/files#diff-306a635579daba4fb10220a64e87ff0b29416fe9cfa2acf8bb8abd5391f8b7cdR48
> 
> Here, can't you just import subprocess and use subprocess.getstatusoutput?

Yes. I think we can. I changed it to use subprocess.getstatusoutput

**Comment by jshin96** [comment]
I actually had the same problem of missing letter at the end that made the code to not copy this “UBOUND” dat file. I asked you in February if this needs to be fixed or not, and you said that it is OK for it having a missing letter.

**Comment by covarell** [comment]
I found the conversation we had about this. I said:
"
OK for the missing final character in $UBOUND (for this, please make a PR on master, for the tutorial I don't think we need it).
"
So I meant it was OK to fix it. :-) Never mind, I wasn't clear. since I have an open PR on the master branch I will fix it.

For me it is a +1 on this PR.

**Pull request merged**
