### PR TITLE
amcnlo dibosons 01j nlo

### PR DESCRIPTION
**Pull request by perrozzi**
WWTo4Q, WZTo1L1Nu, ZZTo2L2Q, ZZTo2Q2Nu

### CODE REVIEW

**Comment by bendavid** [comment]
Since the SUSY group generally cares about the off-shell phase space,
would be preferred for the WZ->lvqq case to generate directly ell+ vl z rather than doing the W decay with madspin.

Otherwise looks good.

**Comment by perrozzi** [comment]
didn't have an example to decay both W in proc_card
is it sufficient to move there the definitions below, from madspin?

define ell+ = e+ mu+ ta+
define ell- = e- mu- ta-
decay w+ > ell+ vl
decay w- > ell- vl~

**Comment by bendavid** [comment]
No, there is no "decay" in NLO mode.

I meant something like
define ell+ = e+ mu+ ta+
define ell- = e- mu- ta-

generate p p > ell+ vl z [QCD] @0
add process p p > ell+ vl z j [QCD] @1
add process p p > ell - vl~ z [QCD] @2
add process p p > ell - vl~ z j [QCD] @3

ie just generate directly ell+ vl z
(this would also include non-resonant diagrams if there were any, but that should be fine)

**Comment by perrozzi** [comment]
hi, what about this pull request? it has been closed, not merged

**Comment by bendavid** [comment]
Sorry, missed the update (actually github doesn't automatically notify us when the pull requests are updated, so please add a comment after doing so)

For the cards.  If you haven't made the gridpacks yet, consider lowering ptj to 15 for consistency with some of the others which have been done (I don't think this should matter much, so if you've already made the gridpacks, don't bother)

**Comment by perrozzi** [comment]
I already created WZTo2L2Q, WZTo1L1Nu2Q, ZZTo2L2Q and I am waiting for ZZTo2Q2Nu... 
After that, only ZZTo4Q and WWTo4Q are missing, I might change ptj for them if requested (but as far as I remember they are relevant mostly for Hbb)

**Pull request merged**
