### PR TITLE
Add DisplacedTop Cards

### PR DESCRIPTION
**Pull request by PaulVaucelle**
Providing the cards for the different benchmark of our signal process as requested by the MC&I contacts of the EXO group. (Analysis reference: Displaced top quark, EXO->LLP sub-group, no CADI-line)

### CODE REVIEW

**Comment by lviliani** [comment]
Please do not commit the full set of cards for all the mass points.
Just put there template cards and a script to generate the full grid.

**Comment by PaulVaucelle** [comment]
Removed the cards and added a script to generate the cards

**Comment by lviliani** [comment]
Thanks! But it seems you are adding also some other stuff not related to your cards. 
Can you please clean it? If it's easier we can close this PR and you open a new one.

**Comment by PaulVaucelle** [comment]
My bad.. Removed the files mistakenly added.
Sorry for the inconvenience

**Comment by lviliani** [comment]
Thank you and sorry for the delayed reply.
Regarding the param_card, if you are using the default one and just changing a few parameters, usually we suggest to use a customize_card instead, where you include only the parameters that will be changed.
Can you do that, or is there a reason why you need to commit the full run card?

Regarding the PDF choice (306000), do you need that particular PDF set? You can also get the default recommendation by using these lines in the run card:
```
    $DEFAULT_PDF_SETS = lhaid     ! if pdlabel=lhapdf, this is the lhapdf number
    $DEFAULT_PDF_MEMBERS  = reweight_PDF
```

**Comment by PaulVaucelle** [comment]
For the PDF, we can definitely use the default recommendation.
For the param card,  we can set everything in the customize card (masses + SELMIX block)

**Comment by lviliani** [comment]
Thank you! I'll merge the PR.

**Pull request merged**
