### PR TITLE
Suu Diquark

### PR DESCRIPTION
**Pull request by evahal**
Adding Suu Diquark files to master branch

### CODE REVIEW

**Comment by evahal** [comment]
Just checking on the status of this pull request.  Thanks.

**Comment by qliphy** [comment]
Can you resolve the conflict?

**Comment by evahal** [comment]
ok, done.  thanks.

**Comment by qliphy** [comment]
You have both CP5 and CUEP8M1
https://github.com/cms-sw/genproductions/blob/e933f265633e55c7f37325787685edf4228d3487/python/ThirteenTeV/VH_M125_Toa01a01_Tobbbb_M12to60-LO_Pythia_cfg.py#L10

Moreover, please don't paste all lines from pythia8CP5Settings and pythia8PSweightsSettings there.

**Comment by evahal** [comment]
This file is not related to my pull request, and does not belong to me.  Thanks.

**Comment by evahal** [comment]
Hello, can you let me know if the pull request is ready?  As I mentioned, the file genproductions/python/ThirteenTeV/VH_M125_Toa01a01_Tobbbb_M12to60-LO_Pythia_cfg.py 
is not related to my pull request.  So I hope all is ok on my end?  Let me know.  Thank you!

**Comment by qliphy** [comment]
@evahal   It seems many commits are mixed up.  Can you make a new PR with only those cards from you?  Thanks a lot!

**Comment by evahal** [comment]
@qliphy - I believe I have done what you requested?  I hope I fixed the mixed up commits.  Can you let me know if it looks ok and the pull request is ready?  If not, let me know and I can try again. Many thanks.

**Pull request merged**
