### PR TITLE
Add aQGC T8 T9 in ZZjj

### PR DESCRIPTION
**Pull request by Werbellin**

### CODE REVIEW

**Comment by perrozzi** [comment]
@kdlong can you have a brief look?

**Comment by kdlong** [comment]
Looks good to me. The cards are only slightly modified from [1] and I know Philipp tested extensively. Though @Werbellin, unless you have a strong preference to keep things as they are, I'd rather see the cards moved into the AnomalousCouplings-SMP folder for organization.

[1] https://github.com/cms-sw/genproductions/tree/master/bin/MadGraph5_aMCatNLO/cards/production/13TeV/AnomalousCouplings-SMP/WLLJJ_WToLNu_aQGC-FT_EWKOnly

**Comment by Werbellin** [comment]
@kdlong I'm fine with putting it elsewhere.

**Comment by kdlong** [comment]
Thanks! @perrozzi should be good to merge now.

**Comment by perrozzi** [comment]
thanks a lot!

**Pull request merged**
