### PR TITLE
added MadGraph5_aMCatNLO cards for sample TGGJets

### PR DESCRIPTION
**Pull request by mmachet**

### CODE REVIEW

**Comment by bendavid** [comment]
pdf's should be changed to 4fs versions (for both central value and uncertainties)

**Comment by mmachet** [comment]
I used the 4f values already used for the TGJets cards (
https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/cards/production/13TeV/TGJets_4f_ckm_NLO/TGJets_4f_ckm_NLO_run_card.dat)
,
following your suggestion and looking at these cards:
https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/cards/examples/wplustest_4f_NLO/wplustest_4f_NLO_run_card.dat

It's not correct?

Thanks

2015-07-20 16:37 GMT+02:00 Josh Bendavid <notifications@github.com>:

**Comment by covarell** [comment]
Seems correct to me...

**Comment by bendavid** [comment]
Sorry, you're right, I read too quickly.  The pdfs are correct.

One other doubt I have is about the ptj cut, which can lead to the sample being not fully inclusive. (for the t-channel single top ptj was set to 0)

**Comment by mmachet** [comment]
I can put the ptj cut to 0. In this case I imagine I have to change also
the TGJets card already in github.

2015-07-20 16:55 GMT+02:00 Josh Bendavid <notifications@github.com>:

**Comment by bendavid** [comment]
Yes I think so.

**Comment by mmachet** [comment]
ok I put the ptj to 0. For the TGJets cards already in github I have to do
another pull request?

2015-07-20 18:15 GMT+02:00 Josh Bendavid <notifications@github.com>:

**Comment by bendavid** [comment]
or add the change to this one.

**Comment by mmachet** [comment]
done

2015-07-20 19:17 GMT+02:00 Josh Bendavid <notifications@github.com>:

**Pull request merged**
