### PR TITLE
updated model and updated PDF

### PR DESCRIPTION
**Pull request by tiwariPC**
Dear all,
We have updated the model and the PDF which we will use in the sample production.
Please have a look and merged this PR.
Thanks a lot,
Praveen

### CODE REVIEW

**Comment by qliphy** [comment]
Why do you need this specific PDF with ID 13100?

**Comment by tiwariPC** [comment]
This pdf has been suggested by Katerina Lipka, and Exo MC contacts, MCI and MET+X convenors have given the green light the for this pdf hence we have used this PDF

**Comment by qliphy** [comment]
Ok, thanks.  To leave a record for future reference, can you give a bit more details or provide a link to refs?

**Comment by tiwariPC** [comment]
For the details, please have a look here :
https://indico.cern.ch/event/800504/contributions/3326573/attachments/1800774/2937275/bbDM_StatusUpdate_22022019.pdf#page=3
For the pdf selection, the discussion was over mail.

**Comment by qliphy** [comment]
But "13100 CT14nlo" may brings inconsistency with Pythia8 Tunes.
If you don't want NNLO PDF, then why not just use NNPDF3.1LO with CP2 Tune?  
https://twiki.cern.ch/twiki/bin/view/CMS/PhysicsComparisonAndGeneratorTunes#Recommendations_on_the_usage_of

**Comment by tiwariPC** [comment]
We will use the following combination for our sample production:
ME (NNPDF3.1 NLO) + PS (CP3)
this combination has also been suggested in the twiki no?

**Comment by qliphy** [comment]
Yes,  that is fine.  But then why setting 13100 (CT14nlo) in run_card.dat?

**Comment by tiwariPC** [comment]
Dear Qiang Li,
Thanks a lot for clarification.
We will use NNPDF3.1 NLO as the central pdf. I checked here: 
https://lhapdf.hepforge.org/pdfsets
I see that for NNPDF3.1 NLO the pdf ID is 305000.
But this PDF id I do not see in the following list:
https://github.com/cms-sw/genproductions/blob/master/MetaData/pdflist_5f_2017.dat
Our main motive is that we want to save  NNPDF3.1 NLO as central pdf and also save 13100 (CT14nlo) for systematics.
Could you please let me know what is the way to do that and how to check if the systematics are saved in the LHE file?
Thanks a lot,

**Comment by qliphy** [comment]
But there is  "305800 NNPDF31_nlo_hessian_pdfas 103"  which you can use.

To check PDF information, you can refer to: 
https://twiki.cern.ch/twiki/bin/viewauth/CMS/HowToPDF

**Comment by tiwariPC** [comment]
Dear Qiang,
I have updated the cards, please have a look.
Thanks a lot

**Pull request merged**
