### PR TITLE
Update condor management to work also on lxplus

### PR DESCRIPTION
**Pull request by kdlong**
Small updates to the condor interface to be more robust across different condor versions. Tested and working on both new (installed on lxplus) and old versions of condor.

@khurtado, @lorusso7, would it be straightforward to test this version with CMS Connect?

@huohuo21, would you be able to run some test gridpacks at Fermilab or another Tier 2? The lxplus afs issues are not yet solved.

### CODE REVIEW

**Comment by khurtado** [comment]
@kdlong : We could test, here is a couple of points to consider though:

- I remember `mg25x` had issues with the `set cluster_type condor` where even if declared it ran everything on the submission node in multicore mode on CMS Connect. This was related to the version of Madgraph `mg25x` uses, which is why I moved to the `master` branch. Was that also a problem on `lxplus` machines at some point? If not, that would be the first thing to re-test.
- Assuming the above works, I can make a pull request with the CMS Connect changes I added to the `master` branch and either @lorusso7 or me could test ( I would actually need to add an [extra patch](https://github.com/khurtado/genproductions/commit/53253fe5c9eef0cf5fac3fde4e81335c788cd009) in @lorusso7 has been testing that fixes an issue with CMS Sites using Singularity )

Does that sound reasonable?

**Comment by kdlong** [comment]
You're right. I realized this problem was still there shortly after making this pull request. It's a bug in MadGraph itself, though I think a work around should be trivial. I'll hopefully have an update shortly.

**Comment by menglu21** [comment]
@kdlong sure, i will do that

**Comment by menglu21** [comment]
@kdlong , submit_condor_gridpack_generation.sh works fine at Fermilab

**Comment by kdlong** [comment]
Thanks @menglu21! Though I suspect it was running in multicore mode and not on the cluster, because of the problem @khurtado mentioned (if you look at the log file and see that the exact same number of jobs were always running at the same time, it would give you a strong indication that this was the case).

I'll push a quick fix to this problem shortly and we can try again.

**Pull request merged**
