### PR TITLE
modified gridpack script to avoid compilation problems in ggHH

### PR DESCRIPTION
**Pull request by agrohsje**
disabled unneeded pythia 8 part of ggHH makefile

### CODE REVIEW

**Comment by perrozzi** [comment]
have you checked that it doesn't break up `gg_H` ?

**Comment by agrohsje** [comment]
Good point. For the time being it doesn't, but to be sure there is never an issue, I split the if statement.

**Comment by perrozzi** [comment]
sorry, I don't want to be too picky but leaving the code as it was and add another if only for gg_HH would be better

**Comment by agrohsje** [comment]
Done.

**Pull request merged**
