### PR TITLE
Settings for TTWW 5FS LO

### PR DESCRIPTION
**Pull request by jfernan2**

### CODE REVIEW

**Comment by perrozzi** [comment]
hi, why NLO PDF?

**Comment by jfernan2** [comment]
There's no LO 5FS pdf, right?
https://lhapdf.hepforge.org/pdfsets.html

**Comment by perrozzi** [comment]
generally speaking, when no flavor is specified, it's 5F. 
You can see that 263000 doesn't specify 5F and the other close-by PDFs specify 3F, 4F, 6F
263000	NNPDF30_lo_as_0130	101	2	
263200	NNPDF30_lo_as_0130_nf_3	101	2	
263400	NNPDF30_lo_as_0130_nf_4	101	2	
263600	NNPDF30_lo_as_0130_nf_6	101	2
so you can use 263000

**Comment by jfernan2** [comment]
OK. I believe you are right. I have updated the settings

**Comment by jfernan2** [comment]
Sorry, I screwed up the PR, I'll close and create a new one

**Pull request closed without merging**
