### PR TITLE
Single top t-channel 4 FNS for 2017 MC production

### PR DESCRIPTION
**Pull request by Andrej-CMS**
please check the powheg input files for the 2017MC production

### CODE REVIEW

**Comment by efeyazgan** [comment]
Could you please discuss the parameters in the ME with the TopModGen group? Thanks.

**Comment by efeyazgan** [comment]
@jfernan2

**Comment by jfernan2** [comment]
@Andrej-CMS are you taking care of prodcuing these gridpacks?
@ckmackay can you have a look and confirm? For me they look fine but I don't know real details for ST...
Thanks

**Comment by Andrej-CMS** [comment]
@jfernan2 
Yes, I'm producing the gridpacks for these processes. 
The only updated the particle masses according to the recommendations on the twiki and CKM matrix according to DPG. The values in the old cards were outdated

**Pull request merged**
