### PR TITLE
fixed syntax in critical madspin patch (0015) to make sure all decay …

### PR DESCRIPTION
**Pull request by agrohsje**
…me's are properly generated

### CODE REVIEW

**Comment by agrohsje** [comment]
Hi @ckmackay . This PR should fix the madspin problem in 2.6.1. I will try to redo your gridpacks:
https://github.com/cms-sw/genproductions/tree/master/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/TGGJets_leptonDecays_4f_ckm_LO
and let you know.

**Comment by qliphy** [comment]
@agrohsje   Thanks a lots!  Let's wait for your test result before merging this.   Please also make a same PR to mg261_UL branch.

**Comment by agrohsje** [comment]
@ckmackay @qliphy @efeyazgan I tested this PR with Kates gridpacks and everything is working well. There were some patch complaints which I just fixed to avoid confusing output. 
One remark. I noticed that using these cards https://github.com/cms-sw/genproductions/tree/master/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/TGGJets_leptonDecays_4f_ckm_LO the pilot run fails to generate enough events, or better say, not the required number of events. This is because of singularities in the setup, e.g. missing dR cuts. At the same time, some dR cuts are already 0.4 i.e. as on detector level. Is that intended? 
Anyway, these points are independent from the actual problem, my PR. Should I merge?

**Comment by qliphy** [comment]
Thanks @agrohsje   Can you also update mg261_UL branch accordingly?

**Pull request merged**
