### PR TITLE
update Phantom script to fit CONDOR

### PR DESCRIPTION
**Pull request by menglu21**

### CODE REVIEW

**Comment by qliphy** [comment]
Thanks.  It would be great if you can give a report on Phantom at the MEFG+Validation meeting on 9th March.

**Comment by menglu21** [comment]
> Thanks. It would be great if you can give a report on Phantom at the MEFG+Validation meeting on 9th March.

Hi Qiang, 

Ok, i think i can give an update on this topic.

Cheers,
Meng

**Comment by qliphy** [comment]
Thanks.  Added to the agenda: https://indico.cern.ch/event/873797/

**Comment by agrohsje** [comment]
Hi @menglu21 . Should we still wait before merging? Can you quickly comment on your next steps? I assume your PR was triggered by the point Benedikt raised, or ?

**Comment by menglu21** [comment]
> Hi @menglu21 . Should we still wait before merging? Can you quickly comment on your next steps? I assume your PR was triggered by the point Benedikt raised, or ?

Hi @agrohsje , it's due to the pdf issue. the difference seems not small, i think we may need to reproduce the sample. The sample size is small (WA: 700K, ZA: 300K), so i guess we can afford redoing the production in a short time.

**Pull request merged**
