### PR TITLE
fix when we get NaN in MCFM

### PR DESCRIPTION
**Pull request by hroskes**
Sometimes events with 4 lepton interference have NaN somewhere in the phase space.  When the event generation finds this NaN, MCFM crashes because there's an assertion in LHAPDF that q^2 > 0, and NaN is not > 0.

This is a patch to run MCFM multiple times and merge the LHE file together, dropping the events that are only partially written with no </event>.  Because MCFM doesn't always produce the exact number of events requested, the script selects random ones to drop.  (This was done already, but now it looks through multiple files.)

The implementation is mostly copied from the Madgraph one, with some adaptations.  I've run some local tests and it works well.

### CODE REVIEW

**Comment by perrozzi** [comment]
this is to fix the errors recently observed in production, right?

**Comment by hroskes** [comment]
Yes that's right

**Comment by perrozzi** [comment]
has this been tested?

**Comment by hroskes** [comment]
I tested it by using a script to patch existing gridpacks, and it works great.  We haven't tested one produced from scratch yet.

**Pull request merged**
