### PR TITLE
pm1 and pm6 top mass variation TT POWHEG sample

### PR DESCRIPTION
**Pull request by rgoldouz**

### CODE REVIEW

**Comment by maierbenedikt** [comment]
Is it possible to merge this pull request? TOP would like to report these samples in the MCCM this Thursday.

Thanks!

**Comment by covarell** [comment]
powheg part looks fine to me.
Just to be sure, are the proc_cards and run_cards totally identical, and just renamed n times to please the gridpack generation script?

**Comment by maierbenedikt** [comment]
Yes, the only file content that is changed is the customizecard with different top masses. All other cards are identical except for the name.

**Comment by bendavid** [comment]
Ah ok, missed that this contains both powheg and madgraph cards.  @maierbenedikt this was intentional right?

**Comment by rgoldouz** [comment]
Yes Josh, Top group needs both Powheg and madgraph TT samples while the top mass is varied.
I am preparing the grid packs for the madgraph samples.

Thanks,
Reza

**Comment by bendavid** [comment]
Ok thanks (was just confused by the name of the pull request)

**Pull request merged**
