### PR TITLE
Zz polarized

### PR DESCRIPTION
**Pull request by susmitamondal29**
Uploading cards for ZZ Polarization analysis. Previously, cards were already checked by conveners on master branch (previous pull request link here:https://github.com/cms-sw/genproductions/pull/2893#issuecomment-1027132849).

### CODE REVIEW

**Comment by menglu21** [comment]
Hi, it seems you uploaded the cards to both example and production directory, if they are the same, could you please remove those in "example" directory. and also there is an additional runcard~, please also remove it.

**Comment by susmitamondal29** [comment]
Hi I am sorry for the delayed reply. I have removed the cards in the "example' directory and have removed  the additional runcard~. Kindly let me know if anything else is required.

**Comment by menglu21** [comment]
it seems the cards under example are still there, maybe you forgot to commit the change

**Comment by menglu21** [comment]
Hi, btw, we are planning to upgrade MG to 29X very soon, maybe you can withdraw this PR and make a new PR to master after the migration.

**Comment by susmitamondal29** [comment]
Hi I am sorry but I am not sure I understand what you meant. I was told previously to upload my cards here in the mg27x branch since the master doesn't support that polarization syntax. I also submitted this pull request link for requesting my MC samples and I would prefer to not withdraw this PR for that reason.

**Comment by menglu21** [comment]
Hi @susmitamondal29 our master are now MG299 (for run3). the run2 UL branch is now mg265UL, could you please withdraw this PR and push a new one to mg265UL, and not put them under the "example" directory.

**Comment by susmitamondal29** [comment]
Hi sorry for the delayed reply. In my previous pull request , I was told that polarization syntax is supported on mg27 version (see previous comment: https://github.com/cms-sw/genproductions/pull/2893#issuecomment-1047734279) and it is not supported on mg265 there I should put them in this 27x branch. The new run2UL is mg265UL, so does that support polarization syntax or is a new branch for mg27 going to be created? Kindly let me know.

**Comment by menglu21** [comment]
Hi @susmitamondal29 you can push this to the current master branch, it's now MG299 which supporting the syntax.

**Comment by bbilin** [comment]
Closing the ticket due to timeout, if needed, please reopen.

**Pull request closed without merging**
