### PR TITLE
Fragments for EXO PhotonIndBkgGGToLL for RunIISummer15GS

### PR DESCRIPTION
**Pull request by davidsheffield**
from Dimitri Bourilkov

### CODE REVIEW

**Comment by covarell** [comment]
PDF setting should be removed from all cards

**Comment by covarell** [comment]
unless there is a specific need for this (very old) PDF set. In any case I believe this is overwritten in the Pythia tune.

**Comment by bouril** [comment]
This PDF is needed because only QED PDFs provide photons needed to calculate the photon induced background.

To avoid overwriting with the Pythia tune, I think the fragments should be modified:

PDF:useHard = LHAPDF6:MRST2004qed.LHgrid

This way Pythia will use a specific PDF for the hard process (the one we need here), and the standard PDF for the tune.

**Comment by bouril** [comment]
Correction: after more testing, this is the setup to use a specific PDF for the hard process (the one we need here), and the correct (different) PDF for the tune.

PDF:useHard on
PDF:pHardSet  = LHAPDF6:MRST2004qed.LHgrid
PDF:pSet = <tune_PDF>

**Comment by bendavid** [comment]
I believe that the default nnpdf23LO pdfset in pythia8 DOES have a photon pdf included.  Does it not work?

**Comment by bouril** [comment]
Correct, it has QED included and works. The problem is that it gives suspiciously high cross sections at high mass 2-3 TeV, the MRST2004 PDF behaves more reasonably.

**Comment by davidsheffield** [comment]
Can you approve these fragments?

**Pull request merged**
