### PR TITLE
Sherpa: ttH+0/1jet Run card

### PR DESCRIPTION
**Pull request by mharrend**
I have a Sherpack for this run card ready and would like to run this Sherpack as part of the normal priority campaign of the Higgs group as soon as possible.

Do I have to change the lines 7 and 18?

I would upload the Sherpack to the corresponding /store/group/phys_generator/cvmfs/gridpacks/<your scram architecture>/13TeV/<your generator>/<your version>/ folder after your approval.

### CODE REVIEW

**Comment by bendavid** [comment]
No, sherpacks should go instead still to afs
/afs/cern.ch/cms/generators/www/slc6_amd64_gcc481/13TeV/sherpa/

I let @thuer or @pmillet comment on the other question.

**Comment by thuer** [comment]
yes the sherpacks should go to /afs/cern.ch/cms/generators/www/$SCRAM_ARCH/13TeV/sherpa/

The openloops line has to stay otherwise it sherpa will not find openloops at the grid. The HepMC line can be kept, it is ignored in the SherpaInterface.

But you need the python fragment and not the Run card for the production (should be produced with the sherpack) and add the location where you store the sherpack, e.g. slc6_amd64_gcc491/13TeV/sherpa/

**Comment by mharrend** [comment]
Dear all,

I have now uploaded the sherpack to /afs/cern.ch/cms/generators/www/slc6_amd64_gcc491/sherpa/2.1.1/13TeV/sherpa_ttH_Hinclusive_01j_MCatNLO_OpenLoops_13TeV_MASTER.tgz
and added the python config script to this pull request.

However, I have found a problem with my sherpack. I have generated the sherpack by using OpenMPI to get it produce in a reasonable time of some days on the DESY NAF. 
If I am now trying to run the sherpack inside of CMSSW_7_5_X on the LXPLUS I get the following error messages:

**Comment by mharrend** [comment]
#########################################################
 #     ___                                               #
 #    /   \ ___  ____  _  _  |     __   __  ___   __     #
 #    |   | |__| |__   |\ |  |    /  \ /  \ |__| /__     #
 #    \___/ |    |___  | \|  |___ \__/ \__/ |    __/     #
 #                                                       #
 #########################################################
 #  You are using OpenLoops to evaluate loop amplitudes  #
 #                     Authors:                          #
 # F. Cascioli, J. Lindert, P. Maierhoefer, S. Pozzorini #
 #    Please cite Phys. Rev. Lett. 108 (2012) 111601     #
 #########################################################
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
Matrix_Element_Handler::BuildProcesses(): Looking for processes Library_Loader::LoadLibrary(): libmpi_cxx.so.1: cannot open shared object file: No such file or directory
Library_Loader::LoadLibrary(): Failed to load library 'libProc_P2_3_2_2_63_16_8_0.so'.
Library_Loader::LoadLibrary(): libmpi_cxx.so.1: cannot open shared object file: No such file or directory
Library_Loader::LoadLibrary(): Failed to load library 'libProc_P2_3_2_2_63_16_8_0.so'.
Library_Loader::LoadLibrary(): libmpi_cxx.so.1: cannot open shared object file: No such file or directory
Library_Loader::LoadLibrary(): Failed to load library 'libProc_P2_3_2_2_63_16_8_0.so'.

So the corresponding OpenMPI library is not found.

Looking into the  sherpa_ttH01mcnlo_libs.tgz tar zipped library file I found out that the problem is that the Amegic libraries are compiled with OpenMPI.
Can I assume that the OpenMPI library is available if Sherpa is used in McM?

Or another way: Inside the sherpa_ttH01mcnlo_libs.tgz library file I still have the source code of the different processes. Should I recompile this source code and produce new versions of the failing libraries?

**Comment by thuer** [comment]
Dear Marco,

no the Sherpa version in CMSSW do not have OpenMPI available. You can fix the Sherpack by redoing the Library creation + compilation using the CMSSW Sherpa version (you can use the MakeSherpaLibs.sh script with -o LIBS option). This step should not take too long and afterwards you can create the sherpack with these libs combined wiht the other results using the MPI Sherpa version.

-Sebastian

**Comment by mharrend** [comment]
Dear Sebastian, dear all,

I have now updated the sherpack, so that the libraries do not depend on OpenMPI.
The sherpack is now also working fine on LXPLUS. Thus, please merge this pull request.

Unfortunately, I could not overwrite the old sherpack
/afs/cern.ch/cms/generators/www/slc6_amd64_gcc491/sherpa/2.1.1/13TeV/sherpa_ttH_Hinclusive_01j_MCatNLO_OpenLoops_13TeV_MASTER.tgz

Instead I had to copy the updated sherpack to a new file
/afs/cern.ch/cms/generators/www/slc6_amd64_gcc491/sherpa/2.1.1/13TeV/sherpa_ttH_Hinclusive_01j_MCatNLO_OpenLoops_13TeV_MASTER_V2.tgz

Can you please remove the old sherpack?

One further question in regard to the McM production and the necessary steps:
* I now have to clone a GS request in McM and to adjust "Name of fragment" and "Fragment tag" so that they point to the merged python configuration of my sherpack. Of course, also changing the other parameters like number of events and so on.
* Afterwards I will start a validation of the GS request and not a chain validation since I do not have a LHE file.

Is this the right procedure?

**Comment by covarell** [comment]
Done removing old sherpack. The McM procedure should be correct

**Comment by mharrend** [comment]
Can you please merge this pull request?

Thanks

**Pull request merged**
