### PR TITLE
Merge branch mg29x to the master

### PR DESCRIPTION
**Pull request by SanghyunKo**
This PR will merge the mg29x branch to the master branch, and the current master branch is cloned to the mg265UL branch. All merge conflicts were resolved. I propose to hold this PR until we make a proper announcement for the migration @Saptaparna @GurpreetSinghChahal @menglu21

### CODE REVIEW

**Comment by sihyunjeon** [comment]
:)

**Comment by menglu21** [comment]
+1

**Comment by Saptaparna** [comment]
+1

**Comment by Saptaparna** [comment]
I will merge this by the end of the day in Chicago if there are no further comments!

**Comment by sihyunjeon** [comment]
@shimashimarin @SanghyunKo Forgot to ask. Were we able to check this in cms connect before merging?

@Saptaparna @menglu21 @GurpreetSinghChahal  Maybe we should alert MC contacts first (through MccM or cms talk earlier before merging)? Some people might just use master branch without checking what the versions are. Or I will add some printout lines when deploying gridpack generation jobs

**Comment by sihyunjeon** [comment]
@menglu21 @Saptaparna @GurpreetSinghChahal Could we get the PDF sets also updated in this branch altogether?

**Pull request merged**
