### PR TITLE
13TeV light charged higgs to cb decay signal sample in tt event

### PR DESCRIPTION
**Pull request by diracyoon**

### CODE REVIEW

**Comment by diracyoon** [comment]
13TeV light charged higgs to cb bar decay signal sample in tt event

**Comment by diracyoon** [comment]
13TeV light charged higgs to cb decay signal sample in tt event

**Comment by perrozzi** [comment]
can the review start or do you need to add any other commit?

**Comment by diracyoon** [comment]
Dear Perrozzi,

   You can start the review. Thank you.

Sincerely,
Inseok

2016-11-10 08:30에 perrozzi 이(가) 쓴 글:

**Comment by perrozzi** [comment]
can you confirm that the model is using 5F pdf?

**Comment by diracyoon** [comment]
Dear Perrozi,

   Yes. The model is using 5F pdf. Thank you.

Sincerely,
Inseok

2016-11-16 17:56에 perrozzi 이(가) 쓴 글:

**Comment by diracyoon** [comment]
Thank you! - Inseok Yoon


2016-11-18 17:50에 perrozzi 이(가) 쓴 글:

**Pull request merged**
