### PR TITLE
ST_tW_nunu cards

### PR DESCRIPTION
**Pull request by ckmackay**
ST_tW_nunu_5f_LO madgraph cards

### CODE REVIEW

**Comment by efeyazgan** [comment]
Could you please get rid of the commented or unused lines?

**Comment by ckmackay** [comment]
Is run_card OK like this, or should I take out more of the comments?

**Comment by ckmackay** [comment]
Removed the unnecessary lines.

**Comment by efeyazgan** [comment]
You have "True = pdfwgt" twice.

**Comment by ckmackay** [comment]
Removed one of them

**Pull request merged**
