### PR TITLE
Change on center of mass energy request  

### PR DESCRIPTION
**Pull request by G-Vian**
Dear GEN Team,

I hope this message finds you well. 

Please consider only the cards I submited in the folIowing folders:
[cms-sw/genproductions/tree/master/bin/MadGraph5_aMCatNLO/cards/production/13p6TeV/TTHH_5f_LO] 
and [cms-sw/genproductions/tree/master/bin/MadGraph5_aMCatNLO/cards/production/13p6TeV/TT4b_5f_LO]

### CODE REVIEW

**Comment by sihyunjeon** [comment]
6840GeV beam comes from where ? also you mistakenly touched 13TeV directory which is fine with 6500GeV...

**Comment by neutrino-vian** [comment]
My intention is to obtain a center of mass energy of 13680 TeV for the proton collision, that's why each beam have a energy of 6840 GeV.

I corrected the directory, now the files are uploaded in the 13p6TeV directory

**Comment by sihyunjeon** [comment]
well that is still not 13.6TeV, maybe you should explain the motivation for that beam energy (or is there a plan from LHC to run at that energy before HL-LHC?)

your git commit still has 13.6TeV run_card.dat touched which should not be there

**Comment by neutrino-vian** [comment]
Now I adjusted the energy of the beams to 6800 GeV. 
I"ve also corrected the  13TeV run_card.dat.

**Comment by G-Vian** [comment]
Dear GEN Team,

I apologize for the previous error regarding the center-of-mass energy values. I have now corrected them and also made adjustments to the directories that I had inadvertently modified.

I look forward to any further updated you may have.

Thank you very much for your understanding and assistance.

**Comment by G-Vian** [comment]
Dear GEN Team,

I would like to kindly request if there are any updates about my request of change in the Center of Mass energy in the ttHH and tt4b cards.

Thank you very much!

**Comment by lviliani** [comment]
Hi @G-Vian, sorry I have merged this PR but there are actually still a few potential issues as @sihyunjeon pointed out.

1.  In the ttHH run card you set `15000.0 =  bwcutoff`. This can lead potentially to both computing and physics issues, such wrong cross sections. Do you need such a large value? Otherwise please set it to 15 as in the other card.
2. In the tt4b run card you are applying the following cuts which are likely not necessary (unless you have a specific reason) and could have an impact on the analysis:
```
  10.0	=  mmjj     ! min invariant mass of a jet pair 
  10.0	=  mmbb     ! min invariant mass of a b pair 
 ```
 Can you please create a new PR to address these problems?
 Thanks and sorry for not realizing before.

**Comment by asavoy829** [comment]
Hi @lviliani, related to the email here above sent to @G-Vian, please find here below our answers to the 2 points you mentioned:
Point 1: we found the link to the cards for Run2 production [1]. The bwcutoff is the same value. I can see the person who prepared the cards uses a github account name jfernan2 but I did not recognize who he/she is
[1] https://github.com/jfernan2/genproductions/tree/935ee2b8f8fce279c60c0696fa9e03b7e556a91a/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/TTHH_5f_LO

Point 2: The Run2 tt4b cards were handled by Sebastian Wieland (former PhD student at KIT), but he left about 8 months ago. You can find the previous pull requests for tt4b Run2 in the links below [2,3,4]. It seems there was an intention to set mmjj and mmbb parameters.
[2] https://github.com/cms-sw/genproductions/pull/2601
[3] https://github.com/cms-sw/genproductions/pull/2595
[4] https://github.com/cms-sw/genproductions/pull/2481 
Unfortunately we have no more information about these points than those we mention here above. Hope it is useful for GEN.
Many thanks in advance and staying tuned.

**Comment by asavoy829** [comment]
Hi @lviliani 
It looks like [2], [3], [4] didn't were well reproduced so here below again:
[2] https://github.com/cms-sw/genproductions/pull/2601
[3] https://github.com/cms-sw/genproductions/pull/2595
[4] https://github.com/cms-sw/genproductions/pull/2481

**Pull request merged**
