### PR TITLE
Adding Displaced photon cfgs

### PR DESCRIPTION
**Pull request by shchauha**

### CODE REVIEW

**Comment by perrozzi** [comment]
please move the files to a common subfolder named GMSB or similar

**Comment by shchauha** [comment]
I have moved the config files to GMSB and HVDS  directories. Could you please approve the pull request now?

**Comment by perrozzi** [comment]
I still see a lot of HVDS-like files outside of the HVDS folder, can you please check?

**Comment by shchauha** [comment]
I have now deleted the GMSB and HCDS files outside of the corresponding directories. Apologies for the trouble.

**Pull request merged**
