### PR TITLE
 import validation tools including location for validation gridpacks …

### PR DESCRIPTION
**Pull request by agrohsje**
…and README

### CODE REVIEW

**Comment by perrozzi** [comment]
bin/GenValidation/validation_cards/dy01234mlm/dy01234mlm_proc_card.dat
seems to be an empty file, can you please remove it?

**Comment by agrohsje** [comment]
I know. I created this as an example. If you don't want to merge it we can also wait for files provided by Sapta.

**Comment by perrozzi** [comment]
should not harm to wait

**Comment by agrohsje** [comment]
I just included the latest card files. From my side it isready. Once it is merged, Sapta will add condor for job submission.
Thanks!

**Pull request merged**
