### PR TITLE
add top width to UL17 st production cards

### PR DESCRIPTION
**Pull request by llechner**
add powheg cards for UL17 single-top production
copied from F18-cards
added line "tdec/twidth 1.31" for the top width

see here:
https://indico.cern.ch/event/855960/contributions/3602128/note/

### CODE REVIEW

**Comment by agrohsje** [comment]
Copy/paste email to keep track :
Dear Giulia, dear Lukas,

thanks for all your work. Please find feedback below. I hope my mail is clear. Let me know if you want to discuss something directly.

Cheers, Alexander.


1.) How many neg weights do we have in tW DR? I see that the default powheg.input has
foldcsi   5
foldy     5
while we have only 1 folding for each of them.
2.) tdec/twidth is the option in hvq. For tW/-channel it should be topwidth.
3.) I see alphaem_inv  132.3384323. Shouldn't we pick the value at the top or Z mass rather than the Thompsan alpha_s ? What does the value of 0.2226459 for the Weinberg angle correspond to? We should set this consistently with s-channel production.  
4.) hvq has 80.4 GeV for the W mass: https://github.com/cms-sw/genproductions/blob/d21f0ed12748aebf04112603157711756407e978/bin/Powheg/production/2017/13TeV/TT_hdamp/TT_hdamp_NNPDF31_13TeV_powheg.input or is this outdated. I would make it consistent. This is also in sync with the w width which is always 2.141. Maybe you can add this explicitly to the input in case we want to change that at some point together with hvq. Same holds for s-channel.
5.) Maybe add a reference where the CKM values are coming from. Why is it different from s-channel?
6.) I would propose to sync also these settings with hvq (not available in s channel):
     lhfm/emass
     lhfm/mumass
     lhfm/taumass
     lhfm/cmass
     lhfm/bmass .
  as well as these ones (also available in s channel):
    tdec/emass
    tdec/mumass
    tdec/taumass
    bottomthr
    charmthr
   
    charmthrpdf
    bottomthrpdf
7.) long term we could change sin2cabibbo to 0.050 in hvq.
8.) https://github.com/cms-sw/genproductions/blob/d21f0ed12748aebf04112603157711756407e978/bin/Powheg/production/2017/13TeV/st_tW_5f_dr_ckm_13TeV_mtop1695/ST_tW_DR_5f_ckm_antitop_13TeV_mtop1695_UL.input
Shouldn't we change the width when we change the mass? I am wondering if this is done in hvq. Do you mind checking?

**Comment by llechner** [comment]
@agrohsje @GiuliaNegro 

Hi Alexander, Hi Giulia,

I changed the cards according to the comments and the email conversation:

1.) Changed it to foldcsi 5 foldy 5 for now. Need to run a small test to know how many negative weights are expected
2.) Change it to "topwidth"
3.) Changed alphaem_inv and sthw2 to the values at the M_Z mass equal to the s-channel cards
4.) Changed M_W to 80.4 GeV and added wwidth being 2.141
5.) Changed the CKM matrix entries according to the PDG values http://pdg.lbl.gov/2019/reviews/rpp2018-rev-ckm-matrix.pdf
6.) Added the following values (for s-channel only the tdec/ masses)
lhfm/emass 0.00051
lhfm/mumass 0.1057
lhfm/taumass 1.777
lhfm/cmass 1.5
lhfm/bmass 4.8
tdec/emass 0.00051
tdec/mumass 0.1057
tdec/taumass 1.777
bottomthr 4.8
charmthr 1.27
bottomthrpdf 4.8
charmthrpdf 1.27

7.) For the moment I left the value of 0.051
**8) For the top width dependence on the top mass, I currently left it constant, need to follow up on that via email**


Best,
Lukas

**Comment by llechner** [comment]
Additionally:
Currently we use a non-UL PDF set in the cards: 306000
instead of NNPDF31 NNLO, 325300 for 5F or 325500 for 4F

do we need to change that?

**Comment by llechner** [comment]
Updated the cards:
-) top width according to the calculations, mass dependent top width
-) changed charm mass to 1.27
-) added 4f t-channel cards for nominal hdampup/down and mtop dependent
-) changed hdamp values in t-channel to synchronize with other cards

**Comment by llechner** [comment]
Updated the cards:
-) changed bottom mass from 4.8 to the pdg value of 4.18
-) added ST t-channel cards with top width variied by +-15% and +-30% with fixed top mass

**Pull request merged**
