### PR TITLE
update AtoZh cards and modify gridpack_generation.sh accordingly

### PR DESCRIPTION
**Pull request by gitytakahas**

### CODE REVIEW

**Comment by covarell** [comment]
@bendavid @govoni , looks fine to me. Since the number of exotic model is growing, I wonder if we should let the script download all of them in every run (this seems the case now)?

**Comment by bendavid** [comment]
Indeed this is something which could be improved.

**Comment by covarell** [comment]
If you would agree, I can modify the script to accept an extra argument with the model name. If that argument exists and makes sense, then the relative tarball is unpacked

**Comment by bendavid** [comment]
Small issue is that this would break compatibility with existing wmlhe fragments.

**Comment by covarell** [comment]
OK, but there are very few committed I think (mostly they are written directly in the fragment box, so they are bound to a specific release)

**Comment by bendavid** [comment]
Alright, let's hold off on that change until we move to the 2.3.x branch in that case.

**Comment by bendavid** [comment]
For this pull request, please replace param cards with customizecards as usual.  Also you probably want cut_decays = F in the run cards to avoid applying unintended cuts to the decay chains.

**Comment by gitytakahas** [comment]
I now updated the cards. 

Regarding the cut_decays values, should I need to reproduce the gridpacks again after fixing cut_decays = F ?

Thanks,
Yuta

**Comment by bendavid** [comment]
Yes you would, although looking at the cards, given that the decay chains are always to leptons, and there are no cuts on lepton pt or eta, it should actually be ok to leave it as is if gridpacks have already been produced.

**Comment by bendavid** [comment]
How did you produce the gridpacks using the param cards though?  The gridpack scripts ignore those completely.

**Comment by gitytakahas** [comment]
Hi Josh,

oh, it is just my mistake when I asked pull request.
I produced gridpacks using custermized cards. Sorry for the confusion.

Best,
Yuta

2015-08-22 16:05 GMT+02:00 Josh Bendavid <notifications@github.com>:

> How did you produce the gridpacks using the param cards though? The
> gridpack scripts ignore those completely.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/genproductions/pull/592#issuecomment-133706927>
> .
>



-- 
Yuta Takahashi
LHC - CMS experiment,
CERN (European Organization for Nuclear Research)

**Comment by bendavid** [comment]
ok, If you're going to use the existing gridpacks with cut_decays=T I think it is ok, but then please update the pull request so that the cards match what was actually used.

**Comment by gitytakahas** [comment]
Sorry, I, by mistake push "close" now it is reopened.

Yuta

**Pull request merged**
