### PR TITLE
HJ MiNNLO

### PR DESCRIPTION
**Pull request by mseidel42**
Compile HJ in MiNNLO mode when `minnlo 1` is found in config

### CODE REVIEW

**Comment by mseidel42** [comment]
@covarell Actually, it seems there is no conflict with your PR, we can just adapt the MiNNLO processes later to allow for greater flexibility with your scheme -- for now it works with the `minnlo 1` flag.

**Comment by Saptaparna** [comment]
Hi Markus, My apologies for the slow response here. Since Roberto's request is merged, can we merge yours too?

**Comment by mseidel42** [comment]
Hi Sapta, I just added a small README as there is interest from HIG, it can be merged, thanks!

I will move this and W/Z MiNNLO to Roberto's new subprocess syntax when I have a free minute.

**Comment by mseidel42** [comment]
Hey, condor DAG submission got broken by https://github.com/cms-sw/genproductions/pull/3207, fixing that here (and adding DY configs at 5 and 8 TeV).

Could you merge it, please?

**Comment by mseidel42** [comment]
@sihyunjeon could you have a look here, please? :innocent:

**Pull request merged**
