### PR TITLE
Disabled cut_decays in run card

### PR DESCRIPTION
**Pull request by daoverton**

### CODE REVIEW

**Comment by agrohsje** [comment]
hi @daoverton , can you provide some more context. thanks!

**Comment by sihyunjeon** [comment]
Ah I can comment on this.

**Comment by sihyunjeon** [comment]
This is about the cut_decays = T/F affecting mutliparton samples or not, which I felt safer to disable this. Do you remember the skype chat?

**Comment by agrohsje** [comment]
I do. So also gridpacks will be based on cut_decay = F ?

**Comment by sihyunjeon** [comment]
Yes I asked them to redo the gridpacks with cut_decay = F during mccm

**Comment by agrohsje** [comment]
Ok. So if you set auto_ptj_mjj, all jets will be affected except for cut_decays = F. I confirm from reading the code.

**Comment by daoverton** [comment]
Hi, I was asleep or I would have commented as well. Thanks for merging!

**Pull request merged**
