### PR TITLE
vbf_wp_wp powheg.input cards

### PR DESCRIPTION
**Pull request by AndrewLevin**
These cards were made starting from the powheg.input file in 

vbf_wp_wp/testrun/ 

and by applying the changes recommended in the 

vbf_wp_wp/Docs/manual-BOX-VBF_Wp_Wp.pdf

for each of the steps

### CODE REVIEW

**Comment by govoni** [comment]
Andrew, for my information: do these card match the tests performed by Jasper?

**Comment by AndrewLevin** [comment]
I think Jasper was using a single card for all of the steps, which was much slower and different from the instructions. I asked Jasper and he said he was OK with these cards.

**Comment by covarell** [comment]
Is there already a fix available for the wrong helicity angles?
If yes, is it also propagated to the version we are using in CMSSW?
@syuvivida @yuanchao

**Comment by AndrewLevin** [comment]
The powheg authors updated the powheg svn with a fix two weeks ago. Jasper and I have been using the powheg svn directly.

**Comment by govoni** [comment]
Ok, then I am merging this cards, please wait in submitting a request until the new powheg release is ready in the CMS system.  @yuanchao are you aware of the issue?

**Comment by yuanchao** [comment]
@govoni Need some pointer about the helicity angle bug. @AndrewLevin Does the current powheg version in CMSSW work with this input card? Or should I just check with the CVS version?

**Comment by AndrewLevin** [comment]
See here:

https://hypernews.cern.ch/HyperNews/CMS/get/generators/2723.html

The bugfix does not involve any changes to the input cards.

**Comment by yuanchao** [comment]
Thanks! I'm wondering if the settings on ncall1, ncall2, itmx1, itmx2 are universal for other processes? If so I can implement them into run_pwg.py script.

**Comment by AndrewLevin** [comment]
They are not universal. They came from the manual for this specific process and they are different for example in the Wp_Wp_J_J process.

**Pull request merged**
