### PR TITLE
updated non res HH cards

### PR DESCRIPTION
**Pull request by sudhaahuja**
Updated the Non resonant HH cards, after the comments given on this pull request - https://github.com/cms-sw/genproductions/pull/549/

### CODE REVIEW

**Comment by syuvivida** [comment]
In general the cards look OK to me. Two questions:
1) is the model BSM_gg_hh already in the afs generator area? you also need to update gridpack_generation.sh to include this model
2) could you list the number of events requested for each variation of parameters? Are there 56 variations?

**Comment by OlivierBondu** [comment]
Hi Eiko,

1)
  * yes, it was uploaded by Josh, is is located at ```/afs/cern.ch/cms/generators/www/BSM_gg_hh.tar```
  * I'll let @sudhaahuja answer about the ```gridpack_generation.sh``` script

2) 
  * There are 14 variations and 4 final states (bbbb, bbTT, bbGG, bbVV), hence (14 variations) x (4 final states) x (3 cards) = 168 files
  * The plan is to ask 300k event for bbbb, bbTT, bbVV final states and 50k for bbGG (which is within the budget discussed in December for the 1B+4B campaign). Only 4 variations out of 14 are intended for the 1B

**Comment by sudhaahuja** [comment]
@syuvivida , the gridpack_generation.sh script has been updated with the model.

**Comment by syuvivida** [comment]
@sudhaahuja 
 sorry for late reply, but if I check the current version of gridpack_generation.sh, I don't see
BSM_gg_hh.tar being untared in the script.

**Comment by OlivierBondu** [comment]
@syuvivida : I am not sure I understand: the script was updated in the latest commit by Sudha and shows up in this PR, namely this line: https://github.com/sudhaahuja/genproductions/commit/4632c11b17d8a000f82a8593223b3d17484cf679#diff-56bfba1423a749bf2d1829498400b7b4R349

are you referring to something else ?

**Comment by syuvivida** [comment]
ok, I missed the pull request for gridpack_generation.sh since there are many files committed.
In this case. This is fine.

@bendavid and @covarell can you merge the pull request then?

**Comment by sudhaahuja** [comment]
The new request with the changes is here - https://github.com/cms-sw/genproductions/pull/604. Please merge the changes from there. Thanks.

**Pull request closed without merging**
