### PR TITLE
ST-tch_4f input cards

### PR DESCRIPTION
**Pull request by smhasan0201**
These input cards correspond to the nominal requests of the following ticket - [https://its.cern.ch/jira/projects/CMSTOPMCREQ/issues/CMSTOPMCREQ-28?filter=allopenissues](https://its.cern.ch/jira/projects/CMSTOPMCREQ/issues/CMSTOPMCREQ-28?filter=allopenissues)

### CODE REVIEW

**Comment by agrohsje** [comment]
dear @smhasan0201 , do you submit these on behalf of TMG. are they for systematics? how many events do you need? we should handle this centrally with the common backgrounds.

**Comment by smhasan0201** [comment]
Hi @agrohsje, thanks for your comment, I am not sure about the first question. Giulia told me to work on this, so I guess I am submitting this on behalf of TMG. They are for run 3 single top samples. 
For the nominal requests, we need, 
ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8 - Events: 144 M
ST_t-channel_antitop_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8 - Events: 72 M

**Comment by agrohsje** [comment]
I would turn on the neg. weights:
withnegweights 1
to keep better control. 
Maybe you can remove the #smartsig #bornonly, but purely cosmetics. 
For the sample name, we propose:
TbarBQ_4FS-t-channel_TuneCP5_13p6TeV_powheg-madspin-pythia8
Then we can delete SMP afterward. @sihyunjeon We agreed on this, right? I couldn't find in Skype. 
For madspin etc you can check InputCards in 
/cvmfs/cms.cern.ch/phys_generator/gridpacks/RunIII/13p6TeV/slc7_amd64_gcc900/Powheg/st_tch_antitop_4f_13p6TeV_powheg_maspin_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz

**Comment by smhasan0201** [comment]
Hi @agrohsje, Thanks for your suggestions. I have modified the input cards to address the suggestions. Please let me know if they are okay.

**Comment by smhasan0201** [comment]
Hi @menglu21, to make sure I understand this correctly, these samples are already produced and I need to download the gridpack, unpack it and then copy the cards here and delete what I have created?

**Comment by GiuliaNegro** [comment]
Hi @menglu21 , the SMP sample was produced with different Powheg settings. We are now using the common MC v2 settings for Powheg so these cards should be approved in order to produce a new sample with correct settings (in sync with ttbar).

**Comment by menglu21** [comment]
> Hi @menglu21 , the SMP sample was produced with different Powheg settings. We are now using the common MC v2 settings for Powheg so these cards should be approved in order to produce a new sample with correct settings (in sync with ttbar).

could you please point out the difference

**Comment by GiuliaNegro** [comment]
Hi @menglu21 , the difference is in the following settings (in sync with the Run 3 TT and ST samples centrally produced): 
hdamp 250 ! common MC v0.2 
bmass 5.06 ! common MC v0.2 
bottomthr    5.06 ! common MC v0.2
bottomthrpdf 5.06 ! common MC v0.2
charmthr     1.525 ! common MC v0.2
charmthrpdf  1.525 ! common MC v0.2

**Pull request merged**
