### PR TITLE
Add cards for VBF narrow-width Radion, Wprime and BulkGrav ZV->llqq samples

### PR DESCRIPTION
**Pull request by nurfikri89**
This PR is to add cards for VBF production samples of narrow-width Radion, Wprime and BulkGrav resonances decaying to ZZ or ZW which then exclusively decays to llqq. The VBF inclusive decay samples are available but the effective statistics for the llqq channel is poor, hence the need to request samples that exclusively decay to llqq.

### CODE REVIEW

**Comment by qliphy** [comment]
Please follow our [recommendations](https://twiki.cern.ch/twiki/bin/view/CMS/Fall18Repack) and set pdfwgt to F
https://github.com/cms-sw/genproductions/blob/91e775a199d34c8bdd90b51b4c4dd217d4fe653b/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/exo_diboson/Spin-0/Radion_VBF_ZZ_ZlepZhad/Radion_VBF_ZZ_ZlepZhad_narrow_M/Radion_VBF_ZZ_ZlepZhad_narrow_M_run_card.dat#L71

**Comment by nurfikri89** [comment]
@qliphy Thanks! Does this also apply for pre2017 cards?

**Comment by qliphy** [comment]
yes

**Comment by nurfikri89** [comment]
@qliphy The fix has been committed.

**Pull request merged**
