### PR TITLE
Excited top quark with spin 3/2 (fixed a mistake)

### PR DESCRIPTION
**Pull request by ymtzeng**
Here is the SHA code " 33032da0eba3466b92d9f139afd447ce6193b3b6 "

### CODE REVIEW

**Comment by bendavid** [comment]
Is the model already available in the gridpack_generation.sh script?  Does the model have massive or massless b-quarks by default?  (The cards here are set up for 4-flavour scheme production, which is fine if and only if the model has massive b-quarks by default)

**Comment by ymtzeng** [comment]
Dear Josh,

Many thanks for your reminders.
This model is already put on
https://cms-project-generators.web.cern.ch/cms-project-generators/top32.tgz
. Yes, this model has massive b-quark (4.7GeV) by default.

Cheers,
Jacky

**Comment by bendavid** [comment]
Ok, is the model included in gridpack_generation.sh as well?

**Comment by ymtzeng** [comment]
Dear Josh,

Yes, I include this model in my "gridpack_generation.sh".

Cheers,
Jacky

**Comment by bendavid** [comment]
Right, but in order for the gridpacks to be reproducible, this has to be included in the central gridpack_generation.sh as well.

**Comment by ymtzeng** [comment]
Dear Josh,

Could you remind me how to officially make it?
Thanks again.

Cheers,
Jacky

**Comment by bendavid** [comment]
You need to add the changes to gridpack_generation.sh as part of the pull request.

**Comment by ymtzeng** [comment]
Dear Josh,

I have added top32 model in gridpack_generation.sh as SHA code of 4a13406.
If you need further things from my side, please let me know.
Many thanks.

Cheers,
Jacky

**Comment by ymtzeng** [comment]
Dear Josh,

Thanks for your help.
What else should I do to prepare?

Cheers,
Jacky

**Comment by bendavid** [comment]
Now it's merged, so you can prepare the gridpacks, upload them to eos, and then you or MC contacts need to prepare the MCM requests.

**Comment by ymtzeng** [comment]
Dear Josh,

Many thanks.

Cheers,
Jacky

**Pull request merged**
