### PR TITLE
Model: dark-Higgs WW 

### PR DESCRIPTION
**Pull request by calderona**
New MC model and cards for Dark-Higgs --> WW signal inside the EXO group.

### CODE REVIEW

**Comment by agrohsje** [comment]
Looks good to me. Maybe one question: Should we really have the hadronizer here? @qliphy feel free to merge.

**Comment by qliphy** [comment]
We got noticed that it is possible setting 'event_norm = average' (default is 'sum') for LO processes will cause issues in production.  Can you have a check by generating gridpacks with different event_norm setting and test locally?

**Comment by calderona** [comment]
I have tested both settings: sum and average, and it works with both. If you recommend to move to the default 'event_norm =sum', we will go ahead with it

**Comment by qliphy** [comment]
Thanks.  Please set event_norm as sum

**Pull request merged**
