### PR TITLE
Add DiphotonJet backgrounds 13p6TeV card

### PR DESCRIPTION
**Pull request by chuwang1**
Dear expert,
We want to add one sherpapack for RunIII diphoton analyses.
The RunII sherpa card located in:
https://github.com/cms-sw/genproductions/blob/master/bin/Sherpa/cards/production/2017/13TeV/higgs/Run.dat_13TeV_gamgam_3j_loop_Mgg80-13000

We just changed the beam energy. But we also want to know if we need to change any other things?
Like the pdf set, I see now they recommend to use PDF3.1.
Do we need to change that?
Looking forward to your reply.

Bests!
Chu Wang

Tag HIG MC contact
@attikis @hftsoi

### CODE REVIEW

**Comment by menglu21** [comment]
Hi @chuwang1 I have some questions on some parameters and sent an email to sherpa team, let's wait for a bit for the reply.

**Comment by chuwang1** [comment]
> Hi @chuwang1 I have some questions on some parameters and sent an email to sherpa team, let's wait for a bit for the reply.
Hi @menglu21 
Thank you very much!
That's very helpful!
Chu Wang

**Comment by menglu21** [comment]
card look fine to me. @Saptaparna @GurpreetSinghChahal please have a look

**Comment by menglu21** [comment]
> > Hi @chuwang1 I have some questions on some parameters and sent an email to sherpa team, let's wait for a bit for the reply.
> > Hi @menglu21
> > Thank you very much!
> > That's very helpful!
> > Chu Wang

is your email address "chu.wang@cern.ch", I can forward you some suggestion from sherpa author.

**Pull request merged**
