### PR TITLE
Added variations for tchannel 5 TeV

### PR DESCRIPTION
**Pull request by Cvico**
Hi,

This PR is to included hdamp variations of the tchannel process at 5 TeV.
I took the nominal card and changed the hdamp value.

Best,
Carlos Vico

### CODE REVIEW

**Comment by Cvico** [comment]
Small remark: I've changed the names of the files so it's more clear which variations are performed and I've also fixed a typo in one of the cards.

**Comment by menglu21** [comment]
Hi @Cvico could you please change "13TeV" to "5TeV" or simply remove it from the name of the subdirectory

**Comment by lviliani** [comment]
Hello, can we close this PR or is it still relevant?

**Comment by bbilin** [comment]
I am closing the PR, since its long pending. If it is needed please reopen.

**Pull request closed without merging**
