### PR TITLE
second try to change name

### PR DESCRIPTION
**Pull request by ferdos**
change name of powheg DYtoEE input

### CODE REVIEW

**Comment by perrozzi** [comment]
I don't see the need of this PR after https://github.com/cms-sw/genproductions/pull/1348
Am I missing something?

**Comment by ferdos** [comment]
I did it just to change name of PDF in input name, 
Is there better way to do it ? I don't know that .

**Comment by perrozzi** [comment]
ok I see, there was still the 30 file

**Comment by ferdos** [comment]
in my remote directory under "powInput_CorrName" tag, I don't see any more the 30 file. maybe  you see it  because 1348 was merged before.

**Comment by perrozzi** [comment]
yes, the 30 is deleted now (if you want it, please upload it in the "pre2017" folder

**Pull request merged**
