### PR TITLE
Included extramodels.dat, updated proc_card.dat after changing the mo…

### PR DESCRIPTION
**Pull request by smshaheen**
Included extramodels.dat, updated proc_card.dat after changing the model name, updated the syntax of customizecards.dat bringing to a working condition

### CODE REVIEW

**Comment by smshaheen** [comment]
Dear Josh,
                         Any follow up on the commit after the latest updates?


Cheers,
Sarmad Masood Shaheen

**Comment by bendavid** [comment]
@covarell @govoni 
this looks fine to me (and follows from a discussion with Sarmad about the remaining issues with this one)

**Comment by smshaheen** [comment]
Dear Josh,
                                If everything seems fine, then is it possible to merge?

**Comment by bendavid** [comment]
I'm not in charge of this anymore, so up to @govoni and @covarell

**Comment by smshaheen** [comment]
Dear Josh,
                              Thanks for your kind replies and suggestions. Hope @govoni and @covarell  would take actions accordingly.

**Pull request merged**
