### PR TITLE
Cards from Varun

### PR DESCRIPTION
**Pull request by dnash86**
Pythia config cards for Photon+Jet samples binned in pT from Varun Sharma

### CODE REVIEW

**Comment by bendavid** [comment]
Why is this needed given that we already have the HT-binned madgraph samples?

**Comment by dnash86** [comment]
Not sure actually, I had thought the requester was aware of the HT-binned ones but upon double checking an email thread that may not be the case.  Checking now.

**Comment by dnash86** [comment]
Okay, they are aware of it.  They use the single photon dataset for their analysis, with single photon trigger thresholds of 165, 175, 250, and 300 GeV.  The HT binned samples have a highest bin of HT=600-inf, I believe, so they do not have sufficient statistics at higher pT.

The analyzers point out another thing I was not aware of: The GJets sample does not have all prompt photon production modes on (only numbers 201,202, and 203).  For these, PromptPhoton is set to "all", which apparently includes 201-205.

**Comment by bendavid** [comment]
That is intentional, since 204 and 205 are double photon production, which are covered by other samples.  We do NOT want to include this in the gamma+jet samples, since this makes their use by other analysis groups much more complicated.

And ok, if the only reason the madgraph samples are not good is because they don't go high enough, why not just request additional madgraph HT bins?

**Comment by dnash86** [comment]
I'll link the requesters to this thread so they can explain further.

In general it seems that these samples are fairly standard and used by a few groups inside EXO.  Weren't there pT binned samples back in 2012, or not?

**Comment by bendavid** [comment]
Yes, there were pt binned pythia6 samples in Run1.  

In principle they don't add anything on top of the madgraph samples though aside from different kinematic binning, and the madgraph samples should be preferred.

So if it's just a matter of statistics it would be better to extend/add bins for the madgraph.

**Comment by govoni** [comment]
Any news on this? If not, I will close it tomorrow.

**Comment by dnash86** [comment]
@govoni Sorry I left this issue dangling.  Yes, it seems we will likely be going another route with this issue (not using pt-binned samples).  I'll close the request.

**Pull request closed without merging**
