### PR TITLE
Data cards and grid packs for monoZprime pencil jet analysis

### PR DESCRIPTION
**Pull request by varuns23**
- Request for 2016, 2017 and 2018 signal samples.
- Urgent request for 2016 and 2017

### CODE REVIEW

**Comment by qliphy** [comment]
Gridpacks are not supposed to be uploaded here.  

Please remove lines as below:
https://github.com/cms-sw/genproductions/blob/1562da9c129a0765929a5257f43deef0a38d77ee/python/ThirteenTeV/monoZprime_DMEFT2ZpNewV2/Vector/run_card.dat#L269-L281

And you have set
         T = cut_decays 
which will cut on e.g. Zp> u u~,  please make sure that is what you want.

**Comment by varuns23** [comment]
- Regarding gridpacks, do you want to me to remove them from here or make a new PR?

- I will remove the lines suggested.

- We would like to have this; 
     T = cut_decays; the reason for having this is that we are applying, "0.0	=  drjj     ! min distance between jets" and want this to propogate to Zp > u u~

**Comment by qliphy** [comment]
>Regarding gridpacks, do you want to me to remove them from here or make a new PR?

You can remove them from here.

>T = cut_decays; the reason for having this is that we are applying, "0.0 = drjj ! min distance between >jets" and want this to propogate to Zp > u u~

0.0 = drjj is essentially no cut on drjj.  
Instead, if you set T = cut_decays,  "20 = ptj" will be applied on u u~

**Comment by varuns23** [comment]
I am having issues deleting the grid packs from here. 

I will make a new PR and let you know. After that may be you can delete this PR. 

Thanks!

**Comment by varuns23** [comment]
New PR made with #1967.

Closing this PR

**Pull request closed without merging**
