### PR TITLE
Add 2HDMa model cards for 2017 bbDM 

### PR DESCRIPTION
**Pull request by tiwariPC**
Dear All,
Please review the datacards which I have added here:
https://github.com/tiwariPC/genproductions/tree/master/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/bbDM_2HDMa
Thanks,
Praveen

### CODE REVIEW

**Comment by qliphy** [comment]
Please change to PYTHIA8 in this line:
https://github.com/cms-sw/genproductions/pull/1840/files#diff-72a6642086f435772ea3d94083353528R73

And please check more https://twiki.cern.ch/twiki/bin/view/CMS/Moriond18MC
for example, the PDF setting should follow recommendations.

Moreover, I saw you have duplicated files, are you also uploading a script to produce cards for other benchmark points?  If no, please clean the duplication.

**Comment by qliphy** [comment]
There is no photon in your process, so I think you should not switch on the photon isolation cuts: https://github.com/tiwariPC/genproductions/blob/ba41c3d2ad0c27bfbf19782e9cddc8334185c77f/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/bbDM_2HDMa/Template/run_card.dat#L152-L157

Here please change HERWIG6 to PYTHIA8:
https://github.com/tiwariPC/genproductions/blob/ba41c3d2ad0c27bfbf19782e9cddc8334185c77f/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/bbDM_2HDMa/bbDM_2HDMa_MH3_600_MH4_100_Mchi_10/bbDM_2HDMa_MH3_600_MH4_100_Mchi_10_run_card.dat#L73

**Comment by tiwariPC** [comment]
For photon isolation cuts (https://github.com/tiwariPC/genproductions/blob/ba41c3d2ad0c27bfbf19782e9cddc8334185c77f/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/bbDM_2HDMa/Template/run_card.dat#L152-L157): 
This was default settings created by madgraph. 
Can you please let me know how can I switch off photon isolation?
Should I put like this:
  0.0  = ptgmin    ! Min photon transverse momentum
 -1.0  = etagamma  ! Max photon abs(pseudo-rap)
  0.0  = R0gamma   ! Radius of isolation code
  1.0  = xn        ! n parameter of eq.(3.4) in hep-ph/9801442
  1.0  = epsgamma  ! epsilon_gamma parameter of eq.(3.4) in hep-ph/9801442
 False  = isoEM  ! isolate photons from EM energy (photons and leptons)

**Comment by qliphy** [comment]
Yes, please  set as
 0.0 = ptgmin ! Min photon transverse momentum
and this will disable the photon isolation cuts.

**Comment by tiwariPC** [comment]
Hi,
Only 0.0 = ptgmin ! Min photon transverse momentum suffices?

Should I keep the following lines to their default values?
-1.0 = etagamma ! Max photon abs(pseudo-rap)
0.0 = R0gamma ! Radius of isolation code
1.0 = xn ! n parameter of eq.(3.4) in hep-ph/9801442
1.0 = epsgamma ! epsilon_gamma parameter of eq.(3.4) in hep-ph/9801442
False = isoEM ! isolate photons from EM energy (photons and leptons)

**Comment by qliphy** [comment]
Yes, just  set 0.0=ptgmin

If you check standalone madgraph cards, you can find the following:

#***********************************************************************
# Photon-isolation cuts, according to hep-ph/9801442                   *
# When ptgmin=0, all the other parameters are ignored                  *
# When ptgmin>0, pta and draj are not going to be used                 *

**Pull request merged**
