### PR TITLE
Switch of directories

### PR DESCRIPTION
**Pull request by amagitte**
Hi all,

I changed the directory of H-> ZZ -> 2l2nu Powheg input files from: genproductions/bin/Powheg/production --> genproductions/bin/Powheg/production/V2/13TeV/Higgs

These two directories:
1- H_ZZ_2l2nu_NoJHUGen_NNPDF30_13TeV
2- H_ZZ_2l2nu_withJHUGen_NNPDF30_13TeV

has to be removed from their current position (genproductions/bin/Powheg/production)..

Many thanks!
Alessio

### CODE REVIEW

**Comment by amagitte** [comment]
Hi all,

I changed the decay of the Z from (11,13,12,14,16) to (11,13,15,12,14,16).
The filter is changed in the same way

Alessio

**Comment by syuvivida** [comment]
The cards look fine to me. @covarell @bendavid can you merge the cards? Thanks!

**Comment by amagitte** [comment]
Hi all,

I changed the hfact value in Powheg input file after the higgs MC meeting of this morning, for ggH.

Cheers,
Alessio

**Comment by syuvivida** [comment]
The cards look OK to me.

**Comment by amagitte** [comment]
Hi all,

@cavarell and @bendavid, might you kindly merge my cards?

Cheers,
Alessio

**Comment by amagitte** [comment]
Thanks!

Alessio

**Pull request merged**
