### PR TITLE
Mg26x

### PR DESCRIPTION
**Pull request by whahmad**
**Add  Z_LFV (Lepton Flovor Violation in Z decays)  cards for 2017.**

Dear Experts, 
please check it if there are comments or corrections please let me know.

Regards,
Wael Haj Ahmad

### CODE REVIEW

**Comment by whahmad** [comment]
**Add  Z_LFV (Lepton Flovor Violation in Z decays)  cards for 2017.**

Dear Experts, 
please check it if there are comments or corrections please let me know.

Regards,
Wael Haj Ahmad

**Comment by agrohsje** [comment]
Looks good. Suggest to remove the default lines in proc card, i.e. everything before you import your model. 
You might consider including parton shower weights in the fragment. But that can be done for the mc request.

**Comment by whahmad** [comment]
The default lines in proc card are removed.

**Comment by agrohsje** [comment]
I would also suggest to remove the header as the version info of 2.5 is misleading. 
Why do you start from mg26x branch? What are the samples for?

**Comment by whahmad** [comment]
I removed the header.... I am starting from mg26x branch becuase i have produced the gridpack for Lepton Flavor Violation in Z decays using mg260.

**Comment by whahmad** [comment]
Dear experts, could you please move my cards folder to be in this path:
"genproductions/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/"
I have locate it outside the MadGraph5_aMCatNLO cards by mistake.

Regards.

**Comment by qliphy** [comment]
@whahmad   We have reverted this PR so you can make a new one to put your cards in the right folder.

**Pull request merged**
