### PR TITLE
powheg cards for WW and ttb processes

### PR DESCRIPTION
**Pull request by dnash86**

### CODE REVIEW

**Comment by covarell** [comment]
@syuvivida was it verified for these two processes that the fraction of negative weights is negligible, thus "withnegweights 0" is safe?

**Comment by syuvivida** [comment]
No, these two processes have not been checked yet. We checked inclusive W/Z/VBF_H, VBF_Z_Z, VBF_HJJJ processes so far. In the end, we recommend users to check this for their specific production.

**Comment by dnash86** [comment]
@syuvivida do you have a suggestion for a quick method for checking this?

**Comment by covarell** [comment]
Produce some o(10^4) events with withnegweights 1, check how many have negative weights (can be checked directly from the XWGTUP entry of the LHE file)

**Comment by dnash86** [comment]
Okay, thanks.  I will do that and report back to this thread.

**Comment by dnash86** [comment]
I sampled one for each process:
For ww->ee:  
negative weight fraction:   2.1048759642054281E-003

For ttbar->mumu:
negative weight fraction:   2.5414618957040609E-003

So both seem negligible.

**Pull request merged**
