### PR TITLE
Changes for additional CMS Connect and condor compatibility

### PR DESCRIPTION
**Pull request by khurtado**
These are bug fixes and features added based on @lorusso7 run tests.

Bug fixes:
-  Madgraph uses `getenv` in condor to copy the cvmfs environment to the worker node. Tier Sites using Singularity containers don't allow this for `LD_LIBRARY_PATH` for linux security reasons. Patch madgraph job templates to append `SRT_LD_LIBRARY_PATH_SCRAMRT` when this is set and is not already part of `LD_LIBRARY_PATH` to workaround this.
- Fix location of `condor_chirp` for singularity-contained jobs.
- Do not execute `git status` from the gridpack_generation script when running from CMS Connect, but do it on its own script instead. Otherwise, `git status` would be run on the worker node where there is no genproductions git repository.
- Fix dashboard reporting.

Features:
- Replace `condor_q` command line subprocesses with the condor python API schedd query. Make sure the python binding directory is defined in the PYTHONPATH (otherwise bare python can still detect it from the system libraries, but somehow the python binaries from CVMFS don't after executing scram/cmsenv)
- Add functions to Madgraph to automatically release hold codes (so that they run again somewhere else) that are known to be transient (e.g: Hitting a Worker node with CVMFS problems, transient networking issues while transferring files,  etc). This is only triggered when the following environment variables exist: `CONDOR_RELEASE_HOLDCODES, CONDOR_RELEASE_HOLDCODES_SHADOW_LIM`. The first variable defines the list of known problematic hold codes, the second imposes a limit to the number of shadows (default 10) for automatic release of a job (default values present in the submit_cmsconnect script). 
- Add a proxy watcher. This is a cron job that checks the user's proxy remaining lifetime and sends an e-mail reminders to renew the proxy in the login node.
- Progressive Walltimes: This  should fix issue #1212. For this to work, `CONDOR_SET_MAXWALLTIMES` needs to exist in the environment (default values present in the submit_cmsconnect script).

### CODE REVIEW

**Comment by perrozzi** [comment]
great, thanks a lot!
do you suggest merging and then testing, or hold and wait for further feedback?

**Comment by khurtado** [comment]
@perrozzi : Well, I tested these changes on CMS Connect and went just fine. The only components that could give any issues in other environments (like `submit_condor` on condor 8.6.x with its corresponding python bindings) are all in the madgraph patches directory, which are isolated changes and can be easily removed if needed without modifying the code, so I think just merging and then testing is okay.

**Comment by perrozzi** [comment]
what is the status of cms connect and mg5_amc 2.5.x ?
would you mind porting this also to https://github.com/cms-sw/genproductions/tree/mg25x ?

**Comment by khurtado** [comment]
Will do.

**Comment by kdlong** [comment]
Thanks @khurtado, this is really nice! I think we should also consider talking to the MadGraph authors about whether they would be interested in merging this into their master code.

How do you envision enforcing the requirement that the python bindings should be available at the site? For lxplus/Wisconsin I see it in /usr/lib64/python2.6/site-packages/. It doesn't appear to be an issue to import it and use in Pythia 2.7, however.

**Pull request merged**
