### PR TITLE
Z'-> ttbar signal samples for Fall17 production  

### PR DESCRIPTION
**Pull request by karavdin**
MG 2.4 cards for Z' models for Fall17 signal samples production

### CODE REVIEW

**Comment by karavdin** [comment]
The same as [1], but for 2.4 MG branch. 
[1] https://github.com/cms-sw/genproductions/pull/1903

**Comment by qliphy** [comment]
https://github.com/cms-sw/genproductions/blob/8ea270df297fe0fbdfc3ee05255b8909610047e6/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/Top_Philic/TopPhilicZprimeToTTbar_M500/TopPhilicZprimeToTTbar_M500_run_card.dat#L88

> 15000 = bwcutoff ! (M+/-bwcutoff*Gamma)

We don't recommend to set large bwcutoff, please change it to 15

**Comment by qliphy** [comment]
https://github.com/cms-sw/genproductions/blob/8ea270df297fe0fbdfc3ee05255b8909610047e6/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/Top_Philic/TopPhilicZprimeToTTbar_M500/TopPhilicZprimeToTTbar_M500_extramodels.dat#L1

Probably you need to add an empty line similar as for the following card

https://github.com/cms-sw/genproductions/blob/8ea270df297fe0fbdfc3ee05255b8909610047e6/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/ZPrimeToTTJets_012j_LO_MLM/ZPrimeToTTJets_M500GeV_W5GeV/ZPrimeToTTJets_M500GeV_W5GeV_extramodels.dat

**Comment by karavdin** [comment]
> [genproductions/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/Top_Philic/TopPhilicZprimeToTTbar_M500/TopPhilicZprimeToTTbar_M500_extramodels.dat](https://github.com/cms-sw/genproductions/blob/8ea270df297fe0fbdfc3ee05255b8909610047e6/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/Top_Philic/TopPhilicZprimeToTTbar_M500/TopPhilicZprimeToTTbar_M500_extramodels.dat#L1)
> 
> Line 1 in [8ea270d](/cms-sw/genproductions/commit/8ea270df297fe0fbdfc3ee05255b8909610047e6)
>  Top_Philic_V1_NLO.zip 
> 
> Probably you need to add an empty line similar as for the following card
> 
> https://github.com/cms-sw/genproductions/blob/8ea270df297fe0fbdfc3ee05255b8909610047e6/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/ZPrimeToTTJets_012j_LO_MLM/ZPrimeToTTJets_M500GeV_W5GeV/ZPrimeToTTJets_M500GeV_W5GeV_extramodels.dat

No, it works without empty line.

**Comment by qliphy** [comment]
Ok, please then change bwcutoff to 15 in the run_card files.

**Comment by karavdin** [comment]
> [genproductions/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/Top_Philic/TopPhilicZprimeToTTbar_M500/TopPhilicZprimeToTTbar_M500_run_card.dat](https://github.com/cms-sw/genproductions/blob/8ea270df297fe0fbdfc3ee05255b8909610047e6/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/Top_Philic/TopPhilicZprimeToTTbar_M500/TopPhilicZprimeToTTbar_M500_run_card.dat#L88)
> 
> Line 88 in [8ea270d](/cms-sw/genproductions/commit/8ea270df297fe0fbdfc3ee05255b8909610047e6)
>  15000  = bwcutoff      ! (M+/-bwcutoff*Gamma) 
> 
> > 15000 = bwcutoff ! (M+/-bwcutoff*Gamma)
> 
> We don't recommend to set large bwcutoff, please change it to 15

Gridpack production fails if the parameter changed to 15.

**Comment by qliphy** [comment]
I checked the log, it seems problem is not related to bwcutoff.

But anyway, as for TopPhilicZprimeToTTbar,   bwcutoff indeed is not used (as your process doesn't involve any decay), so should be ok.

For ZPrimeToTTJets_M500GeV, please change bwcutoff to 15.

**Comment by karavdin** [comment]
In ZPrimeToTTJets it's already 15, please see
https://github.com/cms-sw/genproductions/blob/8ea270df297fe0fbdfc3ee05255b8909610047e6/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/ZPrimeToTTJets_012j_LO_MLM/ZPrimeToTTJets_M500GeV_W5GeV/ZPrimeToTTJets_M500GeV_W5GeV_run_card.dat#L89

**Pull request merged**
