### PR TITLE
Adding AJJ_EWK_SM_5f_NLO cards

### PR DESCRIPTION
**Pull request by UAEDF-tomc**
Adding the cards for electroweak (VBF) photon+2j production at NLO

### CODE REVIEW

**Comment by qliphy** [comment]
Please change to 
               True	= store_rwgt_info 
               PYTHIA8	= parton_shower 

And  are you sure you want a large Radius cut?
                0.4	= r0gamma ! Radius of isolation code

Also note if it is for 2017/2018, the default PDF should be NNLO (303600), to match with the Pythia8 Tune CP5:
                292000 = lhaid

**Comment by qliphy** [comment]
And why do you need a  FKS_params.dat?

**Comment by UAEDF-tomc** [comment]
> And why do you need a FKS_params.dat?
The FKS_params.dat is modified to turn off the #IRPoleCheckThreshold (set to -1)

**Comment by UAEDF-tomc** [comment]
> Also note if it is for 2017/2018, the default PDF should be NNLO (303600), to match with the Pythia8 Tune CP5:
> 292000 = lhaid

I assumed that we could still use
 _$DEFAULT_PDF_SETS = lhaid
 $DEFAULT_PDF_MEMBERS  = reweight_PDF_
as we did before. Since when did this recommendation change? Then we should update the twiki: https://twiki.cern.ch/twiki/bin/viewauth/CMS/QuickGuideMadGraph5aMCatNLO#PDF_Choice_for_2017_production

**Comment by qliphy** [comment]
Yes, you can still use for 2017/2018 requests
    $DEFAULT_PDF_SETS = lhaid 
    $DEFAULT_PDF_MEMBERS = reweight_PDF
This will set NNLO PDF for you.


>The FKS_params.dat is modified to turn off the #IRPoleCheckThreshold (set to -1)

Can you give some more explanation or ref link?  And have you got green light from the authors?

**Comment by UAEDF-tomc** [comment]
> > The FKS_params.dat is modified to turn off the #IRPoleCheckThreshold (set to -1)
> 
> Can you give some more explanation or ref link? And have you got green light from the authors?
I don't have the explanation myself, though it should have been discussed privately between @azzurrip, @pfs and aMC@NLO authors (Marco Zaro)

**Comment by UAEDF-tomc** [comment]
> And are you sure you want a large Radius cut?
> 0.4 = r0gamma ! Radius of isolation code

Yes, there was also a draj=0.4 cut at LO, so we want to stay with this for NLO too

**Comment by qliphy** [comment]
Thanks for the info.   I have one last question on  0.4= r0gamma

This cut affect the additional jet emission in NLO.   For jet close to photon within the distance of r0gamma,  the smooth isolation will be applied.  Probably, a smaller value of r0gamma may be better, as the additional jet will be more included inclusively.  

In other similar process, 0.05 was used, e.g.:  
https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/cards/production/pre2017/13TeV/ZATo2LA01j_5f_NLO_FXFX/ZATo2LA01j_5f_NLO_FXFX_run_card.dat

**Comment by UAEDF-tomc** [comment]
@azzurrip Could you give your opinion on this r0gamma cut?

> Thanks for the info. I have one last question on 0.4= r0gamma
> 
> This cut affect the additional jet emission in NLO. For jet close to photon within the distance of r0gamma, the smooth isolation will be applied. Probably, a smaller value of r0gamma may be better, as the additional jet will be more included inclusively.
> 
> In other similar process, 0.05 was used, e.g.:
> https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/cards/production/pre2017/13TeV/ZATo2LA01j_5f_NLO_FXFX/ZATo2LA01j_5f_NLO_FXFX_run_card.dat

**Comment by azzurrip** [comment]
I see what you mean.  
Ok yes let's have a 0.05 cut so to cover better all NLO effects.

**Comment by UAEDF-tomc** [comment]
Ok, I have updated this in the cards.
@qliphy  I have addressed all comments of your review now

**Pull request merged**
