### PR TITLE
add low mass DY

### PR DESCRIPTION
**Pull request by gitytakahas**
low mass DY for 1,2,3,4 jets

### CODE REVIEW

**Comment by bendavid** [comment]
NLO is only possible currently with 0,1,2 jets NLO (which means up to 3 jets at LO)

**Comment by bendavid** [comment]
Is this still needed?  There is already a 10<mll<50 GeV NLO sample with 0,1,2 jets and this is the most that can be done for now. (gives also the 3rd jet at LO accuracy as usual)

If you really need the 4th jet, then this needs to be done as LO as for the higher mass samples.

**Comment by gitytakahas** [comment]
Hi Josh,

Thanks for the email - is the 2j inclusive or 2j exclusive ?
If it is 2j inclusive, we are fine with this - it is simply the matter of
statistics then.

Thanks,
Yuta

2015-10-11 13:25 GMT+02:00 Josh Bendavid <notifications@github.com>:

> Is this still needed? There is already a 10<mll<50 GeV NLO sample with
> 0,1,2 jets and this is the most that can be done for now. (gives also the
> 3rd jet at LO accuracy as usual)
>
> If you really need the 4th jet, then this needs to be done as LO as for
> the higher mass samples.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/genproductions/pull/636#issuecomment-147184383>
> .
>



-- 
Yuta Takahashi
LHC - CMS experiment,
CERN (European Organization for Nuclear Research)

**Comment by bendavid** [comment]
Yes the existing sample is inclusive.

**Comment by gitytakahas** [comment]
Thank you Josh for the prompt reply !
May I ask you where I can find the request (or stats.) for each of them ?
(If the stats. are not sufficient for us, can I clone the request if
possible ?)

2015-10-11 17:37 GMT+02:00 Josh Bendavid <notifications@github.com>:

> Yes the existing sample is inclusive.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/genproductions/pull/636#issuecomment-147211866>
> .
>



-- 
Yuta Takahashi
LHC - CMS experiment,
CERN (European Organization for Nuclear Research)

**Comment by bendavid** [comment]
These samples will anyways be extended in the RunIISummer15GS campaign + 76x digi-reco.
(But please let us know how much you would need)

The existing RunIIWinter15GS request is this one. (careful, the fraction of negative weights is something like 0.15)
If you still urgently need more stats in 74x then you can request an extension in this campaign.
https://cms-pdmv.cern.ch/mcm/requests?prepid=SMP-RunIIWinter15GS-00005&page=0&shown=127

**Comment by gitytakahas** [comment]
Thank you Josh,

I will ask relevant analyzers and get back to you !

Best,
Yuta

2015-10-11 17:46 GMT+02:00 Josh Bendavid <notifications@github.com>:

> These samples will anyways be extended in the RunIISummer15GS campaign +
> 76x digi-reco.
> (But please let us know how much you would need)
>
> The existing RunIIWinter15GS request is this one. (careful, the fraction
> of negative weights is something like 0.15)
> If you still urgently need more stats in 74x then you can request an
> extension in this campaign.
>
> https://cms-pdmv.cern.ch/mcm/requests?prepid=SMP-RunIIWinter15GS-00005&page=0&shown=127
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/genproductions/pull/636#issuecomment-147212314>
> .
>



-- 
Yuta Takahashi
LHC - CMS experiment,
CERN (European Organization for Nuclear Research)

**Comment by bendavid** [comment]
Will close this in any case.  Please follow up by email.

**Pull request closed without merging**
