### PR TITLE
switched to Powheg rev 3511 

### PR DESCRIPTION
**Pull request by agrohsje**
supposed to speed up generation of ggHH
physics should be unaffected

### CODE REVIEW

**Comment by agrohsje** [comment]
I found a bug in the ggHH Makefile that the authors released. I will fix it. Than merge the PR yet!

**Comment by agrohsje** [comment]
The PR should be ready to go. Please merge! Xanda will produce a new gridpack. We saw indeed significant runtime performance. Pinging the authors we also got additional info on settings so that replacing the executable is not enough and new presampling is needed.

**Comment by yuanchao** [comment]
A quick test on CMSSW_9_3_0 with test_source_compilation.sh, several channels including dijet, directphoton, disquark, weakinos... failed to be compiled. Please see /afs/cern.ch/user/y/yuanchao/scratch/CMSSW_9_3_0/src/source/LSFJOB_160407743/STDOUT.

**Comment by agrohsje** [comment]
Sorry for not checking. That was my mistake. I should have done so. I was not aware these Makefiles were touched. 
I don't have permissions to check your stdout. . 
Did all of them compile before? Do you know in which release it was tested? We can compare the Makefiles to that.

**Comment by agrohsje** [comment]
The same problems were already discussed here: 
https://github.com/cms-sw/genproductions/issues/1307
Did anybody solve them?

**Comment by perrozzi** [comment]
> Did anybody solve them?
not that I know.

What is the status as of now? Which is the last svn rev? and which processes don't compile?

**Pull request merged**
