### PR TITLE
Adding monotop production cards

### PR DESCRIPTION
**Pull request by MichaelButtignol**
This is going to replace the previous request #379

### CODE REVIEW

**Comment by bendavid** [comment]
Are you sure you want cut_decays=T here?  (This means jet cuts will apply to the hadronic decays)

Also there is a merge conflict in gridpack_generation.sh which needs to be fixed.

**Comment by MichaelButtignol** [comment]
Hi Josh,

You're right (again). We will keep the cut_decays to TRUE but change the 
value to 10 or 15 GeV for pt(jets).

Concerning the conflict, it will be fixed at the next iteration.

Thanks,
Michael

**Comment by bendavid** [comment]
I would really suggest to just set cut_decays to False!
Then we are consistent with other samples, and completely safe, at the expense of a modest cost in statistics for what is probably anyways a small sample.  Feel free to increase the size of the request to compensate if you like.

**Comment by MichaelButtignol** [comment]
OK, thank you fir the advice, we will do this then.

And OK I'll see this.

Thanks,
Michael

**Pull request closed without merging**
