### PR TITLE
Modifications to support the ggHH process (mtdep=3)

### PR DESCRIPTION
**Pull request by covarell**
Also implementing two suggestions:
- Accepting https://github.com/cms-sw/genproductions/pull/2146 and superceding it  @AndrewLevin 
- Setting runInBatchDir as the default for parallel stages, as it is completely tested now @intrepid42

### CODE REVIEW

**Comment by efeyazgan** [comment]
@covarell  this is ready to be merged, right? thanks.

**Comment by covarell** [comment]
Well, yes, as usual I would first let @yuanchao and other people in the thread comment (especially because I merged together several updates)

**Comment by yuanchao** [comment]
@covarell  Just had a quick view. Could you clarify the followings:
* powhegboxV2_rev3633_date20190225_testggHH.tar.gz <--- this is only for test?
* is 10 events good enough (not degrading the grid)
* linking obj-gfortran is not needed as directly copied?

**Comment by covarell** [comment]
The tarball is indeed a "test" in the sense that it contains code not publicly available yet in the POWHEG-BOX. It was provided by theorists to CMS for testing it.

I put a random number for stage 2 and 3 because I think this is not used. Is it used? If so, we need to increase it.

I do not know about obj-gfortran, this is not a change I did.

**Comment by covarell** [comment]
In the last commit I moved to the default nEvents (2000)

About obj-gfortran, bb4l and the like are removed from powhegjhugen run card, since these processes do not support JHUGen

**Comment by yuanchao** [comment]
Ok. Then I'm sure if it's a good idea to put the test package in the official script.
As to the rest, it's fine with me. Thank you!

**Comment by covarell** [comment]
Done! I think this can be merged now.

**Pull request merged**
