### PR TITLE
added cards for tGG+jets process at LO in aMC@NLO

### PR DESCRIPTION
**Pull request by mmachet**
Hi @bendavid,
I started to do the tGG+jets cards with 4fs at LO as you suggested.
Basically I just modified the run card taking this example:
https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/cards/examples/wplustest_4f_LO/wplustest_4f_LO_run_card.dat

Do I have to change something else?

### CODE REVIEW

**Comment by covarell** [comment]
To me they look OK

**Comment by covarell** [comment]
Too fast :-)

Do they need to be LO or NLO? 
Title says LO, proc_card is for NLO, run_card seems for LO

**Comment by mmachet** [comment]
They need to be at LO, because at NLO we have problems to do the gridpack.
What I have to change in the proc_card?

2015-11-16 18:44 GMT+01:00 Roberto Covarelli <notifications@github.com>:

**Comment by bendavid** [comment]
Hi Martina,
Sorry I thought the NLO gridpack did eventually finish correctly?

**Comment by mmachet** [comment]
Hi Josh,

the gridpack that finished correctly is the ttGG+0jets, but the tGG+jets
still has problems, so you suggested to do the cards at LO.

2015-11-23 8:50 GMT+01:00 Josh Bendavid <notifications@github.com>:

**Comment by covarell** [comment]
For LO you have to:
- remove "loop" from the imported model (loop_sm-ckm -> sm-ckm)
- remove [QCD] from the process line(s)

**Comment by mmachet** [comment]
ok I will do these changes,

thanks!

2015-11-23 13:41 GMT+01:00 Roberto Covarelli <notifications@github.com>:

**Comment by mmachet** [comment]
pull request updated

2015-11-23 15:23 GMT+01:00 Martina Machet <martina.machet@cern.ch>:

**Comment by mmachet** [comment]
Hi,

are the cards ok now, and can be approved, or I have to change something
else?

Thanks

2015-11-23 15:51 GMT+01:00 Martina Machet <martina.machet@cern.ch>:

**Pull request merged**
