### PR TITLE
Madgraph cards for H(125)-> 2h_D -> 4Z_D -> 8 ell

### PR DESCRIPTION
**Pull request by cecilecaillol**
Commit for both 2016 and 2017 cards

### CODE REVIEW

**Comment by efeyazgan** [comment]
Hi, could you please keep only representative cards for one parameter sets and if possible a script to produce the other cards. thanks.

**Comment by cecilecaillol** [comment]
Hi, I have kept only one mass point, all the rest is deleted now.

**Comment by efeyazgan** [comment]
Thanks. Could you also get rid of commented/unusued lines such as 
#set group_subprocesses Auto
#set ignore_six_quark_processes False
#set loop_optimized_output True
#set loop_color_flows False
#set gauge unitary
#set complex_mass_scheme False
#set max_npoint_for_channel 0
thanks.

**Comment by cecilecaillol** [comment]
Done

**Pull request merged**
