### PR TITLE
Change the variable name for mass cut

### PR DESCRIPTION
**Pull request by KyeongPil-Lee**

### CODE REVIEW

**Comment by bendavid** [comment]
uh, actually I'm not sure either of these variables exist for NLO running.  Have you checked?  You may need to implement the upper mass cut "by hand" using the cuts.f mechanism.

**Comment by KyeongPil-Lee** [comment]
Oh, I am not familar with the madgraph yet, so maybe there are some mistakes...After your comment, I checked the madgraph files, and I saw that 'mmllmax' is defined in LO directory, not NLO directory. I will define the cut by hand and use them when I generate the gridpack. Thank you!

**Comment by bendavid** [comment]
(You'll probably still need to remove the existing parameter from the card.  Anyways, suggest to do tests first with only the 0 jet process, since this should be much faster)

**Comment by KyeongPil-Lee** [comment]
Hmm, Actually, I want to generate exactly same samples with 'dyellell012j_5f_NLO_FXFX' case except for the mass range, because I will combine them later. even in this case, are there some parameters that should be changed? existing parameters are same with the 'dyellell012j_5f_NLO_FXFX' card's parameter.

**Comment by bendavid** [comment]
I mean you will have to remove the "mllmax_sf" parameter which doesn't exist for NLO.  (This parameter was not needed for the 50_infinity sample of course)

**Comment by KyeongPil-Lee** [comment]
I'm not sure I understand properly. If I define 'mllmax_sf' variable in cut.f, can I use 'mllmax_sf' in the run card? then 'mllmax_sf' doesn't have to be removed. Is this right?

**Comment by bendavid** [comment]
No, I don't think that parameter exists, therefore it has to be removed, and the upper mass cut has to be implemented using cuts.f.

If instead you have tested it and the parameter works, then maybe it can be used (but I doubt it)

**Comment by KyeongPil-Lee** [comment]
Do you mean that I should give M<50 cut directly in the cut.f, instead of define 'mmllmax_sf' variable?
I'm sorry for bothering you.

**Comment by bendavid** [comment]
Yes, I think this is the only way to do it.

**Comment by KyeongPil-Lee** [comment]
Ok. then I will modify cut.f and test it. If it works well, I will give you the pull request to remove 'mmllmax_sf'. Thank you for your kind reply!

**Pull request closed without merging**
