### PR TITLE
Alpgen cards from Emrah

### PR DESCRIPTION
**Pull request by dnash86**
Cards from Emrah for Majorana Neutrino to EE, MuMu, EMu, MuE LHE files.

### CODE REVIEW

**Comment by bendavid** [comment]
Can I ask what pdf was used here?

**Comment by dnash86** [comment]
The pdf was: CTEQ6M.

**Comment by bendavid** [comment]
Ok, but that is an NLO pdf (and quite obsolete).  This also implies an inappropriate alpha_s value is used (~0.118 vs 0.130).  This is also inconsistent with most of the rest of the production.

Can alpgen be easily interfaced with lhapdf?  Do the analyzers care about doing this with pdfs consistent with the rest of the production?

**Comment by dnash86** [comment]
I definitely do not know about how easily alpgen can be interfaced with lhapdf.  I will refer the analyzers to your comment and see what they say.

**Comment by bendavid** [comment]
Even if it can't be interfaced to lhapdf, even CTEQ6L1 would make much more sense than CTEQ6M

**Comment by dnash86** [comment]
Just so you know, this question is not being ignored, the main analyzer I was in contact with said the group is discussing it.

**Comment by etiras** [comment]
We used NLO pdf for Run I analysis with good reason and now just to make sure again we asked Prof. Tao Han, who is a theorist at the University of Pittsburgh and an expert on Majorana Neutrinos, provided estimates for heavy neutrino production at the LHC. Here is our question and his answer:  

Q: 

For the new Run II analysis we have the choice of using 6TEQ6M or CTEQ6L1 pdf for our Leading Order heavy neutrino MC signal samples. Which one do you recommend? We used CTEQ6M before and we applied a kfactor of 1.34.
 
A: 
Although “theoretically”, the LO cross section should match the LO pdf, I strongly recommend you to still use the NLO pdf’s, namely CTEQ6M. I could tell you pros and cons, but you may not need to know these “theoretical arguments”.

So, we would like to continue with NLO pdf, CTEQ6M.

**Comment by dnash86** [comment]
@bendavid Is this answer satisfactory, or is a different pdf set required?  If it is satisfactory, we should be ready to move forward with the request.

**Comment by bendavid** [comment]
I would actually like to know what the arguments are.  We use LO pdfs for ~every single other LO sample in CMS.

**Comment by dnash86** [comment]
@bendavid The analyzers are preparing a comparison study to understand the theoretical differences are.  

In the meantime, would it be possible to do a "partial approval" and proceed with generation of only a few (5-6) MuMu channel points with the NLO pdf for them to start work on the analysis with them?  (With the provision that they may change to the LO pdf for the full production.)

**Comment by bendavid** [comment]
Can we produce samples with both pdf's for a few points rather?  Do we already have an answer as to whether alpgen can be easily interfaced with lhapdf?

**Comment by etiras** [comment]
After discussions with theorists and comparing cross sections, we decided to go with LO PDF, which is CTEQ6L1. We also checked with ATLAS, they are using CTEQ6L1 as well. 
Alpgen is not easily interfaced with lhapdf. We searched for it but couldn't find too much information about it. 
We have generated LHE files with CTEQ6L1, we'll send them soon. Thanks-

**Comment by dnash86** [comment]
@bendavid Just a note, there will be 4 mass points only for this cteq6m production:

MuMu, with M=50,100,500,1000.

I can put "cteq6m" in the dataset names to make it clear.  If that is okay, should I leave this PR for the entire set of cards for ease, or just the 4 that I will be entering corresponding entries in McM?

**Comment by bendavid** [comment]
Let's put just the cards we're going to use in production.

**Comment by dnash86** [comment]
Okay, I'll update remove all but those 4 files from this PR.

**Comment by dnash86** [comment]
I've reduced this PR to just the 4 masses needed, is it okay now?

**Pull request merged**
