### PR TITLE
enable auto_ptj_mjj to DYJets_HT_LO_MLM/DYJets_HT_mll50/DYJets_HT-incl

### PR DESCRIPTION
**Pull request by afanfani**
This change was required to be able to produce a gridpack.

### CODE REVIEW

**Comment by efeyazgan** [comment]
Are the cuts below intentional?
1d2  = etab    ! max rap for the b
 1d2  = etal    ! max rap for the charged leptons 
0.6 = etaonium ! max rap for the quarkonium states

**Comment by afanfani** [comment]
I've tried to be conservative and I didn't changed those cuts wrt to old cards copied with:
./copyOldCardsTo2017.sh DYJets_HT_LO_MLM/DYJets_HT_mll50/DYJets_HT-incl .

I've now checked from EGM-RunIISummer17wmLHEGS-00001 request the gridpack:
/cvmfs/cms.cern.ch/phys_generator/gridpacks/slc6_amd64_gcc481/13TeV/madgraph/V5_2.2.2/DYJets_HT_LO_MLM/DYJets_HT-incl/V1/DYJets_HT-incl_tarball.tar.xz
and therein the process/madevent/Cards/run_card.dat has those cuts. 
If this is meaninful or not I don't know.

**Comment by efeyazgan** [comment]
Could you please check with your group at least? In some previous cards, we may have missed it.

**Comment by perrozzi** [comment]
in principle those cuts look ok as 1d2 = 100 and I am not sure we are producing any quarkonium here :-)

**Comment by efeyazgan** [comment]
Yes, that was understood yesterday but I forgot to merge. Doing it now.

**Pull request merged**
