### PR TITLE
Z+jets divided per jet multiplicities 0j/1j/2j

### PR DESCRIPTION
**Pull request by wvieri**

### CODE REVIEW

**Comment by bendavid** [comment]
Don't you also need the run cards?

**Comment by wvieri** [comment]
@bendavid  I need just one run_card, right?

**Comment by bendavid** [comment]
It can be the same, but to actually make the gridpacks you need one for each gridpack with the proper name/location.

**Comment by wvieri** [comment]
added

**Comment by bendavid** [comment]
only see 2 run cards

**Comment by wvieri** [comment]
done

**Comment by covarell** [comment]
They seem correct to me now

**Comment by bendavid** [comment]
Yes, looks good.

Note that maxjets in the pythia configuration has to be set to "2" for all three of these samples.

**Pull request merged**
