### PR TITLE
spinmode onshell fixes

### PR DESCRIPTION
**Pull request by sihyunjeon**
Hi all,

The formats aren't correct I think... Could you guys take a look at this?
These are fixes that need to be applied to use spinmode onshell in madspin (mg26x)

And sorry for taking too long...

### CODE REVIEW

**Comment by perrozzi** [comment]
@kdlong @qliphy

**Comment by agrohsje** [comment]
did you try : 
git format-patch master --stdout > nameofpatch.patch

**Comment by perrozzi** [comment]
what shall we do with this?

**Comment by perrozzi** [comment]
any news on this?

**Comment by sihyunjeon** [comment]
@perrozzi  Hi I am really sorry for late reply. There are some more problems on using this "spinmode onshell" so I am still checking some things. I will at least provide these patches after checking they are properly applied this weekend.
@agrohsje  Thanks, I think I found out how to do it thanks to your help.

**Comment by kdlong** [comment]
Hi, the reason the tabs didn't work is because the tabs are wrong. I actually fixed them before the break and forgot to make a pull request. Will do this now.

**Comment by sihyunjeon** [comment]
Thanks, then I will close this in few hours

**Comment by kdlong** [comment]
Fixed in #1618

**Pull request closed without merging**
