### PR TITLE
fix defaultPDF

### PR DESCRIPTION
**Pull request by Hooooon12**
Hi, this is a temporary PR to fix default pdf setting in runGetSource function, from old one to the UL setting.

### CODE REVIEW

**Comment by agrohsje** [comment]
Dear @Hooooon12,
can you comment on why we want that change in master? The setting works in UL? 
Thanks, Alexander.

**Comment by Hooooon12** [comment]
Hi Alexander,
sorry for the late reply. This commit is to fix the disagreement in default PDF setting
between the main code: 
https://github.com/cms-sw/genproductions/blob/0635692e97dbea26a9ae344e9df53eb2d84c514e/bin/Powheg/run_pwg_condor.py#L757-L760
and a running function:
https://github.com/cms-sw/genproductions/blob/0635692e97dbea26a9ae344e9df53eb2d84c514e/bin/Powheg/run_pwg_condor.py#L281
in the master branch.

I saw the same issue in several branches, but I did PR for master now as I wasn't sure which branches need this change.
Does it seem ok? or Do we need this in other branches?
@covarell 

Best, Jihun.

**Comment by agrohsje** [comment]
@covarell @qliphy I forgot what we agreed on. Did we want 325300 and 325500 as default PDF in both master and ul2019 or just in ul2019? I thought we agreed to keep 306000 and 320900 as default for master.

**Comment by qliphy** [comment]
@agrohsje    For MG in master, we have already changed the default PDF to 325300 and 325500:
https://github.com/cms-sw/genproductions/blob/master/MetaData/pdflist_5f_2017.dat#L2
https://github.com/cms-sw/genproductions/blob/master/MetaData/pdflist_4f_2017.dat#L2

**Comment by agrohsje** [comment]
@qliphy my worry is mainly ttbar where powheg is heavily used. i am fine with moving as for mg5 but we should warn people in this weeks mccm. 
+1 for merging

**Comment by qliphy** [comment]
" i am fine with moving as for mg5 but we should warn people in this weeks mccm."
Agreed.

**Pull request merged**
