### PR TITLE
Update ZH120_012j_NLO_HtoMuMuGamma_madspin_card.dat

### PR DESCRIPTION
**Pull request by andreypz**
Commenting out Z decay: missed that for 120 GeV mass point

### CODE REVIEW

**Comment by perrozzi** [comment]
do you plam to use pythia for the z decay? why? to reuse the same gridpack with different decay options?

**Comment by andreypz** [comment]
Yes, that is the plan. Because the Z spin would not be correct with this MadSpin card (spinmod=none).
I thought that it will be correct with Pythia-8 decay.  And if it's not correct there too, than what's the difference?
Without Z decays, the gridpacs are quicker to produce.

**Comment by bendavid** [comment]
Agreed that in this case there is no advantage to using madspin for the Z decays over pythia.

The only other possibility would be to have the z decay specified as part of the process definition (but this would require removing one or both of the additional jets because of the extra complexity)

**Comment by andreypz** [comment]
Yes, I thought of that too. I concluded that the extra jets of NLO is a nicer feature if the Z decay is done in pythia.

**Pull request merged**
