### PR TITLE
Cards from Renjie Wang

### PR DESCRIPTION
**Pull request by dnash86**
Dark Matter Mono Z Madgraph cards. If there are questions, can cc analyzers.

### CODE REVIEW

**Comment by bendavid** [comment]
As usual, param cards will be completely ignored by the scripts.  Are they needed?  Normally parameters should be changed with respect to the default using the customizecards.dat mechanism.

**Comment by bendavid** [comment]
This looks like 4 flavour scheme production.  Are the b-quarks massive?

The pdf's are not correct. For 4-flavour scheme leading order should be 263400

**Comment by bendavid** [comment]
Suggested to set  cut_decays  to false to avoid unintended cuts on the lepton kinematics.

**Comment by rjwang** [comment]
I added several line in script to be able to read the param cards 
if [ -e $CARDSDIR/${name}_param_card.dat ]; then
   echo "copying $CARDSDIR/${name}_param_card.dat to working directory"
   cp $CARDSDIR/${name}_param_card.dat ./Cards/param_card.dat
fi

But we will change to the customizecards.dat mechanism

**Comment by rjwang** [comment]
yes, it is 4 flavour scheme, the b-quark is massive;  the pdf will be changed to 263400

**Comment by rjwang** [comment]
cut_decays will be set to false

**Comment by dnash86** [comment]
Uploaded new cards from @rjwang.

**Comment by bendavid** [comment]
Is this model already part of the gridpack_generation.sh script in git?

**Comment by rjwang** [comment]
Not yet, but can be put somewhere if needed, because I modify the gridpack_generation.sh with model download locally just for making grid packs: 

SimplifiedVDM=SimplifiedDM_VectorMediator_UFO.tar.gz
SimplifiedVDMSOURCE=https://rewang.web.cern.ch/rewang/cms_public/${SimplifiedVDM}

  wget --no-check-certificate ${SimplifiedVDMSOURCE}
  cd models
  tar -zxvf ../${SimplifiedVDM}
  cd ..

**Comment by bendavid** [comment]
the model should be added to 
I've copied the model to /afs/cern.ch/cms/generators/www
such that it should be available from
https://cms-project-generators.web.cern.ch/cms-project-generators/

Please add to this pull request the needed change to gridpack_generation.sh to retrieve the script from this area.

The goal here is that your gridpacks should be fully reproducible with the cards here, and no local modifications needed to the scripts.

**Comment by rjwang** [comment]
great, thanks, the updated gridpack_generation.sh will be added in this pull request

**Comment by dnash86** [comment]
Uploaded the updated gridpack_generation.sh file.

**Comment by bendavid** [comment]
param cards still need to be removed and replaced with the corresponding customizecards.dat

**Comment by dnash86** [comment]
Param cards removed and replaced with customizecards.dat, updated run_cards

**Comment by bendavid** [comment]
param cards are still here it looks like.

Also there's a merging conflict now with gridpack_generation.sh

**Comment by dnash86** [comment]
I tried to remove the param_cards and fix the merge conflict - the param cards are gone now but it seems the conflict with gridpack_generation.sh persists.  What is the conflict with that?

**Comment by bendavid** [comment]
The conflict is related to the part which adds the model I guess.  (Some other pull request which was merged in the meantime must have touched nearby lines)

So the gridpack_generation.sh changes will have to be rebased on the current master (or just made again by hand starting with the current version of the script)

**Comment by rjwang** [comment]
Hi David,

The addition we need for this PR is following: 
------------------------------------------------------------------------------------
## DM Model Vector Mediator
SimplifiedVDM=SimplifiedDM_VectorMediator_UFO.tar.gz
SimplifiedVDMSOURCE=https://cms-project-generators.web.cern.ch/cms-project-generators/${SimplifiedVDM}

 ## DM Model Vector Mediator
 wget --no-check-certificate ${SimplifiedVDMSOURCE}
 cd models
 tar -zxvf ../${SimplifiedVDM}
 cd ..
------------------------------------------------------------------------------------
you can checkout a newest version of script and then add the above addition manually. I checkout the one last Saturday, but apparently someone update the script since then. 

Thanks;
Ren-Jie

**Comment by rjwang** [comment]
Hi David,

The addition we need for this PR is following: 

## DM Model Vector Mediator
SimplifiedVDM=SimplifiedDM_VectorMediator_UFO.tar.gz
SimplifiedVDMSOURCE=https://cms-project-generators.web.cern.ch/cms-project-generators/${SimplifiedVDM}

## DM Model Vector Mediator
wget --no-check-certificate ${SimplifiedVDMSOURCE}
cd models
tar -zxvf ../${SimplifiedVDM}
cd ..

you can checkout a newest version of script and then add the above addition manually. I checkout the one last Saturday, but apparently someone update the script since then. 

Thanks;
Ren-Jie

**Comment by rjwang** [comment]
Hi David,

Can you also add 35 more cards for axial-vector coupling:
/afs/cern.ch/user/r/rewang/public/toDavid/DarkMatter/

Before they are all vector coupling, they share the same model file, 
the difference between two is

> < set param_card cV 0
> < set param_card cA 1
> ---
> > set param_card cV 1
> > set param_card cA 0


Cheers;
Ren-Jie

**Comment by dnash86** [comment]
This attempt to fix the conflict seemed to have worked.  I put the changes from @rjwang in "by hand", there were indeed other changes to the production script.

I also included the new cards from @rjwang, if the conflict is solved and the new cards are good, I think this is ready now.

Thanks

**Comment by rjwang** [comment]
thanks a lot!

**Pull request merged**
