### PR TITLE
Yuta for genproductions

### PR DESCRIPTION
**Pull request by gitytakahas**

### CODE REVIEW

**Comment by bendavid** [comment]
Ah, one other thing.
Since the cuts.f files needed for these gridpacks are tied to the madgraph release, you will either need to recreate them starting from the cuts.f in the madgraph 2.3.2.2 release, or else use the mg222 branch to process this request.
(in that case, please make the pull request for the mg222 branch instead)

**Comment by gitytakahas** [comment]
Hi Josh,

Thanks, I would prefer to recreate them starting from 2.3.2.2 release. Is
there an existing example from which I can start ?

Apart from this, I have one more question.
we are currently trying to produce,

inclusive (NLO),
1j(NLO)
2j(NLO)+ 3j(LO)


As you said, 4j is missing. If we want to have a inclusive sample beyond
3j, all what we can do is to generate LO, right ?

Best,
Yuta


2015-10-14 15:19 GMT+02:00 Josh Bendavid <notifications@github.com>:

> Ah, one other thing.
> Since the cuts.f files needed for these gridpacks are tied to the madgraph
> release, you will either need to recreate them starting from the cuts.f in
> the madgraph 2.3.2.2 release, or else use the mg222 branch to process this
> request.
> (in that case, please make the pull request for the mg222 branch instead)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/genproductions/pull/672#issuecomment-148046910>
> .
>



-- 
Yuta Takahashi
LHC - CMS experiment,
CERN (European Organization for Nuclear Research)

**Comment by bendavid** [comment]
You can start from Template/NLO/Subprocess directly from the official tarball
https://launchpad.net/mg5amcnlo/2.0/2.3.0/+download/MG5_aMC_v2.3.2.2.tar.gz

**Comment by bendavid** [comment]
For the NLO samples, you will have
1j (NLO) exclusive
2j(NLO) + 3j(LO) +4j+ (parton shower)
so the last sample is inclusive (but with only parton shower accuracy for 4j and beyond)

**Comment by gitytakahas** [comment]
Hi Josh, Roberto,

Could you consider to accept this PR ?

thanks,
Yuta

**Comment by covarell** [comment]
Has this been tested in 2.3.2.2 finally?

**Comment by gitytakahas** [comment]
No. Josh said,

> Since the cuts.f files needed for these gridpacks are tied to the
madgraph release, you will either need to recreate them starting from the
cuts.f in the madgraph 2.3.2.2 release, or else use the mg222 branch to
process this request.

So I just simply recreate the cut.f starting from 2.3.2.2
Template/NLO/subprocess/cuts.f
Do I suppose to test this in master branch or 2.3.2.2 ?

Best,
Yuta

2015-10-15 10:22 GMT+02:00 Roberto Covarelli <notifications@github.com>:

> Has this been tested in 2.3.2.2 finally?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/genproductions/pull/672#issuecomment-148315366>
> .
>



-- 
Yuta Takahashi
LHC - CMS experiment,
CERN (European Organization for Nuclear Research)

**Comment by bendavid** [comment]
In that case it should be with master branch.

**Comment by bendavid** [comment]
(The master branch has 2.3.2.2 now)

**Comment by covarell** [comment]
2.3.2.2 and master are the same now

**Comment by gitytakahas** [comment]
Hi Josh,

Yes, that is my understanding - and thus PR to master branch.

Best,
Yuta

2015-10-15 10:27 GMT+02:00 Josh Bendavid <notifications@github.com>:

> In that case it should be with master branch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/genproductions/pull/672#issuecomment-148316392>
> .
>



-- 
Yuta Takahashi
LHC - CMS experiment,
CERN (European Organization for Nuclear Research)

**Comment by gitytakahas** [comment]
What action do I need from my side ?

Yuta

2015-10-15 10:29 GMT+02:00 Roberto Covarelli <notifications@github.com>:

> 2.3.2.2 and master are the same now
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/genproductions/pull/672#issuecomment-148316621>
> .
>



-- 
Yuta Takahashi
LHC - CMS experiment,
CERN (European Organization for Nuclear Research)

**Pull request merged**
