### PR TITLE
Cards and fragment for SIDM model [compatible with mg v242]

### PR DESCRIPTION
**Pull request by phylsix**
Requesting 2017 MC for SIDM (Self-Interacting Dark Matter) model. (ref #1887 ) Thanks! weinan.si@cern.ch

### CODE REVIEW

**Comment by qliphy** [comment]
Is line like below intentional? 
https://github.com/cms-sw/genproductions/blob/a9c0696aa919401504bab6fbb1e472a85e422b1d/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/SIDM_LO/BsTo2DpTo4Mu/example/BsTo2DpTo4Mu_run_card.dat#L66

**Comment by qliphy** [comment]
Lines like below can be removed
https://github.com/cms-sw/genproductions/blob/a9c0696aa919401504bab6fbb1e472a85e422b1d/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/SIDM_LO/BsTo2DpTo2Mu2e/example/BsTo2DpTo2Mu2e_proc_card.dat#L8


And these cards are related to the hn discussion, right?
https://hypernews.cern.ch/HyperNews/CMS/get/generators/4088.html

**Comment by phylsix** [comment]
> Is line like below intentional?
> [genproductions/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/SIDM_LO/BsTo2DpTo4Mu/example/BsTo2DpTo4Mu_run_card.dat](https://github.com/cms-sw/genproductions/blob/a9c0696aa919401504bab6fbb1e472a85e422b1d/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/SIDM_LO/BsTo2DpTo4Mu/example/BsTo2DpTo4Mu_run_card.dat#L66)
> 
> Line 66 in [a9c0696](/cms-sw/genproductions/commit/a9c0696aa919401504bab6fbb1e472a85e422b1d)
> 
>  0.0001 = time_of_flight ! threshold below which info is not written

I find the default setting as -1. I was setting this to a small number in hope for Madgraph can write out lifetime of particles in LHE, but it was not successful. We end up with changing pythia settings in hadronizer fragment, which works for SIDM. So I don't mind changing it to -1.

**Comment by phylsix** [comment]
> Lines like below can be removed
> [genproductions/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/SIDM_LO/BsTo2DpTo2Mu2e/example/BsTo2DpTo2Mu2e_proc_card.dat](https://github.com/cms-sw/genproductions/blob/a9c0696aa919401504bab6fbb1e472a85e422b1d/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/SIDM_LO/BsTo2DpTo2Mu2e/example/BsTo2DpTo2Mu2e_proc_card.dat#L8)
> 
> Line 8 in [a9c0696](/cms-sw/genproductions/commit/a9c0696aa919401504bab6fbb1e472a85e422b1d)
> 
>  import model sm 

Ok, I will remove that line. (was written out by Madgraph, so I was not sure if it's relevant)

> And these cards are related to the hn discussion, right?
> https://hypernews.cern.ch/HyperNews/CMS/get/generators/4088.html

Yes, this pull request are for SIDM only.

**Comment by qliphy** [comment]
Thanks.   I would prefer time_of_flight to be changed back to -1

**Comment by phylsix** [comment]
Thanks for merging! I am also wondering what's the procedure to upload extra model -- UFO file to cms-project-generators ?

**Comment by qliphy** [comment]
You can check here
https://twiki.cern.ch/twiki/bin/view/CMS/GeneratorWebRepo

and ask help from your PAG MC Contact

**Comment by phylsix** [comment]
@qliphy I asked EXO MC contacts -- Jose Ruiz and Young Do Oh for help, it turns out they don't have write permission to `/afs/cern.ch/cms/generators/www` directory either, and suggested me to turn to GEN people. If you could help with uploading below UFO file that would be great! Thanks again!

http://wsi.web.cern.ch/wsi/mc/pscalar_darkphoton_UFO.zip

**Comment by qliphy** [comment]
Done.  As you can see from here:
https://cms-project-generators.web.cern.ch/cms-project-generators/pscalar_darkphoton_UFO.zip

**Pull request merged**
