### PR TITLE
New BPH fragments with Tune CP5

### PR DESCRIPTION
**Pull request by oozcelik**

### CODE REVIEW

**Comment by efeyazgan** [comment]
Looks OK to me but @alberto-sanchez could you please take a look at it as well?

**Comment by alberto-sanchez** [comment]
The chib are mine, for the ones for Y(4xxx)  they look good. It is using chic(1,2)  to generate them.  Assuming they have tested

**Comment by oozcelik** [comment]
Do you think it can affect the production time or something if we keep them?

**Comment by alberto-sanchez** [comment]
No really, if production team accept them is ok

**Comment by oozcelik** [comment]
They have already been tested. Please approve.

**Pull request merged**
