### PR TITLE
adding Z aTGC VBF cards

### PR DESCRIPTION
**Pull request by senka**

### CODE REVIEW

**Comment by perrozzi** [comment]
does this gridpack implies compiling code at execution time? (@kenneth)

**Comment by kdlong** [comment]
Ah yes I think so. So we need to address this. Though I believe Senka is using MG2.4, was the accidental use of all cores only an issue in 2.5?

**Comment by senka** [comment]
I am using MG 2.4.2

**Comment by perrozzi** [comment]
@kdlong my only worry is not to abuse this feature due to recent happening, in case this request is not very different from other succesfully produced, I would say please go ahead (but try to address this with the mg5_amcnlo authors asap in parallel)

**Comment by kdlong** [comment]
@perrozzi I was wrong previously, these are LO samples so the process should be fully precompiled. The .f files are removed before the gridpack is produced so it's completely impossible for them to compile on the cluster.

With that said, it looks to me like something went from for the WToLNuJJ sample and the aQGC weights weren't produced.

**Comment by perrozzi** [comment]
@senka I see a new commit, can you please comment?

**Comment by senka** [comment]
I also added W VBF cards. So now the request includes Z VBF and W VBF. The setup is the same for both samples.

**Comment by perrozzi** [comment]
@kdlong but the weights don't work yet? can the pr be merged or needs further updates?

**Comment by senka** [comment]
i fixed the problem with weights for W VBF samples and redid gridpacks. From my side this is fixed now. Kenneth can confirm from his side.

**Comment by perrozzi** [comment]
@kdlong ping

**Comment by kdlong** [comment]
Looks good to me. Both of these gridpacks will have the weights precompiled.

**Pull request merged**
