### PR TITLE
POWHEG-RES Change

### PR DESCRIPTION
**Pull request by jshin96**
Modified the patches such that it includes updated loop calculation codes and compile those codes that need separate compilation.

### CODE REVIEW

**Comment by agrohsje** [comment]
We heavily rely on pulling code from external sites. Shouldn't we copy to our gen space and pull from there. @menglu21 @bbilin @DickyChant @sihyunjeon @covarell ?

**Comment by covarell** [comment]
Hi @agrohsje , for the moment only local gridpack making is supported (on lxplus8 or equivalent) so I don't think pulling code from external sites should be a problem. On the other side, we automatically get updates.

**Comment by menglu21** [comment]
@jshin96 all these updates are validated, right. As for using GEN website, maybe we can add another try between the first "wget" and "fail_exit", 
`wget --user NLOX --password LoopsAreCool http://www.hep.fsu.edu/~nlox/downloads/v1.2.1/NLOX_1.2.1.tar.gz || fail_exit \"Failed to get NLOX_1.2.1 tar ball\"\n \ `
to
`{wget --user NLOX --password LoopsAreCool http://www.hep.fsu.edu/~nlox/downloads/v1.2.1/NLOX_1.2.1.tar.gz || wget XXXX GENWEBPLACE} || fail_exit \"Failed to get NLOX_1.2.1 tar ball\"\n \` to enable the wget can always succeed and get the package from official place as much as possible

**Comment by covarell** [comment]
@jshin96 , can you please fix this suggestion from @menglu21 , so we can proceed with this PR?

**Comment by jshin96** [comment]
@menglu21 Sorry for late response, I was bit caught up with attending AEPSHEP. By "XXXX GENWEBPLACE", could you give me an example of where these webplace is?

**Comment by menglu21** [comment]
Hi @jshin96 actually my comment is based on Alex's comment, copy them to /eos/project/c/cmsweb/www/generators/directories/cms-project-generators, and try to download from this path if downloading from their official site is failing

**Comment by covarell** [comment]
Hi again, can we merge this now (I am not sure if the above unsuccessful checks are meaningful or just depend on strange Linux version conflicts)?

**Comment by agrohsje** [comment]
Dear @bbilin @lviliani @covarell @DickyChant @sihyunjeon @jshin96 : What is the status with this PR? Who is supposed to work on it? We urgently need to split code and cards. We really put our MC production at risk if we don't follow up on such essential requests.

**Comment by bbilin** [comment]
The last question was asked by Meng, who was reviewing the pr. Then, we simply missed the last update, as there was no message but just another commit. To me this looks fine and we can merge it.

**Comment by jshin96** [comment]
I apologize, as I thought making a commit automatically sends messages.

**Pull request merged**
