### PR TITLE
GMSB for 2018 added

### PR DESCRIPTION
**Pull request by czkaiweb**
Hi,

The cff fragments for GMSB 2018 are added.
Please check and approve it.
Thanks!

Cheers,
Kai

### CODE REVIEW

**Comment by qliphy** [comment]
No need to add all the fragment files.

**Comment by czkaiweb** [comment]
Hi,
I have cleaned the cff files.

Cheers

**Comment by qliphy** [comment]
Where do you define the followings?

https://github.com/cms-sw/genproductions/blob/1a224ee5b67cf28325553e9118195bb7f812330d/python/ThirteenTeV/GMSB_2018/GMSB_LXXXTeV_CtauYYYcm_Pythia8_13TeV_cff.py#L4

https://github.com/cms-sw/genproductions/blob/1a224ee5b67cf28325553e9118195bb7f812330d/python/ThirteenTeV/GMSB_2018/GMSB_LXXXTeV_CtauYYYcm_Pythia8_13TeV_cff.py#L21

**Comment by agrohsje** [comment]
Hi @czkaiweb. Please comment on the question from Qiang.

**Comment by agrohsje** [comment]
As fragments will not work, going to close due to inactivity.

**Pull request closed without merging**
