### PR TITLE
Cluster handling via MG plugin

### PR DESCRIPTION
**Pull request by qliphy**
Import to master branch the [PR](https://github.com/cms-sw/genproductions/pull/1662) which has been merged into mg26x branch

### CODE REVIEW

**Comment by qliphy** [comment]
@kdlong @AndreasAlbert @lorusso7 @agrohsje @covarell @efeyazgan 

Would you please have a check and sign?

**Comment by AndreasAlbert** [comment]
Apologies for the delay @qliphy. The code is ready to go, I just now checked again that LSF and condor submission seem to work on lxplus without any issue in this branch. From a merge attempt I just did locally, it seems to me that you already resolved any possible merge conflicts with the cards part of the master branch. This is good to go.

**Comment by AndreasAlbert** [comment]
I checked `wplustest_4f_LO`, which worked fine. Let me check whether I can run your process.

**Comment by qliphy** [comment]
@AndreasAlbert  Indeed. Thanks!   However, I am not sure why this error message always appear at lxplus but not on other sites (e.g. cmslpc).   Although It seems the patch provided by @pmandrik  [1] can make it work.  

Anyway, I will merge this PR and add the patch later.

[1] https://hypernews.cern.ch/HyperNews/CMS/get/generators/3898/1.html

**Pull request merged**
