### PR TITLE
W+C and W+CC madgraph cards

### PR DESCRIPTION
**Pull request by pgunnell**
Two datacard directories, 3f scheme, massive charm

### CODE REVIEW

**Comment by perrozzi** [comment]
ciao paolo, a question for me to understand: why do you call the model
loop_sm-ckm_no_c_mass
but then in the datacards you use 
loop_sm-ckm_c_mass
?
I am missing something?

**Comment by kdlong** [comment]
Hey Luca,

Good catch, this was just stupidity on my part. The model file is correctly named loop_sm-ckm_c_mass but I gave the tarball the opposite name. Would you mind changing the name of the tarball in the generators repo and then we change the name in the cards?

Thanks,

Kenneth

**Comment by perrozzi** [comment]
done

**Comment by perrozzi** [comment]
ah! I merged by mistake. You still need to change the name
in the _extramodels.dat
please make another PR

**Comment by kdlong** [comment]
Thanks Luca! I remade the request.

**Comment by perrozzi** [comment]
should be merged, let me know if anything is missing/pending/wrong

**Pull request merged**
