### PR TITLE
Cards and fragment for EXO Seesaw Type III

### PR DESCRIPTION
**Pull request by davidsheffield**
From Kevin Feigelis.

The analyzers had a question about central production:

"We noticed an issue in our internal generation, and wanted to fix it before going for official production. The issue was that MadGraph and Pythia were using different points for the beam spot, roughly 46 cm part. This ended up drastically reducing our signal yield, since Pythia was using the wrong beam vertex from bosonic decay/hadronization. How do we know that this will not be an issue in official MC generation?"

### CODE REVIEW

**Comment by peterthomassen** [comment]
4.6cm (not 46cm)

**Comment by bendavid** [comment]
The way things are set up for central production, both madgraph and pythia use (0,0,0) for the vertex, then the vertex smearing to produce a realistic beamspot is done after the fact by the CMS generator interfaces (and the 4 vectors + vertices of all particles are coherently adjusted at the level of the HepMCProduct).

Actually in principle madgraph does not have a concept of "vertex position" per se.  I have never tried to run it myself using a non-(0,0,0) vertex position in pythia.

**Comment by peterthomassen** [comment]
Thanks for your input. What are the implications now for our generation request - can we be confident that beamspot inconsistency will not be an issue? Do you need further information from us?

**Comment by bendavid** [comment]
There should be no implications for the request - everything should be consistent same as any other request. 

There are a few other issues/questions though.
There are some inconsistencies for what concerns 4fs/5fs (the process definition implies 5fs, but maxjetflavour=4 is rather for 4fs)
Either way the pdfs need to be updated to "lhapdf" and the appropriate lhapdf id depending on 4fs or 5fs (please see the example cards)

Does the model you are using have massive or massless b's?

**Comment by peterthomassen** [comment]
We have fixed the 4fs vs 5fs inconsistencies (it is now all 5fs). We also changed the PDF set to lhapdf and put the desired ID. Our model has massive b's.

We have notified David already, who I think now needs to update the pull request. To my understanding, everything is ready for production then. Just in case - do you need anything else from us?

**Comment by bendavid** [comment]
Hi,
Sorry, if the model has massive b's, then everything needs to be set consistently for 4fs.  (Since massive b's cannot be included in the proton definition consistently as implied by 5fs)

**Comment by KTFeigelis** [comment]
Hi,
I have updated all run cards currently hosted on lxplus to reflect the inclusion of massive b's.

currently using 4fs, maxjetflavor=4, and lhapdf id # 263400

Cheers,
Kevin

**Comment by peterthomassen** [comment]
Hi! Do you need anything else form us?

**Comment by bendavid** [comment]
Also the proc cards need to be changed so that the p and j definitions do not include b b~

**Comment by KTFeigelis** [comment]
I have updated the lxplus directory to remove b and b~ from all proc card files.

**Comment by peterthomassen** [comment]
Do you need anything else from us / how do we proceed?

**Comment by davidsheffield** [comment]
@bendavid can these cards be merged?

**Pull request merged**
