### PR TITLE
Setting pdfwgt=F in run card

### PR DESCRIPTION
**Pull request by Sumantifr**

### CODE REVIEW

**Comment by Sumantifr** [comment]
This is for the run card for Wprimetotb directory.

**Comment by ph2632** [comment]
So, this update implies that gridpacks should be re-produced (with "F=pdfwgt" configuration) right? 
Antonis, MC-contact

**Comment by agrohsje** [comment]
Yes. Please.

**Comment by Sumantifr** [comment]
We will do. We are also trying to address the comment on merging issue in the ticket [1]. 
We will provide new gridpacks after we take care of it.

[1] https://its.cern.ch/jira/browse/HIGHPRIOREQ-30

**Pull request merged**
