### PR TITLE
Add WZ powheg production card

### PR DESCRIPTION
**Pull request by kdlong**
From the example card, changed m_ll to 12 GeV and set include negative weights to true.

### CODE REVIEW

**Comment by syuvivida** [comment]
Did you check that the fraction of negative weights is really not negligible and that "withnegweights" must be set to 1?
Here is instruction about how to check the fraction of negative weights.
https://twiki.cern.ch/twiki/bin/viewauth/CMS/PowhegBOXPrecompiled#How_to_check_the_fraction_of_eve

**Comment by kdlong** [comment]
I saw that the fraction of negative weights was small, 2.5817156812542315E-003. I turned negative weights on because it is turned on in the default WZ input card distributed with POWHEG, and because storing vs. not storing the negative weights seemed like the conservative approach. Maybe this is not the correct way to think of it?

I will compare the distributions with and without negative weights as soon as my jobs finish. Any suggestions on what I should look for?

**Comment by syuvivida** [comment]
Hi, if the fraction of negative weights is so tiny, I would suggest to keep "wighnegweights=0"
otherwise, you need to be careful when you fill histograms with weights and do any computation of efficiency. The uncertainty needs to be taken care of properly.

If you know which distributions are most important for your analysis (for example, pt of the WZ system, mass of the WZ system, pt of W, Z, ....), please make sure that the negative weights are not populated in only one or two bins.

**Comment by kdlong** [comment]
Hi, I moved the m_ll cut to 4 GeV to be consistent with what we have in MadGraph5_aMC@NLO. With this change the fraction of negative weights is now 5.9521416054882977E-003

I checked the affects of negative weights as you can see here: http://www.hep.wisc.edu/~kdlong/POWHEG_wgts_comp/

My impression is that these can safely be ignored. Do you agree?

**Comment by syuvivida** [comment]
Hi, The distributions look fine to me. Indeed, you could ignore the negative weights.

Josh and Roberto, I am OK with the cards. Could you merge them? Thanks!!

Eiko

**Pull request merged**
