### PR TITLE
Cards for Z' cascade model

### PR DESCRIPTION
**Pull request by jhakala**
As discussed with Sihyun already, this PR is for the model we are using in the B2G Z' cascade analysis (AN-20-120). I have included one set of template cards as well as a script for generating cards for other mass points of the model.

I have already iterated a bit with Sihyun, and one interesting thing he noted was:
> If (cuts_decay == False), the cuts won't do anything because the particle before the decay (ND for you here) won't get affected by ptl ptj etc

so the cuts in the run card don't matter.

### CODE REVIEW

**Comment by sihyunjeon** [comment]
Hi, can you let us know your particle mass variations as well?

**Comment by jhakala** [comment]
Hi Sihyun, here is a tentative list of mass points (from @gracecummings):

```
     mZp      mND      mNS      |       mZp      mND      mNS
    ---------------------------------------------------------
    1200      200        1      |
    1500      200        1      |     1500      600      200
    1300      400        1      |     2000      400      200
    1500      600        1      |     2000      800      200
    2000      400        1      |     2500      600      200
    2000      800        1      |     2500     1000      200
    2500      200        1      |     3000      400      200
    2500      600        1      |     3000      800      200
    2500     1000        1      |     3000     1200      200
    3000      400        1      |     3500      600      200
    3000      800        1      |     3500     1000      200
    3000     1200        1      |     3500     1400      200
    3500      200        1      |     4000      400      200
    3500      600        1      |     4000      800      200
    3500     1000        1      |     4000     1200      200
    3500     1400        1      |     4000     1600      200
    4000      400        1      |     4500      600      200
    4000      800        1      |     4500     1000      200
    4000     1200        1      |     4500     1400      200
    4000     1600        1      |     4500     1800      200
    4500      200        1      |     5000      400      200
    4500      600        1      |     5000      800      200
    4500     1000        1      |     5000     1200      200
    4500     1400        1      |     5000     1600      200
    5000      200        1      |     5500      600      200
    5000      600        1      |     5500     1000      200
    5000     1200        1      |     5500     1400      200
    5000     1600        1      |     5500     1800      200
    ```

**Comment by sihyunjeon** [comment]
I see one mzp=1300 in the middle, is this intended?
1300      400        1

**Comment by gracecummings** [comment]
Hi Sihyun, yes, the 1300 400 1 is intended, but if it complicates anything unnecessarily, it can be omitted.

**Comment by sihyunjeon** [comment]
@gracecummings No not at all, I was just curious to see it because it popped out in the middle of mZD=1500

**Comment by sihyunjeon** [comment]
Are you aware that the cuts you implemented in the run card (ptl, ptj, drjj, ..) won't do anything since you set cut_decays =False? Other than this the cards look fine to me

**Comment by jhakala** [comment]
Hi Sihyun, I looked into why we have these cuts that don't do anything. Basically, they are just default values that MadGraph automatically inserts -- we didn't implement them on purpose. And the reason we didn't remove them is simply because we received instructions on how to run the model from one of its authors, and the instructions don't include anything about editing the run card. So it is just the result of following the author's instructions verbatim without any attempts to improve cosmetics.

However, if you would prefer that these useless lines be removed, we could definitely do it. Let us know.

**Comment by sihyunjeon** [comment]
@jhakala
As long as you are aware that your cut won't be implemented, it is okay for me.

@agrohsje Can you review these cards?

**Comment by jhakala** [comment]
@sihyunjeon the model is 4FS.

**Comment by agrohsje** [comment]
I just removed the default lines in the proc card. Hope that is ok with you. I will merge.

**Pull request merged**
