### PR TITLE
pre 2017 simulation

### PR DESCRIPTION
**Pull request by ksiehl**
simulation for cp odd couplings 2016 data

### CODE REVIEW

**Comment by qliphy** [comment]
Please set store_rwgt_info to True

In proc card, you set 4 flavor:
    define j = g u c d s u~ c~ d~ s~
    define p = g u c d s u~ c~ d~ s~
however, in run_card, you take 5flavor PDF as 292200

Moreover, please just upload one set of cards for an example case

**Comment by ksiehl** [comment]
Okay.  I'll just close the pull request and start over.

**Comment by ksiehl** [comment]
Actually, I checked, and the 5flavor pdf was in the wz section, define j = j b b~ and define p = p b b~
The 4flavor ww section has PDF as 292000
Should I just open a new pull request with one from each, ww and wz, or do a separate pull request for each?

**Comment by qliphy** [comment]
You can make a new PR with one from each.

**Pull request closed without merging**
