### PR TITLE
X to AA model now in MG_242

### PR DESCRIPTION
**Pull request by osherson**
I didn't see a branch for 242, so I assume this is the master branch? Let me know if further changes are needed. Thanks,
- Marc

### CODE REVIEW

**Comment by qliphy** [comment]
Your run_card.dat is not standard.  Please refer to eample file like here:
https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/cards/production/pre2017/13TeV/dymumu012j_5f_NLO_FXFX_M105to160/dymumu012j_5f_NLO_FXFX_M105to160_run_card.dat

**Comment by osherson** [comment]
Let me try to fix this. Incidentally, I am re-submitting 262 Madgraph after
having confirmed with David Yu that this was now possible.

**Comment by osherson** [comment]
I just made the changes to the run card. One question, the example you
showed me (and some others I checked) are using lhaid 292XX, while I
thought the correct version was now 306XX. Is this just outdated? I have
changed it to 292XX for now, but would like some feedback. Thanks.
- Marc

**Comment by qliphy** [comment]
Unfortunately since last Nov,  master branch of genproductions has been switched to MadGraph 260.
MG242 has been moved to mg242legacy branch

https://hypernews.cern.ch/HyperNews/CMS/get/generators/4164.html

So if you want MG242 , you need to make a new PR to mg242legacy branch

As for PDF choice,  for 2017/2018 samples, indeed the default PDF is NNPDF31 NNLO (306000 for 5 flavor and 320900 for 4 flavor),  or you can set as [here](https://github.com/cms-sw/genproductions/blob/mg242legacy/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/TTGJets_5f_NLO_FXFX/TTGJets_5f_NLO_FXFX_run_card.dat)

$DEFAULT_PDF_SETS = lhaid
$DEFAULT_PDF_MEMBERS = reweight_PDF

**Comment by osherson** [comment]
I think I submitted to 26x? That was my original request. If you don't see
it I will send a new one on the new branch.
Thanks,
- Marc

**Comment by qliphy** [comment]
The is PR has been here for some time and the title mentions "X to AA model now in MG_242",  so I thought you still want to merge with mg242.

But if you want 26x, then it is fine.  We can keep this PR.  But please update the PDFs  and also set  set "True = store_rwgt_info" in run_card.dat.  Please follow our examples for 26x:

https://twiki.cern.ch/twiki/bin/viewauth/CMS/Mg26xTests

**Comment by osherson** [comment]
OK, I think it's been done? Let me know the next steps.
- Marc

**Comment by qliphy** [comment]
You can then proceed to produce the gridpacks and make the MC request.

**Pull request merged**
