### PR TITLE
Config file fragment and slha file for 100 GeV, 100 cm sample

### PR DESCRIPTION
**Pull request by wulsin**
This PR just has one mass, lifetime point.  Once it is approved, I will add the corresponding configs for the other mass and lifetime samples.  One question I have is whether a path needs to be specified for the slha file when it is defined in the cff.py file:  
particleFile = cms.untracked.string('geant4_AMSB_chargino_100GeV_ctau100cm.slha')

### CODE REVIEW

**Comment by bendavid** [comment]
The production release is CMSSW_7_1_X.

I assume the file SimG4Core/CustomPhysics/data/RhadronProcessList.txt is already present in this release?  Otherwise a patch release is needed.

For the slha table, if the file here is not already in the release, please use instead the inline syntax.  (Let me find an example)

**Comment by wulsin** [comment]
Yes, RhadronProcessList.txt is already in the release:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_1_X/SimG4Core/CustomPhysics/data/RhadronProcessList.txt

**Comment by bendavid** [comment]
The SLHA table can be inlined in the config as here
https://github.com/cms-sw/genproductions/blob/cecab601e4bd05ecead33cbab93cfd241514802c/python/ThirteenTeV/DisplacedSUSY_stopToBottom_M_1000_100mm_TuneCUETP8M1_13TeV_pythia8_cff.py

So then no patch release is needed.

**Comment by wulsin** [comment]
Thanks for the example.  How should I proceed?  Cancel this PR and start a new one?  Or should I modify the existing PR?

**Comment by bendavid** [comment]
You can modify this one. (please remove the separate slha file from the pull request in any case)

**Comment by wulsin** [comment]
Ok, I'll do that.

**Comment by wulsin** [comment]
I committed a change so that the slha file is defined inline.

**Comment by bendavid** [comment]
Ok sorry maybe I'm confused, do you need the SLHA table to be read by pythia or by geant?

For pythia the correct syntax is 
SLHATableForPythia8 = cms.string('%s' % SLHA_TABLE),

**Comment by wulsin** [comment]
The SLHA file needs to be read by SimG4Core/CustomPhysics/src/CustomParticleFactory.cc <http://customparticlefactory.cc/>, which then passes the information to GEANT.  Given this, I think that defining the slha file inline will not work.

**Comment by bendavid** [comment]
Yes that's right, the inlining mechnanism only works for when the slha file needs to be read by pythia.

In that case indeed you'll have to add it to
https://github.com/cms-data/Configuration-Generator
and then we'll need a patch release

**Comment by wulsin** [comment]
Ok.  So I add the slha file to https://github.com/cms-data/Configuration-Generator <https://github.com/cms-data/Configuration-Generator> but leave the cff.py where it is?

**Comment by bendavid** [comment]
Yes that's right.

Then the path to the slha file in the cff should point to "Configuration/Generator/data/<filename>.slha"

**Comment by wulsin** [comment]
Great, thanks.  I'll do that.

**Comment by wulsin** [comment]
I made a PR:  https://github.com/cms-data/Configuration-Generator/pull/4.

**Comment by degano** [comment]
@wulsin @bendavid I've merged this into 71X and 76X.

**Comment by bendavid** [comment]
The pull request was merged for cmssw, but I think we're still waiting for a new 71x release to proceed with production.

In the meantime, for the gen fragment here, are these samples going to be produced with jet matching?  (can you point me to the madgraph cards used for the lhe part of the request?)

**Comment by bendavid** [comment]
(These changes should be in CMSSW_7_1_19_patch1 already, but please check to confirm)

Would still want to look at the madgraph cards in order to make sure the pythia configuration is consistent.

**Comment by wulsin** [comment]
Hi @bendavid, sorry, but I'm not sure how to check that the changes are already in CMSSW_7_1_19_patch1.  When I look at https://github.com/cms-sw/genproductions, there are no CMSSW_X_Y_Z tags.  

Also, which madgraph cards would you like to check?  The ones here?:  https://github.com/cms-sw/genproductions/tree/master/bin/MadGraph5_aMCatNLO/cards/production/13TeV/exo_DisappTrks/AMSBchargino100GeV

Please let me know if you have any comments on them.  The last thing I need to check are the jet-matching parameters (qcut and xqcut).  Besides that, they should be ready.  But I would appreciate your checking them, since you may notice a problem that I missed. 

Thanks!

**Comment by bendavid** [comment]
If they were already merged into genproductions, then it means we already checked them.

For the release, just try running your gen fragment and see if it finds the extra customize functions which were added.

**Comment by wulsin** [comment]
Great, thanks I'll try that!

**Comment by bendavid** [comment]
Any news on this?

**Comment by govoni** [comment]
Any news on this? If not, I will close it tomorrow.

**Comment by wulsin** [comment]
Hi Pietro, Josh,

I apologize for the delay, but I have not yet had a chance to work on this.  I would request that you give me another week to put my attention to this.

Thanks,
Wells

**Comment by perrozzi** [comment]
Any news on this?

**Comment by wulsin** [comment]
Obviously I didn't have time to work on this lately.  Once I finish some other projects I will try to come back to this and pick it up again.  Fine to leave it closed for now.

**Pull request closed without merging**
