### PR TITLE
patch to run h7 for nlo fxfx with mg 265

### PR DESCRIPTION
**Pull request by agrohsje**
only for 265, not needed in 27x

### CODE REVIEW

**Comment by sihyunjeon** [comment]
Should this be merged after the test?
I was going to try out MG265+H7, I can test it if you want

**Comment by agrohsje** [comment]
One should test it with FxFx. If you are available, that would be nice!

**Comment by sihyunjeon** [comment]
Okay just started making the gridpacks with patches.
Tried generating MG265 with HERWIGPP for sanity check and indeed it fails.

Will let you know once I have results.

**Comment by sihyunjeon** [comment]
Okay this is good to go in.

Checked the gridpacks are produced & LHE files being made with it

**Pull request merged**
