### PR TITLE
Fix mistake in PDF warning printout

### PR DESCRIPTION
**Pull request by kdlong**
Fixing a bug introduced in the last commit.

### CODE REVIEW

**Comment by perrozzi** [comment]
ok so you are introducing the keywords DEFAULT_PDF_....
but they will be checked only after submission, and the user needs to go and check in the log to spot this.
Could it be enforced/checked in the submit_.....sh script requiring the used to acknowledge by pressing a key, before to submit the gridpack production?

**Comment by perrozzi** [comment]
(this can be merged anyhow while thinking of a more "stringent" solution)

**Comment by kdlong** [comment]
@perrozzi, sure I can make the check a bit more restrictive than just the printout. It can also be checked in Lorenzo's scripts. My hope is still that this can be replaced by the "systematics" module where this will happen automatically.

**Comment by perrozzi** [comment]
no rush

**Pull request merged**
