### PR TITLE
Updated HHWWgg Fragments

### PR DESCRIPTION
**Pull request by atishelmanch**
Update to HH->WWgg process fragments

Updates:
- Added W->taunu decays
- Added pdgId 5 to W->qq decays
- Removed inclusive fragments. 

Now have a total of three inclusive fragments: Semi-leptonic, Fully-leptonic, Fully-hadronic.

Thank you,
Abe Tishelman-Charny 

CC: @acarvalh

### CODE REVIEW

**Comment by atishelmanch** [comment]
As a note, the added fragments may actually be further edited, but I will leave the PR for now.

**Comment by atishelmanch** [comment]
Fragments have been updated with a second commit to now include both leptonic and hadronic decays. These are the versions we would like to update the repository with.

Thank you,
Abe

CC: @acarvalh

**Comment by atishelmanch** [comment]
@agrohsje Thank you for the comment. To confirm, after we remove this line would you be able to merge the fragments?

Thanks,
Abe

**Comment by agrohsje** [comment]
Yes, will merge once updated.

**Comment by atishelmanch** [comment]
Hello - I have removed the setting of the higgs' mass in the fragments.

Thanks,
Abe

**Comment by atishelmanch** [comment]
Hello, 

I would like to kindly ask what the status of this pull request is.

Thanks,
Abe

**Comment by agrohsje** [comment]
Unfortunately, the PR has conflicts as you can see from the message above. Can you try doing this from a clean branch so that we can easily merge?

**Comment by atishelmanch** [comment]
Hello,

I've changed the fully leptonic fragment's file name as the file name I tried to merge was deleted in a previous commit somewhere. It appears to me there are now no merge conflicts.

Thanks,
Abe

**Pull request merged**
