### PR TITLE
submitting WZ->3l configuration for 8 TeV

### PR DESCRIPTION
**Pull request by vuko-brigljevic**
Configuration for the production of WZ -> 3 leptons at 8 TeV

It is a copy of the configuration used for 13 TeV, the only change
is the beam energy

### CODE REVIEW

**Comment by bendavid** [comment]
Given that there are some not fully understood physics issues with the corresponding 13TeV sample, I would suggest to hold off on this for now.

**Comment by vuko-brigljevic** [comment]
Hi Josh,

Thanks for the prompt reply. Can we then do it for
3l + 0j @NLO? I am sitting next to Senka who
passed me the configuration. And as far as
we know, the issues found at 13 TeV (I was in the
meeting when Kenneth presented) were with
the +0,1 jet sample.

For this reason, I would have liked to actually see
both the 0 and 0+1 jets.

Cheers,
Vuko

On Tue, Aug 18, 2015 at 12:25 PM, Josh Bendavid <notifications@github.com>
wrote:

> Given that there are some not fully understood physics issues with the
> corresponding 13TeV sample, I would suggest to hold off on this for now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/genproductions/pull/584#issuecomment-132158503>
> .
>



-- 
Vuko Brigljevic
Rudjer Boskovic Institute
Bijenicka 54, HR-10000 Zagreb (Croatia)
Phone: +385-1-4571318 GSM: +385-98-965 8104
Swiss GSM (while @ CERN): +41-76-278 3615
* Currently at CERN *

**Comment by bendavid** [comment]
Hi Vuko,
These comparisons are already in progress at 13TeV (and we're currently waiting for a reply from the authors).

Is it urgent to have a sample at 8TeV, or can we wait a few weeks until the dust settles on the 13TeV comparisons/checks?

**Comment by vuko-brigljevic** [comment]
Hi Josh,

On Tue, Aug 18, 2015 at 12:38 PM, Josh Bendavid <notifications@github.com>
wrote:

> Hi Vuko,
> These comparisons are already in progress at 13TeV (and we're currently
> waiting for a reply from the authors).
>

OK.


> Is it urgent to have a sample at 8TeV, or can we wait a few weeks until
> the dust settles on the 13TeV comparisons/checks?
>
Yes, it is indeed relatively urgent to have a sample at 8 TeV, as
it is one of the final ARC/conveners request. Ok, as it was requested
as a comparison to our results, it will not actually affect the results
in any way. So in principle, one could think of adding it post-approval,
but sooner would be better in this case.

Besides, I was told that the queues are relatively empty these  days,
and that it may change soon. I understand that with a long request
list, priority will obviously not be given to 8 TeV samples.

That's why I suggested to at least submit the 0 jet sample as this
one seems to be ok.

Note that it would also be good if we manage to send a powheg
sample at 8 TeV, but I am waiting for Kenneth to come back at
CERN next week to learn the configuration from him. If we manage
to get a powheg sample in the queue soon, I would not insist on having
aMCatNLO now.

Cheers,
Vuko

—
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/genproductions/pull/584#issuecomment-132163615>
> .
>



-- 
Vuko Brigljevic
Rudjer Boskovic Institute
Bijenicka 54, HR-10000 Zagreb (Croatia)
Phone: +385-1-4571318 GSM: +385-98-965 8104
Swiss GSM (while @ CERN): +41-76-278 3615
* Currently at CERN *

**Comment by bendavid** [comment]
Alright, agreed to go ahead with the 0j if you want.

Changes needed to the cards here are to remove the 1j processes, then in the run card change ickkw to 0, and jetradius to 0.7.  (And change the name of the cards, also removing FXFX)

**Comment by vuko-brigljevic** [comment]
Ok, thanks! I will do the changes asap and let you know.

Cheers,
Vuko

On Tue, Aug 18, 2015 at 5:24 PM, Josh Bendavid <notifications@github.com>
wrote:

> Alright, agreed to go ahead with the 0j if you want.
>
> Changes needed to the cards here are to remove the 1j processes, then in
> the run card change ickkw to 0, and jetradius to 0.7. (And change the name
> of the cards, also removing FXFX)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/genproductions/pull/584#issuecomment-132249190>
> .
>



-- 
Vuko Brigljevic
Rudjer Boskovic Institute
Bijenicka 54, HR-10000 Zagreb (Croatia)
Phone: +385-1-4571318 GSM: +385-98-965 8104
Swiss GSM (while @ CERN): +41-76-278 3615
* Currently at CERN *

**Comment by vuko-brigljevic** [comment]
Hi Josh,

I have one doubt before resubmitting (in a differently named
folder btw): the PDF set. Right now, it's 292200, which I take
from the LHADPDF is

NNPDF30_nlo_nf_5_pdfas
<http://www.hepforge.org/archive/lhapdf/pdfsets/6.1/NNPDF30_nlo_nf_5_pdfas.tar.gz>

As all other 8 TeV samples were generated with the cteq family,
it would may be make sense to use one of these, e.g. CT10.
What do you think? And in case you see no problem with this,
which of these would be the one to use:

CT10, CT10as, or some other CT10xx from the list at

https://lhapdf.hepforge.org/pdfsets.html

Cheers,
Vuko

On Tue, Aug 18, 2015 at 5:53 PM, Vuko Brigljevic <Vuko.Brigljevic@cern.ch>
wrote:

> Ok, thanks! I will do the changes asap and let you know.
>
> Cheers,
> Vuko
>
> On Tue, Aug 18, 2015 at 5:24 PM, Josh Bendavid <notifications@github.com>
> wrote:
>
>> Alright, agreed to go ahead with the 0j if you want.
>>
>> Changes needed to the cards here are to remove the 1j processes, then in
>> the run card change ickkw to 0, and jetradius to 0.7. (And change the name
>> of the cards, also removing FXFX)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cms-sw/genproductions/pull/584#issuecomment-132249190>
>> .
>>
>
>
>
> --
> Vuko Brigljevic
> Rudjer Boskovic Institute
> Bijenicka 54, HR-10000 Zagreb (Croatia)
> Phone: +385-1-4571318 GSM: +385-98-965 8104
> Swiss GSM (while @ CERN): +41-76-278 3615
> * Currently at CERN *
>



-- 
Vuko Brigljevic
Rudjer Boskovic Institute
Bijenicka 54, HR-10000 Zagreb (Croatia)
Phone: +385-1-4571318 GSM: +385-98-965 8104
Swiss GSM (while @ CERN): +41-76-278 3615
* Currently at CERN *

**Comment by bendavid** [comment]
I have no strong preference, though those nnpdf sets are the only ones so far that include built-in alpha_s variations in the weights.

If you want to use CT10 you should use pdf set 11000.  Note that this is in any case pretty different from cteq6l1 used for the LO samples, so I would only worry about this if you care about consistency with other 8TeV NLO samples.

**Comment by vuko-brigljevic** [comment]
There are no other 8 TeV NLO samples, so let's stick to NNPDF then.
The LO sample (Madgraph) has been produced with CTEQ6L1 indeed.

Thanks for the information!

Cheers,
Vuko

On Tue, Aug 18, 2015 at 6:52 PM, Josh Bendavid <notifications@github.com>
wrote:

> I have no strong preference, though those nnpdf sets are the only ones so
> far that include built-in alpha_s variations in the weights.
>
> If you want to use CT10 you should use pdf set 11000. Note that this is in
> any case pretty different from cteq6l1 used for the LO samples, so I would
> only worry about this if you care about consistency with other 8TeV NLO
> samples.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/genproductions/pull/584#issuecomment-132274352>
> .
>



-- 
Vuko Brigljevic
Rudjer Boskovic Institute
Bijenicka 54, HR-10000 Zagreb (Croatia)
Phone: +385-1-4571318 GSM: +385-98-965 8104
Swiss GSM (while @ CERN): +41-76-278 3615
* Currently at CERN *

**Comment by vuko-brigljevic** [comment]
HI Josh,

Sorry to bother you again, but I am now fighting with git, trying
as last time to follow exactly the procedure at:

https://twiki.cern.ch/twiki/bin/viewauth/CMS/GitRepositoryForGenProduction#Adding_new_fragments_in_the_repo

from "Commit a fragment to your repository"
(I guess I dont' have to repeat the "one time setup"),
I created a new folder under productions/8tev/
and added it with
git add <all files>
and then "git commit -m <comment>"

But I am apparently failing in the last steps:

[vuko@lxplus0036 8TeV]$  git pull --rebase upstream master
Enter passphrase for key '/afs/cern.ch/user/v/vuko/.ssh/id_rsa':
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
From github.com:cms-sw/genproductions
 * branch            master     -> FETCH_HEAD
First, rewinding head to replay your work on top of it...
Applying: submitting WZ->3l configuration for 8 TeV
Applying: adding WZ->3l + 0j NLO
[vuko@lxplus0036 8TeV]$ git push origin master
Enter passphrase for key '/afs/cern.ch/user/v/vuko/.ssh/id_rsa':
To git@github.com:vuko-brigljevic/genproductions.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:
vuko-brigljevic/genproductions.git'
To prevent you from losing history, non-fast-forward updates were rejected
Merge the remote changes before pushing again.  See the 'Note about
fast-forwards' section of 'git push --help' for details.

and the new folder  "WZTo3LNu0j_5f_NLO"
is indeed not present in my repository:

https://github.com/vuko-brigljevic/genproductions/tree/master/bin/MadGraph5_aMCatNLO/cards/production/8TeV

Do you happen to know what I am doing wrong?

Cheers,
Vuko



On Tue, Aug 18, 2015 at 6:59 PM, Vuko Brigljevic <Vuko.Brigljevic@cern.ch>
wrote:

> There are no other 8 TeV NLO samples, so let's stick to NNPDF then.
> The LO sample (Madgraph) has been produced with CTEQ6L1 indeed.
>
> Thanks for the information!
>
> Cheers,
> Vuko
>
> On Tue, Aug 18, 2015 at 6:52 PM, Josh Bendavid <notifications@github.com>
> wrote:
>
>> I have no strong preference, though those nnpdf sets are the only ones so
>> far that include built-in alpha_s variations in the weights.
>>
>> If you want to use CT10 you should use pdf set 11000. Note that this is
>> in any case pretty different from cteq6l1 used for the LO samples, so I
>> would only worry about this if you care about consistency with other 8TeV
>> NLO samples.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cms-sw/genproductions/pull/584#issuecomment-132274352>
>> .
>>
>
>
>
> --
> Vuko Brigljevic
> Rudjer Boskovic Institute
> Bijenicka 54, HR-10000 Zagreb (Croatia)
> Phone: +385-1-4571318 GSM: +385-98-965 8104
> Swiss GSM (while @ CERN): +41-76-278 3615
> * Currently at CERN *
>



-- 
Vuko Brigljevic
Rudjer Boskovic Institute
Bijenicka 54, HR-10000 Zagreb (Croatia)
Phone: +385-1-4571318 GSM: +385-98-965 8104
Swiss GSM (while @ CERN): +41-76-278 3615
* Currently at CERN *

**Comment by vuko-brigljevic** [comment]
Hi Josh,

Forget it, solved.

Cheers,
Vuko

On Tue, Aug 18, 2015 at 7:37 PM, Vuko Brigljevic <Vuko.Brigljevic@cern.ch>
wrote:

> HI Josh,
>
> Sorry to bother you again, but I am now fighting with git, trying
> as last time to follow exactly the procedure at:
>
>
> https://twiki.cern.ch/twiki/bin/viewauth/CMS/GitRepositoryForGenProduction#Adding_new_fragments_in_the_repo
>
> from "Commit a fragment to your repository"
> (I guess I dont' have to repeat the "one time setup"),
> I created a new folder under productions/8tev/
> and added it with
> git add <all files>
> and then "git commit -m <comment>"
>
> But I am apparently failing in the last steps:
>
> [vuko@lxplus0036 8TeV]$  git pull --rebase upstream master
> Enter passphrase for key '/afs/cern.ch/user/v/vuko/.ssh/id_rsa':
> remote: Counting objects: 7, done.
> remote: Compressing objects: 100% (7/7), done.
> remote: Total 7 (delta 0), reused 0 (delta 0), pack-reused 0
> Unpacking objects: 100% (7/7), done.
> From github.com:cms-sw/genproductions
>  * branch            master     -> FETCH_HEAD
> First, rewinding head to replay your work on top of it...
> Applying: submitting WZ->3l configuration for 8 TeV
> Applying: adding WZ->3l + 0j NLO
> [vuko@lxplus0036 8TeV]$ git push origin master
> Enter passphrase for key '/afs/cern.ch/user/v/vuko/.ssh/id_rsa':
> To git@github.com:vuko-brigljevic/genproductions.git
>  ! [rejected]        master -> master (non-fast-forward)
> error: failed to push some refs to 'git@github.com:
> vuko-brigljevic/genproductions.git'
> To prevent you from losing history, non-fast-forward updates were rejected
> Merge the remote changes before pushing again.  See the 'Note about
> fast-forwards' section of 'git push --help' for details.
>
> and the new folder  "WZTo3LNu0j_5f_NLO"
> is indeed not present in my repository:
>
>
> https://github.com/vuko-brigljevic/genproductions/tree/master/bin/MadGraph5_aMCatNLO/cards/production/8TeV
>
> Do you happen to know what I am doing wrong?
>
> Cheers,
> Vuko
>
>
>
> On Tue, Aug 18, 2015 at 6:59 PM, Vuko Brigljevic <Vuko.Brigljevic@cern.ch>
> wrote:
>
>> There are no other 8 TeV NLO samples, so let's stick to NNPDF then.
>> The LO sample (Madgraph) has been produced with CTEQ6L1 indeed.
>>
>> Thanks for the information!
>>
>> Cheers,
>> Vuko
>>
>> On Tue, Aug 18, 2015 at 6:52 PM, Josh Bendavid <notifications@github.com>
>> wrote:
>>
>>> I have no strong preference, though those nnpdf sets are the only ones
>>> so far that include built-in alpha_s variations in the weights.
>>>
>>> If you want to use CT10 you should use pdf set 11000. Note that this is
>>> in any case pretty different from cteq6l1 used for the LO samples, so I
>>> would only worry about this if you care about consistency with other 8TeV
>>> NLO samples.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/cms-sw/genproductions/pull/584#issuecomment-132274352>
>>> .
>>>
>>
>>
>>
>> --
>> Vuko Brigljevic
>> Rudjer Boskovic Institute
>> Bijenicka 54, HR-10000 Zagreb (Croatia)
>> Phone: +385-1-4571318 GSM: +385-98-965 8104
>> Swiss GSM (while @ CERN): +41-76-278 3615
>> * Currently at CERN *
>>
>
>
>
> --
> Vuko Brigljevic
> Rudjer Boskovic Institute
> Bijenicka 54, HR-10000 Zagreb (Croatia)
> Phone: +385-1-4571318 GSM: +385-98-965 8104
> Swiss GSM (while @ CERN): +41-76-278 3615
> * Currently at CERN *
>



-- 
Vuko Brigljevic
Rudjer Boskovic Institute
Bijenicka 54, HR-10000 Zagreb (Croatia)
Phone: +385-1-4571318 GSM: +385-98-965 8104
Swiss GSM (while @ CERN): +41-76-278 3615
* Currently at CERN *

**Comment by vuko-brigljevic** [comment]
I have now added the WZ+0j @NLO configuration

**Pull request closed without merging**
