### PR TITLE
sherpa card for DY+01234jets

### PR DESCRIPTION
**Pull request by menglu21**
DY sample requested by Z+c analysis for 2016, they require e/mu/tau and m_ll>50.
the xsection for exclusive 0/1/2/3/4jets is around 3400/1000/330/100/50pb, in order to get stats:
0J -  50M events
1J -  50M events
2J -  20M events
3J -   5M events
4J -   3M events

set enhance factor like:
Enhance_Factor 4 {3}
Enhance_Factor 4 {4}
Enhance_Factor 4 {5}
Enhance_Factor 4 {6}

### CODE REVIEW

**Comment by qliphy** [comment]
Looks good to me.

Adding @GurpreetSinghChahal for further checks

**Comment by qliphy** [comment]
It seems you forgot to add this line in madspin card:
                          set ms_dir ./madspingrid

**Comment by menglu21** [comment]
> Looks good to me.
> 
> Adding @GurpreetSinghChahal for further checks

@GurpreetSinghChahal, could you please have a further check on sherpa card for DY+01234jets, then i can proceed to produce the samples as asked.

**Comment by qliphy** [comment]
@menglu21 
It seems you miss some semicolons in your sherpa card

**Comment by menglu21** [comment]
> @menglu21
> It seems you miss some semicolons in your sherpa card

modified

**Comment by GurpreetSinghChahal** [comment]
Hi @menglu21 Apologies for the delay. The run card/enhance factors looks ok. You can remove *LOOSE_METS* because you don't have those final states. 

  Scales LOOSE_METS{FSF*MU_F2}{RSF*MU_R2}{QSF*MU_Q2} {7,8};

Basically the LOOSE_METS scale setter, a simplified version of the METS scale setter, is used for the highest multiplicities (if NJET is set to 5 or 6) to speed up the calculation.

**Comment by menglu21** [comment]
modified

> Hi @menglu21 Apologies for the delay. The run card/enhance factors looks ok. You can remove this line with _LOOSE_METS_ because you don't have those final states:
> 
> Scales LOOSE_METS{FSF_MU_F2}{RSF_MU_R2}{QSF*MU_Q2} {7,8};
> 
> Basically the LOOSE_METS scale setter, a simplified version of the METS scale setter, is used for the highest multiplicities (if NJET is set to 5 or 6) to speed up the calculation.

**Comment by agrohsje** [comment]
Let me close as this conflicts with master. @menglu21 let me know if an update is needed. thanks

**Pull request closed without merging**
