### PR TITLE
Adding cards for Wprimetotb MC sample

### PR DESCRIPTION
**Pull request by Sumantifr**
We have requested the production of MC samples for Wprimetotb signal with MC@NLO generator. We are here uploading cards for check.

### CODE REVIEW

**Comment by qliphy** [comment]
please set pdfwgt to F
$DEFAULT_PDF_SETS = lhaid
$DEFAULT_PDF_MEMBERS = reweight_PDF

**Comment by Sumantifr** [comment]
Thanks Qiang! I have added the lines in run card.

**Comment by qliphy** [comment]
The p/j is defined as 5 flavor:
  define p = p b b~
  define j = j b b~

**Comment by Sumantifr** [comment]
As @qliphy already mentioned that we have defined 
p = p b b~
j = j b b~
in proc card. 
We have also asrwgtflavor = 5 in run card for alpha_s running.

Do you then recommend to change the PDF? 
We are currently using NNPDF31_lo_as_0130 (index: 315200).

**Comment by Sumantifr** [comment]
> No. This should be consistent. @Sumantifr : Please fix.
As @qliphy already mentioned that we have defined
p = p b b~
j = j b b~
in proc card.
We have also asrwgtflavor = 5 in run card for alpha_s running.

Do you then recommend to change the PDF?
We are currently using NNPDF31_lo_as_0130 (index: 315200).

**Comment by agrohsje** [comment]
I still see in line 73 of the run_card.dat pdfwgt = T : 
https://github.com/cms-sw/genproductions/pull/2465/files#diff-ae0ba8c77587692e724f3d34454ad346R73
Do I look at the wrong link?

**Comment by agrohsje** [comment]
Flavor looks ok:
p = p b b~ same for jet.
asrwgtflavor = 5  and maxjetflavor = 5.

**Comment by Sumantifr** [comment]
> I still see in line 73 of the run_card.dat pdfwgt = T :
> https://github.com/cms-sw/genproductions/pull/2465/files#diff-ae0ba8c77587692e724f3d34454ad346R73
> Do I look at the wrong link?


You are correct. Do we need to put pdfwgt = F ?
I now see that an issue is reported here [1].
[1] https://indico.cern.ch/event/746828/contributions/3087449/attachments/1712834/2761990/2018-09-10_GENnews.pdf#page=11&zoom=auto,-74,254

**Comment by agrohsje** [comment]
Yes. Please check p4 of 
https://indico.cern.ch/event/841564/contributions/3530752/attachments/1934708/3206598/2019-10-29_GENnews.pptx.pdf

**Comment by Sumantifr** [comment]
I've created a new pull [1] request as this one is closed.
I realized that pdfwgt was not updated last time (which was supposed to be the case)
[1] https://github.com/cms-sw/genproductions/pull/2469

**Pull request merged**
