### PR TITLE
Cards for the additional mass points for VBFH, based on the existing one...

### PR DESCRIPTION
**Pull request by chayanit**
...s

### CODE REVIEW

**Comment by syuvivida** [comment]
These cards have all necessary settings for getting scale/PDF weights.
How are the hwidth determined?

**Comment by covarell** [comment]
These values are available from the LHC XS WG page

**Comment by covarell** [comment]
For the moment the agreement with the Higgs group is to generate maximum 3 mass points per final state (125 GeV and two close to ir). Why are these needed?

**Comment by chayanit** [comment]
Dear Roberto (cc MC Higgs conveners),

I might have missed the agreement but these mass points are preparing for Higg-Exo requests.

Thanks and regards,
Chayanit
Higgs-Exo MC contact


Sent from my iPhone

On Apr 29, 2015, at 8:18 PM, Roberto Covarelli <notifications@github.com<mailto:notifications@github.com>> wrote:


For the moment the agreement with the Higgs group is to generate maximum 3 mass points per final state (125 GeV and two close to ir). Why are these needed?

**Pull request merged**
