### PR TITLE
MiNNLO + Powheg EW + Horace + HTCondor DAG

### PR DESCRIPTION
**Pull request by mseidel42**
* Scripts and cards for MiNNLO production
* Powheg job submission via DAG to get good grids for complicated processes
* Fetch Powheg from SVN instead of tarball (make optional?)
* Powheg EW
* Horace

Merge conflicts still to be solved

### CODE REVIEW

**Comment by Saptaparna** [comment]
Thanks @mseidel42. @covarell, just wanted to check with you to see if you have any comments.

**Comment by mseidel42** [comment]
* Introduced new option `--svn revision` to fetch Powheg from SVN instead of CMS tarball
* Completely removed DYNNLOPS (obsolete with MiNNLO)

Should be ready for merge now 🙂

**Comment by Saptaparna** [comment]
Hi @mseidel42, I see a number of changes to  bin/Powheg/runcmsgrid_powheg.sh and possibly scripts used by other analyses. Do you foresee any issues and should we run checks? Otherwise, I am happy to merge.

**Comment by mseidel42** [comment]
Hi Sapta, I checked that I get working gridpacks with Zj and hvq.
But it would be good if @covarell or @agrohsje could have a quick look as well.
Or we add continuous integration checks for the base scripts in this repository? I think we should be able to create a CI runner on CERN OpenStack...

**Comment by Saptaparna** [comment]
I like the idea of CI runner a lot!

**Comment by mseidel42** [comment]
Hi, I now applied the automatic tests (https://github.com/cms-sw/genproductions/pull/3186) to this MiNNLO PR and things look fine: https://github.com/mseidel42/genproductions/actions/runs/2468225053

If you don't mind I'd suggest to merge both PRs now, and then talk about setting up the runners for the genproductions repository later.

**Comment by Saptaparna** [comment]
Done!

**Comment by mseidel42** [comment]
Thanks!

**Pull request merged**
