### PR TITLE
Contact Interactions Fragments for EXO group

### PR DESCRIPTION
**Pull request by jotadram6**

### CODE REVIEW

**Comment by jotadram6** [comment]
I missed 20 fragments to be included in the pull request, should I revert this pull request or should I do a new one?

**Comment by govoni** [comment]
as you wish

**Comment by perrozzi** [comment]
may I suggest to simply add the missing cards instead of creating a commit to revert and another to add them all? probably it is a bit cleaner, although you will have 2 commits for the datacards (I suggest use the same name and use pt2 or so)

**Comment by jotadram6** [comment]
Ok, no problem

**Pull request merged**
