### PR TITLE
adding cards for WJetsToLNu sample

### PR DESCRIPTION
**Pull request by deepakcern**
I would like to add the cards for the WJetsToLNu_13Tev sample.

### CODE REVIEW

**Comment by perrozzi** [comment]
@deepakcern may I ask what is the use case for this sample?

**Comment by perrozzi** [comment]
why do you include only w- ?
why both the 1j and the 2j start at 0j ?
not sure I understand...

**Comment by deepakcern** [comment]
Sorry for mistake, i talked to Anirban and then compare with previous cards https://github.com/cms-sw/genproductions/tree/pre2017/bin/MadGraph5_aMCatNLO/cards/production/13TeV/WJets_jetbinning_LO_MLM
and i found that we need to include W+ and W- , we don't need to include 0j, 1j and 2j.
I will make some changes according to previous cards.

**Comment by anirban1982** [comment]
Yes, Deepak has to change the lhaid as well, he will do the changes and make fresh PR soon.

**Pull request merged**
