### PR TITLE
remove mgrwgt block

### PR DESCRIPTION
**Pull request by qliphy**
Related to https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/4526/1/1/1/1/1.html

Only affect NLO not LO

### CODE REVIEW

**Comment by perrozzi** [comment]
this can be merged, right?

**Comment by qliphy** [comment]
@perrozzi   Yes, I think so.  Already tested from my side.

**Comment by bendavid** [comment]
Is this still needed given the fix to the duplicate header issue?

**Comment by qliphy** [comment]
@bendavid    I think this is different from the duplicate header case (you meant last week's fix, right?).  There is no multiple runs and merge.pl will not be called.   

The problem here is  due to a new block "mgrwgt" appear in LHE with mg26X [1] which triggers bugs when pythia tries to hardonize these events.  Currently one simple solution is to remove this block...

[1]https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/4526/1/1/1/1/1.html

**Comment by bendavid** [comment]
No I wasn't referring to the merging issue, but rather the handling of headers from multiple lhe files at the CMSSW level, as addressed here
https://github.com/cms-sw/cmssw/pull/18846

(so my question is whether this change is still needed given the above pull request)

**Pull request merged**
