### PR TITLE
Update ttH Powheg card for UL production

### PR DESCRIPTION
**Pull request by sebwieland**

### CODE REVIEW

**Comment by agrohsje** [comment]
Hi @sebwieland. Can you also update the fakevirt setting in the template card as well as in master: 
https://github.com/cms-sw/genproductions/tree/master/bin/Powheg/production/2017/13TeV/Higgs/ttH_inclusive_hdamp_NNPDF31_13TeV_M125
Or is there a reason why you only want that in UL?

**Comment by sebwieland** [comment]
Hello @agrohsje,
I updated also the the template card for this PR into the UL branch.
I can also prepare a pull request in the master branch.

Should I only update the fakevirt setting or the pdf set as well for the master?

**Comment by gourangakole** [comment]
> Hi @sebwieland. Can you also update the fakevirt setting in the template card as well as in master:
> https://github.com/cms-sw/genproductions/tree/master/bin/Powheg/production/2017/13TeV/Higgs/ttH_inclusive_hdamp_NNPDF31_13TeV_M125
> Or is there a reason why you only want that in UL?

Hello @sebwieland @agrohsje ...for my knowledge .."fakevirt 0" is the latest recommendation?  what is see from 
https://usermanual.wiki/Pdf/manual.2069603384.pdf
"We recommend to generate the grid with the option fakevirt 1 in powheg.input. When
using this option, the virtual contribution is replaced by a fake one proportional to the Born
term. This speeds up the generation of the grid." 

thank you.

**Comment by sebwieland** [comment]
Hi @gourangakole 
In my understanding this fakevirt setting is only to speed up the generation of the grid.
Since we are not really limited by computing resources I went ahead and disabled it.

I already tested producing the grid in my fork and it finished within a few hours.

**Comment by agrohsje** [comment]
That was my thinking too. The statement is about CPU not physics. The new choice is for sure more accurate. Not saying it has a huge impact, but is for sure more correct. You can leave the PDF to be 306000. In fact, we never studied the impact for SM phase space between 306000 and 325300, so I have no recommendation. Both is fine.

**Comment by sebwieland** [comment]
I created another PR into the master branch adjusting the fakevirt setting.

**Pull request merged**
