### PR TITLE
MG5_aMC 2.6.0 -> 2.6.5 cardfile modification for ggH CP sample generation

### PR DESCRIPTION
**Pull request by maravin**
New cardfiles for the UL glu glu Higgs -> tau tau production for the new MG5 for the UL production.

### CODE REVIEW

**Comment by sihyunjeon** [comment]
Hello, the files are too many to review for one commit.
Can you first commit one of the benchmark processes and provide us the card generating script?
ggHCPjets/GluGLuToHToTauTauPlusXJets and a script generating script that make 0,1,2 jet cards?
And make separate commits for MaxmixH and Psuedoscalar?

**Comment by sihyunjeon** [comment]
@maravin Reminder

**Comment by agrohsje** [comment]
ping @maravin : please see comment by sihyun.

**Comment by maravin** [comment]
Apologies for the delay - I was on a vacation. To answer the questions - there was no card generating script. The owner of the scripts is Danny Winterbottom (d.winterbottom15@imperial.ac.uk) he can provide you with more details if needed. Do you really want me to split the commits into 3 separate ones? I am just not following why it would change anything except for delaying things further. Thanks much, let me know.

**Comment by sihyunjeon** [comment]
This commit has 60 files so it's difficult for us to read, thus it would delay the review process

**Comment by maravin** [comment]
I am not sure how splitting the commit is going to expedite things as you will have to review all 60 files anyways, but OK. Please let me know what I should do, as I am not experienced with git, and I see only instructions on how to create a commit (https://twiki.cern.ch/twiki/bin/view/CMS/GitRepositoryForGenProduction). Should I close this commit and start a new one with say, SM 0, 1, and 2jets? Is this what you want?

**Comment by sihyunjeon** [comment]
You can close this and open a new one.
If you don't have a script that generates the other jets configurations, I guess you can split this into 3 commits :
1. Things that start with GluGluToHToTauTau
2. GluGluToMaxmixHToTauTau
3. GluGluToPseudoscalarHToTauTau

**Comment by agrohsje** [comment]
What helps us a lot is a script with templates. Even if you split in 3 PR's this will not help us. Please use a script with templates where you replace single settings. I will close this PR now.

**Pull request closed without merging**
