### PR TITLE
replace automatically maxjetflavor to avoid inconsistencies

### PR DESCRIPTION
**Pull request by perrozzi**

### CODE REVIEW

**Comment by perrozzi** [comment]
@qliphy @kdlong I have checked that it works properly, can you please crosscheck briefly?

**Comment by qliphy** [comment]
@perrozzi   Tests with wplustest_LO_4/5f work well.  For NLO, there is no 'maxjetflavor' in run_card.dat so this might not be needed.

**Comment by perrozzi** [comment]
updated, thanks a lot

**Comment by bendavid** [comment]
Mm, I believe this setting should also be there for NLO.

**Comment by perrozzi** [comment]
I interpret the fact that is not there as being set automatically, isn't it?
would you prefer to have an explicit setting anyway, as for LO?

**Comment by bendavid** [comment]
From which card was it drawn the conclusion that it's not present?

**Comment by qliphy** [comment]
@bendavid    I checked [1] contains "maxjetflavor" while [1] not.     

I then checked with standalone MG242 and generated process like  
generate p p >  w+ [QCD]
or the FxFx one
generate p p >  w+ [QCD]
add process p p > w+ j [QCD]
In the output run_card.dat, I don't find "maxjetflavor", so I think it is not needed.  And in [1], it might just copied from elsewhere?

[1] https://github.com/cms-sw/genproductions/blob/mg26x/bin/MadGraph5_aMCatNLO/cards/examples/dyellell012j_4f_NLO_FXFX/dyellell012j_4f_NLO_FXFX_run_card.dat

[2] https://github.com/cms-sw/genproductions/blob/mg26x/bin/MadGraph5_aMCatNLO/cards/examples/wplustest_5f_NLO/wplustest_5f_NLO_run_card.dat

**Comment by bendavid** [comment]
It could be that the default is 5 and so it wasn't included in the 5f cards (to be double checked)

**Comment by qliphy** [comment]
@bendavid   Yes, it seems the 4f w NLO card contains "maxjetflavor"

@perrozzi  So maybe it is more safe to include "maxjetflavor" for NLO case, although from standalone MG it seems not needed.  

[1] https://github.com/cms-sw/genproductions/blob/mg26x/bin/MadGraph5_aMCatNLO/cards/examples/wplustest_4f_NLO/wplustest_4f_NLO_run_card.dat

**Comment by perrozzi** [comment]
ok then. question: shall I only replace it when it exists or also add it if is missing?
(same question is in principle valid for LO too)

**Comment by qliphy** [comment]
@perrozzi     "also add it if is missing" sounds good to me.

**Comment by perrozzi** [comment]
https://github.com/cms-sw/genproductions/pull/1418 (not tested yet, can you please do?)

**Comment by qliphy** [comment]
@perrozzi    

" +      echo "${nFlavorScheme}\ =\ maxjetflavor" >> ./Cards/run_card.dat"
**should be**
" +      echo "${nFlavorScheme} = maxjetflavor" >> ./Cards/run_card.dat "

After correcting this,  tests with LO/NLO 4f/5f work well.

**Comment by perrozzi** [comment]
thanks a lot, please check now

**Comment by qliphy** [comment]
@perrozzi   Checked. It works now.

**Pull request merged**
