### PR TITLE
hadronizer for GJet NLO sample

### PR DESCRIPTION
**Pull request by idebruyn**

### CODE REVIEW

**Comment by bendavid** [comment]
It's discouraged to have the full expanded configuration here.  You should just allow the common blocks to be imported without expanding their contents like with the other fragments.

**Comment by idebruyn** [comment]
Like this?

**Comment by bendavid** [comment]
Also the amcatnlosettings should not be expanded.

**Comment by idebruyn** [comment]
Ok!

**Comment by bendavid** [comment]
This looks fine now.

**Pull request merged**
