### PR TITLE
updating DYJetsToMuMu and WJetsToLNu cards to 13.6 TeV

### PR DESCRIPTION
**Pull request by leyva-daina**
Dear GEN experts,
This PR includes updated DYJetsToMuMu and WJetsToLNu cards from 14 TeV to 13.6 TeV.
The corresponding gridpacks were successfully produced.
Best,
Daina, for the Tracker group

Edit: DYJetsToMuMu gridpack having issues with process folder empty

### CODE REVIEW

**Comment by menglu21** [comment]
since the central production of MLM VJets are under preparation, is it necessary to have DYtoMuMu seperately

**Comment by menglu21** [comment]
There are centrally produced DY process https://github.com/cms-PdmV/GridpackFiles/tree/master/Cards/MadGraph5_aMCatNLO/DY/DYto2L-4Jets_MLL-50_madgraphMLM-pythia8, it's better to syncronize the parameters with it.

**Comment by leyva-daina** [comment]
Dear @sihyunjeon, @menglu21,

Thank you very much for your support on this matter.

Regarding these samples, we need a di-muon sample, so Z->mumu, for tracker alignment purposes, at 13.6 TeV. These samples usually require unique chains leading to ALCARECO datasets, and applying ALCA:TkAlZmumu filters. The filters results in a low efficiency, i.e. we usually request 30M events to have ~5M after filters. 

I had a look at the cards you mentioned, for the centrally produced DY samples. Since these include all DY processes, while we only need Z->mumu, I would be concerned about the statistics to be requested in order to have the events needed after filter efficiency. Therefore, I fully support your proposal to separate the decay channels. Could you kindly confirm if it's possible for the cards for the DY sample in the di-muon decay channel to be provided centrally? I would also appreciate guidance on how to proceed.

On another note, I wanted to mention that I've been facing issues with the gridpacks corresponding to the cards in this PR. Unfortunately, I haven't been able to resolve these issues yet, so there may be some problems with them.

Once again, thank you for the ongoing support on this issue.
Daina

**Comment by leyva-daina** [comment]
Dear @menglu21,

I want to return to this matter as we await this urgent sample for alignment purposes.

Could I have confirmation from GEN that the cards for the di-muon decay channel can be provided centrally? For when shall we expect to have them (and/or the gridpacks)?

As I mentioned earlier, if we were to use the ones provided at the moment we'd need to request 90M events instead of the usual 30M due to filter efficiency. If this would work better also for pdmv, please let me know. We also cannot use the already produced samples and apply our filters on top because we need special conditions for this request.

I kindly ask for your support and advice on this issue,
Best,
Daina

**Comment by menglu21** [comment]
Hi, sorry for the late reply. The inclusive DY requests have been already prepared, https://cms-pdmv.cern.ch/mcm/requests?page=0&dataset_name=DYto2L-4Jets_MLL-50*_TuneCP5_13p6TeV_madgraphMLM-pythia8, you want 30M mumu event for GEN-Run3Summer22 or for  GEN-Run3Summer22EE.

**Comment by leyva-daina** [comment]
Hi @menglu21, 

Thanks for your reply. 

We are unable to use standard production for this sample. We need the Z->mumu ALCARECO but with ideal conditions (global tag, beamspot), in a Run3Winter23 campaign. 

Alternatively, we have considered cloning the inclusive DY to generate the GEN with the desired conditions. However, as I said earlier, we would need 90M inclusive events instead of the usual 30M DY to mumu. Additionally, I would like to emphasize that this is not the only Z->mumu production for ALCARECO that is currently on hold. We also require at least one more sample with slightly different conditions. During the last MCCMs, the feedback received indicated that requesting 90 million events would place a substantial computational burden, making it preferable to produce the individual di-muon channel.

Could you kindly confirm if the DY to mumu cards can be provided, as we previously discussed? If not, I will proceed with the aforementioned alternative, as obtaining this sample is quite urgent for the tracker alignment group's work on several fronts.

Please feel free to request any further information if needed.

Thank you once again for your assistance.
Daina

**Comment by menglu21** [comment]
Hi @leyva-daina thanks for the clarification, I put the cards used for the requests above at /afs/cern.ch/user/m/melu/public/DYtoLL_InputCards/, you just need to change the lepton definition to mu only. @sihyunjeon I got these files by untarring the gridpack, please confirm this is fine.

**Comment by leyva-daina** [comment]
Thanks @menglu21, I'll proceed as you suggest
Best,
Daina

**Comment by sihyunjeon** [comment]
those are good to go

**Comment by menglu21** [comment]
Hi @leyva-daina could you please close this pr

**Pull request closed without merging**
