### PR TITLE
Same sign WW dim6 cards

### PR DESCRIPTION
**Pull request by GiacomoBoldrini**
The extra-model additional restriction card can be found here
http://gboldrin.web.cern.ch/gboldrin/generators/restrict_cW_cHWB_cHDD_cHbox_cHW_cHl1_cHl3_cHq1_cHq3_cqq1_cqq11_cqq31_cqq3_cll_cll1_massless.dat

### CODE REVIEW

**Comment by GiacomoBoldrini** [comment]
Following the PRs 
https://github.com/cms-sw/genproductions/pull/2969
https://github.com/cms-sw/genproductions/pull/3079

a SMEFTsim model with multiple restriction cards might be needed in https://cms-project-generators.web.cern.ch/cms-project-generators

I tried to add some general restriction cards for the PRs above and also single and pairs of operators from a set of 15. I do not know if adding a restriction card every-time is sustainable but if you need you can find the tarred SMEFTsim model with the restrictions here:

http://gboldrin.web.cern.ch/gboldrin/generators/SMEFTsim_U35_MwScheme_UFO.tar.gz

Thank you! I'm at disposal for anything

**Comment by agrohsje** [comment]
Dear @GiacomoBoldrini , I prefer including the restriction cards in the central file so it is easier to keep track. Let's first finish : 
https://github.com/cms-sw/genproductions/issues/3084#issuecomment-1016340216 
and then finish the review of this PR as well as 
#2969
#3079 ? 
Does this make sense?

**Comment by sihyunjeon** [comment]
@GiacomoBoldrini ping

**Comment by Saptaparna** [comment]
Hi @GiacomoBoldrini : I see this PR: https://github.com/cms-sw/genproductions/issues/3084 is connected too. Any news on either front?

**Comment by anpicci** [comment]
Hello everybody, 
I'm writing this as contact person of the ssWW VBS analysis with hadronic tau. We are also interested to produce samples with this set of cards, but we would like to update a new reweight_card that is compatible with the needs of aforementioned analysis

[VBSssWW_dim6_reweight_card.dat.txt](https://github.com/cms-sw/genproductions/files/8541612/VBSssWW_dim6_reweight_card.dat.txt)

If for you it is ok to implement it in the gridpack, we would like to add this reweight_card to this PR.

@mpresill also supervisioned the writing of this card.

**Comment by Saptaparna** [comment]
@anpicci: Since you are adding taus, please commit your process card.

**Comment by anpicci** [comment]
Hi @Saptaparna , the taus (also the hadronic ones) should be already included in the current proc_card, for what both @GiacomoBoldrini and I know.

This type of implementation of taus was used also for other VBS processes, and in those cases at the end there were also events with hadronic taus.

**Comment by anpicci** [comment]
Hi @Saptaparna , the taus (also the hadronic ones) are already included in the current proc_card, for what both @GiacomoBoldrini and I know about the implementation of taus in madgraph.

This type of implementation of taus was used also for other VBS processes, and in those cases at the end there were also events with hadronic taus. The latter should depend only on the Pythia side, shoudn't it?

**Comment by Saptaparna** [comment]
Cards look fine to me. 
` j = g u c d s u~ c~ d~ s~ b b~, 5 = maxjetflavor` and the b's are massless. All good, I think!
@menglu21 and @mlizzo please cross check, so we can merge this PR. Thanks!

**Comment by Saptaparna** [comment]
Thanks, @menglu21. I can take care of uploading the model.

**Comment by GiacomoBoldrini** [comment]
Thanks @mlizzo and @Saptaparna to having a look.
I agree with the eta cut that would for sure help the efficiency but as you noticed the run card is identical to the dim-8 one for consistency. We will take that into consideration for future iterations.
If you'd like a 3 > |etal| cut i can add it anyway, let me know.

Best, 
Giacomo

**Comment by Saptaparna** [comment]
@GiacomoBoldrini can you please send me this model: SMEFTsim_U35_MwScheme_UFO-cW_cHWB_cHDD_cHbox_cHW_cHl1_cHl3_cHq1_cHq3_cqq1_cqq11_cqq31_cqq3_cll_cll1_massless or is it regular SMEFT with the restrict card? We need to make that there are no name issues when the gridpack is extracted during central production of samples.

**Comment by GiacomoBoldrini** [comment]
Hello @Saptaparna, 

Yes your second answer is correct.
The model is SMEFTsim_U35_MwScheme_UFO and the restriction card I added to this PR (restrict_cW_cHWB_cHDD_cHbox_cHW_cHl1_cHl3_cHq1_cHq3_cqq1_cqq11_cqq31_cqq3_cll_cll1_massless.dat) was copied inside.

**Pull request merged**
