### PR TITLE
cards for TTToHcToWA_AToMuMu

### PR DESCRIPTION
**Pull request by choij1589**
A script for making cards and cards for 2D mass points of charged Higgs(Hc) and pseudoscalar Higgs(A).

==== Description ====
Cards for Hc to WA decay mode while A decay into dimuon in ttbar process for mass points
mHc: mA
80: 15 75
100: 15 60 95
130: 15 55 90 125
160: 15 75 85 155

I have prepared the gridpacks and would like to request signal samples using the UL MC campaign as soon as they are validated.

### CODE REVIEW

**Comment by sihyunjeon** [comment]
Hi,

Can you make a pull request with only one mass point as an example + card generating script?

**Comment by choij1589** [comment]
Hi,
I uploaded the example cards and generating scripts in #2910

**Comment by sihyunjeon** [comment]
Should we close this one then? We don't need all mass points to go in

**Comment by agrohsje** [comment]
Superseeded by  #2910.

**Pull request closed without merging**
