### PR TITLE
Heavyneutrino s and tchannel

### PR DESCRIPTION
**Pull request by sihyunjeon**
Hi all,

I am using default mg26x way of pdf weightings
and modified the changes.

Are there more that I should change?

### CODE REVIEW

**Comment by efeyazgan** [comment]
Could you please put one mass point for each case? thanks.

**Comment by sihyunjeon** [comment]
They are with different settings (decay channels are different, and there is "spinmode onshell" used only on several mass points.) Are these differences negligible?

**Comment by efeyazgan** [comment]
No, sorry, then they should stay like that.

**Comment by sihyunjeon** [comment]
This should be good to go for merge?

**Pull request merged**
