### PR TITLE
WWJTo2L2Nu_MiNNLOPS card added for UL campaign

### PR DESCRIPTION
**Pull request by sv3048**

### CODE REVIEW

**Comment by Saptaparna** [comment]
@covarell and @agrohsje:  could you please take a look, if possible. Thanks!

**Comment by mlizzo** [comment]
Hi, this is the input card I tested for generating the MiNNLO WWJ process, following authors' instructions. Other than some specific MiNNLO settings, it is the same as this one https://github.com/cms-sw/genproductions/blob/master/bin/Powheg/production/2017/13TeV/WWJTo2L2Nu_NNLOPS/WWJTo2L2Nu_NNLOPS_13TeV.input

**Comment by covarell** [comment]
+1 from me

**Comment by mlizzo** [comment]
Hi @agrohsje , actually the gridpack was already produced with these settings - after weeks of trials and errors to get it done. I don't know if it's worth it to redo it from scratch just to change this parameter, as I don't think we need it determined with uttermost precision in diboson analyses. I guess the m(WW) distribution is quite more relevant there, but please correct me if I'm wrong

**Comment by agrohsje** [comment]
Let me merge so it is clear that it is approved @sv3048 .

**Comment by mlizzo** [comment]
Thank you!

**Pull request merged**
