### PR TITLE
Nnlops

### PR DESCRIPTION
**Pull request by lenzip**
this pull request should enable HJ+NNLOPS

### CODE REVIEW

**Comment by govoni** [comment]
Ciao Giulio,

is there anywhere in the scripts a way to save what version of powheg has been used for the generation?

pietro

**Comment by lenzip** [comment]
Hi,
     do you mean the name of the tarball used?
I guess it can be put in the logfiles. Should I add it?
Giulio

**Comment by govoni** [comment]
Ciao,
yes I mean the name of our tarball. I think it would be useful in the log, or in the LHE header, so that we know what code has been used.
pietro

**Comment by lenzip** [comment]
Hello Pietro,
    I added a VERSION file which ends up in the gridpack itself.
Cheers
Giulio

**Comment by perrozzi** [comment]
ciao, this PR shouldn't have been merged so fast, as it contains modifications that clash with https://github.com/cms-sw/genproductions/pull/952 (from which some modifications of this PR are taken, which are now obsolete)
I will try to solve the conflict...

**Comment by govoni** [comment]
my fault, sorry about that

**Comment by perrozzi** [comment]
https://github.com/cms-sw/genproductions/pull/952 merged, will make sure once more that everything is ok

**Pull request merged**
