### PR TITLE
ttb_NLO_dec with meta gridpack including all decay channels

### PR DESCRIPTION
**Pull request by intrepid42**
- generate_all_[process].py creates gridpacks for all decay channels from template input file.

Meta gridpack needs to include:
- multipack_[process].py
- modified runcmsgrid.sh
- copy of run_generic_tarball_cvmfs.sh

CMSSW is completely agnostic of this, so it should work in every version :-)

### CODE REVIEW

**Comment by intrepid42** [comment]
There might be a problem with `topdec 1` (`tbardec 1` is ok), investigating...

**Comment by intrepid42** [comment]
This seems to fix (but still running the full test)
```
- Rev. 3335: Fixed bug in gen_radiation.f that affected only the
             ttb_NLO_dec process, preventing the generation of events
             with no emissions at production.  The effect on final
             distributions is very small, but the bug occasionally
             also caused the program to loop indefinitely while
             generating events.
```

**Comment by intrepid42** [comment]
Following things still need to be done:
- [ ] Hadronic decay modes still crash, under investigation by Powheg authors
- [ ] Randomize event order within a file

**Comment by perrozzi** [comment]
ping

**Comment by intrepid42** [comment]
Emanuele is still working on the hadronic decays, he hopes to fix them soon.

**Comment by perrozzi** [comment]
any news?

**Comment by intrepid42** [comment]
Unfortunately not, I pinged Emanuele again yesterday.

But we can also check with Paolo Nason in person at LHCtopWG meeting next week.

**Comment by efeyazgan** [comment]
Markus, were you able to talk to Paolo Nason?

**Comment by perrozzi** [comment]
ping

**Comment by intrepid42** [comment]
Author promised "few-days timescale" 10 days ago ;) Maybe you can remind him in person if he is still in Les Houches?

**Comment by perrozzi** [comment]
you will find the powheg authors here https://indico.cern.ch/event/572734/timetable/
;-)

**Comment by intrepid42** [comment]
* Multi gridpack now randomizes event order
* Got a patch for the hadronic decays but it is not working out-of-the-box yet. It might be a problem with the old gfortran48-compatible Powheg version

**Comment by perrozzi** [comment]
in principle after this https://github.com/cms-sw/genproductions/pull/1202
you can pick up upstream a cmssw version when creating the gridpack and the same cmssw version will be used in the worker node independently of the cmssw version of the wmLHE campaign. Once tested and validated we could even merge the two powheg branches

**Comment by intrepid42** [comment]
Nice, that would solve these problems I think :)

**Comment by intrepid42** [comment]
This should finally work! Creating a test gridpack on the batch system now to get better grids

**Pull request merged**
