### PR TITLE
update PR #731 on PDF info in LHE

### PR DESCRIPTION
**Pull request by yuanchao**
The old patch failed to apply due to the changes in the latest Powheg source code. This PR will fix the issue.

### CODE REVIEW

**Comment by perrozzi** [comment]
@yuanchao I assumed you have tested it and is all right? 
(explicitly notifying @covarell)

**Comment by yuanchao** [comment]
I've tested it on gg_H during checking the updated twiki page. :)

**Comment by covarell** [comment]
Ok for me. I think you want to PR also to "master" branch, since we are keeping the two in synch now (and eventually will drop this one).

**Comment by yuanchao** [comment]
Ok. Sure.

**Comment by perrozzi** [comment]
in fact, the branch powheg_gcc530 should be deleted, I will do it soon

**Comment by perrozzi** [comment]
(btw I changed on the fly the base branch on which to merge this PR, is a very nice feature of github. No need for a new PR)

**Pull request merged**
