### PR TITLE
Heavy ChargedHiggs Hp to tb 13 mass points

### PR DESCRIPTION
**Pull request by chayanit**
new commit after received Roberto's comments and fixed

### CODE REVIEW

**Comment by chayanit** [comment]
Added new commit of EWK Z+2jets and W+2jets samples

**Comment by chayanit** [comment]
Hi,

Could you help me merge these two commits please?

Best,
Chayanit

**Comment by covarell** [comment]
Two comments:
- two unrelated commits should not be piled up in one PR. You should start from a clean branch and open a different one (OK for this time)
- H+ fragments will really just produce H+ (i.e. not the charge conjugate) AFAICT. Is that ok?
- in W -> l nu samples you set bwcutoff = 15, this will not produce off-shell W (as opposed to Z -> nunu), is it ok?

**Comment by covarell** [comment]
They are actually 3 comments :-)

**Comment by chayanit** [comment]
Thank you Roberto for you reply and comment!

1. I have tried to separate them but they ended up to pile together. Sorry :-( I will be careful next time.
2. Ok.
3. Ok.

**Pull request merged**
