### PR TITLE
Modification of the runcards for the light charged Higgs boson (ickkw : 3 -> 0, jetradius :1.0 -> 0.7, ptj : 20 -> 10)

### PR DESCRIPTION
**Pull request by gitytakahas**
LO. This request is to cover the W+jet samples for H->tautau analysis

### CODE REVIEW

**Comment by bendavid** [comment]
This pull request seems to mix additonal W+jets cards with changes to charged higgs.  Is it intentional?

**Comment by gitytakahas** [comment]
OK, I now removed it. Sorry.

Yuta

**Comment by bendavid** [comment]
Can you rename the pull request also?

**Comment by bendavid** [comment]
and also remove the run_card.dat.back file?

**Comment by gitytakahas** [comment]
OK, I now did it.

Yuta

**Pull request merged**
