### PR TITLE
BSM Htautau signal gridpacks production code 

### PR DESCRIPTION
**Pull request by zhiyuanlcern**
Hi, 

This merge request contains two part of code:
1. 2HDM loop reweighting in runcmsgrid_powheg.sh and tuning up the lhrwg_maxnheader parameter (required by running reweighting)
2. cards production 

Cheers,
Jordan

### CODE REVIEW

**Comment by zhiyuanlcern** [comment]
Hi Meng@menglu21, could you have a look at this PR? Appreciated for your comments and suggestions.
Cheers,
Jordan

**Comment by menglu21** [comment]
Hi @zhiyuanlcern could you please put both the patch and runcmsgrid_powheg.sh into the directory of your process, since they are specific for your process

**Comment by zhiyuanlcern** [comment]
> Hi @zhiyuanlcern could you please put both the patch and runcmsgrid_powheg.sh into the directory of your process, since they are specific for your process

Hi @menglu21 , thanks a lot for the review, I have revert the changes in the two files and put the customised version in the production folder. Though the runcmsgrid_powheg.sh should only apply reweight on gg_H_2HDM and not affecting other processes, I think it's fine to integrate to the official version?  
I wonder how these customisations would be applied when we submit official production? Is extra code needed?

Cheers,
Jordan

**Comment by menglu21** [comment]
sorry, what do you mean by "I wonder how these customisations would be applied when we submit official production? Is extra code needed?"

**Comment by zhiyuanlcern** [comment]
> sorry, what do you mean by "I wonder how these customisations would be applied when we submit official production? Is extra code needed?"

Hi @menglu21, thanks a lot for your reply, sorry I have misunderstood previously. I have no further question, please go ahead merging if you approve.

Cheers,
Jordan

**Comment by zhiyuanlcern** [comment]
> Hi @zhiyuanlcern , could you please remove ".keepdir", and could you please elaborate a bit on how you get the libs

Hi @menglu21, The lib inherits from this repo: https://github.com/danielwinterbottom/ggh-mssm/tree/master/template/lib, which I believe is the repo used to produce the mssm signals for Run2 mssm H->tautau analysis.

**Pull request merged**
