### PR TITLE
tHq NLO CP cards

### PR DESCRIPTION
**Pull request by FloMau**
NLO tHq cards for CP analyses.
Replaces tHq-part of previous MR https://github.com/cms-sw/genproductions/pull/3638 to circumvent problematic reweighting + MadSpin at NLO. 

Here, seven parameter configurations are chosen in 2D plane of CP-even and -odd top Yukawa coupling modifiers. Semi leptonic and hadronic top decays are separated.

The cards can be generated with `python writeCards.py` from the ones in the `originalCards/` directory.

### CODE REVIEW

**Comment by FloMau** [comment]
Dear @menglu21 and @bibilin, 

could you please have a look at these cards and check? We would like to move forward with the sample request since the analysis has a tough timeline. 

Thanks!

**Comment by menglu21** [comment]
Hi @FloMau please only keep the writeCard.py and the template cards

**Comment by FloMau** [comment]
> Hi @FloMau please only keep the writeCard.py and the template cards

Hi @menglu21, sure, I removed the explicit cards. Is the rest OK?

**Comment by FloMau** [comment]
Dear @menglu21 and @bbilin,

could you please have a look at these cards and let us know if we can move forward with the production requests?

Thanks!

**Pull request merged**
