### PR TITLE
fixed pdf list for powheg

### PR DESCRIPTION
**Pull request by agrohsje**

### CODE REVIEW

**Comment by agrohsje** [comment]
Hi @gvonsem . This should fix the problem you pointed out (https://github.com/cms-sw/genproductions/issues/2783). Note that I generally re-ordered and assigned 4fs and 5fs properly as well as hessian vs replicas. Do you mind checking? 
@covarell can you check my PR? If ok, I will merge.

**Comment by covarell** [comment]
Hello, thanks for taking care of this! Somehow for a long time this list was incorrect, because Jihun's merges always put back the wrong version... 

The pdf names and codes look OK to me now, I wonder if the weight numbers could be reordered a little (e.g. in 5f the main pdf has the code 3000, with 2000 coming later, in 4f this is different. But it is not so important.

**Comment by agrohsje** [comment]
Hi @covarell . Thanks for checking. I didn't want to change the numbers, maybe somebody is using the info, don't know. Do you suggest to re-order the numbers or change?

**Comment by covarell** [comment]
Can we use the same numbering as MadGraph? That would be ideal. Though I don't think people are really using these weight numbers for analysis, since they changed so many times during Run2.

**Comment by agrohsje** [comment]
In MG5 the number just goes through: 
<weight id="1353" MUR="1.0" MUF="1.0" PDF="23796" > PDF=23790 MemberID=6 </weight>

<weight id="1354" MUR="1.0" MUF="1.0" PDF="25410" > PDF=25410 MemberID=0 </weight>

**Comment by covarell** [comment]
OK, mmm, we cannot do that. Then maybe it is not worth changing the order.

**Pull request merged**
