### PR TITLE
changed folding parameters to decrease negative weight fraction

### PR DESCRIPTION
**Pull request by chayanit**

### CODE REVIEW

**Comment by syuvivida** [comment]
@covarell I am not an expert of folding parameter. could you check these cards? Thanks!!
(or show me where to find the proper numbers).

**Comment by chayanit** [comment]
Hi, could you help me merge this card? The folding parameters are changed after we tested to get proper negative weight fraction. Thanks!

**Comment by syuvivida** [comment]
@bendavid, @covarell I checked the cards, they are OK, could you merge them?

**Comment by chayanit** [comment]
Hi again, could you help me merge these cards? it needs for Higgs group requests. Thanks in advance.

**Pull request merged**
