### PR TITLE
Opposite sign WW dim6 cards

### PR DESCRIPTION
**Pull request by chquaggio**
The restriction card needed for the generation can be retrieved here 
http://gboldrin.web.cern.ch/gboldrin/generators/restrict_cW_cHWB_cHDD_cHbox_cHW_cHl1_cHl3_cHq1_cHq3_cqq1_cqq11_cqq31_cqq3_cll_cll1_massless.dat

### CODE REVIEW

**Comment by sihyunjeon** [comment]
The restriction card you uploaded has mb!=0 thus this should be in 4 flavor scheme, no?

**Comment by agrohsje** [comment]
Indeed. The restriction is 4FS, but doesn't the massless in the end point to a massless b ? Please fix the card or the restriction file. Thanks.

**Comment by menglu21** [comment]
@chquaggio ping

**Comment by govoni** [comment]
@GiacomoBoldrini I don't know how to answer this, maybe Bianca or you could comment?

**Comment by GiacomoBoldrini** [comment]
Hi, the restriction was updated and now reads 
```
Block MASS 
    ...
    5 0.000000e+00 # MB

Block YUKAWA 
    ... 
    5 0.000000e+00 # ymb 
```

**Comment by bbilin** [comment]
Closing the ticket due to timeout, if needed, please reopen.

**Pull request closed without merging**
