### PR TITLE
WWTo2L2Nu_card_run3

### PR DESCRIPTION
**Pull request by seharajmal**

### CODE REVIEW

**Comment by menglu21** [comment]
Hi @seharajmal there are already official WW samples produced centrally, e.g., https://cms-pdmv.cern.ch/mcm/requests?prepid=GEN-Run3Summer22EEwmLHEGS-00206&page=0&shown=127, the inputs are here https://github.com/cms-PdmV/GridpackFiles/tree/master/Cards/Powheg/WW, maybe you can extract the full input card from the gridpack and update the PR with that card

**Comment by agrohsje** [comment]
Thanks @menglu21 for the heads-up!  @seharajmal what is the goal of this PR?

**Comment by seharajmal** [comment]
Hi @menglu21 @agrohsje we needed this sample (WWTo2L2Nu_TuneCP5_13p6TeV-powheg-pythia8) but from the link meng shared i can see it's already centrally produced. So there is no need of this.. Thanks

**Comment by menglu21** [comment]
Hi @seharajmal maybe you can close this pr since it's not needed

**Pull request closed without merging**
