### PR TITLE
fix f2py compiling issue under SL7

### PR DESCRIPTION
**Pull request by qliphy**
https://hypernews.cern.ch/HyperNews/CMS/get/generators/4411/1/2/1.html

### CODE REVIEW

**Comment by qliphy** [comment]
Under SL7,  there are different versions of f2py (used for MG reweighting to make I/O fast),  the default one seems to be f2py3.6 which triggers python3, while MG26X is not ready with python3 yet.

Currently a quick and simple hack:  by setting f2py to f2py2.7

There might be other more elegant way.  Comments are welcome.

**Comment by qliphy** [comment]
@grasph @lviliani @covarell @efeyazgan @agrohsje

**Comment by efeyazgan** [comment]
This solution looks good. thanks.

**Comment by grasph** [comment]
Perfect. Thanks Qian.

Philippe.

**Pull request merged**
