### PR TITLE
g2hdm cards

### PR DESCRIPTION
**Pull request by efeyazgan**

### CODE REVIEW

**Comment by qliphy** [comment]
Why not just combine the lines, e.g. as below?:
add process p p > t~ Hp QCD=99, (t~ > w- b~ , W- > l- vl~), ( Hp > t b~, (t > w+ b, w+ > l+ vl))
add process p p > t~ Hp QCD=99, (t~ > w- b~ , W- > l- vl~), ( Hp > t b~, (t > w+ b, w+ > j j))

**Comment by efeyazgan** [comment]
You mean something like this?

generate p p > t~ Hp QCD=99, (t~ > w- b~ , W- > l- vl~), ( Hp > c b~)
add process p p > t~ Hp j QCD=99, (t~ > w- b~ , W- > l- vl~), ( Hp > c b~)
add process p p > t Hm j QCD=99, (t > w+ b , W+ > l+ vl), ( Hm > c~ b)
add process p p > t~ Hp QCD=99, (t~ > w- b~ , W- > j j), ( Hp > t b~, (t > w+ b, w+ > l+ vl))
add process p p > t~ Hp QCD=99, (t~ > w- b~ , W- > l- vl~), ( Hp > t b~, (t > w+ b, w+ > l+ vl))
add process p p > t~ Hp QCD=99, (t~ > w- b~ , W- > l- vl~), ( Hp > t b~, (t > w+ b, w+ > j j))
add process p p > t~ Hp j QCD=99, (t~ > w- b~ , W- > l- vl~), ( Hp > t b~, (t > w+ b, w+ > l+ vl))
add process p p > t~ Hp j QCD=99, (t~ > w- b~ , W- > l- vl~), ( Hp > t b~, (t > w+ b, w+ > j j))
add process p p > t~ Hp j QCD=99, (t~ > w- b~ , W- > j j), ( Hp > t b~, (t > w+ b, w+ > l+ vl))
add process p p > t Hm QCD=99, (t > w+ b , W+ > l+ vl), ( Hm > c~ b)
add process p p > t Hm QCD=99, (t > w+ b , W+ > j j), ( Hm > t~ b, (t~ > w- b~, w- > l- vl~))
add process p p > t Hm QCD=99, (t > w+ b , W+ > l+ vl), ( Hm > t~ b, (t~ > w- b~, w- > l- vl~))
add process p p > t Hm QCD=99, (t > w+ b , W+ > l+ vl), ( Hm > t~ b, (t~ > w- b~, w- > j j))
add process p p > t Hm j QCD=99, (t > w+ b , W+ > l+ vl), ( Hm > t~ b, (t~ > w- b~, w- > l- vl~))
add process p p > t Hm j QCD=99, (t > w+ b , W+ > l+ vl), ( Hm > t~ b, (t~ > w- b~, w- > j j))
add process p p > t Hm j QCD=99, (t > w+ b , W+ > j j), ( Hm > t~ b, (t~ > w- b~, w- > l- vl~))

**Comment by qliphy** [comment]
I mean you can combine e.g.
add process p p > t~ Hp QCD=99, (t~ > w- b~ , W- > l- vl~), ( Hp > t b~, (t > w+ b, w+ > l+ vl))
add process p p > t~ Hp QCD=99, (t~ > w- b~ , W- > l- vl~), ( Hp > t b~, (t > w+ b, w+ > j j))
to a single line
add process p p > t~ Hp QCD=99, (t~ > w- b~ , W- > l- vl~), ( Hp > t b~, (t > w+ b, w+ > all all))

**Comment by efeyazgan** [comment]
Thanks. But then to exlude taus, I will need to add
`define all = j e+ mu+ e- mu- vl vl~`
right?

**Comment by qliphy** [comment]
I think anyway you need to consider the effect (either as signal or background) from tau, right?

**Comment by efeyazgan** [comment]
Yes, right but at least for now we want to keep the signal simpler.

**Comment by qliphy** [comment]
ok, then I am fine. 
+1
@agrohsje

**Pull request merged**
