### PR TITLE
Add EXO multilepton cards (ttPhi, SeesawTypeIII)

### PR DESCRIPTION
**Pull request by maxiheindl**
Add cards for EXO multilepton signals: ttPhi, SeesawTypeIII

### CODE REVIEW

**Comment by qliphy** [comment]
Please notice that we just changed master branch of genproductions from mg242 to mg26X
https://hypernews.cern.ch/HyperNews/CMS/get/generators/4164.html

So please close this one and make a PR to the mg242legacy branch, if it is mg242 you want to use.

**Comment by maxiheindl** [comment]
I used the mg26x branch for the gridpack production using these cards, so can I keep this pull request or do I need to change something?

**Comment by qliphy** [comment]
Ok then, you can keep this PR.

About the PDF, you are using:
            263400 | NNPDF30_lo_as_0130_nf_4

Please refer to
https://twiki.cern.ch/twiki/bin/view/CMS/PhysicsComparisonAndGeneratorTunes#Recommendations_on_the_usage_of

At least you should change to NNPDF3.1 LO PDF to match the new Tunes (CPX Pythia8 Tune).

https://indico.cern.ch/event/673269/contributions/2826138/attachments/1576801/2491833/20171218_PDF.pdf#page=5&zoom=auto,-329,69

**Comment by maxiheindl** [comment]
This is for the 2016 request only, the 2017+18 include the NNPDF3.1 recommendations. We want to keep the 2016 PDF/tune for signal comparable to the SM background MC PDF/tune choice.

**Comment by qliphy** [comment]
Ok, then please note what is mentioned in https://twiki.cern.ch/twiki/bin/view/CMS/Mg26xTests
“To use the 2016 pdfs, contained in the file pdflist_5f_2016.dat, you need to modify https://gith“ub.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/gridpack_generation.sh#L564-L565 to have 2016 instead of 2017. Also, note that currently, 2016 file contains only 3 sets and no variations due to historical reasons. This will be updated soon. ”   or you can make a PR to match 2016

**Pull request merged**
