### PR TITLE
HNL with tau couplings (2016+2017)

### PR DESCRIPTION
**Pull request by cecilecaillol**
Heavy neutral leptons with couplings to taus
2016 and 2017 gridpacks

### CODE REVIEW

**Comment by qliphy** [comment]
Why do you add "SM_HeavyN_FilesWithUFO.tgz"  in the extramodels.dat cards?

As note [here](https://twiki.cern.ch/twiki/bin/viewauth/CMS/Mg26xTests),  In mg26x, we recommend to set "True = store_rwgt_info" in run_card.dat for NLO process, which is necessary for the "systematics" module afterwards.

**Comment by cecilecaillol** [comment]
Your suggestions have been implemented. SM_HeavyN_FilesWithUFO.tgz was not necessary.

**Comment by qliphy** [comment]
It seems you still miss  "True = store_rwgt_info"  in HeavyNeutrino_trilepton_M-1000_V-0.01_tau_NLO_run_card.dat

**Comment by cecilecaillol** [comment]
I thought it was for 2017 datacards only. Now it is also added in the 2016 version.

**Comment by qliphy** [comment]
"True = store_rwgt_info" is required for MG26X version (in master branch of genproductions).

**Pull request merged**
