### PR TITLE
mg27x update

### PR DESCRIPTION
**Pull request by sihyunjeon**
@agrohsje Because mg27x was not cleaned up few months ago (e.g. genfragments directory) and remained uncleaned there are thousands of changes in this commit...

### CODE REVIEW

**Comment by sihyunjeon** [comment]
@agrohsje I just made a pull request to discuss this here.

The thing I did was
1. start from master branch
2. change madgraph release from mg265 to mg273
3. Added these lines https://github.com/sihyunjeon/genproductions/blob/mg27x_update/bin/MadGraph5_aMCatNLO/gridpack_generation.sh#L93-L101 : this is needed since at some point between mg265 and mg273, typo in madgraph-madspin Nevents_for_max_weigth was corrected to Nevents_for_max_weight by the authors
4. checked LO and NLO gridpack generations locally + LO gridpack generation in cmsconnect
5. made pull request

**Comment by sihyunjeon** [comment]
But as you can see here the madgraph cards in mg27x branch disappeared and they are also synchronised to master branch ones. Should we keep mg27x cards? But for me I don't see any point keeping mg27x cards separately

**Comment by agrohsje** [comment]
Hi @sihyunjeon . I agree. No need to keep them separately. Once we move to a split of cards and code it makes no sense anyway. Please merge your PR if there is nothing left to do. I will then add my xml patch. Thanks so much!

**Comment by sihyunjeon** [comment]
@menglu21 @SanghyunKo @choij1589 
Can anyone check whether the gridpack generations are fine with you guys as well?
Just to make sure, to be safe.
Everything is the same except MG versions changed to v273 + patches are replaced to MGv27x patches from master branch

https://github.com/sihyunjeon/genproductions/tree/mg27x_update

**Comment by choij1589** [comment]
Hi @sihyunjeon
I have tried with two card sets (one for LO and the other for NLO) and there was no problem with gridpack generation.

https://github.com/sihyunjeon/genproductions/tree/mg27x_update/bin/MadGraph5_aMCatNLO/cards/examples/wplustest_5f_LO
https://github.com/sihyunjeon/genproductions/tree/mg27x_update/bin/MadGraph5_aMCatNLO/cards/examples/dyellell012j_5f_NLO_FXFX

**Comment by sihyunjeon** [comment]
@choij1589 Thanks,
@agrohsje merging

**Pull request merged**
