### PR TITLE
HToZdZdTo4l cards and template for various mass points

### PR DESCRIPTION
**Pull request by rosedj1**
Included is the template for making ZdZd cards and the already-prepared cards for mass points.

### CODE REVIEW

**Comment by qliphy** [comment]
Do you really need to upload so many cards?  Most of the run_card.dat files indeed are the same

**Comment by rosedj1** [comment]
> Do you really need to upload so many cards? Most of the run_card.dat files indeed are the same

Updated.

**Comment by qliphy** [comment]
For LO process with mg26X (similar as for mg242), you should also add in run_card.dat: " True  = use_syst      ! Enable systematics studies"

**Comment by rosedj1** [comment]
> For LO process with mg26X (similar as for mg242), you should also add in run_card.dat: " True = use_syst ! Enable systematics studies"

Added.

**Comment by qliphy** [comment]
"True     = use_syst" is fine.

**Pull request merged**
