### PR TITLE
add 500 GeV mass points for BulkGraviton_ZZ_ZhadZhad_narrow and BulkG…

### PR DESCRIPTION
**Pull request by clelange**
…raviton_WW_inclu_narrow

These will be requested via B2G, gridpacks have been created and will be uploaded by B2G MC contacts.

### CODE REVIEW

**Comment by perrozzi** [comment]
just to crosscheck, the model supports 4F PDF?

**Comment by clelange** [comment]
I think so, but I only changed the resonance mass based on already existing cards in the same directories. This model (`RS_bulk_ktilda`) has been created by @acarvalh and can be found at https://twiki.cern.ch/twiki/bin/view/Sandbox/DiHiggsModels.
I actually had to adjust the gridpack generation scripts to allow creating a gridpack from it. Will make another PR for that.

**Comment by perrozzi** [comment]
ping

**Comment by clelange** [comment]
Anything you need from me, @perrozzi?

**Comment by perrozzi** [comment]
I was waiting for a confirmation about the PDF scheme used by the model.

**Comment by clelange** [comment]
I'm pretty sure that this uses/supports 4FS PDFs, but I'm not sure how to check this. I didn't find any information in the model itself.

**Comment by perrozzi** [comment]
don't know what to say then... I hope it will be fine (especially if it was already used for other productions...)

**Comment by govoni** [comment]
did you get any feedback from Xanda?

**Comment by perrozzi** [comment]
nope

**Comment by clelange** [comment]
I sent her a mail, will let you know. I'm pretty sure that this is for 4FS, and this is anyway gluon-gluon fusion, but maybe you could briefly explain what's worrying you. Is it about the "proton" needs to be redefined for 5FS?

**Comment by clelange** [comment]
Just to follow up on this, here's Xanda's response:
"Yes, I think it supports all schemes for proton why it would not?
All the production is based in the default RS from madgraph. The bulk signal is gluon fusion  production, at LO this question it doesn't even matter. The model does not support NLO."

**Comment by acarvalh** [comment]
Hi all
I just realized I should be reading this thread, I am sorry.
As Clemens forwarded, the signal is lo gluon fusion, so there is no such an
issue I believe

Cheers
Xanda

Em 10/04/2017 11:29, "Clemens Lange" <notifications@github.com> escreveu:

**Pull request merged**
