### PR TITLE
remove the upper mass cut in the run card

### PR DESCRIPTION
**Pull request by KyeongPil-Lee**

### CODE REVIEW

**Comment by bendavid** [comment]
The cuts.f will also have to be added as part of the cards, so I leave this one open until that detail is sorted out.

**Comment by KyeongPil-Lee** [comment]
I included cuts.f in the card directory and rename it to match the format. please let me know if there are things should be done.

**Comment by bendavid** [comment]
This looks good.  Can you just add a brief comment at the top of the modified cuts.f explaining what was changed and where?  (I found it and it looks ok, but took me a minute or two, so good to document it at the top)

**Comment by KyeongPil-Lee** [comment]
OK. I added some comments on cut.f.

**Pull request merged**
