### PR TITLE
b*->tW 5f scheme cards have been cleaned

### PR DESCRIPTION
**Pull request by smshaheen**
b*->tW 5f scheme cards have been cleaned while implementing the last comments

### CODE REVIEW

**Comment by bendavid** [comment]
Can you confirm the model has massless b-quarks now?

For 5fs you are missing
define j = p b b~ (which is needed in addition to define p = p b b~)

Then the pdf and maxjetflavour in the run cards are still set to 4fs values.
Also use_syst needs to be set to true.

**Comment by smshaheen** [comment]
Oh my mistake. I may had copy the old version of the cards. I will just replace them now.

**Comment by bendavid** [comment]
Any update on this?

**Comment by smshaheen** [comment]
Dear josh Bendavid,
                                    Since in order to have massless b quark I am changing the card setting the mass of the b-quark to be zero. I will upload the cards quite soon.

**Comment by smshaheen** [comment]
I will probably upload the cards today for your review.

**Comment by smshaheen** [comment]
Dear Josh Bendavid, 
                                              I hope uploaeded  the cards and have created a new pull request as well. Please do have a look at 
https://github.com/smshaheen/genproductions 
And let me know whether they are able to be merged and used to gridpack production or I need to change some parameters.

Cheers,
Sarmad Masood Shaheen

**Pull request closed without merging**
