### PR TITLE
Add ttH_HToTT datacards for Run2UL

### PR DESCRIPTION
**Pull request by sitongan**
Add ttH_HToTT datacards for Run2UL for MC request to SUS

### CODE REVIEW

**Comment by menglu21** [comment]
Hi @sitongan can you move those cards to directory 2017/13TeV. you can use the template cards, and use a script to implement all the mass points. another question is that do you need slha, which parameter you want to change w.r.t the model

**Comment by sitongan** [comment]
Hi @menglu21 ,

Cards moved, and template cards / scripts are being used now.
I'm submitting these cards for a request to SUS to produce these BSM samples for Run2 UL/ Run3, and the cards using slha are taken directly from the Run2 pre-legacy version of the same samples. I'm not sure why the pre-legacy cards used slha, but I'm just submitting it as it is apart from necessary UL/Run 3 modifications to keep it the same as the pre-legacy samples.

**Comment by sitongan** [comment]
To further clarify, the parameter mH is changed w.r.t. the model.

**Comment by sitongan** [comment]
Hi @menglu21 ,

Is there anything else I should do to facilitate this PR?

Many thanks,
Sitong

**Comment by sitongan** [comment]
Hi @menglu21 , thank you for merging the run3 PR. If there's no further modifications to be made, could you kindly also merge this one too?

**Comment by sitongan** [comment]
Hi @menglu21 , is there any other modification that you'd recommend for this PR?

**Comment by sitongan** [comment]
Hi @menglu21 , is there any other modification needed on this PR? Thank you very much

**Pull request merged**
