### PR TITLE
Adding interference card files 

### PR DESCRIPTION
**Pull request by maravin**
The last set of the card files (SM and PS were pulled about 5 months ago), this is the set for interference cards. This should be it.

### CODE REVIEW

**Comment by sihyunjeon** [comment]
Hi, can you point out to us where in the cards are different from the old requests you've made?

**Comment by maravin** [comment]
The physics differences in kAgg and kHgg values, located in *param_card.dat files, for example 
diff GluGluToHToTauTauPlusTwoJets_M125_13TeV_amcatnloFXFX_pythia8/GluGluToHToTauTauPlusTwoJets_M125_13TeV_amcatnloFXFX_pythia8_param_card.dat GluGluToPseudoscalarHToTauTauPlusTwoJets_M125_13TeV_amcatnloFXFX_pythia8/GluGluToPseudoscalarHToTauTauPlusTwoJets_M125_13TeV_amcatnloFXFX_pythia8_param_card.dat
34,35c34,35
<    14 1.414000e+00 # kHgg  
<    15 0.000000e+00 # kAgg  
---
>    14 0.000000e+00 # kHgg  
>    15 0.943000e+00 # kAgg

Is this what you need?

**Comment by maravin** [comment]
P.S. And of course the number of jets simulated (total, zero jets, one jet, two jets)

**Comment by agrohsje** [comment]
@sihyunjeon feel free to merge. ideally we would handle all cards with a simple script. as we will restructure anyway, i am ok with just merging.

**Pull request merged**
