### PR TITLE
single top t-channel leptonic decay powheg cards

### PR DESCRIPTION
**Pull request by ckmackay**
Please can you check these cards for single top t-channel leptonic decay powheg, thanks.

### CODE REVIEW

**Comment by efeyazgan** [comment]
please remove the commented inputs

**Comment by ckmackay** [comment]
Removed, thanks

**Comment by efeyazgan** [comment]
And don't you need to add:
    pdfreweight 0
    storeinfo_rwgt 0 ! store weight information
    withnegweights 1 ! default 0

**Comment by efeyazgan** [comment]
By commented inputs I meant the ones below

#smartsig       1 
#bornonly   1     ! (default 0) if 1 do Born only
#testplots  1     ! (default 0, do not) do NLO and PWHG distributions
#rand1     0      ! initialize random number sequence 
#rand2     0      ! initialize random number sequence 
#manyseeds 1   

And I guess this was discussed before but for single top you want to keep hdamp at 172.5, right?

**Comment by ckmackay** [comment]
Sorry, I misunderstood, I've removed them now.
Yes, hdamp 172.5 for single top

**Pull request merged**
