### PR TITLE
cards for resonant and non-resonant HH

### PR DESCRIPTION
**Pull request by acarvalh**

### CODE REVIEW

**Comment by vischia** [comment]
Dear GEN,

do we have to wait for the PR to be approved to move on?
If so, could you please approve it?

Thanks in advance!
Cheers,
Pietro

**Comment by perrozzi** [comment]
would it be possible to upload only one representative set of cards for the parameter scan, and a script to create the others? we are trying to keep the number of files low in the repoitory to avoid slow down

**Comment by acarvalh** [comment]
I did that for the resonant case, for the nonresonant it would involve a
bit more of scripting work - is it absolutelly necessary?
The easiest way to reduce the file load is I leave only the customize cards
(remove extramodels/run of all but one representative)

2018-03-03 10:07 GMT+01:00 perrozzi <notifications@github.com>:

**Comment by perrozzi** [comment]
are the others datacards except customize cards the same for all?

**Comment by acarvalh** [comment]
Yes

**Comment by vischia** [comment]
@perrozzi, then would it be OK to remove those and have a script that copies the same files to all the other filenames?

**Comment by perrozzi** [comment]
yes that would be sufficient, thanks for your understanding

**Comment by acarvalh** [comment]
Hi Pietro,
I had just removed the duplicated extramodels and run_cards
thanks
Xanad

2018-03-04 23:02 GMT+01:00 perrozzi <notifications@github.com>:

**Pull request merged**
