### PR TITLE
update bbH, H->bb with narrow width

### PR DESCRIPTION
**Pull request by chayanit**
We have updated the fragment after discussed with Steve to get narrow width resonance and already used for official production in Moriond17 but never committed to github. For the future record, please merge this change. Thank you very much.

### CODE REVIEW

**Comment by efeyazgan** [comment]
Could you please move them to https://github.com/cms-sw/genproductions/tree/pre2017 ?

**Comment by perrozzi** [comment]
question: is this fragment meant to be used for Morionf17 or Moriond18 (aka MC 2017 v2 aka Fall17) ?

**Comment by chayanit** [comment]
Hi Luca, these fragments won't be used for Fall17 as we plan to move to MG NLO but I need to commit this for a future record. 

Could you guide me how I can make PR to the tag?

Cheers,
Chayanit

**Comment by perrozzi** [comment]
thanks for the clarification. unfortunately can't be made to the tag :-)
In principle the request could be merged as it is, although we are thinking to adopt a similar pre2017-2017 also for pythia only requests.
I have a more general question: I suppose that if the corrected fragments are uploaded only now, you used "hand-written" cfg in McM and didn't link to genproductions. if so, why? (just to understand)

**Comment by chayanit** [comment]
ok hmm I have already closed this PR. Is it ok to re-open another one? 

Yeah, it was urgently needed during that time for ICHEP16 so I didn't manage to upload the fragments to github and used hand-written on McM. I found this way is quicker and more user-friendly than waiting until they are merged to get fragment tag. Sorry :-(

**Comment by efeyazgan** [comment]
Yes, it should be ok to re-open another one.

**Comment by perrozzi** [comment]
(for the record, this PR can't be re-opened because you deleted the branch `unknown repository` otherwise it would have been possible to re-open this one itself.
Concerning the fragment wvs hand-written cfg, I understand quicker (although without review errors can appear more often), why also user-friendly? we can try to make it more user-friendly if needed

**Comment by chayanit** [comment]
Personally, I found only under /Thirteen sub-directory we already have thousands of pythia fragment and sometimes it's hard to find corresponding fragments, looking for hand-written fragment directly on McM (specific requests) and make changes on fragment box is more user-friendly but I understand it's not good for the record.

**Comment by perrozzi** [comment]
Thanks for the feedback.
I fully agree that is a problem to have thousands of files in the same folder.
For this reason I spent quite some time trying to rationalize things
https://github.com/cms-sw/genproductions/tree/master/python/ThirteenTeV
and we will watch the new PR to always have a subfolder to avoid this problem.
Does it sound a good compromise/solution? Let us know if you have other suggestions or comments

**Comment by perrozzi** [comment]
> I see it looks more promising now with subfolder but I think it will end up with too many folders according to processes again. How about subfolder with sub-groups (POG/PAG)? 

This is probably not efficient because different pog/pag can produce similar samples (for instance TTbar)

> Since all current fragments need to update with the new Tune, why don't you move everything to tags/pre2017 and restart with subfolder according to sub-group? Just a suggestion :-)

Yes this is something we are considering, thanks

**Pull request closed without merging**
