### PR TITLE
runcmsgrid_NLO modification for MG5 gridpack

### PR DESCRIPTION
**Pull request by minerva1993**
This PR is to re-organize runcmsgrid_NLO.sh for MG5 gridpack. 
Related HN: https://hypernews.cern.ch/HyperNews/CMS/get/generators/4243/1/1/1/1.html
Related issue: https://github.com/cms-sw/genproductions/issues/2100

  * Changed order of madspin and reweighting 
  * Store all weights if reweighting is ON (following https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/runcmsgrid_LO.sh#L171-L175)
  * Properly move and clean input lhe files for the next steps

This script is tested with the gridpack of cards/production/pre2017/13TeV/WVTolnujj_cpodd/aTGCstudy_cpodd_wz_wvmass600to800. Cut.f is removed for independent issue, change mode = LO, and change helicity False.

Generation of a event with/without reweighting and madspin is tested.

### CODE REVIEW

**Comment by qliphy** [comment]
Thanks!   It would be nice to have some additional checks with NLO +reweighting only and NLO + madspin only.

 @kdlong @AndreasAlbert @agrohsje @lviliani @covarell    Would you please have a check?

**Comment by agrohsje** [comment]
@qliphy using standalone mg5_amc@nlo I saw problems using LO + madspin + reweighting. While the cross sections agreed with direct production, the distributions didn't. It would be interesting to perform some more detailed validation. I will see if I can find somebody connected to top to help us.

**Comment by qliphy** [comment]
@agrohsje  Ok,  sounds interesting. Yes, further physics validation is needed then.

But here the PR is mainly for the gridpack generation itself, i.e. whether the reweighting and madspin are applied.

**Comment by qliphy** [comment]
ping

**Comment by minerva1993** [comment]
Is there anyone tested with the different datasets? Maybe I can check further.

@qliphy Do you have any suggestion?

**Comment by qliphy** [comment]
@minerva1993  Sorry for being late.   @JINGFFF and @yangheng-PKU are now trying to checking your PR.  Hopefully they should update us soon.

**Comment by Saptaparna** [comment]
@qliphy I think someone from the Purdue group maybe available to look into this too (in case help is needed).

**Comment by qliphy** [comment]
@Saptaparna   That is great. Please go ahead.

**Comment by Saptaparna** [comment]
@qliphy Thanks! @gu180 Please take a look! Thanks!

**Comment by gu180** [comment]
Hi, @minerva1993 , since I am the first time to do validation task, could you tell me what sample I should generate and what I should validate against?

**Comment by minerva1993** [comment]
Hi, @gu180, I have tested with this script with aTGCstudy_cpodd_wz_wvmass600to800 sample. However, I recommend you to produce gridpacks with different datasets, such as DY+01234jets (if the production doesn't go well, you can reduce the number of additional jets), or any sample with NLO / NLO+reweight / NLO+madspin / NLO+madspin+reweight, respectively (if possible). If you find files in the repository with keyword "reweight_card", you may find a bunch of samples. For example, WWTolnunu seems fine for me.

https://github.com/cms-sw/genproductions/tree/master/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/AnomalousCouplings-SMP/WWTolnulnu_01j_aTGC_lep_WWmass_4f_NLO_FXFX/WWTolnulnu_01j_aTGC_lep_WWmass-0to400_4f_NLO_FXFX

@qliphy, do you have any specific samples in mind?

**Comment by qliphy** [comment]
@minerva1993 @gu180  I think any sample with NLO / NLO+reweight / NLO+madspin / NLO+madspin+reweight can be tested.
Indeed, since master branch has been switched to mg265 from mg260, so all these will be useful for testing mg265 itself. In this sense,  aTGCstudy_cpodd_wz_wvmass600to800 should also be retried.

**Comment by agrohsje** [comment]
@minerva1993 @gu180 @qliphy I agree with Qiang. One question about 
https://github.com/cms-sw/genproductions/tree/master/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/AnomalousCouplings-SMP/WWTolnulnu_01j_aTGC_lep_WWmass_4f_NLO_FXFX/WWTolnulnu_01j_aTGC_lep_WWmass-0to400_4f_NLO_FXFX
The model uses a restriction card. I think restriction cards do not allow reweighting? Were these cards ever tested?

**Comment by Saptaparna** [comment]
@minerva1993 Would it be possible for you to give quick overview of this PR at one of the GEN meetings? After talking to @agrohsje it seems this issue with the restrict card is rather important and it would be good to clarify this in a short presentation. Thanks!

**Comment by minerva1993** [comment]
@agrohsje @Saptaparna Hi, since it's been ~3 months ago, it took some time to remember the details. While testing, I got some error and discussed with Qiang but it overlooked soon. (Sorry for miss, I was very new to GEN works.) It was able to create a root file via gridpack if the number of event is set to one. It is also checked that the reweighting values are *somehow* stored in LHE file (but it seems not physical). 

I will travel to CERN tomorrow and will be available from the next week. Probably we can discuss in person if you are at CERN, and I can prepare a short presentation as well.

**Comment by Saptaparna** [comment]
@minerva1993 Since I am not at CERN, could we have a Skype chat about this? I am unfortunately very busy until Wednesday of next week but should be relatively free after that. Thanks!

**Comment by minerva1993** [comment]
@Saptaparna Sure, you can add me with skype id jiwonpark1993!

**Comment by agrohsje** [comment]
Dear @minerva1993 @Saptaparna  @gu180 ,
since this thread is a few months old and we should see that we make progress to validate the reweighting @ NLO, is anybody actively working on this? 
Cheers, Alexander.

**Comment by Saptaparna** [comment]
@agrohsje I think the only way to go forward is to schedule a meeting with the author and quickly chat about the restrict card and reweighting. @gu180 is doing this. We should be able to chat next week.

**Comment by gu180** [comment]
@minerva1993 
Hi Jiwoon, we tried to generate the gridpack, but the restrict card does not exist. Could you provide us the restrict card?

MadGraph5Error : No such file /genproductions/bin/MadGraph5_aMCatNLO/aTGCstudy_cpodd_wz_wvmass600to800/aTGCstudy_cpodd_wz_wvmass600to800_gridpack/work/MG5_aMC_v2_6_0/models/EWdim6NLO/restrict_no_cbmass_cpodd.dat

**Comment by minerva1993** [comment]
Hi @gu180,
It requires a special model file. I will send it by your mail.

**Comment by Saptaparna** [comment]
@minerva1993 : Could you please send me the model file too? Thanks!

**Comment by gu180** [comment]
@minerva1993 Hi Jiwon, I tried to use absolute path, it still doesn't work.

**Comment by minerva1993** [comment]
@gu180 Hi, I just tested with master branch, it works definitely in LXPLUS (now running madloops). From your email, in the cp command, it seems that you also missed '.'(period) for the destination. Could you please check it again? 

Also, to make it runs, you need to change proc_card.dat so that the output name is same as datacard name.(output aTGCstudy_cpodd_wz_wvmass600to800 -nojpeg) As I mentioned in the fist PR message, I removed cut.f and changed reweight card (change mode = LO, and change helicity False) (there was ongoing discussion about this...)

If there is any additional problem, please let me know so that I can reproduce the error on my side.

**Comment by gu180** [comment]
@minerva1993 I did put './' for the destination in the gridpack_generator.sh. I think the problem is that I didn't change the proc_card.dat. It said 'the name of output doesn't match that of the process'.

Now I have modified the proc_card.dat. The gripack can be generated but I can't successfully run the gridpack to generate lhe file. PS I did this for the branch of your pull request.

Besides, the generating of the gridpack takes about 40 minutes. Is that normal?

**Comment by minerva1993** [comment]
@gu180 Yes it can takes > 30 min since it is the NLO gridpack. As mentioned in the chat, there was error if I tried to run many events (possible due to restricted model). The error message was something like this:
Command "reweight cmsgrid -from_cards" interrupted with error: 
DEBUG: KeyError : (((-1, 2), (-11, 12, 21, 23)), 'V')

Could you try this command:

nohup ./runcmsgrid.sh 1 1234 5 > log.txt &

which was fine (means that the lhe file was produced) for me (generating only one event).
After that can you see all the weights (reweights as well as pdf weights) in the lhe file?
If this work, you may move on to next step; removing the model restriction from proc_card, etc

**Comment by gu180** [comment]
@minerva1993
Hi Jiwon,
I put the model file in /MadGraph5_aMCatNLO/cards/gzFile. And then I modified the gripack_genreator.sh and proc_cards.dat.  The gridpack can be generated but the when I run the runcmsgrid.sh, no lhe file can be generated.


cp: cannot stat './Events/cmsgrid_decayed_1/events.lhe.gz': No such file or directory
gzip: cmsgrid_final.lhe.gz: No such file or directory
sed: can't read cmsgrid_final.lhe: No such file or directory

**Comment by minerva1993** [comment]
Hi, @gu180  it seems that madspin is not properly ended. Could you put the gridpack on lxplus so that I can copy and test?

**Comment by menglu21** [comment]
add a similar sample's setting,
/cvmfs/cms.cern.ch/phys_generator/gridpacks/slc6_amd64_gcc481/13TeV/madgraph/V5_2.4.2/WWToLNuQQ_aTGC_NLO_FxFx/WWTolnujj_01j_aTGC_semilep_Wpt-180toInf_WVmass-600to800_4f_NLO_FXFX_tarball.tar.xz

cards:
https://github.com/cms-sw/genproductions/tree/051985b3acb79ec7809f0a0a65d1ee5434319b5d/bin/MadGraph5_aMCatNLO/cards/production/13TeV/AnomalousCouplings-SMP/WWTolnujj_01j_aTGC_semilep_Wpt_WVmass_4f_NLO_FXFX/WWTolnujj_01j_aTGC_semilep_Wpt-180toInf_WVmass-600to800_4f_NLO_FXFX

**Comment by qliphy** [comment]
The previous one is with mg242, of which the script may have already been changed a lot in mg26x in master branch.  Anyway, it would be nice to check between [mg242legacy branch](https://github.com/cms-sw/genproductions/blob/mg242legacy/bin/MadGraph5_aMCatNLO/runcmsgrid_NLO.sh) with [master one](https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/runcmsgrid_NLO.sh).

**Comment by agrohsje** [comment]
Hi @minerva1993 ,
thanks for preparing this! I finally included your changes in this PR: 
https://github.com/cms-sw/genproductions/pull/2631
All validated at NLO and LO. Will close this PR.

**Pull request closed without merging**
