### PR TITLE
HJ_MINLO_NNPDF31 for UL without any \pt thresholds

### PR DESCRIPTION
**Pull request by Soumyatifr**
Dear @covarell and @agrohsje, 
I need HJ MINLO sample without any Higgs \pt thresholds and found that the available input card is old. So I have changed the input cards according to the UL configuration. It would be nice if you can kindly go through the input card and send your comments to merge. 

Yours sincerely,
Soumya Mukherjee.

### CODE REVIEW

**Comment by covarell** [comment]
The PDF change is correct. Other changes are merely technical points and do not affect the Higgs pT spectrum, AFAIK

**Comment by Soumyatifr** [comment]
Thank you very much, for reviewing the input cards and merging to the master branch.

**Comment by Soumyatifr** [comment]
@covarell but I can't see the changes in the master branch yet, Will it take some time to be updates. 
https://github.com/cms-sw/genproductions/tree/master/bin/Powheg/production/2017/13TeV/Higgs/HJ_MiNLO_NNLOPS_NNPDF31_13TeV

**Comment by covarell** [comment]
I don't have write access to genproductions

**Comment by agrohsje** [comment]
Looks good to me. I suggest to set fakevirt 0 if this is what you have in mind. Otherwise I can merge.

**Comment by Soumyatifr** [comment]
Dear @agrohsje 
I tried to be identical input card with the one with Higgs_pt > 200 GeV 
https://github.com/cms-sw/genproductions/blob/master/bin/Powheg/production/2017/13TeV/Higgs/HJ_MINLO_Pt-200ToInf/HJ_MiNLO_NNPDF31_13TeV.input
So I removed "fakevirt 0" and if this doesn't matter too much, it would be nice if you can merged it. 
Thanks a lot.

**Comment by agrohsje** [comment]
Ok. I just checked myself. I cannot find the option at all in HJ source code. No idea why this was there in first place. Anyway.

**Pull request merged**
