### PR TITLE
WJets cards with pdfwgt set to F

### PR DESCRIPTION
**Pull request by aloeliger**
WJets inclusive and jet binned cards with pdfwgt set to F for use in UL2017 based on recent studies.

### CODE REVIEW

**Comment by qliphy** [comment]
As discussed here: https://github.com/cms-sw/genproductions/pull/2432
The direct production is preferred.

**Comment by aloeliger** [comment]
Something like that then? Is that the correct way to do handle direct production?

**Comment by qliphy** [comment]
looks good, except this one:
https://github.com/cms-sw/genproductions/blob/909156a3ff68a640529cf76b5f8b4aa1b185ca23/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/WJetsToLNu_pdfwgt_F/W2JetsToLNu_13TeV-madgraphMLM-pythia8/W2JetsToLNu_13TeV-madgraphMLM-pythia8_proc_card.dat

**Comment by aloeliger** [comment]
That should fix the typos I think.

**Pull request merged**
