### PR TITLE
add pythia8 gen fragment (w/ qcut setting after tuning) for EFT ttDM

### PR DESCRIPTION
**Pull request by mtosi**
those new Pythia8 gen fragment are needed for the new MC production of EFT ttDM signal samples

the qcut tuning has been already performed

m_DM   qcut                    eff [%]               cross-section [pb]
1          90                         31.4+/-0.1            6.821e-06+/-5.425e-09
10        90                         31.2+/-0.1            6.788e-06+/-6.332e-09
50        90                         30.4+/-0.1            6.233e-06+/-4.810e-09
100      90                         29.9+/-0.1            5.415e-06+/-5.325e-09
200      94                         28.6+/-0.1            3.827e-06+/-3.533e-09
500      111                        26.7+/-0.1            1.001e-06+/-1.060e-09
600      119                        26.2+/-0.1            6.150e-07+/-5.568e-10
1000    130                        24.5+/-0.1            8.358e-08+/-6.913e-11

@peiffer @decosa @oiorio @pinna

### CODE REVIEW

**Comment by bendavid** [comment]
Ok thanks, the qcut scaling with mass looks reasonable, and the cards look ok.  Please remove the param cards from the pull request, since this is otherwise confusing when someone looks at the cards later.  (Implies that they are needed/used to prepare the gridpacks/samples, while in fact they are ignored by the scripts)

The addition to the gridpack_generation.sh of the model looks incomplete, because the location of the tarball is specified, but it seems that it's not used.

**Comment by mtosi** [comment]
opsi, thanks @bendavid !
I fix the gridpack_generation.sh script, now

**Comment by bendavid** [comment]
Thanks, that looks fine now.  But please remove the param cards from the pull request.

**Comment by mtosi** [comment]
done

**Pull request merged**
