### PR TITLE
fix PDF ini for nnlo reweighting, switch to NNPDF 3.1 (306000)

### PR DESCRIPTION
**Pull request by agrohsje**
@covarell @gourangakole @perrozzi 
On top of fixing the PDF initialization, I moved to NNPDF 3.1. Is that what we want or should I invert this change?

### CODE REVIEW

**Comment by perrozzi** [comment]
ciao @agrohsje the file chmod changed from 100755 to 100644, not sure is intentional, can you please revert it back?

**Comment by perrozzi** [comment]
concerning the PDF, I wonder if NNPDF31 of PDF4LHC should be used. It is a question that might be worth discussing with a broader group of people too.

**Comment by agrohsje** [comment]
@perrozzi 
should we chat this afternoon in coordination

**Comment by perrozzi** [comment]
yes, but HIG and LHCHXSWG should be involved and decide (Roberto can comment more)

**Comment by agrohsje** [comment]
should I just change it back for now or should we wait ?

**Comment by covarell** [comment]
I would certainly move to 3.1.

If it is used for all other generators we should be consistent for hnnlo


Inviato da Samsung Mobile.

<div>-------- Messaggio originale --------</div><div>Da: perrozzi <notifications@github.com> </div><div>Data:23/10/2017  10:22  (GMT+01:00) </div><div>A: cms-sw/genproductions <genproductions@noreply.github.com> </div><div>Cc: Roberto Covarelli <roberto.covarelli@cern.ch>, Mention <mention@noreply.github.com> </div><div>Oggetto: Re: [cms-sw/genproductions] fix PDF ini for nnlo reweighting, switch
  to NNPDF 3.1 (306000) (#1441) </div><div>
</div>yes, but HIG and LHCHXSWG should be involved and decide (Roberto can comment more)

**Comment by agrohsje** [comment]
@perrozzi I still need to change chmod !

**Comment by perrozzi** [comment]
oups! please open another pr...

**Pull request merged**
