### PR TITLE
adding the Suu files to master branch with the recent updates to pdf …

### PR DESCRIPTION
**Pull request by evahal**
…and 5flavors

### CODE REVIEW

**Comment by evahal** [comment]
Hopefully this is ok now.  Let me know.  Thanks!

**Comment by evahal** [comment]
Hi, I'm checking in on this again.  Is it ready to be approved?  Let me know if there are any issues.  Thanks!

**Comment by agrohsje** [comment]
+1 from my side for merging.

**Comment by evahal** [comment]
Thanks!

**Pull request merged**
