### PR TITLE
first attempt

### PR DESCRIPTION
**Pull request by ksiehl**
cards for a gridpack of pp -> WW , semileptonic channel

### CODE REVIEW

**Comment by qliphy** [comment]
Please follow https://github.com/cms-sw/genproductions/blob/7ade8e717ab4bf4408265a944f8002cbaa4882c4/bin/MadGraph5_aMCatNLO/cards/examples/WW_aTGC_reweight/WW_aTGC_reweight_reweight_card.dat

For example, add  "change rwgt_dir rwgt"  in reweight card


Moreover,  you are setting "change mode NLO" for a LO sample?
https://github.com/cms-sw/genproductions/blob/7ade8e717ab4bf4408265a944f8002cbaa4882c4/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/aTGCstudy_cpodd_ww/aTGCstudy_cpodd_ww_reweight_card.dat#L20

**Comment by qliphy** [comment]
Also remove 
https://github.com/cms-sw/genproductions/blob/7ade8e717ab4bf4408265a944f8002cbaa4882c4/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/aTGCstudy_cpodd_ww/aTGCstudy_cpodd_ww_run_card.dat#L269-L281

**Comment by qliphy** [comment]
These two lines are for mg242legacy branch but not the current master branch, which has different PDF settings:
https://github.com/cms-sw/genproductions/blob/7ade8e717ab4bf4408265a944f8002cbaa4882c4/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/aTGCstudy_cpodd_ww/aTGCstudy_cpodd_ww_run_card.dat#L47-L48

Please set PDF explicitly as here:
https://twiki.cern.ch/twiki/bin/view/CMS/Mg26xTests#Wgamma_aTGC_MG5_aMC_NLO_FxFx_DON

**Comment by ksiehl** [comment]
Okay, I've made the changes that you suggested, and commited them. The only differences I saw in the reweight card were the ones you explicitly mentioned.

**Comment by qliphy** [comment]
I don't see your new commits...

**Comment by ksiehl** [comment]
can you see them now?

**Comment by qliphy** [comment]
Thanks!  Some further comments:

1.  Please set PDF to 36000 from 292200.  For 2017/2018 productions, we are using CP5 Tune, and the PDF is recommended to be NNLO;
2.  Please adjust your proc card according to
https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/cards/examples/WW_aTGC_reweight/WW_aTGC_reweight_proc_card.dat
                    define p = g u c d s b u~ c~ d~ s~ b~
                    define j = p
              and add "/ t h"

**Comment by qliphy** [comment]
@0/1 is not necessary.

"/ t t~ h" or "/ t h" for this process should be the same.

**Pull request merged**
