### PR TITLE
2017 cards for VHbb samples

### PR DESCRIPTION
**Pull request by tiwariPC**
Dear all,
Please find the cards for 2017 cards for VHbb samples

### CODE REVIEW

**Comment by qliphy** [comment]
For WBJets, you may also want to exclude top quark in the process definition.

Moreover,  "T  = cut_decays" will cut on W decay products, so depending on what you want, you may set " F  = cut_decays "  or write process as "generate p p > ell+ vl  bquark / t h"

**Comment by qliphy** [comment]
To exclude top quark, you can do as following:

generate p p > ell+ vl bquark / h @0
->
generate p p > ell+ vl bquark / t  h @0

**Comment by tiwariPC** [comment]
Does this have to be done for DY and Zbjets as well?

**Comment by qliphy** [comment]
Only for WBJets, as  W+b can come from top

**Pull request merged**
