### PR TITLE
Fix for dilepton decay en ttbar

### PR DESCRIPTION
**Pull request by jfernan2**

### CODE REVIEW

**Comment by efeyazgan** [comment]
This doesn't make it decay only to electrons but to other leptons as well, right?
 +                     ! 20000    both top go into e l nu (with the appropriate signs)

**Comment by jfernan2** [comment]
@efeyazgan Only to electrons, as in the semileptonic case...
See line 32...

**Comment by efeyazgan** [comment]
But then is it correct?

**Comment by jfernan2** [comment]
Now it is, before it wasn't: only electrons, no mu and taus

**Comment by perrozzi** [comment]
sorry, not sure I understand yet: does 
`topdecaymode 22200`
include electrons, muons and taus?

**Comment by jfernan2** [comment]
@perrozi Yes, 22200 includes e, mu and tau

**Comment by perrozzi** [comment]
ok so is the pr ready to be merged? (better to be pedantic)

**Comment by jfernan2** [comment]
Yes. Sorry again

**Comment by efeyazgan** [comment]
Ok I see that there was "!". So all fine.

**Pull request merged**
