### PR TITLE
Settings for ttbar Powheg

### PR DESCRIPTION
**Pull request by jfernan2**
Preliminary settings, hdamp value still pending tuning

### CODE REVIEW

**Comment by perrozzi** [comment]
@jfernan2 is the PR intended to wait for the new hdamp values?

**Comment by jfernan2** [comment]
Yes, we need it for final settings...

**Comment by jfernan2** [comment]
hdamp value set to 237.8775 (i.e 1.379mtop)
Please sign

**Comment by perrozzi** [comment]
Hi, there are a few "problems" with the naming conventions of this PR.
- The sub-folder for the center of mass energy is missing 
- a common folder called "TT" or similar can be added after 2017/ to avoid the proliferation of the number of files/folders in the main directory. 
- each folder currently contains a single file named poheg.input while the usual convention was to use what is now the directory name as filename.

More generally speaking, probably we should create a folder for each powheg process to avoid any source of confusion (@kdlong, @covarell , @yuanchao what do you think?)

**Comment by perrozzi** [comment]
following https://hypernews.cern.ch/HyperNews/CMS/get/generators/3606.html
indeed can you please cleanup the datacards? there are a lot of commented lines, other than removing the last lines which are added automatically
https://github.com/cms-sw/genproductions/blob/master/bin/Powheg/run_pwg.py#L861-L865

@agrohsjean @jfernan2

**Comment by kdlong** [comment]
@perrozzi so the cards should be in production/2017/13TeV...? Is there any production that would qualify as both 2017 and not 13 TeV?

**Comment by agrohsje** [comment]
@jfernan2 should I do it or are you already working on it ?

**Comment by perrozzi** [comment]
@kdlong yes, for instance 5TeV pp run later this year. 
In any case 2017 referers more to the conditions than the data taking year.

**Comment by jfernan2** [comment]
Sorry, the real PR is #1360
I will update there

**Pull request merged**
