### PR TITLE
Add hadronizer for EXO-RunIIWinter15GS-02815 ---> EXO-RunIIWinter15GS…

### PR DESCRIPTION
**Pull request by davidsheffield**
…-02817

### CODE REVIEW

**Comment by bendavid** [comment]
How has qcut=20 been determined?

**Comment by gomber** [comment]
I found that in order to make sure that the choice of Qcut is ok, one needs to look at the differential jet rates. To do this, just set the value of the outTree_flag to 1 when you perform the showering, this will produce an events.tree file that you can read with the code you get in GeneratorInterface/PartonShowerVeto/test/plotDJR.C. When we produce these samples, one of the students studied this DJR plot and from that we know it is 20 GeV.

**Comment by bendavid** [comment]
@gomber but outTree_flag is obsolete and pertains only to the old jet matching code.  Was that study done in pythia8 at least?

**Comment by bendavid** [comment]
With the new jet matching, the DJR plots can be made directly from the EDM file after running the GEN step using the macro in
https://github.com/covarell/usercode/blob/master/src/GenMacros/plotdjr.C

**Comment by gomber** [comment]
I can run this plot again using the script which you mentioned, but could one of you tell me the
instructions for the GEN-step on the gridpack, so that I can produce the EDM file.?

**Comment by bendavid** [comment]
You can use the chain test command from mcm
https://cms-pdmv.cern.ch/mcm/public/restapi/chained_requests/get_test/EXO-chain_RunIIWinter15wmLHE_flowRunIIWinter15wmLHEtoGS_flowRunIISpring15DR74Startup25ns-01753

(just remove SIM from the list of steps and edit the number of events as appropriate)

**Comment by bendavid** [comment]
and for the other request
https://cms-pdmv.cern.ch/mcm/public/restapi/chained_requests/get_test/EXO-chain_RunIIWinter15wmLHE_flowRunIIWinter15wmLHEtoGS_flowRunIISpring15DR74Startup25ns-01751

**Comment by gomber** [comment]
Hi.. sorry didn't get time earlier to do this. 
So i followed your instructions and got the root file after running the GEN step.
I obtained a root file, and when I am running your script plotdjr.C  on it, I am getting the following error (*).

I did edmDumpEventContent on the root file and I do see "GenEventInfoProduct" class there, so not sure why i am getting the error.

Here is my gen root file for Wgamma sample 
~gomber/public/EXO-RunIIWinter15GS-02817.root

Any suggestions?



(*)
Warning in <TClass::TClass>: no dictionary for class edm::Parentage::Transients is available
Error in <TTreeFormula::DefinedVariable>: Class probably unavailable:GenEventInfoProduct
Error in <TTreeFormula::Compile>:  Part of the Variable "GenEvent.weight()" exists but some of it is not accessible or useable
Error in <TTreeFormula::DefinedVariable>: Class probably unavailable:GenEventInfoProduct
Error in <TTreeFormula::Compile>:  Part of the Variable "GenEvent.weight()" exists but some of it is not accessible or useable
Error in <TTreeFormula::DefinedVariable>: Class probably unavailable:GenEventInfoProduct
Error in <TTreeFormula::Compile>:  Part of the Variable "GenEvent.weight()" exists but some of it is not accessible or useable
Error in <TTreeFormula::DefinedVariable>: Class probably unavailable:GenEventInfoProduct
Error in <TTreeFormula::Compile>:  Part of the Variable "GenEvent.weight()" exists but some of it is not accessible or useable
Error in <TTreeFormula::DefinedVariable>: Class probably unavailable:GenEventInfoProduct
Error in <TTreeFormula::Compile>:  Part of the Variable "GenEvent.weight()" exists but some of it is not accessible or useable
Error in <TTreeFormula::DefinedVariable>: Class probably unavailable:GenEventInfoProduct
Error in <TTreeFormula::Compile>:  Part of the Variable "GenEvent.weight()" exists but some of it is not accessible or useable
Error in <TTreeFormula::DefinedVariable>: Class probably unavailable:GenEventInfoProduct
Error in <TTreeFormula::Compile>:  Part of the Variable "GenEvent.weight()" exists but some of it is not accessible or useable
Error in <TTreeFormula::DefinedVariable>: Class probably unavailable:GenEventInfoProduct
Error in <TTreeFormula::Compile>:  Part of the Variable "GenEvent.weight()" exists but some of it is not accessible or useable
Error in <TTreeFormula::DefinedVariable>: Class probably unavailable:GenEventInfoProduct
Error in <TTreeFormula::Compile>:  Part of the Variable "GenEvent.weight()" exists but some of it is not accessible or useable
Error in <TTreeFormula::DefinedVariable>: Class probably unavailable:GenEventInfoProduct
Error in <TTreeFormula::Compile>:  Part of the Variable "GenEvent.weight()" exists but some of it is not accessible or useable
Error in <TTreeFormula::DefinedVariable>: Class probably unavailable:GenEventInfoProduct
Error in <TTreeFormula::Compile>:  Part of the Variable "GenEvent.weight()" exists but some of it is not accessible or useable
Error in <TTreeFormula::DefinedVariable>: Class probably unavailable:GenEventInfoProduct
Error in <TTreeFormula::Compile>:  Part of the Variable "GenEvent.weight()" exists but some of it is not accessible or useable
Error in <TTreeFormula::DefinedVariable>: Class probably unavailable:GenEventInfoProduct
Error in <TTreeFormula::Compile>:  Part of the Variable "GenEvent.weight()" exists but some of it is not accessible or useable
Error in <TTreeFormula::DefinedVariable>: Class probably unavailable:GenEventInfoProduct
Error in <TTreeFormula::Compile>:  Part of the Variable "GenEvent.weight()" exists but some of it is not accessible or useable
Error in <TTreeFormula::DefinedVariable>: Class probably unavailable:GenEventInfoProduct
Error in <TTreeFormula::Compile>:  Part of the Variable "GenEvent.weight()" exists but some of it is not accessible or useable
Error in <TTreeFormula::DefinedVariable>: Class probably unavailable:GenEventInfoProduct
Error in <TTreeFormula::Compile>:  Part of the Variable "GenEvent.weight()" exists but some of it is not accessible or useable
Error in <TTreeFormula::DefinedVariable>: Class probably unavailable:GenEventInfoProduct
Error in <TTreeFormula::Compile>:  Part of the Variable "GenEvent.weight()" exists but some of it is not accessible or useable
Error in <TTreeFormula::DefinedVariable>: Class probably unavailable:GenEventInfoProduct
Error in <TTreeFormula::Compile>:  Part of the Variable "GenEvent.weight()" exists but some of it is not accessible or useable
Error in <TTreeFormula::DefinedVariable>: Class probably unavailable:GenEventInfoProduct
Error in <TTreeFormula::Compile>:  Part of the Variable "GenEvent.weight()" exists but some of it is not accessible or useable
Error in <TTreeFormula::DefinedVariable>: Class probably unavailable:GenEventInfoProduct
Error in <TTreeFormula::Compile>:  Part of the Variable "GenEvent.weight()" exists but some of it is not accessible or useable
Info in <TCanvas::SaveAs>: ROOT file output.root has been created

**Comment by covarell** [comment]
Ok, but does the canvas output.root make sense or is it empty?

**Comment by gomber** [comment]
It is empty :(

**Comment by gomber** [comment]
Any suggestions/comment?

**Comment by davidsheffield** [comment]
Maybe the output from GEN was a problem? I ran it for 20k events for EXO-RunIIWinter15GS-02815 and EXO-RunIIWinter15GS-02817 (I'm not sure if that is enough, there looks to still be a lot of noise). I didn't have any problem generating the plots. I've placed what I have in `~dsheffie/public/DMMonophoton/`. The commands to generate the samples are in the `.sh` files (it has a qcut of 20 GeV unless you change it). And I also placed the DJR plots from 20k events in `test-*.root` for q cuts of 20, 30, and 40 GeV.

**Comment by covarell** [comment]
Yes, then it looks like Bhawna ran out of space... These output files are really big.

**Comment by gomber** [comment]
Thanks David for checking. It looks like i ran out of space. Looking at your plots,  qcut 20 seems reasonable. What do you think?

**Comment by bendavid** [comment]
Can you remind me what xqcut is in the lhe generation?

**Comment by gomber** [comment]
xqcut is 10 geV.
________________________________

**Comment by gomber** [comment]
I think then our qcut is fine at 20 GeV. If so can we go ahead with production or is there something else?

**Comment by davidsheffield** [comment]
@bendavid or @covarell is this qcut OK?

**Pull request merged**
