### PR TITLE
add scram_arch and cmssw versions as parameters

### PR DESCRIPTION
**Pull request by perrozzi**
ongoing work, PR to let people start commenting in case

### CODE REVIEW

**Comment by perrozzi** [comment]
@bendavid what do you think?

**Comment by bendavid** [comment]
All this does is makes the release more easily configurable at gridpack generation time.  We rather wanted to modify the runtime scripts I thought.

**Comment by perrozzi** [comment]
indeed, getting there soon

**Comment by perrozzi** [comment]
this should be it https://github.com/cms-sw/genproductions/pull/1202/commits/e6cf46eaa1226d37965f3013c1cdab12cd29f991
unless we change also https://github.com/cms-sw/cmssw/blob/CMSSW_7_1_X/GeneratorInterface/LHEInterface/data/run_generic_tarball_cvmfs.sh 
right?

**Comment by perrozzi** [comment]
(need to source from cvmfs, of course...)

**Comment by perrozzi** [comment]
updated and in synch with https://github.com/cms-sw/genproductions/pull/1206

**Comment by kdlong** [comment]
One thing I don't understand, why is it necessary to specify CMSSW version and SCRAM_ARCH? Why wouldn't you always just take the scram_arch from the CMSSW version?

**Comment by perrozzi** [comment]
others might comment better than me, but afaik to avoid any problem you should always set SCRAM_ARCH first and then source CMSSW

**Comment by bendavid** [comment]
Also a given release may exist in different scram_archs, and one might explicitly like to override this in the future (eg if older releases are rebuilt/repackaged for a newer Linux distribution)

**Pull request merged**
