### PR TITLE
Early 13.6TeV cards for POGs

### PR DESCRIPTION
**Pull request by sihyunjeon**
Added cards for processes in 13.6 TeV
DY LO 01234j
DY NLO 012j
TTbar NLO 012j

Follow ups from discussion in MccM [1]

[1] https://docs.google.com/document/d/15ATgf2hexWZ3IY4pXrYYXBegVKu2GvPB4W4bdBGbBvo/edit

### CODE REVIEW

**Comment by sihyunjeon** [comment]
@agrohsje @menglu21
Just to provide you some context, several POGs asked if they can request 13.6TeV samples for DY process (added TTbar here without particular reasons). So I thought it would be a good opportunity to check the PdmV developments for Run3 sample preparations ONLY for gridpacks (the rest - fragment, validation, ... are up to the POGs).
So nothing serious! I think I just used the old cards that were used for DY and TTbar (and didn't really care too much about the customizations with PDG values here).

@jordan-martins @GurpreetSinghChahal @Saptaparna

**Comment by sihyunjeon** [comment]
Change the model files to diagCKM matrix cases

**Comment by Saptaparna** [comment]
Is there a ttbar@NLO with 3 jets sample? I'm fine with ttbar@NLO with 2 jets but to capture the maximal complexity, it might be worth to also test ttbar@NLO with 3 jets.

**Comment by menglu21** [comment]
Hi @sihyunjeon , 
just one small comment on the run card, "store_rwgt_info" should be added for the weight.

**Comment by menglu21** [comment]
> @menglu21 Ugh ok thanks! It actually is steered here but yeah better to have it in the cards
> 
> https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/Utilities/gridpack_helpers.sh#L67

i didn't notice this, so things changed a lot after i left MC contact :-)

**Comment by sihyunjeon** [comment]
Again tested NLO3j but based on the process rate, looks like >20days even with 30 cores. I think it's not really safe to push things in the system where reproducibility is limited too much. Let me merge this.

**Comment by agrohsje** [comment]
> > @menglu21 Ugh ok thanks! It actually is steered here but yeah better to have it in the cards
> > https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/Utilities/gridpack_helpers.sh#L67
> 
> i didn't notice this, so things changed a lot after i left MC contact :-) Then i'm fine with the cards

Hihi. I was so tired of checking this in MCM requests that I made sure people cannot escape. :-D

**Pull request merged**
