### PR TITLE
SUSY WJets_HT requests

### PR DESCRIPTION
**Pull request by alkaloge**

### CODE REVIEW

**Comment by bendavid** [comment]
Why are the drell yan cards being touched here?

**Comment by alkaloge** [comment]
git behaves strange - In principle there were some misspelled cards in the DY_600toInf directory which I "git rm" and then I "git add" the inclusive gridpack cards in a separate dir. Git reported this as renaming the "DYHT_600toInf" though.

**Comment by bendavid** [comment]
Ok, but git is reporting two completely new drell-yan cards.

**Comment by alkaloge** [comment]
yes, that is correct - these stand for the inclusive gridpack as I said. This is my structure

cards/production/13TeV/DYJets_HT_LO_MLM/DYJets_HT_mll50/DYJets_HT-100to200:
DY_HT-100to200_proc_card.dat  DY_HT-100to200_run_card.dat  DYJets_HT-100to200_proc_card.dat  DYJets_HT-100to200_run_card.dat

cards/production/13TeV/DYJets_HT_LO_MLM/DYJets_HT_mll50/DYJets_HT-200to400:
DY_HT-200to400_proc_card.dat  DY_HT-200to400_run_card.dat  DYJets_HT-200to400_proc_card.dat  DYJets_HT-200to400_run_card.dat

cards/production/13TeV/DYJets_HT_LO_MLM/DYJets_HT_mll50/DYJets_HT-400to600:
DY_HT-400to600_proc_card.dat  DY_HT-400to600_run_card.dat  DYJets_HT-400to600_proc_card.dat  DYJets_HT-400to600_run_card.dat

cards/production/13TeV/DYJets_HT_LO_MLM/DYJets_HT_mll50/DYJets_HT-600toInf:
DYJets_HT-600toInf_proc_card.dat  DYJets_HT-600toInf_run_card.dat

cards/production/13TeV/DYJets_HT_LO_MLM/DYJets_HT_mll50/DYJets_HT-incl:
DYJets_HT-incl_proc_card.dat  DYJets_HT-incl_run_card.dat

cards/production/13TeV/DYJets_HT_LO_MLM/DYJets_HT_mll50/DYJets_HT-ptZ150_600toInf:
DYJets_ptZ150_HT-600toInf_proc_card.dat  DYJets_ptZ150_HT-600toInf_run_card.dat

**Comment by bendavid** [comment]
ok, got it.

**Pull request merged**
