### PR TITLE
Added 2017 cards for several samples

### PR DESCRIPTION
**Pull request by wverbeke**
I added the updated 2017 cards for several samples

### CODE REVIEW

**Comment by efeyazgan** [comment]
please remove  p and j definitions.

Note that we are holding MLM for now until we finalize (in ~1 day) our decision on the pdfwgt parameter,

**Comment by efeyazgan** [comment]
Please change to
T = pdfwgt in the run cards
(following https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/4427/1.html)

**Comment by perrozzi** [comment]
I believe the main folder for these datacards should be
bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/

**Comment by wverbeke** [comment]
Indeed. Sorry for not paying attention to this. Maybe you could move the folders? Since I don't think there is a way to edit this pull request anymore.

**Comment by perrozzi** [comment]
can you please prepare a new PR?

**Comment by wverbeke** [comment]
Ok. So if I understand correctly you would want me to revert the previous PR and then make a new one?

**Comment by perrozzi** [comment]
you can simply use 
`git mv`
https://git-scm.com/docs/git-mv
and make a new PR

**Comment by wverbeke** [comment]
I created the new PR https://github.com/cms-sw/genproductions/pull/1404

**Pull request merged**
