### PR TITLE
ggF Higgs cards

### PR DESCRIPTION
**Pull request by pallabidas**
following the parameters from previous production: https://github.com/cms-sw/genproductions/tree/pre2017/bin/Powheg/production/V2/13TeV/Higgs/gg_H_quark-mass-effects_NNPDF30_13TeV with changed pdf, distinguishing from HZZ cards.

### CODE REVIEW

**Comment by efeyazgan** [comment]
I guess you should not commit .gitignore

**Comment by pallabidas** [comment]
Hi @efeyazgan I actually copied from the earlier commit which I changed from gg_H_* to gg_H_ZZ_*, gitignore was already there, so I put it in the new directory as well.

**Comment by efeyazgan** [comment]
please delete it

**Comment by pallabidas** [comment]
Hi @efeyazgan done.

**Comment by efeyazgan** [comment]
Probably last request: please remove the commented input lines:
#ndns1 131         ! pdf set for hadron 1 (mlm numbering)
#ndns2 131         ! pdf set for hadron 2 (mlm numbering)

**Comment by pallabidas** [comment]
Commented lines removed.

**Pull request merged**
