### PR TITLE
add stitched cards

### PR DESCRIPTION
**Pull request by menglu21**
add stitched cards for FxFx DY

### CODE REVIEW

**Comment by agrohsje** [comment]
Hi @menglu21. The PR looks good to me. Just one question: What is the motivation to check jet multiplicity stitching? Wouldn't make more sense to check ht or something?

**Comment by kdlong** [comment]
For reasons that are really unclear to me, the jet multiplicity stitching doesn't actually close perfectly with the inclusive, at least for DY 2017/8:

Z+jets 2016
http://kelong.web.cern.ch/kelong/PlottingResults/ZGen/NanoAOD/CompareNLOJetBinnedInclusive2016/

Z+jet 2017/2018. Left is uncorrected, right is adjusting the xsecs so that the spectrum ~agrees with inclusive
http://kelong.web.cern.ch/kelong/PlottingResults/ZGen/NanoAOD/CompareNLOJetBinnedInclusive2017/

W+jets inclusive 2016 vs. jet binned 2017/2018:
http://kelong.web.cern.ch/kelong/PlottingResults/WGen/NanoAOD/CompareJetBinned/plots/nJets.pdf

Here there is no inclusive 2017/2018 as far as I know, so the closure can't really be checked.

**Comment by agrohsje** [comment]
Hi Kenneth, 
do you mind adding the info to the known MC issues:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/MCKnownIssues .
 
Maybe we should arrange a chat with a few people to come up with a todo list and follow-up. 
Do you have the FxFx efficiencies  and cross sections at hand to post them as well? 

What if we have a chat at 2pm on Monday before GEN starting at 3pm? @menglu21 @gourangakole @qliphy @kdlong @smrenna @covarell would you be available?

**Comment by gourangakole** [comment]
I am available.

**Comment by covarell** [comment]
I am available too, could be a bit late because of a lecture ending at 1pm + lunch break   :-)

**Comment by qliphy** [comment]
+1

**Comment by menglu21** [comment]
Hi @agrohsje, 2pm is fine to me.

**Comment by smrenna** [comment]
I can be there.

**Comment by kdlong** [comment]
> Hi Kenneth,
> do you mind adding the info to the known MC issues:
> https://twiki.cern.ch/twiki/bin/viewauth/CMS/MCKnownIssues .

Yes, I haven't yet, but I will

> 
> Maybe we should arrange a chat with a few people to come up with a todo list and follow-up.
> Do you have the FxFx efficiencies and cross sections at hand to post them as well?
> 
> What if we have a chat at 2pm on Monday before GEN starting at 3pm? @menglu21 @gourangakole @qliphy @kdlong @smrenna @covarell would you be available?

Works for me. Could be of interest to @bendavid @AndreasAlbert also

**Comment by covarell** [comment]
Is the chat on the same zoom meeting?

**Comment by qliphy** [comment]
@covarell   Yes, Meeting ID:   862-966-725; PWD: 436;   https://cern.zoom.us/j/862966725

**Pull request merged**
