### PR TITLE
Add MG5 cards for generation of DY Jets mll=10-50 GeV for inclusive and 1, 2, 3, 4 Jets

### PR DESCRIPTION
**Pull request by anikiten**

### CODE REVIEW

**Comment by agrohsje** [comment]
@menglu21  @sihyunjeon Shouldn't we use the opportunity to sync settings. Which directories we want to use for validation/official production. In principle I would prefer not to duplicate things.

**Comment by agrohsje** [comment]
Let me also add @SanghyunKo.

**Comment by sihyunjeon** [comment]
@agrohsje Ahhh... yes I agree. And it would be totally nice to synchronise the settings with other common SM processes (#2714 for instance).
Maybe we can start with the cards in #2696 as a reference and make pull requests to the production cards?

**Comment by menglu21** [comment]
> @agrohsje Ahhh... yes I agree. And it would be totally nice to synchronise the settings with other common SM processes (#2714 for instance).
> Maybe we can start with the cards in #2696 as a reference and make pull requests to the production cards?

for the low mass DY, i have not added the pt-binned or jet-binned cards yet, i could add them now.

**Comment by agrohsje** [comment]
@menglu21 the yukawa of e and mu are 0, so only tau would contribute. i am fine with vetoing to speed up production. 
If your cards are otherwise in sync with @anikiten , should we merge the 2 pr's in a single one? 
@sihyunjeon We can also add a README to examples and stay that everything is in validation? 
suggest to continue the discussion here if we agree to merge:
https://github.com/cms-sw/genproductions/pull/2696 ?

**Comment by anikiten** [comment]
Hi,  settings are exactly the same as for officially produced already DY50 samples. I have just changed dilepton mass range to10-50. So I am wondering why do you discuss it. It was a proposal from my side to Alexandros from the very beginning.

**Comment by agrohsje** [comment]
"exactly the same as for officially produced already DY50 samples"
In fact, settings can be quite different. We found several problems in centrally produced samples and inconsistent settings. 
That's why we are discussing this now. We try to set up a single, consistent source. Right now there are tons of folders with even more cards. 
What was your proposal to Alexandros? If you have a different scope, please let me know. Which MC production do you target?

**Comment by sihyunjeon** [comment]
> @sihyunjeon We can also add a README to examples and stay that everything is in validation? suggest to continue the discussion here if we agree to merge: #2696 ?
@agrohsje Yes README would be nice.

**Comment by anikiten** [comment]
Sorry, we are talking about trivial DY+jets production which CMS is running for years.  Do you have a problem with DY + jets generation cards or not ?  I proposed to Alexandros that I re-use DY50Jets cards with just changing dilepton mass range and he fully agreed and Gouranga send me links to these cards and helping in request preparation. Everything was done and gridpacks tested. I do not understand why do you block this request with "general consideration" ! Please, consider my case, but not a "general one" and be practical. Did you have a problem with DY50Jets samples ? I will write Alexandros and Gurpreep

**Comment by kdlong** [comment]
In fact it's not trivial and we've had countless problems over the years...

**Comment by menglu21** [comment]
> Sorry, we are talking about trivial DY+jets production which CMS is running for years. Do you have a problem with DY + jets generation cards or not ? I proposed to Alexandros that I re-use DY50Jets cards with just changing dilepton mass range and he fully agreed and Gouranga send me links to these cards and helping in request preparation. Everything was done and gridpacks tested. I do not understand why do you block this request with "general consideration" ! Please, consider my case, but not a "general one" and be practical. Did you have a problem with DY50Jets samples ? I will write Alexandros and Gurpreep

Since these cards (not only DY) are always copied from previous place, but as the MG is keeping updating, and as Kenneth mentioned we keep finding issues, we want to have an overall sync on these cards, especially for DY/Wjets which need large number of events

**Comment by agrohsje** [comment]
> Sorry, we are talking about trivial DY+jets production which CMS is running for years.

Indeed CMS does and several analysis groups report serious discrepancies, because settings are wrong and not consistent. As 20UL is still in preparation, it is the right point in time to solve these problems and set up a single coherent source instead of having several different cards in genproductions/eos. 
This is the PR: https://github.com/cms-sw/genproductions/pull/2696 .

**Comment by anikiten** [comment]
Thank you for explanations.  I can only say that in our public analysis with 2016 data and MG5 DYJets 10-50 and 50 we have a very good agreement with data, HIG-16-017.  If MG5 has drastically changed since that time and does need an old cards revision I can understand it. Does it also affect PY8 settings for hadronization and showering of LHE MG5 files ? By the way, since I am a beginner for a such requests and gridpack preparation what does it mean "Pull request closed" ? Do you accept my request and my cards ?

**Comment by agrohsje** [comment]
Discrepancies are unfortunately also present in 2016 for DY production, see e.g. this talk : 
https://indico.cern.ch/event/841559/contributions/3547525/attachments/1901143/3139399/2019-08-28_vht_comparison_forhn.pdf
In which MC campaign you want to use your cards? For UL production I would suggest to wait for what we will centrally produce based on this PR :
https://github.com/cms-sw/genproductions/pull/2736

**Comment by anikiten** [comment]
We need MG5 LO DY10-50 and DY50 for UL.  As for our 2016 analysis we need samples 1J, 2J, 3J (exclusive) and 4J inclusive. We add them together at analysis level. We also need inclusive DYJets10-50 and 50.  It is the same samples we used in our 8 TeV and 13 TeV 2016 public analysis. But this time it will be UL. Thanks !  Do I need again to produce and test gridpacks by myself with your cards or you do it ?

**Comment by agrohsje** [comment]
We will discuss and handle preparation of these requests.

**Comment by anikiten** [comment]
I had a look at the talk you pointed me to. It explains the difference between 2016 and 2017 V MCs by pdfwgt settings. Is it a setting for ME-PS matching at PY8 level, right ?  Discrepancy with 2016 data is anyway when it set to F, but  I must say the phase space for data selections is rather exotic (very hard: pTj > 100 GeV and so on). We have a publications on much more inclusive DY selections in SMP group which shows a good agreement with 2016 data. I will double check. We will check in our analysis pTZ data/MC 2016 and let you know.

**Comment by anikiten** [comment]
OK, thanks !
________________________________

**Comment by anikiten** [comment]
Hi.  What's about status of our DY10-50 request ?  We are at the point that we already ready to analyse it and compare with UL2017 data.

**Comment by agrohsje** [comment]
currently producing gridpacks.

**Pull request closed without merging**
