### PR TITLE
configure seed for powheg stages 2 and 3

### PR DESCRIPTION
**Pull request by hroskes**
- seeds for the 10 jobs start from the one provided on the command line
- fix some headers to use the right python

if @covarell agrees

### CODE REVIEW

**Comment by covarell** [comment]
Can you please be more specific? 
- Why is the current pwgseeds.dat file (numbers from 1 to njobs) not correct? AFAIK it is sufficient that the numbers are different from each other.
- What is "the right python"? If you type "python run_pwg.py" rather than "./run_pwg.py" (as it is advertized in the Twiki) doesn't it select the python version coming from cmsenv?
@yuanchao

**Comment by yuanchao** [comment]
Indeed as we advertized in twiki that "python run_pwg.py", it should not be a problem. Though I think it's ok to point to the python specified in the environment.
As to the seeds, I think we should stick to the current pwgseeds.dat.

**Comment by hroskes** [comment]
Hi, is there any obstacle to merging?

**Comment by qliphy** [comment]
@covarell @yuanchao    It seems ready to be merged, right?

**Comment by covarell** [comment]
Ok for me

**Pull request merged**
