### PR TITLE
Add cards for X to AA to 4 Photons

### PR DESCRIPTION
**Pull request by SClarkPhysics**
Adding the cards for our process X -> aa -> 4 photons in the mg26x branch. Cards are organized in one directory for a single mass point and one directory of template cards for creating gridpacks of different masses.

### CODE REVIEW

**Comment by qliphy** [comment]
+1 @agrohsje

**Comment by SClarkPhysics** [comment]
Any update on getting this pull request approved? Would like to start using this to produce gridpacks. Let me know of anything I can do. Thanks!

**Comment by agrohsje** [comment]
What is the reason to have JetMatching:qCutME = 35 in the fragment ?

**Comment by SClarkPhysics** [comment]
Meant to remove that line, it is now removed in the latest commit.

**Comment by agrohsje** [comment]
Thanks. To add QED=0 has no impact here. Will merge!

**Pull request merged**
