### PR TITLE
cards for VBF HH production at 13.6 TeV

### PR DESCRIPTION
**Pull request by fabio-mon**
Cards copied from the corresponding Run 2 folders (bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/VBF_HH/) with the only change in the beam energy which is set to 6800.

### CODE REVIEW

**Comment by Saptaparna** [comment]
@fabio-mon are the setups identical except for the variations in the couplings?

**Comment by fabio-mon** [comment]
> @fabio-mon are the setups identical except for the variations in the couplings?

yes

**Comment by Saptaparna** [comment]
@fabio-mon can you please clean up the PR then? So, we can only check one set of cards.

**Comment by fabio-mon** [comment]
The cards corresponding to the different couplings are now replaced by a single template card + a script to edit it

**Pull request merged**
