### PR TITLE
nonthermal dark matter cards

### PR DESCRIPTION
**Pull request by sundleeb**

### CODE REVIEW

**Comment by sundleeb** [comment]
I am looking forward for approval of my model's production cards. thanks.

**Comment by perrozzi** [comment]
hi, just to check: the pdf seem to be 5F. is the model 5F or 4F?

**Comment by sundleeb** [comment]
hi , I am sorry but I couldn't understand what 5F or 4F means. Please explain. Thanks

**Comment by perrozzi** [comment]
the PDF can use massless bottom in the proton (5F) or just gluon and massive bottoms through gluon splitting (4F). I wonder if your model is 4F or 5F, if you can't answer please check with whoever provided the model

**Comment by sundleeb** [comment]
Hi , my apologies for late reply as I didn't know the answer and had to ask author. According to him although the contribution from bottom quark will be small, use of 5F for PDF seems to be correct. The pdf setup in gridpack is correct and does not need any modification. thanks

**Comment by sundleeb** [comment]
I have cleaned up all the proc cards

**Pull request merged**
