### PR TITLE
Data Cards for h(125)_aa_2m2b Analysis

### PR DESCRIPTION
**Pull request by aashaqshah**

### CODE REVIEW

**Comment by qliphy** [comment]
Please clean the banner in the proc card:

https://twiki.cern.ch/twiki/bin/view/CMS/Moriond18MC#Checks_to_the_datacards_BEFORE_T

Please also remove, e.g.

https://github.com/aashaqshah/genproductions/blob/0b669d65836ecbf1d4481efbcb3ee0fafda97bde/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/higgs_aa_2mu2b/ggH_aa/ggh01_M125_Toa01a01_M15_Tomumubb/ggh01_M125_Toa01a01_M15_Tomumubb_run_card.dat#L272-L283

Moreover, please don't upload all fragments. Just an example one together with the script to make others.

**Comment by efeyazgan** [comment]
Hi @aashaqshah are you planning to follow the suggestion from @qliphy or shall we close the PR? thanks.

**Comment by aashaqshah** [comment]
Hi @efeyazgan , I have implemented suggestions and have updated the cards. However, in ggH_Za_2mu2b which include five new samples for h->Za->.2mu2b process is more urgent. Also, the model to be used in the process should be https://github.com/aashaqshah/NMSSMHET.git. The original model produces off-shell Z-bosons and new model have been written by the author on the basis of our request and produces on-shall Z's.  (The updated model is not yet at https://cms-project-generators.web.cern.ch/cms-project-generators/. ) The latter suggestion was provided by Higgs conveners.

**Comment by aashaqshah** [comment]
Essentially, our group modified gridpack_generation.sh the script when we were looking on-shall z bosons and the modification worked.
#modification is
 #wget --no-verbose --no-check-certificate https://cms-project-generators.web.cern.ch/cms-project-generators/$model      
   wget --no-verbose --no-check-certificate https://github.com/aashaqshah/NMSSMHET/raw/master/NMSSMHET_UFO.zip

Please let us know if it would be possible to use the model as placed on the GitHub link https://github.com/aashaqshah/NMSSMHET.git instead of the model which is int extra-model cards (which is actually not updated). Thanks a lot!

**Comment by qliphy** [comment]
The model file has been uploaded.  But note you still need an extra-model card.

Moreover, please take into account the other comments as mentioned above:

**"remove, e.g.

https://github.com/aashaqshah/genproductions/blob/0b669d65836ecbf1d4481efbcb3ee0fafda97bde/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/higgs_aa_2mu2b/ggH_aa/ggh01_M125_Toa01a01_M15_Tomumubb/ggh01_M125_Toa01a01_M15_Tomumubb_run_card.dat#L272-L283

Moreover, please don't upload all fragments. Just an example one together with the script to make others."**

**Comment by aashaqshah** [comment]
Hi, thanks for the quick reply and sorry if I was not very clear in my last comment.
Please take note of the following things:

1.  Please remove this **mass point =15 sample** mass point, i.e. the directory: 
**higgs_aa_2mu2b/ggH_aa/ggh01_M125_Toa01a01_M15_Tomumubb**. This is no more needed. Other mass points 20 to 60 GeV in steps of 5 are only needed.

2. wehave already extra model directory here:
        genproductions/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/higgs_aa_2mu2b/ggH_aa/ggh01_M125_Toa01a01_M20_Tomumubb/ggh01_M125_Toa01a01_M20_Tomumubb_extramodels.dat
      
and this is fine for directories **ggH**_aa and **vbf_aa** . i.e. for samples **h->aa->2mu2b**

3. The model problem is for **ggH_Za_2mu2b** directory i.e, for samples **h->Za->2mu2b** case where the imported model **NMSSMHET_UFO.zip ** is producing off-shall Z bosons. To avoid the off-shell Z production, normally customizecards are modified by fixing the **width** and this does not work for the current model. Therefore, we have got the model re-written from the original author of the model where we can fix the **Briet Wigner (BW) width** by extra cards. And this model is not available at **[1]** where Madgraph imports models https://cms-project-generators.web.cern.ch/cms-project-generators/.

The model has to be imported locally when grip pack will be generated.  In case you need already generated grid packs with this model, let me know. I shall be able to provide you.

Hope this clarifies why and need to use the model [2].

[1] https://cms-project-generators.web.cern.ch/cms-project-generators/
[2] https://github.com/aashaqshah/NMSSMHET.git


Thanks once again.

**Comment by aashaqshah** [comment]
Hi all,

Can I please hear any update on this. I would be really thankful if these samples are done!

Many thanks.


Best,
- Aashaq

**Comment by qliphy** [comment]
>"Moreover, please don't upload all fragments. Just an example one together with the script to make >others."

You are still uploading 82 cards?  Please take into account the above comment.

>we have got the model re-written from the original author of the model where we can fix the Briet >Wigner (BW) width by extra cards

Can you share this modified model?  You can rename it and we can add it to https://cms-project-generators.web.cern.ch/cms-project-generators/

**Comment by aashaqshah** [comment]
OMG!
I can't believe, its pity! They are still not available.

I don't know how many times I would have to remind you about it.
In my previous comments also, I have already told that I have two analysis:
1. h->aa for which no model is required. At least I would have expected signal samples ready. Atleast one, I could have validated my own.
2. h-Za for which the model has been rewritten. 

And to your comment, "Can you share this modified model? You can rename it and we can add it to https://cms-project-generators.web.cern.ch/cms-project-generators/", I have already uploaded it to my GitHub link but had I been the permission to upload it to the link you are mentioning, then why would I upload it to my own GitHub. Isn't it logical? 

Also if you go back to previous comments, they have said, "The model file has been uploaded"


It is clear that I can't upload the model, Because of this analysis is struggling from last one year to get to the public.

I don't know what you want me to do now finally. But if you have problems in model uploading or so, how about If I share my grid packs and those can be directly used by MC team.

**Comment by qliphy** [comment]
Yes, the model has been uploaded in Feb 
https://cms-project-generators.web.cern.ch/cms-project-generators/NMSSMHET_UFO.zip
If this is the model you want, then it is ok.

But it seems that you have not followed previous comment
"Moreover, please don't upload all fragments. Just an example one together with the script to make others."

For example, the two cards for different parameters are the same.  You don't need to upload all of them, just some example cards are enough. Otherwise too many cards will slow down git.

https://raw.githubusercontent.com/cms-sw/genproductions/d644ed6b46553e70ca06279150ee757feefb0f0a/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/higgs_aa_2mu2b/ggH_Za_2mu2b/ggh01_M125_ToZa01_M91M15_Tomumubb/ggh01_M125_ToZa01_M91M15_Tomumubb_run_card.dat

https://raw.githubusercontent.com/cms-sw/genproductions/d644ed6b46553e70ca06279150ee757feefb0f0a/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/higgs_aa_2mu2b/ggH_Za_2mu2b/ggh01_M125_ToZa01_M91M12_Tomumubb/ggh01_M125_ToZa01_M91M12_Tomumubb_run_card.dat

**Comment by aashaqshah** [comment]
Hi @qliphy , 

I just got busy in between, can you please let me know what sort of script should it be, C++, Python etc.?

I suppose people might have already done it, so rather than starting from scratch, if you could share it as an example, I will modify and upload it, it could save some of my time. Other way around is also fine.
Thanks.


Best,

**Comment by qliphy** [comment]
You can find some examples e.g.  in the PR below:

https://github.com/cms-sw/genproductions/pull/2198
https://github.com/cms-sw/genproductions/pull/2213

**Comment by aashaqshah** [comment]
Hi, 
Cards have been updated with scripts, please let me know in case it is not still OK.
thanks.

Best,
-- Aashaq

**Comment by qliphy** [comment]
Thanks!  Now you have the scripts, you can just keep one example set of cards and remove most of the others.  For example:   just keep one from ggh01_M125_ToZa01_M91M15 and ggh01_M125_ToZa01_M91M20

**Comment by qliphy** [comment]
Please also remove backup files (*~)

And remove the SysCalc parameters *_sys block that start with the following comments, for example:
https://github.com/cms-sw/genproductions/blob/c56ff4b814bad096eec76b79b1e74aa58966ca56/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/mumubb_final_state/ggF_aa/ggh01_M125_Toa01a01_Tomumubb_M/ggh01_M125_Toa01a01_Tomumubb_M_run_card.dat#L253-L260

**Comment by aashaqshah** [comment]
Hi,
I have deleted all the superfluous files and have kept one example card set with a given script for each category (h->aa with ggF and vbf, and h->Za with only ggF). 


Best,

**Comment by qliphy** [comment]
But I still find file like this which should also be removed:
https://github.com/cms-sw/genproductions/blob/c56ff4b814bad096eec76b79b1e74aa58966ca56/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/mumubb_final_state/ggF_aa/ggh01_M125_Toa01a01_Tomumubb_M/ggh01_M125_Toa01a01_Tomumubb_M_proc_card.dat%7E

**Comment by qliphy** [comment]
And please update the run_card.dat files as mentioned above, by removing the SysCalc parameters, as you can see from GEN twiki:
https://twiki.cern.ch/twiki/bin/view/CMS/Fall18Repack

**Comment by qliphy** [comment]
Thanks!  The last thing is to remove in run_card those SysCalc parameters, as mentioned above:

https://github.com/cms-sw/genproductions/blob/22ea09ee4a0207ff7c7ae0b3c41cf881f08d7b08/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/mumubb_final_state/ggF_Za/ggh01_M125_ToZa01_Tomumubb_M91M/ggh01_M125_ToZa01_Tomumubb_M91M_run_card.dat#L254-L262

https://github.com/cms-sw/genproductions/blob/22ea09ee4a0207ff7c7ae0b3c41cf881f08d7b08/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/mumubb_final_state/ggF_aa/ggh01_M125_Toa01a01_Tomumubb_M/ggh01_M125_Toa01a01_Tomumubb_M_run_card.dat#L253-L260

https://github.com/cms-sw/genproductions/blob/22ea09ee4a0207ff7c7ae0b3c41cf881f08d7b08/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/mumubb_final_state/vbf_aa/vbfh01_M125_Toa01a01_Tomumubb_M/vbfh01_M125_Toa01a01_Tomumubb_M_run_card.dat#L252-L261

**Comment by aashaqshah** [comment]
Hey,
All done, please check.

Thanks.

**Comment by aashaqshah** [comment]
Hi Qiang,
Is there any way I can monitor the status of these samples.  Since these were for 2017 data, what if I have to submit a separate request for  2018 data (for whole Run-II).
Thank you!

Best,
Aashaq

**Comment by qliphy** [comment]
@aashaqshah  You can use pmp [1] or ask help from MC Contacts

[1] https://indico.cern.ch/event/807778/

**Pull request merged**
