### PR TITLE
adding JHUGen bare

### PR DESCRIPTION
**Pull request by violatingcp**
Scripts to generate simplified model dark matter with JHUGen. However can easily be adapted for JHUGen bare production. Additional scripts have been added for dark matter scans.

### CODE REVIEW

**Comment by covarell** [comment]
Instructions for testing this must be provided, please

**Comment by violatingcp** [comment]
To run 
./install.py 

For information on the options
./install.py --help

A specific set of parameters (DM mass 50 GeV and mediator of 500) : 
./install.py --carddir cards/ScalarVH --name ScalarVH --q 8nh --dmrange 50 --medrange 500

**Comment by covarell** [comment]
Tested for one process, compiling appears OK.

However, when I try to run events:

mkdir test
cd test
cp ../JHUGen_ScalarWH_500_50.tgz .
tar -zxvf JHUGen_ScalarWH_500_50.tgz
bash
./runcmsgrid.sh 100 1893 2

I get the following errors:
[...]
./runcmsgrid.sh: line 1: 1: command not found
./runcmsgrid.sh: line 1: 2c#!/bin/bash: No such file or directory    (indeed first line in the script seems garbled)
[...]
mv: cannot stat `cmsgrid_final.lhe': No such file or directory

and no lhe is produced in the directory.

Also small questions:
- can you add a simple command to the python script so that the tgz is copied into the main directory (and not in XXX_JHUGen)
- Why NNPDF3.0 data is copied from an external source (mi.infn.it) while it is already included in JHUGenerator/pdfs/? Also notice that we will soon move to JHUGen 5.3 where pdfs will not be copied brutally anymore but taken from LHAPDF (will require small updates).

**Comment by covarell** [comment]
The lhe file in JHUGen_XXX_medmass_mass/cmsgrid.lhe ends in:
</LesHo
rather than
</LesHouchesEvents>

**Comment by violatingcp** [comment]
Hmm, I do not have these errors. Can you point me to the gridpack. Maybe we
have different ones.

Phil

**Comment by covarell** [comment]
Hi, I put two examples in:
/afs/cern.ch/user/c/covarell/public/forPhil

gridpacks have been created in CMSSW_7_1_15_patch1 (the one used in Run2 official production) using e.g.:
./install.py --carddir cards/ScalarZH --name ScalarZH --q 8nh --dmrange 50 --medrange 500
(same for WH)

**Comment by violatingcp** [comment]
This is different ot hte ones I have. There was a buggy version for a short
period last week. Can we recopy all of the g-packs?

They live here :

eos ls eos/cms/store/cmst3/user/pharris/gen/

On Tue, May 12, 2015 at 1:46 PM, Roberto Covarelli <notifications@github.com

**Comment by covarell** [comment]
Sorry I do not understand.
I need to test the gridpack production in order to merge your changes in genproductions, not to test gridpacks which are already produced. Are you saying I missed later commits when I checked out the code?

**Comment by violatingcp** [comment]
ah sorry, you made the gridpacks? Ok. then I can update




On Tue, May 12, 2015 at 1:54 PM, Roberto Covarelli <notifications@github.com

**Comment by covarell** [comment]
Yes, please.

Stuff in this area of genproductions are indeed supposed to be used by end-users to make their own gridpacks.

When the DM stuff is working I can modify this in order to make of general use for JHUGen

**Comment by violatingcp** [comment]
i fixed it two days ago
have a look.
Le 14 mai 2015 14:18, "Roberto Covarelli" <notifications@github.com> a
écrit :

**Comment by covarell** [comment]
I got your latest commit thanks.

Still when I run in CMSSW_7_1_15_patch1 (which is the one used in production) I get correct files out of JHUGen, but then when the files are edited by boltdmdec they are corrupted in the end.

in bash I do:
$ cmsStage /store/cmst3/user/pharris/gen/JHUGen_ScalarZH_300_50.tgz .
$ tar -zxvf JHUGen_ScalarZH_300_50.tgz
...
[ here I comment the line "rm ${file}" from runcmsgrid.sh to compare the two files ]
...
$ ./runcmsgrid.sh 100 348 1
$ tail -2 JHUGen_ScalarZH_300_50/Out.lhe
leftangle /event rightangle
leftangle /LesHouchesEvents rightangle
$ tail -2 cmsgrid_final.lhe 
leftangle /event rightangle
leftangle /LesHo

**Comment by covarell** [comment]
ping

**Comment by violatingcp** [comment]
Ok should be fixed. Updated the fortran code in boltdmdec

On Tue, May 19, 2015 at 9:08 AM, Roberto Covarelli <notifications@github.com

**Pull request merged**
