### PR TITLE
Heavy ChargedHiggs Hp to tb 14 mass points

### PR DESCRIPTION
**Pull request by chayanit**
Similar as existing ChargedHiggs_Heavy_M* cards but these ones charged higgs decays to tb instead of taunu

### CODE REVIEW

**Comment by covarell** [comment]
Are the files named ChargedHiggs_heavy (with no mass suffix) added by mistake? They seem to have incorrect syntax (mhc set in the proc_card, a leftover "output"...). Others seem fine

**Comment by chayanit** [comment]
Hi Roberto,
Indeed, the one without mass suffix is added by mistake. Should I re-commmit and pull request again or you can merge the rest? 

Thanks in advance.

Best,
Chayanit

**Comment by covarell** [comment]
Not possible, sorry, you need a new commit

**Comment by chayanit** [comment]
Hi again,

OK. I will close this one and commit again :-) thanks!

Chayanit

**Pull request closed without merging**
