### PR TITLE
upload cards for Dim-6 operator: Cw

### PR DESCRIPTION
**Pull request by freejiebao**
For SMEFT study, upload cards for one of Dim-6 operators: Cw.  To simulate SM component, linear term, quadatic term independently.

### CODE REVIEW

**Comment by agrohsje** [comment]
The model is 5F scheme, but 320900 NNPDF31_nnlo_as_0118_nf_4. 
For 2017 samples, me recommend to use the following settings: 
lhapdf = pdlabel ! PDF set
 $DEFAULT_PDF_SETS = lhaid
 $DEFAULT_PDF_MEMBERS  = reweight_PDF
I would add NP=0 to the SM process card to be more explicit. 
Which cuts you want to apply? Only invariant jet mass above 100 GeV?

**Comment by qliphy** [comment]
@freejiebao  @hn-cms-eft
Has this model (SMEFTsim_A_U35_MwScheme_UFO_v2.1.tar.gz) been uploaded to [Generator repository](https://twiki.cern.ch/twiki/bin/view/CMS/GeneratorWebRepo)?
Can you also give the official link to the package, or have you done some customization?

**Comment by freejiebao** [comment]
> The model is 5F scheme, but 320900 NNPDF31_nnlo_as_0118_nf_4.
> For 2017 samples, me recommend to use the following settings:
> lhapdf = pdlabel ! PDF set
> $DEFAULT_PDF_SETS = lhaid
> $DEFAULT_PDF_MEMBERS = reweight_PDF
> I would add NP=0 to the SM process card to be more explicit.
> Which cuts you want to apply? Only invariant jet mass above 100 GeV?

@agrohsje 
I have updated the pdf settings. For the cuts I will keep them same as the official sample.

**Comment by freejiebao** [comment]
> @freejiebao
> Has this model (SMEFTsim_A_U35_MwScheme_UFO_v2.1.tar.gz) been uploaded to [Generator repository](https://twiki.cern.ch/twiki/bin/view/CMS/GeneratorWebRepo)?
> Can you also give the official link to the package, or have you done some customization?

@qliphy 
No, the model haven't been uploaded to  [Generator repository](https://twiki.cern.ch/twiki/bin/view/CMS/GeneratorWebRepo).
The official package could be found [here](https://feynrules.irmp.ucl.ac.be/attachment/wiki/SMEFT/SMEFTsim_A_U35_MwScheme_UFO_v2.1.tar.gz).
But I need other restrict cards to speedup the event generationin. So I attached those cards in http://stash.osgconnect.net/+jiexiao/SMEFTsim_A_U35_MwScheme_UFO_v2.1.tar.gz , please let me know can we use this one?

**Comment by qliphy** [comment]
@agrohsje  and others may comment more on the model file,  you may also ask at 
https://hypernews.cern.ch/HyperNews/CMS/get/eft.html

**Comment by agrohsje** [comment]
Dear all,
for now I wouldn't mind adding this one:
http://stash.osgconnect.net/+jiexiao/SMEFTsim_A_U35_MwScheme_UFO_v2.1.tar.gz
We are still not at the point where we of common standards. @qliphy Would that be ok with you?
Cheers, Alexander.

**Comment by qliphy** [comment]
@freejiebao   http://stash.osgconnect.net/+jiexiao/SMEFTsim_A_U35_MwScheme_UFO_v2.1.tar.gz  has been uploaded to [Generator repository](https://cms-project-generators.web.cern.ch/cms-project-generators/?C=M;O=A)

Please note there have already some other SMEFT model files:

[   ] SMEFTsim_A_general_alphaScheme_UFO_v2.tar.gz                      25-Oct-2019 21:14  1.3M  
[   ] SMEFTsim_A_general_MwScheme_UFO_v2.tar.gz                         25-Oct-2019 21:18  533K  
[   ] SMEFT_alpha_UFO.tar.gz                                            25-Oct-2019 21:22  1.1M  
[   ] SMEFT_mW_UFO.tar.gz                                               25-Oct-2019 21:24  765K

**Pull request merged**
