### PR TITLE
update PDF setting in WJetsToLNu cards

### PR DESCRIPTION
**Pull request by harrypuuter**
This is an update of the run Cards for WJetsToLNu according to the recommended PDF settings mentioned in https://twiki.cern.ch/twiki/bin/viewauth/CMS/QuickGuideMadGraph5aMCatNLO#PDF_Choice_for_2017_production

### CODE REVIEW

**Comment by qliphy** [comment]
please change pdfwgt to F,  as you can find from recent discussions

https://hypernews.cern.ch/HyperNews/CMS/get/generators/4492/1/1/1.html

**Comment by qliphy** [comment]
One more thing, it is better to change from the indirect production e.g. "“generate p p > w+, w+ >ell+ vl"  to direct production syntax "generate p p > ell+ vl" 
https://indico.cern.ch/event/781231/contributions/3263950/attachments/1795337/2926551/2019PPD-SUSY-GEN.pdf

**Comment by harrypuuter** [comment]
I am a bit confused for the processes with jets should it then be 
```
add process p p > j ell+ vl $$ t t~ h @1
add process p p > j j ell+ vl $$ t t~ h @2
add process p p > j j j ell+ vl $$ t t~ h @3
add process p p > j j j j ell+ vl $$ t t~ h @4

```
or do those stay unchanged like before ?

**Comment by qliphy** [comment]
something like below:

generate p p > ell+ vl $$ t t~ h @0
add process p p > j ell+ vl  $$ t t~ h @1
add process p p > j j ell+ vl $$ t t~ h @2
add process p p > j j j ell+ vl $$ t t~ h @3
add process p p > j j j j ell+ vl $$ t t~ h @4

add process p p > ell- vl~ $$ t t~ h @5
add process p p > j ell- vl~ $$ t t~ h @6
add process p p > j j ell- vl~ $$ t t~ h @7
add process p p > j j j ell- vl~ $$ t t~ h @8
add process p p > j j j j ell- vl~ $$ t t~ h @9

**Pull request merged**
