### PR TITLE
New Analysis

### PR DESCRIPTION
**Pull request by osherson**
Dear GEN Conveners,

I've uploaded the cards for a new signal being considered in the B2G PAG: A heavy X decaying to two lighter a particles going to 2 bs each. One thing I am unclear on is where to upload my actual Madgraph model?

Cheers,
- Marc

### CODE REVIEW

**Comment by qliphy** [comment]
Please contact relevant MC Contact for uploading model.

About madspin card, please follow  
https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/cards/examples/wplustest_4f_NLO/wplustest_4f_NLO_madspin_card.dat
and add
set ms_dir ./madspingrid
set max_running_process 1

And above all, we don't recommend to use mg26X yet.   Please switch to 242, and adjust your cards.

**Comment by qliphy** [comment]
We use gridpack to produce LHE and then shower them with Pythia8 in CMSSW.

**Comment by osherson** [comment]
I have made the changes recommended, and would like to renew this pull request.
Thanks,
- Marc

**Comment by efeyazgan** [comment]
Could you please make this PR to master? thanks.

**Comment by agrohsje** [comment]
@osherson As nothing happened for 6 months: Can we close this pull request ?

**Comment by osherson** [comment]
Hi, after some modification to the template for creating new gridpacks, we are uploading a new version for a pull.
Please let us know if anything else needs to change. This is meant to be in the mg26x branch which is stable for our analysis.
- Marc

**Comment by osherson** [comment]
Just added a few changes to our templates, and looking to pull to the cms-sw mg26x branch. Please let me know if you have further questions.

**Comment by qliphy** [comment]
Is the process a LO MLM one from loop induced, or NLO FxFx?
If it is the former, you need to set pdfwgt to F.
If it is the latter, ickkw should be 3, and the run_card.dat should be a NLO one.

**Comment by osherson** [comment]
LO MLM from a loop, I'll set pdfwgt to F, thanks,
- Marc

**Pull request merged**
