### PR TITLE
Allow jobs to read PDF sets directly from cvmfs

### PR DESCRIPTION
**Pull request by khurtado**
This pull request fixes the `cluster_local_path` in madgraph.
Just like other settings, `set cluster_local_path <value>` doesn't work, so I had to workaround that by directly setting that into the configuration. This setting is used twice: during the code-generation step, some fortran templates are modified according to this value... then it is use in the integrate step too. The first part failed because our cvmfs paths are too long in string, so I had to fix that too.

I tested on CMS Connect with the `wplustest_4f_NLO` gridpack and worked fine. Haven't tested further.

This is related to #1223

### CODE REVIEW

**Comment by perrozzi** [comment]
@kdlong I meant ready to merge this before #1243 unless there are other comments

**Comment by kdlong** [comment]
Thanks @khurtado! @perrozzi there's no reason it couldn't be merged before  #1243. Let me test it and get back to you.

**Comment by kdlong** [comment]
Currently testing with #1243 and it seems to be working. However, with all these PDF sets the jobs seem to be taking quite a bit longer at NLO and haven't yet finished.

**Comment by kdlong** [comment]
I confirm that this is working with the full list of PDF sets. Looks ready to merge to me.

**Pull request merged**
