### PR TITLE
Upgrade to MG 265

### PR DESCRIPTION
**Pull request by lviliani**
Upgrade of the genproduction scripts to MG 265.
Update patches and remove the ones that are not needed anymore.
No issues found testing a couple of LO and NLO processes locally and with condor.
Need to test the submission with CMS connect.

### CODE REVIEW

**Comment by qliphy** [comment]
Thanks Lorenzo. This is an important step to MG265.  Let's start doing more checks.

@Saptaparna @soarnsoar @AndreasAlbert @kdlong @covarell @agrohsje @efeyazgan @minerva1993

**Comment by soarnsoar** [comment]
Hi, I submit some DY physics processes  at cms-connect.
- DY LO 012j with pdfwgt ==T / F
- DY LO 01234j with pdfwgt == T/F
- DY NLO 012j 

I have a question on submission configuration for cms connect.

I set "DESIRED_SITE" in 'submit_cmsconnect_gridpack_generation.sh' to US Tier2 


+DESIRED_Sites="T2_US_MIT,T2_US_Florida,T2_US_Purdue,T2_US_UCSD,T2_US_Vanderbilt,T2_US_Wisconsin,T2_US_Caltech,T2_US_Nebraska,T3_US_Baylor,T3_US_Colorado,T3_US_Cornell,T3_US_FIT,T3_US_FIU,T3_US_NotreDame,T3_US_Omaha_Long,T3_US_OSU,T3_US_PuertoRico,T3_US_Rutgers,T3_US_TAMU,T3_US_TTU,T3_US_UCD,T3_US_UCR,T3_US_UCSB,T3_US_UMD,T3_US_UMiss"

The list is from
https://ci-connect.atlassian.net/wiki/spaces/CMS/pages/22609953/Selecting+Sites
.

Also, I comment out "proxy-watcher -remove " to prevent loosing proxy.


Is this setting fine? 

I want to set the site list as safe as possible because whole gridpack generation can be failed even if only one subjob is failed.( Even one of the sites in the list doesn't respond, all the others jobs will be useless.)


If there's anything wrong, please let me know.

Best,

Junho

**Comment by lviliani** [comment]
Thanks a lot @soarnsoar for taking care of this.

I think it would be better first to test the submit_cmsconnect_gridpack_generation.sh script as it is, without making any changes.
In case you find problems with specific sites we can mask them, but I haven't seen this kind of issue before.

'proxy-watcher  -remove' should remove the proxy-watcher only when your task is finished, so it shouldn't give any problem, right? Or are you experiencing some problems with the proxy?

**Comment by soarnsoar** [comment]
Hi, @lviliani . 

Let me explain why I commented out 'proxy-watcher -remove' first. I submitted several jobs at the same time. Let's think about the case 'proxy-watcher -remove' exists in the submission script.

When one of the job is done, the finished job will remove all proxy-watchers. So, other jobs which are still running will be lost.

About the site selection, do you know simple way to trace which site makes problem? When I ran dy01234j LO gridpack generation, which have large number of subprocesses, I failed the jobs because some subjobs didn't respond within Ntrial(maybe 30 times). When I selected only some working sites I can produce gridpacks. 

As far as I know @minerva1993 has also exprienced the same thing.


Best,

Junho

**Comment by lviliani** [comment]
Ok, I didn't realize there were these problems with the proxy-watcher. Maybe @khurtado has some insights on this?

About the sites that are giving troubles, one way to trace them could be looking at the CMS Dashboard.

**Comment by Saptaparna** [comment]
Thank you for making the PR @lviliani and thank you for getting the ball rolling on this @soarnsoar! A couple of questions/comments:

-- do we have to make the +4 jet gridpacks or can we start with +2 jet gridpacks (@LO MLM) and +1jet gridpack (@NLO FxFx )? 

-- can we also try to submit samples via lxplus condor (using tmux to deal with issues with terminal)?

**Comment by khurtado** [comment]
@soarnsoar @lviliani 

The proxy-watcher has that problem indeed, but it should be harmless. As its name suggests, this is just a watcher... it doesn't create or destroy proxies, but rather... it sends email notifications to the user when the proxy is about to expire. Even if all proxy-watchers are removed, jobs should be unaffected and other gridpack production runs should continue normally (unless the proxy expires, of course).

Regarding looking into sites that failed, here are some ES dashboard plots that can be helpful.
Note, you can use the filter option in the first dashboard in order to constrain results to a specific gridpack card. All card names are shown in the second dashboard plot. These are all gridpack jobs that didn't finish with exit code = 0.

Failed gridpack jobs per Site
https://es-cms.cern.ch/kibana/goto/eb50cb1e42f9e2968923c9f34394a91b

Failed gridpack jobs per card name
https://es-cms.cern.ch/kibana/goto/ebf6d8dad6d62b162594869d9302e456

**Comment by soarnsoar** [comment]
@khurtado Thank you so much! These are what I want :) It's much better than CMS dashboard.

I guess why my jobs were dead without proxy-watcher. Maybe I didn't notice that my proxy was expired. I just didn't get warning message.

@Saptaparna I guess DY+012j NLO is fine. It takes not that much to make gridpack. 

@qliphy @lviliani Could I ask the timeline for this task?

Best,

Junho

**Comment by Saptaparna** [comment]
@soarnsoar While @qliphy and @lviliani provide us with a timeline, I suggest that we start by looking at the simplest processes (like +1/2 jets at NLO/LO) and provide feedback on those. @soarnsoar please let me know if you need help. I'll be at CERN next week and can split some initial tasks with you.

**Comment by soarnsoar** [comment]
@Saptaparna Yep. I already submitted some processes as I wrote on my first message. I'll also add DY01jNLO as well
But I can not guarantee that I can meet you next week because I go back to my country next Tuesday.

**Comment by Saptaparna** [comment]
@soarnsoar Thanks, sorry for missing that detail in the first message (read too quickly!).

**Comment by soarnsoar** [comment]
@khurtado How can I filter to monitor my jobs only? (Maybe User = Junho Choi?? but it seems not working now)

**Comment by khurtado** [comment]
@soarnsoar I have updated my previous comment to include a split per owner (that's the attribute name for "users").
Is your CMS username jhchoi rather than junho?

**Comment by soarnsoar** [comment]
@khurtado Right :) Thanks! Now I can use the cmsconnect for MG gridpack generation :)

**Comment by qliphy** [comment]
"Could I ask the timeline for this task?"

@soarnsoar 

I would say the sooner the better.  Ultra Legacy campaign will start in about 1.5 months, and if we can validate MG265, then we can have it ready for UL production. 

Moreover, MG265 has many nice feature (read-only gridpack, multi-thread, improved computing support) we have been waiting to test for long.

**Comment by soarnsoar** [comment]
Hello. @khurtado . I have a question on cms connect's DESIRED_Sites.

I added following line
+DESIRED_Sites="T2_US_MIT,T2_US_Florida,T2_US_Purdue,T2_US_UCSD,T2_US_Vanderbilt,T2_US_Wisconsin,T2_US_Caltech,T2_US_Nebraska,T3_US_Baylor,T3_US_Colorado,T3_US_Cornell,T3_US_FIT,T3_US_FIU,T3_US_NotreDame,T3_US_Omaha_Long,T3_US_OSU,T3_US_PuertoRico,T3_US_Rutgers,T3_US_TAMU,T3_US_TTU,T3_US_UCD,T3_US_UCR,T3_US_UCSB,T3_US_UMD,T3_US_UMiss"

to create_codegen_jdl().

https://github.com/cms-sw/genproductions/blob/0d984113a2ec720b498302606a41c7acaa5f0b1f/bin/MadGraph5_aMCatNLO/submit_cmsconnect_gridpack_generation.sh#L6


I can see "codegen_<process_name>.jdl" has the line. But if you look at monitoring page of my job
https://es-cms.cern.ch/kibana/goto/587a4a8ca8b1489f14be603d10ef781c

You can see some of jobs were submiited to non- US site such as T2_ES_IFCA.


Do I use "+DESIRED_Sites" in correct way?


Best,

Junho

**Comment by khurtado** [comment]
@soarnsoar That will only work for the codegen step. Madgraph creates its own jobs afterwards.

You can use:

```
export CONDOR_DEFAULT_DESIRED_SITES="site1,site2,etc"
```

In your shell session before submitting your gridpack for all jobs in that session to respect the list of sites. If you want this to be permanent for you, you can add that line in your ~/.bashrc file.

**Comment by soarnsoar** [comment]
Thanks! It makes sense :)

**Comment by soarnsoar** [comment]
Hi. There's a problem on NLO process. 

1)For both DY012jNLO and DY01jNLO gridpack generations, I got following error :


 File "/local-scratch/jhchoi/gridpack_validation/mg265/genproductions/bin/MadGraph5_aMCatNLO/dyellell01j_5f_NLO_FXFX/dyellell01j\
_5f_NLO_FXFX_gridpack/work/processtmp/bin/internal/misc.py", line 1954, in from_plugin_import
    logger.info(info % {'plug': plug, 'key':keyname}, '$MG:BOLD')
ValueError: unsupported format character '{' (0x7b) at index 44



it's from misc.py and related to format. 


2) [Geuss] If it is misc.py 's problem, it must have shown @ lxplus. I tested gridpack generation @ lxplus with interactive mode, the job ended successfully. I don't understand it.


3) I need to look into more detail. I am checking if it's from my mistake.  But can anyone check whether this problem is reproduced @ cms connect?

**Comment by Saptaparna** [comment]
@soarnsoar At which stage did you encounter this error? I just ran the 012j NLO setup and haven't encountered errors so far.

**Comment by soarnsoar** [comment]
@Saptaparna Hi. 
I ran it with this command

nohup ./submit_cmsconnect_gridpack_generation.sh dyellell012j_5f_LO_MLM cards/examples/dyellell012j_5f_LO_MLM > dyellell012j_5f_LO_MLM.debug 2>&1 &
.

If I check the logfile, 

^[[1;31mCommand "launch -n pilotrun" interrupted with error:

It seems like occured at pilotrun.

**Comment by Saptaparna** [comment]
@soarnsoar Hi Junho! I managed to produce the +01j @NLO gridpack without errors. I will validate it later today against a +01j  NLO gridpack in 261.

**Comment by soarnsoar** [comment]
Hi, you succeeded at cms connect, right? Can you give me the command that you used?

**Comment by Saptaparna** [comment]
Sorry, no. I ran the process interactively.

**Comment by soarnsoar** [comment]
The error is only at cms connect as I said. I checked this error doesn’t occur at lxplus

**Comment by lviliani** [comment]
Hi @soarnsoar ,

I think this is a problem related to a `%{` character in the logging information.

I created a patch but I have not tested it yet, so I do not guarantee it will solve the problem. Do you have time to give it a try? Otherwise I will do it in the next days.

The patch is the following:
[https://github.com/lviliani/genproductions/blob/mg265_patch/bin/MadGraph5_aMCatNLO/patches/0025-fix-logging-info.patch](https://github.com/lviliani/genproductions/blob/mg265_patch/bin/MadGraph5_aMCatNLO/patches/0025-fix-logging-info.patch)

By the way did you try using condor at lxplus? You should get the same error if my understanding is correct.

**Comment by soarnsoar** [comment]
Hi :) thanks for caring this. Actually, I am on my flight back to Korea so I cannot take care of my tasks for 1-2 days. I will try it after my arrival. Sorry. If someone follows up this issue, please help.


Best,

Junho

**Comment by lviliani** [comment]
From a quick test with cms connect the patch seems to solve the issue.

**Comment by qliphy** [comment]
thanks @lviliani   
I found the line as below seems to be there in official MG since MG261:
                "info = 'cluster handling will be done with PLUGIN: %{plug}s' )"

Would you please (1) make a similar PR to mg261 branch?  (2) inform the authors to fix this in their version?

**Comment by lviliani** [comment]
You are right @qliphy. The reason why we didn't see this issue with 261 is that we don't have a CMS_CLUSTER plugin in the mg261 branch.

Indeed, it is the presence of a cluster plugin that triggers that message and therefore the error.

By the way, do you know why the CMS_CLUSTER plugin was not added in the mg261 branch?

PS: I will contact the authors to inform them about this fix.

**Comment by qliphy** [comment]
>By the way, do you know why the CMS_CLUSTER plugin was not added in the mg261 branch?

I think it is just due to historical reason.  The plugin was added for both mg26x and master branches at that time.  It is not for mg261 as the branch was not ready yet.  We can add it later of course.

>I will contact the authors to inform them about this fix.
Thanks!

**Comment by soarnsoar** [comment]
Hi. I found the #0012 is not applied properly to mg265.
I made a PR for it.

https://github.com/cms-sw/genproductions/pull/2214

Without this commit, it has the same symptom with this report:

https://indico.cern.ch/event/742345/contributions/3067893/attachments/1683481/2705925/180707_jhchoi_v4.pdf

**Comment by soarnsoar** [comment]
Dear all,

I found there's 'merging' step in runcmsgrid.sh and it doesn't work for me.

(at least my gridpack..) You can get my gridpack(mg265, dy012j LO) here:

http://147.47.242.72/USER/jhchoi/crab_monitor/SKFlat/ProductionStatus/Run2Legacy_v1/Status_2016.html




If you untar the gridpack and do

./runcmsgrid.sh 10000 10 1
,

the job will be divided into two of 5,000evts jobs. And each job runs well. But events_1.lhe.gz, events_2.lhe.gz are not merged well. It seems like "merge.pl" doesn't parse the lhe.gz files well.


The merge.pl is from

/cvmfs/cms.cern.ch/phys_generator/gridpacks/lhe_merger/merge.pl

.


Actually, I can generate events by several jobs of 5,000 events. But this new feature seems added at mg265 and need to be validated and fixed if needed.


Anyone can check the merge.pl? I am not familiar with merge.pl now so cannot handle the problem quickly.


Cheers,

Junho

**Comment by qliphy** [comment]
@soarnsoar   It seems not the problem of merge.pl.  It is due to in the header the xsec is always written as 0 as below: 

</initrwgt>
<MGGenerationInfo>
#  Number of Events        :       1000
#  Integrated weight (pb)  :       0
</MGGenerationInfo>
</header>
<init>

This triggers the problem on this line in merge.pl:
      if (abs(($newxsec - $oldxsec) / $newxsec) > 0.05 ) {...


This seems to be a problem in MG265 itself.  If I generate a gridpack with MG265 standalone (not with genproductions script), I will get xsec as 0 in the banner.  While with MG261, it works well with a proper number written.

Can you have a double check and ask MG authors on this?

**Comment by Saptaparna** [comment]
Another update on this front: 

I generated an NLO gridpack here:
http://nuhep.northwestern.edu/~sapta/dyellell01j_5f_NLO_FXFX_VMG5_265_slc6_amd64_gcc630_CMSSW_9_3_8_tarball.tar.xz

but when I try to generate events or even run runcmsgrid.sh, I get the following errors: http://nuhep.northwestern.edu/~sapta/errors.txt

 and the generation stops. Could someone please try to reproduce the errors I am getting? If this is indeed a problem, then I'll investigate the origin of this error.

**Comment by lviliani** [comment]
Hi @Saptaparna ,

I tried to generate the same process with CMS connect a few days ago and I didn't see these errors, so maybe you had some issues with the gridpack generation?

**Comment by Saptaparna** [comment]
@lviliani The gridpack log is here: http://nuhep.northwestern.edu/~sapta/gridpack_generation.log

I don't see an error (if I am not mistaken).

**Comment by lviliani** [comment]
@Saptaparna I don't see an error in your log indeed. The only difference with respect to my gridpack is that I used CMS Connect. Did you use condor with lxplus instead?

@soarnsoar @qliphy Can you please share the cards you used for this test? From my tests I am not able to reproduce the merging issue, and the cross section seems to be written correctly in the LHE header.

**Comment by qliphy** [comment]
@lviliani   I referred to Junho's gridpack:  http://147.47.242.72/USER/jhchoi/generator_group/for_mg265_validation/mg265/

You can find cards after untarring the gridpack.

**Comment by agrohsje** [comment]
@Saptaparna Two points to check:
1.) This patch doesn't work: 
patching file madgraph/interface/loop_interface.py
Hunk #1 FAILED at 498.
1 out of 1 hunk FAILED -- saving rejects to file madgraph/interface/loop_interface.py.rej 
2.) Did you try running on an slc6 machine? What is the detailed seg fault in the log: 
/afs/cern.ch/work/s/sapta/public/CreatingGridpacksWith265/genproductions/bin/MadGraph5_aMCatNLO/process/SubProcesses/P0_ddx_epem/ajob1: line 50: 14433 Segmentation fault      ../madevent_mintMC > log.txt < input_app.txt 2>&1

**Comment by lviliani** [comment]
@agrohsje I was aware about that patch and I was doing a couple of tests to understand if it is still needed.

I also realized that I did not include some of the patches in the mg261 branch. I will check later and add them back if they are needed.

**Comment by lviliani** [comment]
@qliphy I confirm I also see 0 xsec problem.

@soarnsoar Did you manage to report this to the authors?

**Comment by soarnsoar** [comment]
@lviliani Oh, sorry. I haven't followed up the zero xsec header issue yet.

**Comment by lviliani** [comment]
> You are right @qliphy. The reason why we didn't see this issue with 261 is that we don't have a CMS_CLUSTER plugin in the mg261 branch.
> 
> Indeed, it is the presence of a cluster plugin that triggers that message and therefore the error.
> 
> By the way, do you know why the CMS_CLUSTER plugin was not added in the mg261 branch?
> 
> PS: I will contact the authors to inform them about this fix.

MG authors will fix this in MG 2.6.6:
https://bugs.launchpad.net/mg5amcnlo/+bug/1827375

**Comment by soarnsoar** [comment]
Can anyone follow up the xsec header issue and report it to MG launchpad? 
I know it's simple but I have too many items to do and it makes me confused . I appreciate if someone take care of this issue!

**Comment by soarnsoar** [comment]
Hi @lviliani . Have you seen the error like below when you submiited gridpack generation@lxplus?
The message seems from condor. 

I submitted the job  by

source submit_condor_gridpack_generation.sh ${proc} mycard/${proc}/

It maybe related to authorization in AFS.?




------------------------------------------------------------
Using random number seed offset = 21
INFO: Running Survey 
Creating Jobs
Working on SubProcesses
INFO:     P2_gg_llqq  

ERROR: store_cred failed!
Start waiting for update. (more info in debug mode)

ERROR: store_cred failed!

**Comment by soarnsoar** [comment]
Hi. The store_cred error due to ktmux recipe in this [link](http://lhcb.github.io/analysis-essentials/shell-extras/persistent-screen.html)

I closed all ktmux sessions and ran the gridpack generations on 'screen'. There was no error like that.

Please ignore the message related to the store_cred error.

**Comment by qliphy** [comment]
@soarnsoar I have reported the xsec issue at launchpad:
https://bugs.launchpad.net/mg5amcnlo/+bug/1830567

**Comment by soarnsoar** [comment]
@qliphy Thank you so much Qiang!

**Comment by soarnsoar** [comment]
Hi. has anyone got this error @ lxplus?
[Link](147.47.242.72/USER/jhchoi/generator_group/for_mg265_validation/for_debug/lxplus_dy012j_nlo_no_amcconfig/dyellell012j_5f_NLO_FXFX.debug)

  File "/afs/cern.ch/work/j/jhchoi/public/generaotor_group/master_260/genproductions/bin/MadGraph5_aMCatNLO/dyellell012j_5f_NL\
O_FXFX/dyellell012j_5f_NLO_FXFX_gridpack/work/processtmp/bin/internal/common_run_interface.py", line 3325, in set_configuratio\
n
    config_file = open(config_path)
IOError: [Errno 2] No such file or directory: '/afs/cern.ch/work/j/jhchoi/public/generaotor_group/master_260/genproductions/bi\
n/MadGraph5_aMCatNLO/dyellell012j_5f_NLO_FXFX/dyellell012j_5f_NLO_FXFX_gridpack/work/processtmp/Cards/amcatnlo_configuration.txt'
finished pilot run



I can find the 'amcatnlo_configuration' in 'dyellell012j_5f_NLO_FXFX/dyellell012j_5f_NLO_FXFX_gridpack/work/gridpack/process/Cards/amcatnlo_configuration.txt' in jobdirectory.


Please note that this problem is only @lxplus. For all of the 3 mg versions(mg260 mg261 mg265).

I also tested dy0jnlo/dy01jnlo. They don't have this kind of error.

I am stuck in this problem. Someone has any exprience on this kind of error??

**Comment by minerva1993** [comment]
@soarnsoar Hi, it seems the matrix element generation is not properly finished from your log file:
"""
INFO: Generating Helas calls for FKS process: b~ g > ta+ ta- b~ [ all = QCD ] @1 (117 / 645) 
copying generated process to working directory
"""

I launched dyellell012j_5f_NLO_FXFX for test in the master branch and it seems working (now computing upper envelope). I have not been following this thread so maybe I missed some details...

From my experience, I faced some permission problem if I run multiple k5reauth processes for tmux.  This seems not the case?

**Comment by kdlong** [comment]
@soarnsoar I suspect it's an afs issue. Do you see it again and again?

**Comment by soarnsoar** [comment]
@minerva1993 Thanks! Good point.  I missed that point. I found a report with the same problem on MGlaunchpad : https://answers.launchpad.net/mg5amcnlo/+question/673120. It seems related to memory. I used ktmux recipe in this link:http://lhcb.github.io/analysis-essentials/shell-extras/persistent-screen.html and ran several processes one tmux session.


@kdlong I tried it 3times and got the same things.



I'll try it with only one gridpack generation process. I guess the reason is I ran too many processes on one session. Thank you so much:)

**Comment by qliphy** [comment]
The xsec issue should be resolved with #2256   
to be further tested with complicated process

**Comment by soarnsoar** [comment]
Hi. It's been long time since the last update.

I've tried to make gridpacks with following cards

:http://147.47.242.72/USER/jhchoi/generator_group/for_mg265_validation/mycard/

But high jet multiplicity gridpack cannot be generated due to too many subjobs!

At lxplus, some subjobs are in 'hold' state and MG cancel them. At cms connect, some subjobs fail over 10 times.

To make those gridpack in a stable way, I ran jobs in non-batch(interactive mode) in my institute's machine, even it takes long time. 

If some of you can help gridpack generations of 

DY+01234j LO
DY+012j NLO

using master/mg261/mg265 branches, I really appreciate it. 

(Card : http://147.47.242.72/USER/jhchoi/generator_group/for_mg265_validation/mycard/)

**Comment by qliphy** [comment]
@soarnsoar     for your information,   @afanfani has made a DY+01234j LO gridpack with mg261: /afs/cern.ch/user/a/afanfani/public/MadGraph5_aMCatNLO/UL/lxplus_18June/DYJetsToMuMu_LO_MLM_mll50_slc7_amd64_gcc700_CMSSW_10_6_0_patch2_tarball.tar.xz

**Comment by qliphy** [comment]
@afanfani  I tested your gridpack, it looks fine to me.   Would you please help produce also a mg265 gridpack?  Thanks a lot!

**Comment by soarnsoar** [comment]
@qliphy Do I have to test mg261_UL as well? I've tested mg261.

**Comment by qliphy** [comment]
@soarnsoar   mg261 is fine.  mg261_UL (now called UL2019) is just a clone from mg261 with changes on PDF settings.

**Comment by soarnsoar** [comment]
Hi. Sorry for long silence.

I have a minor(but important) issue on pdf seeting on run card.

If you look at this link(https://twiki.cern.ch/twiki/bin/viewauth/CMS/QuickGuideMadGraph5aMCatNLO#PDF_Choice_for_2017_production),

our recommendation for PDF setting is

lhapdf = pdlabel ! PDF set
 $DEFAULT_PDF_SETS = lhaid
 $DEFAULT_PDF_MEMBERS  = reweight_PDF


This setting is fine for "NLO" and all reweight values are stored well.(NLO is fine)

But, for LO, only pdfwgt == F, LHAPDF247000 is set to default PDFset !

If pdfwgt ==T, default PDFset is set to 306000, which we want to set as default.(only when pdfwgt is set to T, PDFsetting is fine)


Anyway, checking reweight is okay but 

default PDFset is dependent on "pdfwgt" parameter in run_card.dat. I haven't expected it.


If anything is unclear, please let me know. You can find my MG card here:

/afs/cern.ch/work/j/jhchoi/public/generaotor_group/for_mg265_validation/mycard

.

Summary for reweight setting:
NLO ->fine
LO, pdfwgt==T ->fine
LO, pdfwgt==F -> default PDF is set to 247000.


If someone crosscheck/reproduce this bug, I really appreciate it :) 

(it occurs for all of 3 versions-260,261,265)

**Comment by lviliani** [comment]
Hi @soarnsoar ,

this is strange indeed...
Can you check the following line in your `runcmsgrid.sh` script for LO gridpacks?
https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/runcmsgrid_LO.sh#L168
I expect to see the full list of PDF sets there. If so, then I guess this feature comes from the systematics module itself.

**Comment by qliphy** [comment]
@soarnsoar  A quick test using your card (dyellell012j_5f_LO_MLM) with  master branch (mg260),  I don't see the issue.     i.e.  pdfwgt ==F and LO -> default PDF set is 306000

**Comment by soarnsoar** [comment]
Oh, I found I made a type. I missed

 'lhapdf'    = pdlabel  

on the card. This makes the wrong result.

**Comment by soarnsoar** [comment]
Anyway, now I have made framework for this study. 

Anyone can help generating a gridpack with this card using mg261 branch?
:
/data9/Users/jhchoi/gridpack_gen/for_mg265_validation/mycard/dyellell01234j_5f_LO_MLM
 
I've resubmitted mg260/mg265 gridpack generation for the process  and it takes 3 days.

**Comment by qliphy** [comment]
Adding  @cmsgql @JINGFFF @yangheng-PKU  who may help generate a mg261 gridpack with the card

**Comment by soarnsoar** [comment]
Hi.

I update the validation plots with PDF/Scale reweighting.

Please find the link below,

https://jhchoi.web.cern.ch/jhchoi/Generator_group/Valdation_plots/

Actually, I don't see all of the plots yet. I'll update more later!

**Comment by agrohsje** [comment]
Hi @soarnsoar , this looks quite good. I have a question about the legend of the plots and the syst. resp. stat. uncertainties. In these plots: https://jhchoi.web.cern.ch/jhchoi/Generator_group/Valdation_plots/mg265LO__dyellell01234j_5f_LO_MLM__over__mg261LO__dyellell01234j_5f_LO_MLM/306000/Zelectron_eta.png is the stat error shown by the cross and the syst by the colored area and the sum of both indicated by the hashed one? 
Did you go through all the plots? Is there still an automitic check that allows us to spot the largest problems?

**Comment by soarnsoar** [comment]
Hi @agrohsje ,
For the first question, yes. I'll change the legend more clear.

For the second question, I don't have an automatic checker yet. 
Central  values of 2 different version must be agreed within stat error. Systematic err as well, right?

**Comment by agrohsje** [comment]
Yes, we should try that.

**Comment by soarnsoar** [comment]
Hi. I try the Chi2Test and KolmogorovTest. I explained how I did it on this link:
https://jhchoi.web.cern.ch/jhchoi/Generator_group/ref/CHI2TEST.pdf

Also, you can find the all of the plots and result :

https://jhchoi.web.cern.ch/jhchoi/Generator_group/Valdation_plots/DY_265_261_260/

Thanks!

**Comment by soarnsoar** [comment]
Hi! I found that lhe file from DY NLO gridpack has a bug.(At least with my runcard)

The first entry of rwgt which is muR=1.0 muF=1.0 with central PDF, has too large value. For example,
==============================
<rwgt>
<wgt id='1001'> +2.6521844e+04 </wgt>
<wgt id='1002'> +1.3225485e+04 </wgt>
<wgt id='1003'> +1.3304872e+04 </wgt>
<wgt id='1004'> +1.2902122e+04 </wgt>
<wgt id='1005'> +1.3027600e+04 </wgt>
<wgt id='1006'> +1.2746499e+04 </wgt>
<wgt id='1007'> +1.3426674e+04 </wgt>
<wgt id='1008'> +1.3236082e+04 </wgt>
<wgt id='1009'> +1.3663051e+04 </wgt>
<wgt id='1010'> +2.6521844e+04 </wgt>
<wgt id='1011'> +1.3262408e+04 </wgt>
<wgt id='1012'> +1.3277623e+04 </wgt>
<wgt id='1013'> +1.3259487e+04 </wgt>
<wgt id='1014'> +1.3347399e+04 </wgt>
<wgt id='1015'> +1.3263497e+04 </wgt>
<wgt id='1016'> +1.3215410e+04 </wgt>
<wgt id='1017'> +1.3243662e+04 </wgt>
==============================

Now, i am investigating what makes this problem. Other things seem fine.

**Comment by soarnsoar** [comment]
Can anyone reproduce this bug ? 
The bug will be found if you run
-with mg261
-NLO process
-then, its central rwgt is ~twice larger than other rwgt values.

**Comment by soarnsoar** [comment]
Thanks! mg261 missed that patch.
I'll apply it and re-run gridpack generation.

**Comment by qliphy** [comment]
Please also make a PR to add the missing patch to mg261 and UL2019 branches, after your test.  Thanks!

**Comment by soarnsoar** [comment]
Hi @qliphy 

Could you merge following PRs for correcting rwgt values?

https://github.com/cms-sw/genproductions/pull/2320


https://github.com/cms-sw/genproductions/pull/2321

**Comment by qliphy** [comment]
@soarnsoar   Thanks!  Just in case, have you checked the PR works? There is no need for small tweaking as the MG version is different?

**Comment by soarnsoar** [comment]
I checked the PR for mg261 works well. As the UL2019 has the same MG version I didn't check the PR and just added the same patch. I'll test the UL2019 as well. Could you merge the mg261 first?

**Comment by qliphy** [comment]
Thanks.  #2320 has been merged

**Comment by soarnsoar** [comment]
UL2019 is also fine:

\<rwgt>
\<wgt id='1001'> +7.5403157e+03 </wgt>
\<wgt id='1002'> +7.2182093e+03 </wgt>
\<wgt id='1003'> +7.9396053e+03 </wgt>
\<wgt id='1004'> +8.3210168e+03 </wgt>
\<wgt id='1005'> +7.9703223e+03 </wgt>
\<wgt id='1006'> +8.7557454e+03 </wgt>
\<wgt id='1007'> +6.6588507e+03 </wgt>
\<wgt id='1008'> +6.3702784e+03 </wgt>
\<wgt id='1009'> +7.0165713e+03 </wgt>

**Comment by soarnsoar** [comment]
I've updated plots here : https://jhchoi.web.cern.ch/jhchoi/Generator_group/Valdation_plots/DY_MG265/

And I tested them requiring pvalue threshold 1e-5.

I'll make slides to explain the result asap

**Comment by qliphy** [comment]
Thanks @soarnsoar 
As you might know, we are setting Aug 20th as the target to switch master to 265.  So please be prepared to give an update by then.

**Comment by soarnsoar** [comment]
Okay.

By the wat, do you have a valid mg card to test reweigjt functionality ? Kind of anomalous coupling

**Comment by qliphy** [comment]
reweight functionality has been checked with mg265:
https://indico.cern.ch/event/783797/contributions/3502929/attachments/1884743/3106389/Madgraph_Version_Comparision1.pdf

cards can be found here:
https://github.com/cms-sw/genproductions/pull/2294

**Pull request merged**
