### PR TITLE
DY MiNNLO 13p6TeV

### PR DESCRIPTION
**Pull request by mseidel42**
DY MiNNLO for 13.6 TeV, these are the NNLO cross sections calculated during gridpack production:
```
ZJToMuMu-13p6TeV-suggested-nnpdf31-ncalls-doublefsr-q139
  total (btilde+remnants) cross section in pb   2103.8137919947922      +-  0.56983756670429542
WplusJToMuNu-13p6TeV-suggested-nnpdf31-ncalls-doublefsr-q139-ckm
  total (btilde+remnants) cross section in pb   12292.986509111422      +-   6.5866707599607119
WminusJToMuNu-13p6TeV-suggested-nnpdf31-ncalls-doublefsr-q139-ckm
  total (btilde+remnants) cross section in pb   9134.3028259480725      +-   3.2039854089865671
```

### CODE REVIEW

**Comment by Saptaparna** [comment]
There's also MATRIX (that ATLAS uses) and MCFM. It would be good to do a proper comparison of all of these calculations and the errors associated with each tool.

**Comment by mseidel42** [comment]
Hi, for Z production the cross section is 1% lower than the MCFM values presented few weeks ago: https://indico.cern.ch/event/1162789/#26-dy-cross-section-136-tev-us
But that could just be due to usage of LUXqed. I would need to check again if MiNNLO can properly use that (= has the photon-induced production).

One of the MiNNLO authors is doing MATRIX as well, so they validated their results against MATRIX, see https://arxiv.org/abs/2006.04133

**Comment by sihyunjeon** [comment]
That reminds me - comments to Rafia few weeks earlier was whether FEWZ includes GG contribution @menglu21

**Comment by mseidel42** [comment]
Right, the presentation was FEWZ!

It seems photon-induced contributions are only included in Powheg Z_ew-BMNNPV, which is NLO (in QCD and EW).

**Comment by sihyunjeon** [comment]
hmph ci failed

**Comment by mseidel42** [comment]
Because no runners 😝

**Comment by menglu21** [comment]
> That reminds me - comments to Rafia few weeks earlier was whether FEWZ includes GG contribution @menglu21
> 
> Ah @mseidel42 is the link you provided wrong or should it be FEWZ not MCFM?



> That reminds me - comments to Rafia few weeks earlier was whether FEWZ includes GG contribution @menglu21
> 
> Ah @mseidel42 is the link you provided wrong or should it be FEWZ not MCFM?

sorry, i totally overlooked this msg, there is sentence talking about the photon-induced process in the manual https://www.hep.anl.gov/fpetriello/FEWZManual_3.1.pdf, but let me confirm with the author

**Pull request merged**
