### PR TITLE
adding Vgamma cards

### PR DESCRIPTION
**Pull request by senka**
Dear all,
here are the Vgamma cards for 2016 data analysis.

Senka

### CODE REVIEW

**Comment by perrozzi** [comment]
I would not use an SMP subfolder
bin/MadGraph5_aMCatNLO/cards/production/pre2017/13TeV/SMP/
but just
bin/MadGraph5_aMCatNLO/cards/production/pre2017/13TeV/

**Comment by senka** [comment]
removed subdir SMP and moved all cards to pre2017/13TeV

**Comment by efeyazgan** [comment]
please cleanup commented/unuseful lines,

**Comment by senka** [comment]
done

**Pull request merged**
