### PR TITLE
Merging mg26x

### PR DESCRIPTION
**Pull request by AndreasAlbert**
This is the merge for mg26x.

For cards, I have added the OR of both branches, i.e. cards that only exist in master are kept and cards that only exist in mg26x are also kept, unless they are explicitly deleted in the other branch.

For the scripts and patches, I have kept the mg26x versions.

Two remaining issues:

* [CONDOR_RELEASE_HOLDCODES_SHADOW_LIM](https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/submit_cmsconnect_gridpack_generation.sh#L135) has different values in the two branches. @khurtado: Should we set it to 10 or 19?

*[This fix](https://github.com/cms-sw/genproductions/commit/898356baf5d50080f0c6cead19c4f9250004296c#diff-710a9160da4881dd500cead4d556cb10) ~~was lost in the merge, will re-apply (non-critical, can also be done after merge)~~ -> Added it back.

### CODE REVIEW

**Comment by AndreasAlbert** [comment]
@perrozzi @agrohsje @kdlong

**Comment by khurtado** [comment]
@AndreasAlbert 19 should be fine, to be more conservative.

**Comment by perrozzi** [comment]
@AndreasAlbert in my opinion the PR should be first done on mg26x
https://github.com/cms-sw/genproductions/compare/mg26x...AndreasAlbert:master_2018-04-24_try1
to do some final check and test before to put into master.
I (or you) can change directly the target branch in the PR to avoid duplicates

**Comment by AndreasAlbert** [comment]
@perrozzi done

**Comment by perrozzi** [comment]
is the remaining issue solved after Kenyi's reply? can the PR be merged?

**Comment by AndreasAlbert** [comment]
@perrozzi Yes, issue is resolved. 

@kdlong @agrohsje Any objections to merging into mg26x?

**Comment by agrohsje** [comment]
@kdlong @AndreasAlbert I don't see the branch from Kenneth merged for the reweighting? We wanted to do that still first. No?

**Comment by agrohsje** [comment]
Yes.

**Comment by perrozzi** [comment]
#1658 it contains conflicts, so @kdlong should fix (I see that maybe is just the trivial repetition of the multi-run in runcmsgrid_LO.sh)

**Comment by perrozzi** [comment]
merged PR into temporary branch mg26x_merge.
@agrohsje how critical is #1658 ?
I tried to do a local merge but runcmsgrid_LO.sh is pretty mangled, although In principle it should not be part of the PR.....

**Comment by agrohsje** [comment]
What do you mean with "mangled"? The script as it is now in mg26x_merge doesn't work if you want to use reweighting and madspin as reweighting has to go before madspin. 
For top eft, it would be great to have, because we should aim to produce some central samples at some point.

**Comment by perrozzi** [comment]
with mangled I mean the numerous series of conflicts (8) I observe if I do
```
git branch --set-upstream mg26x upstream/mg26x # track my local branch to remote official repo
git merge kdlong/fixNLOreweight # include Kenneth's PR
```
the result is this
[runcmsgrid_LO.sh.txt](https://github.com/cms-sw/genproductions/files/1960389/runcmsgrid_LO.sh.txt)
and I would prefer if Kenneth or somebody else would make sure the merge is done properly :)

**Pull request merged**
