### PR TITLE
commit cards for Tp decaying to gluons or photons

### PR DESCRIPTION
**Pull request by dnoonan08**
Add cards for producing samples of TpTp decaying to a top and a gluon or photon (ttgg, ttga, ttaa)

### CODE REVIEW

**Comment by agrohsje** [comment]
Hi @dnoonan08. There is no way we can review 219 files. Do you mind just pushing a script and a set of templates, Really the bare minimum. A computer is much better in handling copies ... Thanks!

**Comment by sihyunjeon** [comment]
Hello, For your case, I think only the scripts will be fine.

**Comment by dnoonan08** [comment]
Hi @agrohsje @sihyunjeon, I just wanted to follow up to see if there is anything else that would be needed to sign off on this PR

**Comment by sihyunjeon** [comment]
Hell @dnoonan08 I don't think the model card is in [1] so I cannot check it myself. Can you upload your modelfile in lxplus public repo so that I can upload it to [1] for future reference. And also can you confirm that your model file is 5f? If you don't know how to check this I can do it for you

[1] https://cms-project-generators.web.cern.ch/cms-project-generators/

**Comment by sihyunjeon** [comment]
Other than this all looks fine

**Comment by agrohsje** [comment]
Hi @dnoonan08 , please provide the UFO to finish and include a extramodel card to download what we will upload here: 
https://cms-project-generators.web.cern.ch/cms-project-generators/
Thanks!

**Comment by dnoonan08** [comment]
Hi @sihyunjeon and @agrohsje 
The ufo file can be found on lxplus here:
`/afs/cern.ch/user/d/dnoonan/public/TPrimeMCGen/top3decays_ufo`

For the extramodel card, this is already part of the script to generate the cards.  It gets [defined here](https://github.com/dnoonan08/genproductions/blob/TpTp_GluonPhotonDecays/bin/MadGraph5_aMCatNLO/cards/production/13TeV/TpTp_GluonPhotonDecays/pairProduction_ttgaChannel.py#L301-L302) and the card is [written here](https://github.com/dnoonan08/genproductions/blob/TpTp_GluonPhotonDecays/bin/MadGraph5_aMCatNLO/cards/production/13TeV/TpTp_GluonPhotonDecays/pairProduction_ttgaChannel.py#L301-L302).  Is there something else that is needed for the extramodel card, or is that it?

**Comment by ravindkv** [comment]
Hi @sihyunjeon and @agrohsje, kindly let us know in case more to be done from our side. Thanks a lot.

**Comment by agrohsje** [comment]
Tarred the UFO and copied it to our webspace. One final comment. There is no higgs involved. 
set param_card mass 25 125.0 should have no effect. But you change the top mass, do you mind changing the width accordingly by doing set param_card DECAY 6 auto. Otherwise this is good. @sihyunjeon please merge once the width is fixed. Thanks!

**Comment by dnoonan08** [comment]
@sihyunjeon @agrohsje I've fixed the top width in the scripts.  Thanks

**Pull request merged**
