### PR TITLE
13p6 TeV powheg cards for early run3 HZZ analysis

### PR DESCRIPTION
**Pull request by jdavis36**
Input cards for VBF, HZ+J, Wplus+J, and Wminus+J powheg production with JHUGen in decay.

### CODE REVIEW

**Comment by menglu21** [comment]
Hi @jdavis36 the cards look good to me, just one minor question, the width of Higgs changes from 0.00407 to 0.00409, is the new value recommended

**Comment by jdavis36** [comment]
Hi @menglu21, I am not sure if it is recommend. I assumed that since the widths changed in YR 4 I would update them to those values. I think that this is the correct approach for Run 3 at least in the HZZ group. I also noticed that other PR involving Higgs production used the new width as well.

**Comment by menglu21** [comment]
> Hi @menglu21, I am not sure if it is recommend. I assumed that since the widths changed in YR 4 I would update them to those values. I think that this is the correct approach for Run 3 at least in the HZZ group. I also noticed that other PR involving Higgs production used the new width as well.

Hi @jdavis36 do you mean xlsx in https://twiki.cern.ch/twiki/bin/view/LHCPhysics/LHCHWG?redirectedfrom=LHCPhysics.LHCHXSWG#Production_cross_sections_and_de, i checked the values inside and i didn't see the value changed, for mH=125, the total width is still 0.0040731099

**Comment by jdavis36** [comment]
Hi @menglu21 I was actually looking at this https://twiki.cern.ch/twiki/bin/view/LHCPhysics/CERNYellowReportPageAt13TeV. The width at 125 is 4.088.

**Comment by jdavis36** [comment]
Hi @menglu21 , jsut pinging to check the status of this PR. I am jsut getting back from break and realize I linked you the incorrect page. The one I use for the width is here: https://twiki.cern.ch/twiki/bin/view/LHCPhysics/CERNYellowReportPageBR

**Comment by menglu21** [comment]
> Hi @menglu21 , jsut pinging to check the status of this PR. I am jsut getting back from break and realize I linked you the incorrect page. The one I use for the width is here: https://twiki.cern.ch/twiki/bin/view/LHCPhysics/CERNYellowReportPageBR

it seems your page is outdated, the page u sent you was updated in 2023-01-20 so i suggest you refer to it. (the difference is small but better to keep it most updated). btw, it seems some of your cards have been in the same repo, could you please have a check

**Comment by jdavis36** [comment]
> > Hi @menglu21 , jsut pinging to check the status of this PR. I am jsut getting back from break and realize I linked you the incorrect page. The one I use for the width is here: https://twiki.cern.ch/twiki/bin/view/LHCPhysics/CERNYellowReportPageBR
> 
> it seems your page is outdated, the page u sent you was updated in 2023-01-20 so i suggest you refer to it. (the difference is small but better to keep it most updated). btw, it seems some of your cards have been in the same repo, could you please have a check

Just to make sure, we are looking at this spreadsheet? https://twiki.cern.ch/twiki/pub/LHCPhysics/LHCHWG/Higgs_XSBR_YR4_update.xlsx 

On the YR4 SM BR page, in column CC, Row 25, I see the width for 125 to be 4.088. Also, the page I linked earlier from 2016 is the same page that the link in https://twiki.cern.ch/twiki/bin/view/LHCPhysics/LHCHWG?redirectedfrom=LHCPhysics.LHCHXSWG#Production_cross_sections_and_de

called "[Recommended values on SM Higgs BR (CERN Report 4) goes to this link with width at 4.088 https://twiki.cern.ch/twiki/bin/view/LHCPhysics/CERNYellowReportPageBR)]

Sorry to keep harping on this, I am just a bit confused.

**Comment by adewit** [comment]
@menglu21 these samples are needed urgently for the H->ZZ measurements with Run 3 data. I concur with Jeff's findings from the spreadsheet on the value of the width. Can you please say exactly where you found the value of 4.07? To be clear, the 4.088 seems to be from

Screenshot 2023-02-02 at 19 04 33

Will ask overall HIG MC to have a look as well.

**Comment by attikis** [comment]
hi @menglu21,

we also confirm the comments made by @jdavis36. Please let us know if you have further comments or suggestions so we can rapidly proceed to merging this PR. We would like to submit these as soon as possible.

Thank you,
Alexandros & Ho-Fung for HIG MC

**Comment by Saptaparna** [comment]
@menglu21 : I checked the cards and everything looks good. Should we merge?

**Comment by menglu21** [comment]
I see, I added all the width in "YR4 BSM width" and it's closer to the previous one. I think your number is correct. but since there is already three files in https://github.com/cms-sw/genproductions/tree/master/bin/Powheg/production/Run3/13p6TeV/Higgs/HZJ_HanythingJ_NNPDF31_13p6TeV, you should not make new ones but modify them instead. then we can merge the PR

**Pull request merged**
