### PR TITLE
cuts.f file for dyellell012j_5f_NLO_FXFX with pt_ll>100GeV

### PR DESCRIPTION
**Pull request by wvieri**

### CODE REVIEW

**Comment by bendavid** [comment]
Are the proc and run cards already there?

**Comment by wvieri** [comment]
proc and run cards should be exactly the same as the default dyellell012j_5f_NLO_FXFX sample, I can copy them here if needed

**Comment by bendavid** [comment]
yes, please do

**Comment by wvieri** [comment]
done

**Comment by bendavid** [comment]
You'll have to rename them for this to work with the gridpack scripts.

**Comment by wvieri** [comment]
ok, done!

**Comment by bendavid** [comment]
Now there are two copies of the files...

**Comment by wvieri** [comment]
deleted

**Pull request merged**
