### PR TITLE
add mglib_path for precompiled lib

### PR DESCRIPTION
**Pull request by sihyunjeon**
taking madgraph interface in CMSSW to fetch ninja (+oneloop) instead of installing ninja everytime when making gridpacks

### CODE REVIEW

**Comment by sihyunjeon** [comment]
@DickyChant present for you

**Comment by DickyChant** [comment]
Is there a way that we can systematically include the libs?

e.g. extracting from `scram tool info madgraph5amcatnlo`

**Comment by sihyunjeon** [comment]
> Is there a way that we can systematically include the libs?
> 
> e.g. extracting from `scram tool info madgraph5amcatnlo`

it could be read from `MADGRAPH5AMCATNLO_BASE` but parsing this seemed like out of my shell scripting knowledge...
i can do `scram tool info madgraph5amcatnlo > log`
and make it parse using python scripts if you think it's better.

or... this could be dirty but one can do

```
scram tool info madgraph5amcatnlo > log
grep "scram tool info madgraph5amcatnlo" log > set.sh
source set.sh
```

sth like this

**Comment by sihyunjeon** [comment]
and then set the paths to `$MADGRAPH5AMCATNLO_BASE/blahblah`

**Comment by DickyChant** [comment]
maybe sth like:
```
MG5_PATH=`scram tool info madgraph5amcatnlo | grep MADGRAPH5AMCATNLO_BASE`
MG5_PATH=${MG5_PATH#*=}
echo $MG5_PATH
```
There are more tricks with `awk` and `grep` but for now I guess this should be enough

**Comment by DickyChant** [comment]
Given that `hepforge` seems to have more downtime, shall we move with this direction?

**Comment by sihyunjeon** [comment]
hi sitian, thanks for the snippets

**Comment by sihyunjeon** [comment]
@Dominic-Stafford i think we also need to add collier installation in CMSSW
MadGraph internally has a setting that it looks for ninja and collier libraries altogether,

problem is that there is no collier in CMSSW so if I only set ninja path, madgraph looks for both ninja and collier, and then it just decides to NOT use collier instead of installing it. so now it has "install collier" after setting ninja. ultimately we should fix this with CMSSW

**Comment by sihyunjeon** [comment]
```
WARNING: The collier reduction library could not be found with PATH:/data9/Users/shjeon/test2/genproductions/bin/MadGraph5_aMCatNLO/wplustest_4f_NLO/wplustest_4f_NLO_gridpack/work/MG5_aMC_v2_9_13/HEPTools/lib specified in mg5_configuration.txt. It will not be available. 
```

This is the error message I get

**Comment by Dominic-Stafford** [comment]
> @Dominic-Stafford i think we also need to add collier installation in CMSSW MadGraph internally has a setting that it looks for ninja and collier libraries altogether,
> 
> problem is that there is no collier in CMSSW so if I only set ninja path, madgraph looks for both ninja and collier, and then it just decides to NOT use collier instead of installing it. so now it has "install collier" after setting ninja. ultimately we should fix this with CMSSW

Hi Sihyun. Sure, I can try adding collier to cmsdist so it builds this as an external for CMSSW. One other thing is we should be careful about making sure the relevant CMSSW releases have the right versions of madgraph. Do you want to do this for both run 2 UL and run 3, or just run 3? And am I right in saying we need MG5 2.9.13 in CMSSW master and 12_4, and 2.6.5 in CMSSW_10_6?

**Comment by sihyunjeon** [comment]
@Dominic-Stafford Hi dominic, I leave this decision to @menglu21 and @bbilin

**Comment by DickyChant** [comment]
> > @Dominic-Stafford i think we also need to add collier installation in CMSSW MadGraph internally has a setting that it looks for ninja and collier libraries altogether,
> > problem is that there is no collier in CMSSW so if I only set ninja path, madgraph looks for both ninja and collier, and then it just decides to NOT use collier instead of installing it. so now it has "install collier" after setting ninja. ultimately we should fix this with CMSSW
> 
> Hi Sihyun. Sure, I can try adding collier to cmsdist so it builds this as an external for CMSSW. One other thing is we should be careful about making sure the relevant CMSSW releases have the right versions of madgraph. Do you want to do this for both run 2 UL and run 3, or just run 3? And am I right in saying we need MG5 2.9.13 in CMSSW master and 12_4, and 2.6.5 in CMSSW_10_6? Also, should we use a specific ninja or collier versions, or just the latest ones?

Hi Dominic, maybe I am wrong (my schedule is totally ruined recently), I remembered MG usually have a relatively fixed version choice of those packages. (either always the newest one, or a fixed version per major release). So it is a relatively easier decision to make... 

Shall we try at some moment having those libraries decoupled from MG as an ultimate solution?

**Comment by sihyunjeon** [comment]
@DickyChant They are fixed for every version of madgraph, it doesn't really depend on madgraph version. They are imported from HEPToolsInstaller.py which is CENTRAL. So madgraph 220 and madgraph 352 would share the same install libraries...

**Comment by DickyChant** [comment]
> @DickyChant They are fixed for every version of madgraph, it doesn't really depend on madgraph version. They are imported from HEPToolsInstaller.py which is CENTRAL [link](https://github.com/mg5amcnlo/HEPToolsInstallers). So madgraph 220 and madgraph 352 would share the same install libraries...
> 
> One of the reasons why madgraph can't really support too old versions...

That's what I thought actually because I never see a different version, and I assume they are the newest available version

**Comment by DickyChant** [comment]
> I might've misunderstood but I think/agree that having totally decoupled versions of external libraries will be the safest choice

yeah that's what I meant, in that case we could perhaps have more flexible MG solution as after all apart from those libs we don't have anything to be compiled...

**Comment by Dominic-Stafford** [comment]
From what I can see with hepforge being down, it doesn't look like ninja or collier versions change too much, actually (I guess they're pretty stable, hopefully all the bugs have been found). So I think it would be fine to put collier in CMSSW, if it was often being updated it would a different story but here I think it's fine. So just to check, you're not actually taking MG from CMSSW, just ninja and collier?

**Comment by DickyChant** [comment]
> From what I can see with hepforge being down, it doesn't look like ninja or collier versions change too much, actually (I guess they're pretty stable, hopefully all the bugs have been found). So I think it would be fine to put collier in CMSSW, if it was often being updated it would a different story but here I think it's fine. So just to check, you're not actually taking MG from CMSSW, just ninja and collier?

Indeed, as hepforge seems to be less stable. Our idea is that for MG itself we need patches & upgrades from time to time, but for those heptools (ninja, collier... etc) we don't need them to be installed and compiled every time. It is neither computationally efficient nor safe with nowadays unstable hepforge. 

Currently, a temporary solution is to nicely use those libraries from your wrapped-up MG in CMSSW, but ultimately it might be a good idea to completely disentangle :)

**Comment by sihyunjeon** [comment]
for now, if no objections until monday afternoon, i'll merge. at least having something is better altho it's not everything (i believe backporting will take longer).

also it would not "likely" happen, but i did check with `pp > w [qcd]` process whether gridpack makes the LHE files properly or not, just in case there could be hidden problems.

**Comment by sihyunjeon** [comment]
actually, let me merge this now. hepforge is down again... :)

**Pull request merged**
