### PR TITLE
Cards for single top t-channel 5FS Vtd=Vts=0.707

### PR DESCRIPTION
**Pull request by ckmackay**

### CODE REVIEW

**Comment by efeyazgan** [comment]
Please remove comments and commented inputs

**Comment by efeyazgan** [comment]
Thanks. 

In fact, I meant lines like:
+!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
+! I need to reproduce exactly MCFM input
+! MCFM (alphainv, sthw2)
+! 132.3384323 
+! 0.2226459

not like:
something something ! ......

**Comment by ckmackay** [comment]
Oh OK, I went a little crazy! But the final one was not done yet...
________________________________

**Comment by efeyazgan** [comment]
Sorry for that. Could you please make another PR?

**Comment by ckmackay** [comment]
Hi Efe,

I am trying to but there is not the option to delete my branch like there usually is after a merge [1]. I see there is a revert option, should I try this?

Thanks, Kate

[1] https://github.com/cms-sw/genproductions/pull/1701
________________________________

**Comment by efeyazgan** [comment]
w/o reverting, you can update to master to fetch the merged commit and from there make a new PR.

**Comment by ckmackay** [comment]
I have updated and got the merged commit which I have then changed but when I try and push I get an error as I never deleted the branch, but I don't have the option to change the branch...

**Comment by perrozzi** [comment]
you can change the branch name like
git checkout -b new_branch_name

**Comment by efeyazgan** [comment]
May be just start from a clean area - or move to a different branch?

**Comment by ckmackay** [comment]
Thanks, it's sorted. I'll make the new pull request.

**Pull request merged**
