### PR TITLE
Try other way of including python

### PR DESCRIPTION
**Pull request by covarell**
What about this one? @agrohsje @fabio-mon

### CODE REVIEW

**Comment by fabio-mon** [comment]
hi @covarell I came up with the same setup and tested it yesterday. It works well

**Comment by covarell** [comment]
Thanks @fabio-mon, I have un-drafted this one, so you can close the other PR

**Comment by menglu21** [comment]
Hi @covarell it's for Run3, right? if it's already validated I will merge this pr

**Comment by covarell** [comment]
Yes, please, @fabio-mon tested this.

**Pull request merged**
