### PR TITLE
use another parser to be compatible with cmssw 53 (i.e. python 2.6)

### PR DESCRIPTION
**Pull request by perrozzi**
and also update to Nov2015 package

### CODE REVIEW

**Comment by perrozzi** [comment]
also restore lhspdf6 functionality for cmssw 53x

**Comment by covarell** [comment]
@yuanchao could you please have a look? thanks

**Comment by yuanchao** [comment]
Sorry for the late reply. With a quick check on the functionality, I get the same batch script output as the argparse parser, except for the extra LHAPDF6TOOLFILE for CMSSW 53x. I think the patch can be merged.

**Comment by perrozzi** [comment]
hello, can you please merge?

**Pull request merged**
