### PR TITLE
LQ cmutau run card changes

### PR DESCRIPTION
**Pull request by Physicsjong1**
Changes flavour scheme from 5Fs to 4FS

### CODE REVIEW

**Comment by swertz** [comment]
Don't forget to also update the top quark mass to the CMS central value using a customize card...

**Comment by swertz** [comment]
Looks goot to me!

**Comment by Physicsjong1** [comment]
I set the lhaid to $DEFAULT_PDF_SETS and is the PDF automatically selected as PDF for 4FS one?
Without that, the value is all the same for the both.

**Comment by Physicsjong1** [comment]
@agrohsje I missed to check the top width when changing the top mass.
Yes, I think it should be changed also. Could you give me the top width? I will commit on the customise card.

**Comment by agrohsje** [comment]
set param_card DECAY   6 auto
should give you the right value as everything is anyway LO 2 - > 2

**Comment by Physicsjong1** [comment]
> set param_card DECAY 6 auto
Does this work for both, the top mass and width?
Then, the mass MT in param card may be useless.

**Comment by agrohsje** [comment]
Wait the line you have now sets the mass. The line that I suggested to add will trigger mg5 to calculate the width for that mass. The settings are independent.

**Pull request merged**
