### PR TITLE
configs from Anirban

### PR DESCRIPTION
**Pull request by dnash86**
Configs for Zprime to tau tau production with pythia8

### CODE REVIEW

**Comment by bendavid** [comment]
Pythia 8.205 currently used in production does not handle tau decays well specifically for the Wprime/Zprime case.

This is fixed in 8.209.  If these samples are not urgent, suggest to wait.  Otherwise can produce them with tauola for the decays (which by default assumes SM-like helicity structure for the Zprime-fermion couplings)

**Comment by dnash86** [comment]
Quick question: how long would the wait be?  (For pythia 8.209)

**Comment by bendavid** [comment]
Could be several weeks given other pending backports and the need for careful validation.

**Comment by dnash86** [comment]
Okay, I am checking with the analyzers.

**Comment by dnash86** [comment]
So the analyzers actually want samples both with, and without taola.  So this set should wait for the fix, they have sent configs with taola, uploaded here: https://github.com/cms-sw/genproductions/pull/442

**Comment by dnash86** [comment]
@bendavid It seems I've forgotten to follow up on this:  The analyzers would like these samples without the taola, with pythia 8.209 as you said, as well.  Do current CMSSW releases have pythia 8.209 yet?  (If so, we should merge this request and I should proceed with those samples.)

**Comment by bendavid** [comment]
No, not yet backported to the production release, validation is still in progress.

**Comment by dnash86** [comment]
Oh, okay, thanks.  Is there a sense of the timeline of that validation?  Or tough to tell?

**Comment by bendavid** [comment]
There were some technical problems with the relvals which have slowed things down.  How urgent are these samples?

**Comment by dnash86** [comment]
Checking on that now.

**Comment by dnash86** [comment]
These samples are actually quite urgent.  Now that some of the other samples are finishing, the analyzers want these for the tau decays in the new Pythia8.

**Comment by dnash86** [comment]
Just checking on the status of the validation for the pythia 8.209 backport.  If its ready, can we merge this PR?  (If not, I suppose there is nothing to do but wait.)  Thanks.

**Comment by bendavid** [comment]
No, there are some issues (related specifically to tau decays) in 8.209.  We're waiting for a fix before moving forward with the pythia releases.

**Comment by dnash86** [comment]
Okay, thanks.

**Comment by dnash86** [comment]
@bendavid Any status update here?

**Comment by bendavid** [comment]
Pythia release with the fix expected next week.

**Comment by dnash86** [comment]
Okay, thanks

**Comment by bendavid** [comment]
Fixed pythia release is out btw, in the process of being integrated in cmssw/tested/backported.

**Comment by dnash86** [comment]
Great, thanks a lot for the update.

**Comment by bendavid** [comment]
The validation and backport of the pythia release is now complete, so these can now go ahead.  (Be sure to use CMSSW_7_1_20 or later)

**Pull request merged**
