### PR TITLE
Add HH to 2G2Tau madgraph pythia fragment

### PR DESCRIPTION
**Pull request by chuwang1**
Dear expert,
Please review this HH to 2G2Tau pythia fragment.
Thanks!
Chu Wang

### CODE REVIEW

**Comment by menglu21** [comment]
looks good to me, @Saptaparna @GurpreetSinghChahal @mlizzo please have a check and feel free to merge.

**Comment by mlizzo** [comment]
Hi @chuwang1 the request is fine to me as well, I just have a question to @menglu21 @Saptaparna and @GurpreetSinghChahal . Are fragments supposed to include the concurrent feature? As far as I understood is now mandatory when submitting an MccM ticket and I was wondering whether fragments in genproductions should comply to this requirement. If not, then this PR can be merged.

**Comment by menglu21** [comment]
Hi @mlizzo , thanks for pointing it out, actually i'm not aware of such policy, maybe @Saptaparna @GurpreetSinghChahal can comment.

**Comment by mlizzo** [comment]
Hi @Saptaparna @GurpreetSinghChahal , could you please comment on this? it's just a matter of deciding whether the concurrent feature should be included in the fragment or not

**Comment by menglu21** [comment]
Hi @mlizzo i checked the gdoc of mccm and what you said should be correct. @chuwang1 could you please change "Pythia8HadronizerFilter" to "Pythia8ConcurrentHadronizerFilter"

**Comment by Saptaparna** [comment]
This is indeed true but a comment needs to be made that this will only work for CMSSW 10_26 or higher. If a backport is needed to 7_1, the concurrent feature will not work.

**Comment by chuwang1** [comment]
> Hi @mlizzo i checked the gdoc of mccm and what you said should be correct. @chuwang1 could you please change "Pythia8HadronizerFilter" to "Pythia8ConcurrentHadronizerFilter"
Hi @menglu21 ,I will add the Concurrent settings.
Thanks!
Chu Wang

**Comment by chuwang1** [comment]
Hi @menglu21 
I have added "Pythia8ConcurrentHadronizerFilter".
Please check them again.
Thanks!
Chu Wang

**Pull request merged**
