### PR TITLE
added MadGraph5_aMCatNLO cards for ZGGJets sample

### PR DESCRIPTION
**Pull request by mmachet**

### CODE REVIEW

**Comment by bendavid** [comment]
Do you care about the gamma* contribution?

**Comment by mmachet** [comment]
Do you mean that the second part $$ t t~ can be deleted?

2015-07-20 18:21 GMT+02:00 Josh Bendavid <notifications@github.com>:

**Comment by bendavid** [comment]
no, I mean that you may want to generate directly l+ l- instead of z (at least for the leptonic decays)

**Comment by mmachet** [comment]
Ah ok! So you suggest to generate l+ l- for the leptonic decay, and in a
similar way for the other decays? Or for the other decays I keep the z?

2015-07-20 18:57 GMT+02:00 Josh Bendavid <notifications@github.com>:

**Comment by bendavid** [comment]
Yes, though to do it that way you will have to split into at least two samples.
Eg. one sample with l+ l- and the other sample with z (and then configure madspin to do only the neutrino and hadronic decays)

**Pull request closed without merging**
