### PR TITLE
Add compatibility with CMS Connect.

### PR DESCRIPTION
**Pull request by khurtado**
2 new scripts added: submit_cmsconnect_gridpack_generation.sh and cmsconnect_utils.sh
1 modified to split gridpack_generation.sh in different steps (ALL, CODEGEN, INTEGRATE...).
ALL is the default when not specified, so this shouldn't break other submission modes.

### CODE REVIEW

**Comment by perrozzi** [comment]
ok for me, any comment deom @bendavid, @kdlong and others?

**Comment by perrozzi** [comment]
@vciulli @qliphy shall we merge?

**Comment by khurtado** [comment]
@kdlong: Fair enough, I have changed the code to check for git instead.

**Comment by perrozzi** [comment]
can it be merged then? any other comment?

**Comment by kdlong** [comment]
I see no reason it can't be merged into master, but it could also be put to a temporary branch for testing if anyone prefers

**Comment by vciulli** [comment]
fine with me to merge with master branch
@lorusso7 could you please check both on lxplus and cms connect?

**Comment by perrozzi** [comment]
ok then, going to merge the PR later today unless there are other comments

**Pull request merged**
