### PR TITLE
mono-Higgs ZpBaryonic and Scalar model cards

### PR DESCRIPTION
**Pull request by dburns7**
The MadGraph UFO tarball is in the top directory of each model. These are the next highest priority models for mono-Higgs, with other simplified and EFT requests delayed until further studies of parameters are done.

### CODE REVIEW

**Comment by bendavid** [comment]
The tarball should not go in git, but rather in /afs/cern.ch/cms/generators/www

As per the new changes discussed in the gen meeting today, you'll also need to add the corresponding _extramodels.dat cards to use it with the current version of the scripts.

**Comment by dburns7** [comment]
I have removed the model tarballs and added the extramodels.dat cards. Please let me know any additional revisions.

**Comment by bendavid** [comment]
I don't actually see the model in 
/afs/cern.ch/cms/generators/www/Higgs_scalar_UFO.tar.gz

If you let me know where I can find it, can copy it there.

**Comment by dburns7** [comment]
By "model" I assume you mean the madgraph model implementation, or UFO
directory. Is that file empty? I have attached the UFO tar for this model
here in case this is what you need.



Dustin Burns
Physics Department
University of California, Davis

**Comment by bendavid** [comment]
Yes I mean the tarball which is referenced in the extramodels.dat
(if you attached it to the email, then it got dropped, because the github comment system doesn't support that I think.  Just put it in your public afs directory or something)

**Comment by dburns7** [comment]
/afs/
cern.ch/user/d/dburns/work/public/MonoHiggs_models/Higgs_scalar_UFO.tar.gz



Dustin Burns
Physics Department
University of California, Davis

**Comment by bendavid** [comment]
Alright, cards look fine except for one thing.  The output directory in the proc card needs to match the name of the cards.

eg for "Scalar_MZp10000_MChi1_proc_card.dat" you need to have
"output Scalar_MZp10000_MChi1 -nojpeg" rather than "output scalar"

**Comment by dburns7** [comment]
I have made this change in the Scalar and ZpBaryonic model cards. Should I
proceed to producing gridpacks now?



Dustin Burns
Physics Department
University of California, Davis

**Comment by bendavid** [comment]
yes, good to go now that it's merged.

**Pull request merged**
