### PR TITLE
Three Higgs mass points and JHU card for gg production of HWW

### PR DESCRIPTION
**Pull request by rebecacern**
Three Higgs mass points and JHU card for gg production of HWW, following HZZ example, hfact should be ok for the three of them (hfact = 0.1*mH + 47.5) the JHU card should be the same for the three of them.

### CODE REVIEW

**Comment by stosi** [comment]
seems OK to me

**Comment by syuvivida** [comment]
Hi, the hwidth you use has no mass dependence and seems different from those used in H->ZZ cards here: https://github.com/cms-sw/genproductions/tree/master/bin/Powheg/production/V2/13TeV/Higgs/ . Is there a reason to do so?

**Comment by rebecacern** [comment]
I'm sorry, my mistake I think I just cloned the 125 card and modified 
only hdamp I am afraid. I will prepare a new set, sorry you can kill 
this request.


On 09/06/15 01:17, syuvivida wrote:
>
> Hi, the hwidth you use has no mass dependence and seems different from 
> those used in H->ZZ cards here: 
> https://github.com/cms-sw/genproductions/tree/master/bin/Powheg/production/V2/13TeV/Higgs/ 
> . Is there a reason to do so?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/genproductions/pull/446#issuecomment-110169602>.
>


-- 
* -----------------------------------
Rebeca Gonzalez Suarez

University of Nebraska (UNL)
CERN: 8/R-016 (+41 22 76) 70860
rebeca@cern.ch
skype: rebeca.gonzalez.suarez
http://rebeca.web.cern.ch
----------------------------------- *

**Comment by rebecacern** [comment]
Just one more thing, I have a new version ready but git won't let me 
push it since this one is still there somehow... any hints on what I 
should use to push the new cards?
Cheers,

Rebeca

On 09/06/15 01:17, syuvivida wrote:
>
> Hi, the hwidth you use has no mass dependence and seems different from 
> those used in H->ZZ cards here: 
> https://github.com/cms-sw/genproductions/tree/master/bin/Powheg/production/V2/13TeV/Higgs/ 
> . Is there a reason to do so?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/genproductions/pull/446#issuecomment-110169602>.
>


-- 
* -----------------------------------
Rebeca Gonzalez Suarez

University of Nebraska (UNL)
CERN: 8/R-016 (+41 22 76) 70860
rebeca@cern.ch
skype: rebeca.gonzalez.suarez
http://rebeca.web.cern.ch
----------------------------------- *

**Comment by covarell** [comment]
That should work in principle. If you really fail, just close this PR and open a new one on a clean branch

**Comment by rebecacern** [comment]
Hi Roberto,
I tried also closing the PR, but I get:

hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Merge the remote changes (e.g. 'git pull')
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

How can I work this around?
Cheers,

Rebeca


On 09/06/15 09:34, Roberto Covarelli wrote:
>
> That should work in principle. If you really fail, just close this PR 
> and open a new one on a clean branch
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/genproductions/pull/446#issuecomment-110261387>.
>


-- 
* -----------------------------------
Rebeca Gonzalez Suarez

University of Nebraska (UNL)
CERN: 8/R-016 (+41 22 76) 70860
rebeca@cern.ch
skype: rebeca.gonzalez.suarez
http://rebeca.web.cern.ch
----------------------------------- *

**Pull request closed without merging**
