### PR TITLE
no spin correlations for ttbar inclusive

### PR DESCRIPTION
**Pull request by GiuliaNegro**

### CODE REVIEW

**Comment by efeyazgan** [comment]
Looks correct but @agrohsje , could you please double check? thanks.

**Comment by agrohsje** [comment]
Hi Giulia, hi Efe, what is the reason to produce an inclusive no spin corr sample? 
As a comment: I checked the tarball powhegboxV2_rev3633_date20190225_testggHH.tar.gz and it has the proper nospincorr option. So keep fingers crossed. :-)

**Comment by agrohsje** [comment]
Sorry one more question. It is on purpose NNPDF 3.0 ?

**Comment by GiuliaNegro** [comment]
Hi Alexander, a no spin corr sample was requested by Georgios Bakas. It has NNPDF 3.1.  @EmyrClement and @ckmackay can confirm it.

**Comment by agrohsje** [comment]
Me culpa 306000 is NNPDF31_nnlo_hessian_pdfas! About the final state, maybe worth checking if he really needs all-hadronic?

**Comment by GiuliaNegro** [comment]
At the moment we are requesting all possible final states (not only fully hadronic), but I will check with Georgios.

**Comment by agrohsje** [comment]
I know that he wants to do some boosted analysis, but not sure what exact final state. In case all-hadronic would not be involved that could gain us some statistics and save resources, while keeping dilepton might be interesting for the 18-006 follow-up.

**Comment by GiuliaNegro** [comment]
Georgios confirmed that he needs all-hadronic final states (see https://hypernews.cern.ch/HyperNews/CMS/get/top-modeling-and-generators/282/1/1/1/1/1/2.html), so we can proceed with the request.

**Pull request merged**
