### PR TITLE
GGGJets and GGJets Pt-15-15-15 fragments

### PR DESCRIPTION
**Pull request by uzzielperez**
GGGJets and GGJets fragments with each photon having a min Pt 15

### CODE REVIEW

**Comment by agrohsje** [comment]
Hi  @uzzielperez . Can you comment on the purpose of this request. Is it for central production? I am wondering if having these files here is really useful. We might just have them in MCM when submitting the samples. Let me know. 
I noted there are at least 3 pathes were this could go, so not sure anybody will ever find the file.

**Comment by uzzielperez** [comment]
Hi @agrohsje, yes it is for central production. The SMP MC contacts had recommended I upload it here so that if there are any errors it can be spotted right away.

**Comment by agrohsje** [comment]
Gurpreet will check and merge. Looks good to me. Gurpreet has trouble with his account but informed the github support. Ping us in case we don't get back to you asap.

**Comment by uzzielperez** [comment]
Cool, thank you!

**Comment by agrohsje** [comment]
Hi @GurpreetSinghChahal . Please check and merge.

**Comment by agrohsje** [comment]
As nothing happened for more than 15 months and the python path doesn't exist anymore I will close this PR.

**Pull request closed without merging**
