### PR TITLE
Monohiggs baryonic Z' model cards

### PR DESCRIPTION
**Pull request by dburns7**

### CODE REVIEW

**Comment by dburns7** [comment]
This pull request contains the process, run, and customize cards for a mass scan over DM mass and Z' mediator mass for the Baryonic Z' Model discussed by ATLAS/CMS DM forum paper: 1507.00966v1. The 36 mass points are taken from Table 2.1 and other parameters from section 3.1.1.1.

There are a total of 36*3 = 108 input cards.

We request 100K events per mass point = 3.6M total events.

**Comment by dburns7** [comment]
Can you please review these cards so I can proceed with the MC request? Thank you.

**Comment by covarell** [comment]
Hello,

Is the model Higgs_hzpzp contained here:
https://cms-project-generators.web.cern.ch/cms-project-generators/
?
If not it must be uploaded there, and the gridpack_generation.sh script must be updated

**Comment by dburns7** [comment]
Hi Roberto,

The model is not uploaded yet. There are several other models that I am in
the process of producing cards for as well. They are all attached in a
tarball. Note that the model I call Higgs_Zp2HDM is in
cms-project-generators as MonoHiggs_Zp2HDM_v1.2.tgz. Do I upload the models
or can you?



Dustin Burns
Physics Department
University of California, Davis

On Wed, Sep 23, 2015 at 4:04 PM, Roberto Covarelli <notifications@github.com

**Comment by covarell** [comment]
I think you do not have the permission... So when you have the full set of models, please send me the location and I will upload the tarballs.

**Comment by syuvivida** [comment]
@covarell 
Just to comment: Dustin will use 2.3.0 to produce gridpacks. Therefore, he only needs to upload tarball of model files. He doesn't have to change gridpack_generation.sh

**Comment by covarell** [comment]
Ah ok, great, I did not know this

**Pull request closed without merging**
