### PR TITLE
tWZ and ttZ with SMEFT@NLO for Run3

### PR DESCRIPTION
**Pull request by AlbertoBelvedere**
Hello, 
I'm doing this PR to add the cards for the production of tWZ and ttZ with SMEFT@NLO for Run3 but also to fix a couple of things of the previous PR.

Fix:
I've been asked to add TTZToNuNu also for Run2 and also there was a mistake in the TTZToQQ cards as I didn't include the Z->bb decay.

Cards for Run3:
Since both MadSTR and the EFT reweighting don't work in MG 2.9.9 I've generated my sample with MG 2.6.5 even if these are samples for Run3. The only difference with respect to the card for the Run2 is the change of the beam energy.

Cards for the production of the following samples:

tWZ with DR1 scheme and reweighting for SMEFT operators:

-TWZToLL_thad_Wlep
-TWZToLL_tlept_Whad
-TWZToLL_tlept_Wlept

tWZ with DR2 scheme, just for systematic computation (no SMEFT operators):

-TWZToLL_thad_Wlep
-TWZToLL_tlept_Whad
-TWZToLL_tlept_Wlept

ttZ, main background and important contribution for SMEFT operators:

-TTZToLL
-TTZToQQ
-TTZToNuNu

### CODE REVIEW

**Comment by Saptaparna** [comment]
Hi @menglu21: based on Giacomo's presentation here: https://indico.cern.ch/event/1175148/contributions/4935576/attachments/2474559/4246168/Boldrini_PHGen_04072022.pdf

There are memory issues with reweighting. @AlbertoBelvedere: perhaps you could also list out the issues we faced too. I don't know about Madspin though. We have shared Giacomo's slides with the Madgraph authors.

**Comment by agrohsje** [comment]
hi @AlbertoBelvedere: What is the issue with the MadStr plugin ?

**Comment by AlbertoBelvedere** [comment]
Hi, sorry I had canceled the gridpacks so I had to run the code again to have them. At this link (https://cernbox.cern.ch/s/YbwtlhZhogmKBaa) you can find them to have a look at the problems that I'm facing. Actually for the madStr problem it doesn't even do the gridpacks so there are just the log file and the folder with different files that is created when running MadGraph.

About MadStr (@agrohsje) I think it's related to the fact that I'm generating at NLO as the error message that I get  is the following:  "Cannot group subprocesses when exporting to NLO". (at the end of the log file MadSTR_problem/tlepWlepZlepDR-vec.log)

Instead for the reweighting it doesn't seem a memory issue as it doesn't even really start it and I get the following "AttributeError : 'NoneType' object has no attribute 'mkPDF'" (in this file reweighting_problem/gridpack_generation.log)

I didn't change anything from with respect to what I was doing in the 2.6.5 version so I don't know why I have this errors now.

**Comment by agrohsje** [comment]
@DickyChant @mlizzo Is one of you available to check what goes wrong in 2.9, i.e. where the above errors (mkPDF and Cannot group...) are coming from? I think we can always use older versions, but should see how to fix problems so that over time we can fully move to the latest version.

**Comment by mlizzo** [comment]
Hi @agrohsje , I can try to have a look at it and hope to find where these multple issues come from

**Comment by AlbertoBelvedere** [comment]
Hi @menglu21  @Saptaparna, what is the plan? should we wait to see if it is possible to solve these issues easily or can we go ahead with the old version? In principle I have already all the gridpacks ready with the old version and everything seems to work fine but of course I would like to know your opinion.

**Comment by mlizzo** [comment]
Dear all, I've run thadWlepZlepDR cards using the mg29x genproductions branch with CMSSW_12_0_2 and SCRAM_ARCH=slc7_amd64_gcc900 (I forced the queue to be local), and I did reproduce @AlbertoBelvedere 's error. I then started to make some modifications to the madstr scripts and I was able to run the code up to a certain point, i.e. when the pilot run is launched. I must say that I'm not 100% sure of the tweaks I made, I just tried to correct the errors (python-wise, not physics-wise) whenever I encountered one. Now I'm stuck with a "re-raised error" (see the pilotrun log file for more detail [1]), which I'm not sure how to tackle and don't know how I should proceed from here on. Here [2] you can find the log file, the cards I've used and the scripts I had to modify to make the code partially run. I'd like to get the feedback from MG experts, maybe I'm just missing something stupid (like an environment variable not set up), could please someone have a look at it? Thanks

[1] /afs/cern.ch/user/m/mlizzo/public/PR3400/pilotrun_tag_1_debug.log
[2] /afs/cern.ch/user/m/mlizzo/public/PR3400/

**Comment by AlbertoBelvedere** [comment]
Hello, as it doesn’t seem that the problems with new MG version will be solved soon, can we proceed with this PR? @agrohsje @Saptaparna @menglu21

**Comment by menglu21** [comment]
Hi @AlbertoBelvedere I just updated the MadSTR for the master branch, could you please have a test using the updated master branch. You may remove the reweight part to only test the MadSTR part

**Comment by AlbertoBelvedere** [comment]
Hi @menglu21 I just tried it updating my branch with the master one but I still have the same error when I try to use MadStr

**Comment by menglu21** [comment]
Hi @AlbertoBelvedere I'll check further on the reweight part, if there is no solution in a short time you can try version 265.

**Comment by menglu21** [comment]
just asked a question to the author, https://answers.launchpad.net/mg5amcnlo/+question/706660

**Comment by AlbertoBelvedere** [comment]
Hello, under @Saptaparna I tried to run the gridpacks produced with MG v2.6.5 with the new settings for Run3. So I produced a NanoGEN file using CMSSW_12_4_11_patch3 and it worked fine, I had to add the EFT reweighting weights trough the usual postfix but it seems to work as when I was using the Run2 settings.

**Comment by AlbertoBelvedere** [comment]
Hello @Saptaparna @menglu21, is there any update or otherwise can we move further with 2.6.5 to have the samples ready as soon as possible?

**Comment by Saptaparna** [comment]
Hi @menglu21 since Aleberto's gridpack work with Run III CMSSW versions, can we give him the green light?

**Comment by menglu21** [comment]
yes, I think it needs time to figure it out, please move forward with 265. btw, before moving to official production, could you please try the private production using the same workflow of Run3

**Comment by AlbertoBelvedere** [comment]
Hi @menglu21, I've already produced a nanoGEN file using CMSSW_12_4_11_patch3 with the suggested Run3 campaign and it worked fine. Do you mean to perform even further production steps? If this is the case could you please point me to some documentation as I've never done it before

**Comment by Saptaparna** [comment]
Hi @menglu21 indeed. Alberto has demonstrated that a 2.6.5 setup works with Run III production. @AlbertoBelvedere This is super useful information for us, so maybe you can elaborate on the exact cmsDriver steps.

**Comment by AlbertoBelvedere** [comment]
Sure this is the command that I've run inside the CMSSW_12_4_11_patch3 release:
cmsDriver.py Configuration/GenProduction/python/NLO_newGenFragment.py   --mc --eventcontent NANOAODGEN --datatier NANOAODSIM --conditions 126X_mcRun3_2022_realistic_postEE_v1 --step LHE,GEN,NANOGEN --era Run3 --fileout file:step0.root  --mc -n 10 --no_exec

Then I've simply run the file obtained in this way using cmsRun

**Comment by AlbertoBelvedere** [comment]
Hello @menglu21 @Saptaparna, sorry for insisting but I would really like to understand if there is something else that has to be done or if this PR can be merged. Thanks in advance

**Comment by AlbertoBelvedere** [comment]
Hello @Saptaparna @menglu21, I just wanted to ask again if this PR can be merged. Thanks

**Comment by Saptaparna** [comment]
@menglu21 since Alberto has done all the tests with Run III cmsDriver commands and shown that 2.6.5 is still compatible with Run III. Is there anything else he needs to do? May I merge the PR?

**Pull request merged**
