### PR TITLE
Moving cards for WpTpb to the right directory

### PR DESCRIPTION
**Pull request by jsiado**
Moving the cards from genproduction to /geproduction/.../WpToTpBottom

### CODE REVIEW

**Comment by perrozzi** [comment]
can you please (re)move https://github.com/cms-sw/genproductions/tree/master/WpToTpBottom ?

**Comment by jsiado** [comment]
I tried to do it but I could not do it

**Comment by perrozzi** [comment]
From inside the folder genproductions type:
git rm -r WpToTpBottom
then
git commit -m "Remove duplicated cfg"
git push master

does it work?

**Comment by jsiado** [comment]
It looks like they have been removed. Do I need to create another pull request?

**Comment by perrozzi** [comment]
perfect, now the PR shows the file as if they were moved from the old to the new destination.
that's what I meant, thanks a lot

**Pull request merged**
