### PR TITLE
Radion hh h v vhbb incl 2017

### PR DESCRIPTION
**Pull request by brentstone**
Requesting Radion hh_hVV_hbb inclusive sample for 2017 MC production. Contact me at brent.stone@cern.ch

### CODE REVIEW

**Comment by qliphy** [comment]
Moreover, please don't upload all cards. Just an example one together with the script to make others.  Otherwise this will slow down git download.

**Comment by brentstone** [comment]
I've recommitted with Template files and a python script for producing cards for different mass points. The mass points we desire are already coded into the python script.

How does this work going forward (my first time going through this process)? Do I wait for approval and then produce the gridpacks and send them to you?

**Comment by qliphy** [comment]
After cards approval, you can start producing gridpacks and contact your PAG/POG MC Contacts and make  requests.

**Comment by brentstone** [comment]
Do I await approval from you or from someone else in GEN?

**Comment by efeyazgan** [comment]
It was already merged (i.e. approved) by @qliphy.

**Pull request merged**
