### PR TITLE
Madgraph5_aMC@NLO 74 and 76 GeV cards

### PR DESCRIPTION
**Pull request by gourangakole**
Two extra mass points (74 and 76 GeV) are added for ggh012j_5f_NLO_FXFX.

### CODE REVIEW

**Comment by govoni** [comment]
Should we wait until feedback from the madgraph authors about the problem at 75 GeV, to make sure it does not affect these gridpacks as well somehow?

**Comment by perrozzi** [comment]
ping

**Comment by vciulli** [comment]
Isn't this solved now and already in McM with the new gridpack done in 2.4.2 ? 

https://cms-pdmv.cern.ch/mcm/requests?prepid=HIG-RunIISummer15wmLHEGS-01126&page=0&shown=134611071

**Comment by perrozzi** [comment]
thanks vitaliano. from the datacard point of view, were these exact datacards used since it was simply a MG5_aMC@NLO version problem?

**Comment by perrozzi** [comment]
@gourangakole ping

**Comment by gourangakole** [comment]
I also agree with @vciulli ...  now the sample is done.  
https://cms-pdmv.cern.ch/mcm/requests?prepid=HIG-RunIISummer15wmLHEGS-01126&page=0&shown=127
if ping wants to comment more.
otherwise, we can close this PR?

**Pull request closed without merging**
