### PR TITLE
WG 40to130 and TTZtoLL_M-1to10

### PR DESCRIPTION
**Pull request by lesenka**
MG LO cards for the lower pT bin for the WGToLNuGamma process
MG LO cards for the ttZ with M-1to10

### CODE REVIEW

**Comment by perrozzi** [comment]
ready to be reviewed?

**Comment by lesenka** [comment]
Yes, please!

Thank you,
Lesya

On 9 Nov 2016, at 17:33, perrozzi <notifications@github.com<mailto:notifications@github.com>> wrote:


ready to be reviewed?

**Comment by perrozzi** [comment]
can you update the pr title?

**Comment by lesenka** [comment]
Done

**Pull request merged**
