### PR TITLE
let us try again, hopefully I will manage to open a pull request now:…

### PR DESCRIPTION
**Pull request by albertobelloni**
… updated WpWpJJ cards - PDF, eta cuts

### CODE REVIEW

**Comment by bendavid** [comment]
Ok, looks good from git perspective.

One last point that I missed before is that since this is 5 flavour scheme, it should use a model with massless b's

so either
"import model sm-ckm_no_b_mass"  (keeps off-diagonal ckm elements)
or
"import model sm-no_b_mass" (diagonal ckm matrix)

depending on what is preferred.

**Comment by albertobelloni** [comment]
Hi Josh,

thanks! Andrew, could you please select your preferred model? I am ready to update the cards and copy the gridpacks (I suspect that they may need to be updated). Best,

Alberto

**Comment by AndrewLevin** [comment]
Hi Alberto,

We will use sm-no_b_mass. Yes, I need to remake the gridpacks with this model. I will let you know when they are ready. 

Andrew

**Comment by covarell** [comment]
Superseded by https://github.com/cms-sw/genproductions/pull/392

**Pull request closed without merging**
