### PR TITLE
Z'-> ttbar signal samples for Fall17 production

### PR DESCRIPTION
**Pull request by karavdin**

### CODE REVIEW

**Comment by qliphy** [comment]
No need to upload so many cards.  You can just keep cards for one benchmark points, together with the script to make other cards.

Can you also explain a bit more about multiple_try patch you would like to add?
https://github.com/cms-sw/genproductions/blob/898cdd736c5f316952dab52c8880d9619424b162/bin/MadGraph5_aMCatNLO/patches/0023-multiple-try-compilation.patch

**Comment by karavdin** [comment]
Hi @qliphy, 
Thank you for quick feedback. Only benchmark points are left. This patch helps a lot to make gridpack production more smooth. I took it from suggestion on HN [1].
[1] https://hypernews.cern.ch/HyperNews/CMS/get/generators/3898/1.html

**Comment by qliphy** [comment]
Just noticed you are committing to 26X branch.   Note the current default is 242 yet.  

26X still needs some time to be the default.

Moreover, your run_card seems to be based on 242 but not 26X.  Please have a check.

And the files are still too many.  This will slow down git clone quite much. Please only keep necessary files. Thanks!

**Comment by karavdin** [comment]
We had issues to generate high mass points with 242 and were suggested switch to 26X version. To be consistent with generated with 2.6 v gridpacks (explicitly checked), I push cards to 26X branch.

**Comment by qliphy** [comment]
But the run_card.dat files is based on 242 template not 26X.  Do you want to update run_card.dat to 26X?

**Comment by karavdin** [comment]
Could you point me to 26X template, please? Do we miss anything critical in run_card? It took more than a month to produce gridpacks and I would like to avoid re-doing them unless its absolutely necessary.

**Comment by karavdin** [comment]
Unfortunately I could not spot any critical difference in examples for 2.6 cards. However I can understand concern  to not have cards under 26X brunch if they don't use 26X functionality. Therefore I created another PR for master branch with cards tested with MG 2.4.2.  This PR is going to be closed.

**Pull request closed without merging**
