### PR TITLE
Fixed error in FCNC with photon sample cards

### PR DESCRIPTION
**Pull request by vrbouza**
(Details in the discussion of https://its.cern.ch/jira/browse/CMSTOPMCREQ-2 )

Fixed error in FCNC with photon samples. Added also explicitly False = pdfwgt and the event_norm parameter as recommended by @agrohsje .

### CODE REVIEW

**Comment by menglu21** [comment]
Hi,
"100000 =  nevents", 100K is not needed in pilot run, the default 10K is fine.

**Comment by vrbouza** [comment]
> Hi, "100000 = nevents", 100K is not needed in pilot run, the default 10K is fine.

Hi @menglu21 . Thanks for your comments. I've corrected the nevents for the pilot run and propagated the fixes to the TLL FCNC samples also. Would this be ok now?

**Comment by Saptaparna** [comment]
Hi @vrbouza, can you please point me to your process cards as well? Presumably they are already in genproductions?

**Comment by sihyunjeon** [comment]
@Saptaparna It's in the same directory the rest of the cards are stored in

**Comment by Saptaparna** [comment]
I am ok with merging. @sihyunjeon anything you want to add?

**Pull request merged**
