### PR TITLE
With all non res HH cards & model inside gridpack_generation.sh

### PR DESCRIPTION
**Pull request by sudhaahuja**

### CODE REVIEW

**Comment by sudhaahuja** [comment]
New Pull request with all the changes requested upto now in the cards & model (coming from this pull request - https://github.com/cms-sw/genproductions/pull/574)

**Comment by bendavid** [comment]
And can you also comment what is supposed to be changed with respect to
https://github.com/cms-sw/genproductions/pull/574
?

**Comment by OlivierBondu** [comment]
it is supposed to be the same as #574 but there was some conflicts with merging, probably due to what you mention, and we had trouble updating it. This PR being a new branch it should be easier to update, we'll correct this.

**Comment by sudhaahuja** [comment]
@bendavid - The deletion has been corrected and the deleted model (2HDM model for A->Zh->lltautau) is now back inside gridpack_generation.sh script along with the new model (NONRES HH model).

**Comment by OlivierBondu** [comment]
Hi,

is there still things to correct or can this be merged ?

Thanks

**Comment by bendavid** [comment]
Sorry it still looks like the AZH model is being removed
-  tar xvf ../${AZHMODEL}
+  tar xvf ../${NONRESHHMODEL}

**Comment by covarell** [comment]
@bendavid the last commit seems OK to me, no?

**Comment by bendavid** [comment]
Since the pull request is too long to view the changes on the web interface, it's hard to check.

I believe the definitive diff of what will be merged is this
https://github.com/cms-sw/genproductions/pull/604.diff

And in that case it does not look ok still.

**Comment by OlivierBondu** [comment]
Hi @bendavid 

the last commit should fix it, on my end it looks like the following:

```
>git diff master..hh_nonres_cards -- gridpack_generation.sh
diff --git a/bin/MadGraph5_aMCatNLO/gridpack_generation.sh b/bin/MadGraph5_aMCatNLO/gridpack_generation.sh
index 81dc67e..2f4ec56 100755
--- a/bin/MadGraph5_aMCatNLO/gridpack_generation.sh
+++ b/bin/MadGraph5_aMCatNLO/gridpack_generation.sh
@@ -156,6 +156,10 @@ CHSOURCE=/afs/cern.ch/cms/generators/www/
 AZHMODEL=2HDM4MG5-may15.tar.gz
 AZHSOURCE=/afs/cern.ch/cms/generators/www/
 
+# NONRES HH model, needed for the non res HH analysis
+NONRESHHMODEL=BSM_gg_hh.tar
+NONRESHHSOURCE= /afs/cern.ch/cms/generators/www/
+
 # Model for EWK DM model
 EWKDMMODEL=EWModel_FermionDM_UFO.tar
 EWKDMSOURCE=https://cms-project-generators.web.cern.ch/cms-project-generators/${EWKDMMODEL}
@@ -349,6 +353,12 @@ if [ ! -d ${AFS_GEN_FOLDER}/${name}_gridpack ]; then
   tar xvf ../${AZHMODEL}
   cd ..
 
+  # get non res HH model
+  cp ${NONRESHHSOURCE}/${NONRESHHMODEL} .
+  cd models
+  tar xvf ../${NONRESHHMODEL}
+  cd ..
+
   #get EWK DM model
   wget --no-check-certificate -O ${EWKDMMODEL} ${EWKDMSOURCE}
   cd models
```

**Comment by OlivierBondu** [comment]
@bendavid : there was some minor corrections needed to the customize cards and the ``gridpack_generation.sh`` in the last commits, the gridpack generation works fine now, is there anything left to correct ?

the current diff of ``gridpack_generation.sh`` is: 
```diff
diff --git a/bin/MadGraph5_aMCatNLO/gridpack_generation.sh b/bin/MadGraph5_aMCatNLO/gridpack_generation.sh
index 81dc67e..b55f196 100755
--- a/bin/MadGraph5_aMCatNLO/gridpack_generation.sh
+++ b/bin/MadGraph5_aMCatNLO/gridpack_generation.sh
@@ -156,6 +156,10 @@ CHSOURCE=/afs/cern.ch/cms/generators/www/
 AZHMODEL=2HDM4MG5-may15.tar.gz
 AZHSOURCE=/afs/cern.ch/cms/generators/www/
 
+# NONRES HH model, needed for the non res HH analysis
+NONRESHHMODEL=BSM_gg_hh.tar
+NONRESHHSOURCE=/afs/cern.ch/cms/generators/www/
+
 # Model for EWK DM model
 EWKDMMODEL=EWModel_FermionDM_UFO.tar
 EWKDMSOURCE=https://cms-project-generators.web.cern.ch/cms-project-generators/${EWKDMMODEL}
@@ -349,6 +353,14 @@ if [ ! -d ${AFS_GEN_FOLDER}/${name}_gridpack ]; then
   tar xvf ../${AZHMODEL}
   cd ..
 
+  # get non res HH model
+  cp ${NONRESHHSOURCE}/${NONRESHHMODEL} .
+  cd models
+  tar xvf ../${NONRESHHMODEL}
+  # there are subdirectories in the tarball, sort this out:
+  ln -s -d NonRes_hh/GF/BSM_gg_hh .
+  cd ..
+
   #get EWK DM model
   wget --no-check-certificate -O ${EWKDMMODEL} ${EWKDMSOURCE}
   cd models
```

**Pull request merged**
