### PR TITLE
Hig 4l 2017

### PR DESCRIPTION
**Pull request by skeshri**
Hi 

This PR is against the my closed PR https://github.com/cms-sw/genproductions/pull/1560 since this PR has conflicts and I couldn't resolve it.

I will commit more config files when this will get approve. Also need to finalize some selections that I will update in coming days.

Please have a look.

Thanks.

### CODE REVIEW

**Comment by perrozzi** [comment]
@govoni should review before to merge

**Comment by govoni** [comment]
The review process is ongoing. Checking the number if calls with phantom authors and the min mll cut with the analysis group.

**Comment by perrozzi** [comment]
any news here?

**Comment by govoni** [comment]
just receieved feedback from Phantom authors. It's ok on the technical side, waiting for feedback from the physics group about the leptons invariant mass cuts from @skeshri

**Comment by skeshri** [comment]
Hi @govoni 

Sorry to come very late on this topic. After discussion with Ulascan, A. Gristan and all others, we would like to stick with the 4 GeV invariant mass cut.

I have already produced all the gridpacks for VBF phantom samples for 4l and 2l2nu. I will make a separate PR again with all the template configuration files and closing this one to avoid any repetition.

Sumit

**Pull request closed without merging**
