### PR TITLE
Moving user-specific patching to after extramodel download

### PR DESCRIPTION
**Pull request by danbarto**
Addressing #3694

### CODE REVIEW

**Comment by bbilin** [comment]
What is the motivation to change this file? If it is for a specific model, I would suggest modifying it for your own use case.

**Comment by kdlong** [comment]
I don't think there was any particular reason to have it before he model loading in the past, so I don't see any reason not to accept this change (speaking as the one who implemented this ages ago).

**Comment by bbilin** [comment]
> I don't think there was any particular reason to have it before he model loading in the past, so I don't see any reason not to accept this change (speaking as the one who implemented this ages ago).

Thanks @kdlong ! Our only concern is that the patches move after MG has been run in l267. Would there be any cases where this would be a problem? ./bin/mg5_aMC mgconfigscript

**Comment by danbarto** [comment]
Thanks for the comments!
In my opinion there are two motivations to not just upload a new model: this way we are flexible in changing things as we need them, and it is also more transparent to the user what is changed wrt the "official" model release.
As mentioned in the issue, we could also move the model download earlier and leave the patching in the same place.

**Comment by bbilin** [comment]
> Thanks for the comments! In my opinion there are two motivations to not just upload a new model: this way we are flexible in changing things as we need them, and it is also more transparent to the user what is changed wrt the "official" model release. As mentioned in the issue, we could also move the model download earlier and leave the patching in the same place.

Thanks, I would indeed prefer this option.

**Pull request merged**
