### PR TITLE
EFT samples of ttZ ZZ and WZ

### PR DESCRIPTION
**Pull request by denschwarz**
Hi all,

for the submission of my gridpacks I was asked to upload my MadGraph cards for you to review them.
Please let my know if there are any problems.

Thank you and cheers,
Dennis

### CODE REVIEW

**Comment by wajidalikhan** [comment]
Hi @denschwarz, if such a model does not exit at the link posted by @sihyunjeon [1]. We have to first make sure that we copy the desired model at the location. Could you please link of the model, please. 

[1] https://cms-project-generators.web.cern.ch/cms-project-generators/

**Comment by denschwarz** [comment]
Hi @sihyunjeon and @wajidalikhan !
Thank you for checking this PR.
I have made my own model which basically sets unused EFT parameters to 0 in the restrict card.
You can find it here: 
deschwar.web.cern.ch/deschwar/models/SMEFTsim_general_MwScheme_UFO.tar.gz

**Comment by agrohsje** [comment]
Hi @denschwarz  wouldn't it make more sense to make this a pure restriction card of the official model We can untar and add your restriction.

**Comment by denschwarz** [comment]
Yes, that also works. Sorry I did not know what the usual procedure is here.

**Comment by agrohsje** [comment]
Hi @denschwarz : Do you plan to submit before the break?

**Comment by denschwarz** [comment]
Hi @agrohsje!
Sorry, I think I misunderstood your last comment. Should I push my own restriction card also to the directories where the cards are (or a different place)? It sounded like you would extract it from the tar.

**Comment by agrohsje** [comment]
Ok. Will try to do it asap.

**Comment by sihyunjeon** [comment]
I just added @0 @1 ... to proc cards.
One question, is it fine to make inconsistent lepton decay modes between WZ and ZZ, one including taus and the other not?

And is the ttZ resonance decays being handled through Pythia?

**Comment by denschwarz** [comment]
Hi @sihyunjeon,
thank you for adding the @0, @1, ...
I don't see why the lepton decays are inconsistent. I include the taus in both cases, don't I?

Also, I just added the Z->ll decay in the ttZ proc_card. The top quark decays are then handled by pythia.

**Comment by sihyunjeon** [comment]
Ugh my bad, misread the lines

**Comment by sihyunjeon** [comment]
Something I just found, and changed for ttZ.
If you do  
p p > w+ z, w+ > lp vp, z > lp lp    NPprop=0 SMHLOOP=0 NP=1   
The NPprop, SMHLOOP, NP are for "p p > w+ z" part right? The the vertex settings should go right after "p p > w+ z"

**Comment by denschwarz** [comment]
You are of course right. I changed it for ZZ and WZ as well.

**Comment by sihyunjeon** [comment]
looks fine to me

**Comment by denschwarz** [comment]
Dear @sihyunjeon,
I just made a small change in the run card. I just saw in a private check that this improves the shower matching. 
Thanks, Dennis

**Comment by denschwarz** [comment]
Dear @sihyunjeon,
how does the process continue now? Should I produce the gridpack with the new settings and get in touch with the MC contacts again?
Thanks
Dennis

**Comment by denschwarz** [comment]
Dear @sihyunjeon ,
what is the current status of this review? 
Best,
Dennis

**Comment by sihyunjeon** [comment]
Hi sorry for not being clear,
Alexander should take a one last look and merge. @agrohsje

**Comment by agrohsje** [comment]
Ping me when the UFO is ready! Thanks.

**Comment by sihyunjeon** [comment]
@denschwarz I think you might not have the permission to do it so I did. Please check if you can find it.

**Comment by denschwarz** [comment]
@sihyunjeon , I do not have permissions to simply copy it to /afs/cern.ch/cms/generators/www/ . Is there a way using the "uploadGridpack.sh" script  as described in https://twiki.cern.ch/twiki/bin/view/CMS/GeneratorWebRepo?

**Comment by sihyunjeon** [comment]
Sorry I meant I uploaded the model cards there for you

**Comment by denschwarz** [comment]
Sorry, I misunderstood. Yes, I can find the model there.

**Comment by denschwarz** [comment]
@sihyunjeon , @agrohsje , can we proceed with the sample production chain now or is there anything you are waiting on from my side?

**Comment by agrohsje** [comment]
Hi @denschwarz , thanks for all your work and sorry for being slow here. I have one final question. I see xqcut is always 10. Did you check the performance. Usually the value needs to be increased when higher masses are involved. Let me know if you settled/checked xqcut and qcut and then I will merge. Not that drjj will be set to 0 in your setup by MG5.  But all ok.

**Comment by denschwarz** [comment]
Hi @agrohsje , I produced the DJR plots for this configuration and those look fine.

**Comment by sihyunjeon** [comment]
@denschwarz Hello Can we take a look at ttZ to make sure? ttZ is usually xqcut = 20 GeV so this is a bit unexpected

**Comment by denschwarz** [comment]
Dear @sihyunjeon , I produced the DJR plot for xqcut=10GeV [1] and xqcut=20GeV [2] and the first option appears to be better.

[1] https://deschwar.web.cern.ch/deschwar/tWZ/plots/DJR/DJR_ttZ_q10.pdf
[2] https://deschwar.web.cern.ch/deschwar/tWZ/plots/DJR/DJR_ttZ_q20.pdf

**Comment by sihyunjeon** [comment]
Hi, you should actually move qcut to sth like 50 if you have xqcut=20. Can you check DJR1->2 as well since you have +1j in matrix element level. If this looks fine I think it's ok to use xqcut=10

**Comment by denschwarz** [comment]
Hi @sihyunjeon ,
here are the plots for 1->2 for xqcut =10 GeV [1] and xqcut = 20 GeV [2]:
[1] https://deschwar.web.cern.ch/deschwar/tWZ/plots/DJR/DJR12_ttZ_q10.pdf
[2] https://deschwar.web.cern.ch/deschwar/tWZ/plots/DJR/DJR12_ttZ_q20.pdf

**Comment by sihyunjeon** [comment]
Not too bad! Merging

**Comment by agrohsje** [comment]
qcut looks a bit better, no ? we can leave as is not to delay but i think higher qcut values would be better.

**Comment by sihyunjeon** [comment]
I think xqcut=20 qcut=50/60 might give the better results then xqcut=10 qcut=20. Worth trying but didn't want to delay too much. @denschwarz @agrohsje Up to you two

**Comment by denschwarz** [comment]
Hi @agrohsje , @sihyunjeon , I will run the same plots with xqcut = 20 and qCut = 50. This should be done tomorrow and I will come back to you.

**Comment by denschwarz** [comment]
Hi @sihyunjeon , @agrohsje , I also produced the DJR plots for xqcut = 20 and qCut = 50 now and still the first option (xqcut=10, qCut=30) seems to work best. Please find all the plots below:

DJR01 xqcut=10, qCut=30: https://deschwar.web.cern.ch/deschwar/tWZ/plots/DJR/DJR01_ttZ_q10_30.pdf
DJR01 xqcut=20, qCut=30: https://deschwar.web.cern.ch/deschwar/tWZ/plots/DJR/DJR01_ttZ_q20_30.pdf
DJR01 xqcut=20, qCut=50: https://deschwar.web.cern.ch/deschwar/tWZ/plots/DJR/DJR01_ttZ_q20_50.pdf
DJR12 xqcut=10, qCut=30: https://deschwar.web.cern.ch/deschwar/tWZ/plots/DJR/DJR12_ttZ_q10_30.pdf
DJR12 xqcut=20, qCut=30: https://deschwar.web.cern.ch/deschwar/tWZ/plots/DJR/DJR12_ttZ_q20_30.pdf
DJR12 xqcut=20, qCut=50: https://deschwar.web.cern.ch/deschwar/tWZ/plots/DJR/DJR12_ttZ_q20_50.pdf

**Comment by sihyunjeon** [comment]
agreed thank you for the checks

**Comment by agrohsje** [comment]
Hi @denschwarz, can you quickly comment on the time scale of the samples? I don't want to cause further delays, but I am also not totally convinced by the conclusions of the studies.

**Comment by denschwarz** [comment]
Hi @agrohsje, if you have specific checks in mind that I can do, please say so. We are still in the early stage of the analysis and there are also other samples that we need, so there is no urgent need for them to be going into production now but of course a large delay would cause problems.

**Comment by sihyunjeon** [comment]
One thing I would suggest is,
Can you turn on all the EFT related couplings and see what the cross sections is you get?

**Comment by agrohsje** [comment]
Thanks @denschwarz . For ttZ I would propose to probe xqcut 20 and 30 a bit better and do some more variations of qcut around 1.5 of xqcut so 30 and 45 say in steps of 5 GeV scanning +-10 or so ?
So xqcut 20, qcut 25, 30, 35, 40 and xqcut 30, qcut 35, 40, 45, 50, 55 .

**Comment by denschwarz** [comment]
@agrohsje , alright I will run this with a bit more of granularity. I hope to come back to you in a few days. 

@sihyunjeon, I don't understand what the cross section when switching on all EFT couplings would help. Can you elaborate a bit on what you want me to check?

**Comment by sihyunjeon** [comment]
@denschwarz It's just a sanity check to see if the ttZ modeling with EFT couplings turned off is consistent to SM samples that we already have. But you can deal with this later

**Comment by denschwarz** [comment]
Ah, you meant "turn off", I understand. I have already checked this but I will also post the cross section here once I finished the DJR studies.

**Comment by agrohsje** [comment]
@denschwarz updated my proposal above.

**Comment by sihyunjeon** [comment]
> Ah, you meant "turn off", I understand. I have already checked this but I will also post the cross section here once I finished the DJR studies.

Oh no worries, don't bother doing it then :)

**Comment by sihyunjeon** [comment]
20/45 and 30/60 looks nice

**Comment by agrohsje** [comment]
Agreed. The 2 look best to me. 30/65 might be interesting. But 20/45 seems already quite good. Thanks @denschwarz for the plots!

**Comment by agrohsje** [comment]
Can you still try 30/65 for ttZ. For ZZ and WZ I would try the above values with xqcut 20.

**Comment by denschwarz** [comment]
Hi @agrohsje, I have now included 30/65 for ttZ and made similar studies for WZ and ZZ. The WZ distributions do not look very smooth. Do you have any idea why it could be so different from ZZ? Or could it be that I am just somehow unlucky with the random seed and need more events? For now, I always used 50k.

WZ, 0 -> 1: https://deschwar.web.cern.ch/deschwar/tWZ/plots/DJR/DJR01_WZ.pdf
WZ, 1 -> 2: https://deschwar.web.cern.ch/deschwar/tWZ/plots/DJR/DJR12_WZ.pdf
ZZ, 0 -> 1: https://deschwar.web.cern.ch/deschwar/tWZ/plots/DJR/DJR01_ZZ.pdf
ZZ, 1 -> 2: https://deschwar.web.cern.ch/deschwar/tWZ/plots/DJR/DJR12_ZZ.pdf
ttZ, 0 -> 1: https://deschwar.web.cern.ch/deschwar/tWZ/plots/DJR/DJR01_ttZ.pdf
ttZ, 1 -> 2: https://deschwar.web.cern.ch/deschwar/tWZ/plots/DJR/DJR12_ttZ.pdf

**Comment by denschwarz** [comment]
Hi @agrohsje , did you have time to look into my studies? It would be great to converge to a setting and start producing those samples. Thanks!

**Comment by agrohsje** [comment]
For ttZ 30/50 looks good. No idea why WZ and ZZ are so different. As they are close in mass I am a bit surprised. For WZ e.g. 20/30 looks good to me. @sihyunjeon do you have an idea what is going on in ZZ or could you ask Olivier when you talk next time to him?

**Comment by Saptaparna** [comment]
Hi @denschwarz: when doing the qcut studies you are studying the SM right? Or the NP scenario that is the default in your customize card?

**Comment by agrohsje** [comment]
@sihyunjeon you prefer 10/20 for wz over 20/30 ?

**Comment by sihyunjeon** [comment]
image

Ah I didn't read your comment fully. But this doesn't look good the dip is too much, no?

**Comment by denschwarz** [comment]
Hi @sihyunjeon , @Saptaparna and @agrohsje ,

all these studies are made at the SM point. I can also check ZZ at 10/20 and 10/25, this should be done tomorrow.

Best,
Dennis

**Comment by denschwarz** [comment]
Hi @sihyunjeon , @agrohsje ,

as promised, I concluded the DJR studies for ZZ at 10/20, 10/25 and I also added 10/30.
You can find the plots with the same links, I will also paste them here again:

WZ, 0 -> 1: https://deschwar.web.cern.ch/deschwar/tWZ/plots/DJR/DJR01_WZ.pdf
WZ, 1 -> 2: https://deschwar.web.cern.ch/deschwar/tWZ/plots/DJR/DJR12_WZ.pdf
ZZ, 0 -> 1: https://deschwar.web.cern.ch/deschwar/tWZ/plots/DJR/DJR01_ZZ.pdf
ZZ, 1 -> 2: https://deschwar.web.cern.ch/deschwar/tWZ/plots/DJR/DJR12_ZZ.pdf
ttZ, 0 -> 1: https://deschwar.web.cern.ch/deschwar/tWZ/plots/DJR/DJR01_ttZ.pdf
ttZ, 1 -> 2: https://deschwar.web.cern.ch/deschwar/tWZ/plots/DJR/DJR12_ttZ.pdf

**Comment by sihyunjeon** [comment]
For WZ and ZZ 10/20 looks great to me @agrohsje

**Comment by sihyunjeon** [comment]
For ttZ 20/45 30/50 both are fine. At this point it's just your taste which decides the answer

**Comment by agrohsje** [comment]
10/20 seems to work for ZZ as well. So maybe easiest to use. Also agree with 20/45 and 30/50 for ttZ.

**Comment by denschwarz** [comment]
Hi @agrohsje, @sihyunjeon ,

great, thanks for having a look. I will change the parameter in the run cards. How do I specify the qcut value in pythia for the central production?

**Comment by agrohsje** [comment]
Via the P8 fragment that is provided in MCM, so adjusted to your needs something like:
https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_fragment/B2G-RunIISummer20UL18wmLHEGEN-00127/0

**Comment by denschwarz** [comment]
I have created a PR to set qcut=30 in the ttZ samples (https://github.com/cms-sw/genproductions/pull/3124). I guess the next step  is to contact the MC contacts to get the production going, right?

**Comment by sihyunjeon** [comment]
yes contact your PAG/POG MC contacts for sample requests

**Pull request merged**
